### PR TITLE
auth: support multiple token typs

### PR DESCRIPTION
**Pull request by xiang90**
@mitake

### CODE REVIEW

**Comment by mitake** [comment]
@xiang90 I feel maybe encoding token type to token would be overkill. Maybe there's no situation that require both of simple token and jwt token at the same time. Actually, current tokenDecode() seems to be failing. How about switching token types with a flag of etcd?

**Comment by xiang90** [comment]
@mitake OK. A configurable token type flag also works for me (it is simpler at least...). I will close this then.

**Comment by mitake** [comment]
@xiang90 `auth/token.go` in this PR seems to be useful (with slight changes) and adding it would be fine. Or should we revive it later?

**Comment by xiang90** [comment]
@mitake let's revisit it later.

**Comment by mitake** [comment]
@xiang90 OK

**Pull request closed without merging**
