### PR TITLE
clientv3: make IsProgressNotify() false on compact event and closed channel

### LINKED ISSUE #6549: IsProgressNotify is true for Compacted errors
I'm running version 3.0.10 on the client and the server.

If I run mirror.SyncUpdates and ask for a revision that's been compacted, the first WatchResponse I get is that the requested revision has been compacted.

```
rpctypes.EtcdError{code:0xb, desc:"etcdserver: mvcc: required revision has been compacted"}
```

I had some code that checked for ProgressNotify() messages and discarded them, since I seemed to get a lot of them at some point, and thought they were used for pinging the watcher / keeping the connection alive (I later diagnosed these messages as reads on a closed channel)

```go
			if wr.IsProgressNotify() {
				continue
			}
```

The documentation is not very clear on their purpose.

```
// IsProgressNotify returns true if the WatchResponse is progress notification.
```

After this "revision has been compacted" error, the channel is closed. I didn't realize a streaming channel could close, so I got tons and tons of messages

```
wr: clientv3.WatchResponse{Header:etcdserverpb.ResponseHeader{ClusterId:0x0, MemberId:0x0, Revision:0, RaftTerm:0x0}, Events:[]*clientv3.Event(nil), CompactRevision:0, Canceled:false, closeErr:error(nil)}
wr.err: <nil>
wr: clientv3.WatchResponse{Header:etcdserverpb.ResponseHeader{ClusterId:0x0, MemberId:0x0, Revision:0, RaftTerm:0x0}, Events:[]*clientv3.Event(nil), CompactRevision:0, Canceled:false, closeErr:error(nil)}
wr.err: <nil>
wr: clientv3.WatchResponse{Header:etcdserverpb.ResponseHeader{ClusterId:0x0, MemberId:0x0, Revision:0, RaftTerm:0x0}, Events:[]*clientv3.Event(nil), CompactRevision:0, Canceled:false, closeErr:error(nil)}
wr.err: <nil>
wr: clientv3.WatchResponse{Header:etcdserverpb.ResponseHeader{ClusterId:0x0, MemberId:0x0, Revision:0, RaftTerm:0x0}, Events:[]*clientv3.Event(nil), CompactRevision:0, Canceled:false, closeErr:error(nil)}
wr.err: <nil>
wr: clientv3.WatchResponse{Header:etcdserverpb.ResponseHeader{ClusterId:0x0, MemberId:0x0, Revision:0, RaftTerm:0x0}, Events:[]*clientv3.Event(nil), CompactRevision:0, Canceled:false, closeErr:error(nil)}
wr.err: <nil>
wr: clientv3.WatchResponse{Header:etcdserverpb.ResponseHeader{ClusterId:0x0, MemberId:0x0, Revision:0, RaftTerm:0x0}, Events:[]*clientv3.Event(nil), CompactRevision:0, Canceled:false, closeErr:error(nil)}
wr.err: <nil>
wr: clientv3.WatchResponse{Header:etcdserverpb.ResponseHeader{ClusterId:0x0, MemberId:0x0, Revision:0, RaftTerm:0x0}, Events:[]*clientv3.Event(nil), CompactRevision:0, Canceled:false, closeErr:error(nil)}
wr.err: <nil>
wr: clientv3.WatchResponse{Header:etcdserverpb.ResponseHeader{ClusterId:0x0, MemberId:0x0, Revision:0, RaftTerm:0x0}, Events:[]*clientv3.Event(nil), CompactRevision:0, Canceled:false, closeErr:error(nil)}
wr.err: <nil>
wr: clientv3.WatchResponse{Header:etcdserverpb.ResponseHeader{ClusterId:0x0, MemberId:0x0, Revision:0, RaftTerm:0x0}, Events:[]*clientv3.Event(nil), CompactRevision:0, Canceled:false, closeErr:error(nil)}
wr.err: <nil>
wr: clientv3.WatchResponse{Header:etcdserverpb.ResponseHeader{ClusterId:0x0, MemberId:0x0, Revision:0, RaftTerm:0x0}, Events:[]*clientv3.Event(nil), CompactRevision:0, Canceled:false, closeErr:error(nil)}
wr.err: <nil>
wr: clientv3.WatchResponse{Header:etcdserverpb.ResponseHeader{ClusterId:0x0, MemberId:0x0, Revision:0, RaftTerm:0x0}, Events:[]*clientv3.Event(nil), CompactRevision:0, Canceled:false, closeErr:error(nil)}
wr.err: <nil>
wr: clientv3.WatchResponse{Header:etcdserverpb.ResponseHeader{ClusterId:0x0, MemberId:0x0, Revision:0, RaftTerm:0x0}, Events:[]*clientv3.Event(nil), CompactRevision:0, Canceled:false, closeErr:error(nil)}
wr.err: <nil>
```

I expect that a non-nil `wr.Err()` will make IsProgressNotify() return false, or the documentation for IsProgressNotify should be clearer.

It'd also be nice if either the WatchChan documentation or the SyncUpdates documentation noted that the channel could close, so I don't try to select() on an empty channel over and over.

### PR DESCRIPTION
**Pull request by heyitsanthony**
Fixes #6549

### CODE REVIEW

**Comment by gyuho** [comment]
lgtm.

**Comment by kevinburke** [comment]
Not sure if you're planning on doing this, but it'd be nice if the docstring for this function was a little clearer about what sort of messages come through.

**Comment by xiang90** [comment]
LGTM.

**Comment by xiang90** [comment]
CI needs to be fixed.

**Pull request merged**
