### PR TITLE
Add docs for configuration flags and env vars

### PR DESCRIPTION
**Pull request by Timer**
Added some missing documentation surrounding etcdctl to hopefully save other people some time in the future (esp. for the environment variables)!

ping @robszumski

### CODE REVIEW

**Comment by robszumski** [comment]
Looks great! Thank you for putting this together.

**Comment by joshix** [comment]
LGTM, too. @xiang90 is there any reason we should not merge?

**Comment by joshix** [comment]
(@xiang90 and company are reviewing for completeness prior to merge)

**Comment by xiang90** [comment]
@joshix Just checked. LGTM

**Comment by xiang90** [comment]
@Timer Can you change the commit message to `etcdctl: add docs for configuration flags and env vars`? I will merge this after you change the commit message. Thanks!

**Comment by Timer** [comment]
Sure @xiang90.

**Comment by Timer** [comment]
@xiang90: rebased and reworded

**Comment by xiang90** [comment]
Thanks!

**Pull request merged**
