### PR TITLE
clientv3: remove strict yaml dependency

### PR DESCRIPTION
**Pull request by heyitsanthony**
Moved to clientv3/yaml

Should this also include username/password fields too? They're missing right now.

### CODE REVIEW

**Comment by gyuho** [comment]
Does this address https://github.com/coreos/etcd/issues/7058?

LGTM /cc @xiang90

**Comment by heyitsanthony** [comment]
@gyuho yeah, half of it

**Comment by xiang90** [comment]
it should include pw. lgtm

**Comment by xiang90** [comment]
LGTM.

for the password thing, shall we do it in a separate pr? /cc @heyitsanthony

**Comment by xiang90** [comment]
> for the password thing, shall we do it in a separate pr? 

never mind. already in here. fine with me.

**Comment by heyitsanthony** [comment]
Failing due to unrelated issue #7259; merging

**Pull request merged**
