### PR TITLE
doc: add branch.io use case into production users

### PR DESCRIPTION
**Pull request by hubt**
@xiang90

### CODE REVIEW

**Comment by xiang90** [comment]
@hubt Can you update commit message to 

```
doc: add branch.io use case into production users
```

Thanks!

**Comment by xiang90** [comment]
Sorry. There is a merge conflict. Other than that LGTM.

**Comment by gyuho** [comment]
@hubt Can you squash the last two commits into one?

**Comment by hubt** [comment]
I'll close and open a different patch.

**Pull request closed without merging**
