### PR TITLE
*: promote debugging metrics

### PR DESCRIPTION
**Pull request by gyuho**
https://github.com/coreos/etcd/issues/9438

### CODE REVIEW

**Comment by xiang90** [comment]
can you explain why do we want to promote these metrics?

**Comment by gyuho** [comment]
@xiang90 Thought `etcd_debugging_*` has always been experimental? Or should we make other metrics be consistent with `etcd_debugging_*`? Since we have `etcd_server_version`, defined right below `etcd_debugging_server_lease_expired_total`?

**Comment by gyuho** [comment]
ref. https://github.com/coreos/etcd/blob/master/Documentation/metrics.md#etcd_debugging-namespace-metrics

**Comment by gyuho** [comment]
Will only promote `etcd_debugging_mvcc_db_total_size_in_bytes` in backward compatible ways. I asked other production users, and found out quite a few are already using `etcd_debugging_*` metrics in production.

**Pull request closed without merging**
