### PR TITLE
fix README: upgrade link

### PR DESCRIPTION
**Pull request by mingqing**

### CODE REVIEW

**Comment by yichengq** [comment]
I think it should point to the doc on how to upgrade to 2.1 at https://github.com/coreos/etcd/blob/master/Documentation/upgrade_2_1.md

**Comment by yichengq** [comment]
@mingqing Are you still working on this?

**Comment by mingqing** [comment]
Sorry, I thought you had modify it. I re pull it now, #3247

**Comment by mingqing** [comment]
@yichengq Sorry, I thought you had modify it. I re pull it now, #3247

**Pull request closed without merging**
