### PR TITLE
Change the build script to use sh instead of bash

### PR DESCRIPTION
**Pull request by bartekrutkowski**
See discussion: https://github.com/coreos/etcd/pull/2891#issuecomment-112227754

### CODE REVIEW

**Comment by yichengq** [comment]
I think #2981 has included the PR for change. Could you review that one instead?

**Comment by bartekrutkowski** [comment]
Unfortunately, I dont see much about that mentioned there. Are you sure you're referencing correct number?

**Comment by yichengq** [comment]
@bartekrutkowski check this one: https://github.com/coreos/etcd/pull/2891/files

**Comment by yichengq** [comment]
It has been merged in #2891

**Pull request closed without merging**
