### PR TITLE
etcdctl: add short flag for 'ls' command

### PR DESCRIPTION
**Pull request by gyuho**
Fix https://github.com/coreos/etcd/issues/4866.

### CODE REVIEW

**Comment by gyuho** [comment]
For reference, see documentation here https://github.com/codegangsta/cli#alternate-names.

**Comment by gyuho** [comment]
Oh totally missed this https://github.com/coreos/etcd/pull/4872. Closing.

**Comment by ajityagaty** [comment]
@gyuho It's my mistake I think. I forgot to reference the bug in my PR. Sorry about that.

**Comment by gyuho** [comment]
Np! Thanks!

**Pull request closed without merging**
