### PR TITLE
clientv3/integration: use clientv3.Event type

### PR DESCRIPTION
**Pull request by gyuho**
Fix https://github.com/coreos/etcd/issues/5001.

### CODE REVIEW

**Comment by heyitsanthony** [comment]
Can this get rid of the `github.com/coreos/etcd/storage/storagepb` import too?

**Comment by xiang90** [comment]
I am not sure this is the root cause. If this is the root cause, the test should always fail? /cc @heyitsanthony

**Comment by heyitsanthony** [comment]
@xiang90 @gyuho I'd expect it to always fail if this were the problem in #5001

**Comment by gyuho** [comment]
At least in my local machine, this fixes the issue. Let me check if I can remove all `storagepb` imports

**Comment by gyuho** [comment]
@heyitsanthony @xiang90  Think this was just being not tested because of other failures in the integration tests.

Replaced more types from clientv3, but storagepb.KeyValue is not wrapped in clientv3 pkg so I just kept it as it is. PTAL.

**Comment by heyitsanthony** [comment]
@gyuho I tried it out and it is in fact failing every time. You're right-- this PR does fix it.

**Comment by heyitsanthony** [comment]
ok lgtm /cc @gyuho

**Comment by gyuho** [comment]
Thanks! Will merge with green https://semaphoreci.com/coreos/etcd/branches/pull-request-5006/builds/2.

**Pull request merged**
