### PR TITLE
*: replace grpc-gateway endpoint with /v3

### PR DESCRIPTION
**Pull request by hexfusion**
This PR replaces the current /v3beta with the stable /v3 API. Currently, support for /v3beta is maintained for one minor iteration and will remove completely as of 3.5. This can be removed now but as we offered the convenience with the last bump I kept it in while completely removing /v3alpha.

I will attempt to improve e2e test coverage in a separate PR.

ref: https://github.com/coreos/etcd/issues/9189

### CODE REVIEW

**Comment by gyuho** [comment]
lgtm. Defer to @xiang90 
Thanks

**Comment by hexfusion** [comment]
Well since I am here I am going to refactor the curl testing and probably break it out over a few different files.

**Comment by xiang90** [comment]
sgtm

**Comment by hexfusion** [comment]
@xiang90 PTAL, if this seems reasonable I would like to get this merged and add the breakout test files in a new commit as this is quite large as is. Will rebase once we are OK.

**Comment by hexfusion** [comment]
@xiang90 kind ping :)

**Comment by xiang90** [comment]
@hexfusion i am fine with this large commit.

**Comment by hexfusion** [comment]
thank you

**Pull request merged**
