### PR TITLE
etcdhttp: add config/local/debug endpoint

### PR DESCRIPTION
**Pull request by xiang90**
PUT on the endpoint sets the GlobalDebugLevel to DEBUG.
DELETE on the endpoint set the GlobalDebugLevel to INFO.
The action overwrites the original log level setting from
users. We need to write doc to warn this.

Close https://github.com/coreos/etcd/issues/2942

### CODE REVIEW

**Comment by philips** [comment]
@xiang90 instead of fooling around with HTTP verbs I feel it would be better to just put with a verbosity parameter insetad.

**Comment by xiang90** [comment]
@philips We can do that. But this is how today's auth/enable works. I wanted to be consistent.

**Comment by yichengq** [comment]
I think debug endpoint is good considering we have https://github.com/coreos/etcd/blob/master/Documentation/auth_api.md#enable-and-disable-authentication already. /cc @philips

**Comment by yichengq** [comment]
we closed this PR because we use master branch as the base branch for development instead of dev-2.2 after etcd 2.1 is cut. we will cherry-pick these commits and send new PR compared to master branch. Sorry for the inconvenience.

**Pull request closed without merging**
