### PR TITLE
etcdserver/auth: cache auth enable result

### LINKED ISSUE #3336: skip key access check when auth is disabled
The check introduces ~10% performance downgrade when doing read requests. This is found through read QPS in benchmark.

From https://github.com/coreos/etcd/pull/3327

### PR DESCRIPTION
**Pull request by xiang90**
fix #3336

### CODE REVIEW

**Comment by xiang90** [comment]
@yichengq It would be great if you can run the benchmark against this change.

**Comment by yichengq** [comment]
it doesn't fix the problem. if nobody enable/disable auth, which happens in most cases, the fast path will not be activated.

**Comment by xiang90** [comment]
@yichengq ah. right. fixed

**Comment by yichengq** [comment]
it works. LGTM

**Pull request merged**
