### PR TITLE
etcdserver/test: use recorderstream in TestApplyRepeat

### LINKED ISSUE #4333: etcdserver/server_test.go: TestApplyRepeat fail
```
--- FAIL: TestApplyRepeat-4 (0.01s)
	server_test.go:200: len(actions) = 0, expected >= 1
```

https://travis-ci.org/coreos/etcd/jobs/105566730

### PR DESCRIPTION
**Pull request by heyitsanthony**
was racing when waiting for the node commit

fixes #4333

### CODE REVIEW

**Comment by gyuho** [comment]
LGTM. Thanks

**Comment by xiang90** [comment]
test failed :(

**Comment by heyitsanthony** [comment]
works now /cc @xiang90

**Comment by xiang90** [comment]
lgtm

**Pull request merged**
