### PR TITLE
clientv3: use any port for metrics example

### PR DESCRIPTION
**Pull request by heyitsanthony**
Was getting bind conflicts causing failures on semaphore.

Cf. https://semaphoreci.com/coreos/etcd/branches/master/builds/1580

### CODE REVIEW

**Comment by xiang90** [comment]
lgtm

**Comment by gyuho** [comment]
LGTM. Thanks!

**Comment by fanminshi** [comment]
lgtm

**Comment by heyitsanthony** [comment]
Failing on unrelated issues #7377 and #6630. Jumping the turnstile.

**Pull request merged**
