### PR TITLE
store: added missing test case scenerio for scan of de-queued entries

### PR DESCRIPTION
**Pull request by sinsharat**
Test case added to check err handing for replaced entries.

#6255

### CODE REVIEW

**Comment by xiang90** [comment]
lgtm

**Comment by sinsharat** [comment]
@xiang90 as suggested i have added it as a new test case.

**Comment by sinsharat** [comment]
@gyuho can you suggest why the semaphoreci check failed.
Thank you.

**Comment by gyuho** [comment]
It's not related to this change

```
--- FAIL: TestCtlV3Lock (1.22s)
	ctl_v3_lock_test.go:91: expected different lock name, got l1="a/186d56d7c292d104\r\n", l2="Error:  lost watcher waiting for delete\r\n"
```

/cc @heyitsanthony

**Pull request merged**
