### PR TITLE
Fix a command error.

### PR DESCRIPTION
**Pull request by ghostplant**
Fix a command error:

`- px | grep etcd`
`+ ps | grep etcd`

Signed-off-by: CUI Wei <ghostplant@qq.com>

### CODE REVIEW

**Comment by heyitsanthony** [comment]
lgtm

**Comment by ghostplant** [comment]
I don't the the 2 of above build failure is related to this commit, but for an environmental error.

**Comment by heyitsanthony** [comment]
@ghostplant no, it's related to this commit. It's a check for the correct commit message formatting:
```
Expected commit title format '<package>{", "<package>}: <description>'
```

Please change the first line of the commit message to `Documentation: replace px typo with ps` so the commit message is conforming. For more information see https://github.com/coreos/etcd/blob/master/CONTRIBUTING.md#format-of-the-commit-message

Thanks!

**Comment by ghostplant** [comment]
@heyitsanthony 
What about the last failure?

**Comment by heyitsanthony** [comment]
@ghostplant it's fine; known issue #7259

**Pull request merged**
