### PR TITLE
clientv3: set current revision to create rev regardless of CreateNotify

### PR DESCRIPTION
**Pull request by heyitsanthony**
Turns out the optimization to ignore setting the init rev for
current revision watches breaks some ordering assumptions. Since
Watch only returns a channel once it gets a response, it should
bind the revision at the time of the first create response.

Was causing TestWatchReconnInit to fail.

### CODE REVIEW

**Comment by xiang90** [comment]
we do not really say any thing about the ordering between watch and other calls from one client. but yea, i agree that this optimization might not worth the effort. the side-effect might be confusing.

**Comment by xiang90** [comment]
lgtm

**Comment by gyuho** [comment]
@heyitsanthony Do we backport this as well? This is following change after https://github.com/coreos/etcd/pull/7795?

**Comment by heyitsanthony** [comment]
@gyuho yeah

**Pull request merged**
