### PR TITLE
op-guide: update gateway routing policy

### PR DESCRIPTION
**Pull request by raoofm**
Update from single available endpoint to round robin.

### CODE REVIEW

**Comment by raoofm** [comment]
@heyitsanthony 
as discussed in #7439

**Comment by heyitsanthony** [comment]
lgtm /cc @xiang90

**Comment by heyitsanthony** [comment]
@raoofm please update the first line in the commit messsage to `op-guide: update gateway routing policy` so this clears CI's `Expected commit title format '<package>{", "<package>}: <description>'`? Then this should be good to merge. Thanks!

**Comment by xiang90** [comment]
LGTM

**Comment by raoofm** [comment]
@heyitsanthony done
thanks

**Comment by fanminshi** [comment]
lgtm

**Pull request merged**
