### PR TITLE
vendor: coreos/bbolt v1.3.1-coreos.0, add others in glide.yaml

### PR DESCRIPTION
**Pull request by gyuho**
Once merged, I will redeploy functional tester cluster.

### CODE REVIEW

**Comment by gyuho** [comment]
Will drop `blackfriday` changes... no idea why it is staged...

**Comment by gyuho** [comment]
Added others in glide.yaml that was missing from glide.lock.
Now `updatedep.sh` will output reproducible builds.

Merging in greens.

Thanks.

**Comment by gyuho** [comment]
Blocked on https://github.com/coreos/bbolt/issues/15.

**Comment by gyuho** [comment]
@heyitsanthony PTAL.

Seems fixed https://jenkins-etcd.prod.coreos.systems/job/etcd-ci-ppc64/1878/.
Commented on the test (will close https://github.com/coreos/bbolt/issues/15).

Thanks.

**Comment by heyitsanthony** [comment]
lgtm; the new freelist page reuse is probably why it stopped working-- allocation is more efficient

**Comment by xiang90** [comment]
lgtm

**Pull request merged**
