### PR TITLE
*: use merge logger for repeating etcdserver error logs

### PR DESCRIPTION
**Pull request by gyuho**
1. pkg/logutil: round off start time, add merge_logger_test.go
2. merge logger for repeating etcdserver error logs

### CODE REVIEW

**Comment by gyuho** [comment]
@xiang90 Tested and confirmed with following logs:

> 17:18:28 etcd2 | 2015-12-29 17:18:28.300291 E | etcdhttp: etcdserver: request timed out, possibly due to previous leader failure [merged 2 repeated lines in 1.000003102s]
> 17:18:28 etcd0 | 2015-12-29 17:18:28.301265 E | etcdhttp: etcdserver: request timed out, possibly due to previous leader failure [merged 2 repeated lines in 1.000010448s]
> 17:18:28 etcd1 | 2015-12-29 17:18:28.301962 E | etcdhttp: etcdserver: request timed out, possibly due to previous leader failure [merged 9 repeated lines in 2.000010296s]

**Comment by xiang90** [comment]
`[merged 2 repeated lines in 1.000003102s]`

The time duration format is not ideal. It is too long and does not make sense for users. We only need accuracy of 2 decimal points

**Comment by gyuho** [comment]
Will fix them. Thanks!

**Comment by gyuho** [comment]
Just tested. Log outputting as follows:


> 19:59:30 etcd1 | 2015-12-29 19:59:30.235677 E | etcdhttp: etcdserver: request timed out, possibly due to previous leader failure [merged 1 repeated lines in 1.38s]
> 19:59:32 etcd1 | 2015-12-29 19:59:32.235674 E | etcdhttp: etcdserver: request timed out, possibly due to previous leader failure [merged 7 repeated lines in 2s]
> 19:59:34 etcd1 | 2015-12-29 19:59:34.235644 E | etcdhttp: etcdserver: request timed out, possibly due to previous leader failure [merged 7 repeated lines in 2s]

**Comment by xiang90** [comment]
LGTM. Thanks for fixing this!

**Comment by gyuho** [comment]
Thanks!

**Pull request merged**
