### PR TITLE
build: do not build internal debugging tool

### PR DESCRIPTION
**Pull request by xiang90**
We are still playing around with the dump-log tool.
Stop building it publicly until we are happy with its
ux and functionality.

/cc @philips

### CODE REVIEW

**Comment by philips** [comment]
what about etcd-migrat? It is largely unneeded now that migrate has been integrated into etcd itself, right?

**Comment by xiang90** [comment]
@philips 
> what about etcd-migrat?
https://github.com/coreos/etcd/blob/master/Documentation/0_4_migration_tool.md
we have doc for that. 

>  It is largely unneeded now that migrate has been integrated into etcd itself, right?
right. So I am not sure if any one still needs that tool though. 

any thoughts @barakmich ?

**Comment by yichengq** [comment]
@philips @xiang90 Could we build internal/experimental ones into another directory? These ones can help development.

**Comment by yichengq** [comment]
@philips @xiang90 Moving into another dir makes the file organization much complicated, and i can build it locally. This approach lgtm

**Comment by barakmich** [comment]
Yeah, it's integrated mostly into etcd itself. With import/export as tools this also gets (slightly) obviated. I'm fine with this change.

**Comment by barakmich** [comment]
LGTM

**Pull request merged**
