### PR TITLE
Dockerfile: use /var/lib/etcd as default data dir

### PR DESCRIPTION
**Pull request by gyuho**

### CODE REVIEW

**Comment by xiang90** [comment]
well... shall we just revert that pr then? what are the other stuff we have changed?

**Comment by gyuho** [comment]
@xiang90 Yeah let's revert it. Here https://github.com/coreos/etcd/pull/5937.

And I think we should use `/var/lib/etcd` too, following this example? https://github.com/coreos/etcd/blob/master/contrib/systemd/etcd.service

**Comment by xiang90** [comment]
what was it before? i do not want to change it if it was /var/etcd. it can break users after they use new image.

**Comment by gyuho** [comment]
@xiang90 There was no default data dir before. It just `mkdir -p /var/etcd`.

If people run etcd in docker before without any flag, it will default to `default.data`.

**Comment by xiang90** [comment]
If you change the default data dir, then it breaks existing users. after they restart etcd with new image, they cannot find the old data-dir since the default location changed. no?

**Comment by gyuho** [comment]
Yeah you are right. Let's keep it as it is now.

Thanks!

**Pull request closed without merging**
