### PR TITLE
*: fixed some  warning

### PR DESCRIPTION
**Pull request by davygeek**

### CODE REVIEW

**Comment by gyuho** [comment]
LGTM. 

Not sure about changing the casing (might break compatibility?)

Defer to @xiang90 and @heyitsanthony 

Thanks!

**Comment by heyitsanthony** [comment]
@davygeek what's giving the warnings? golint?

**Comment by davygeek** [comment]
@heyitsanthony  I use warning maybe not good, just coding style 
golint notice as follow
"can probably use "var newp []*rangePerm" instead"
"struct field DnsCluster should be DNSCluster"
"should replace nSet += 1 with nSet++"

I think use golint easy to unify code style

**Comment by xiang90** [comment]
lgtm

**Pull request merged**
