### PR TITLE
*: fix TLS reload when cert includes only IPs (no domain names in SAN field)

### PR DESCRIPTION
**Pull request by gyuho**
This fixes TLS reload when [certificate SAN field only includes IP addresses but no domain names](https://github.com/coreos/etcd/issues/9541). For example, a member is set up with CSRs (with `cfssl`) as below:

```json
{
  "hosts": [
    "127.0.0.1"
  ],
```

In Go, server calls `(*tls.Config).GetCertificate` for TLS reload if and only if server's `(*tls.Config).Certificates` field is not empty, or `(*tls.ClientHelloInfo).ServerName` is not empty with a valid SNI from the client. Previously, etcd always populates `(*tls.Config).Certificates` on the initial client TLS handshake, as non-empty. Thus, client was always expected to supply a matching SNI in order to pass the TLS verification and to trigger `(*tls.Config).GetCertificate` to reload TLS assets.

However, a certificate whose SAN field does [not include any domain names but only IP addresses](https://github.com/coreos/etcd/issues/9541) would request `*tls.ClientHelloInfo` with an empty `ServerName` field, thus failing to trigger the TLS reload on initial TLS handshake; this becomes a problem when expired certificates need to be replaced online.

Now, `(*tls.Config).Certificates` is created empty on initial TLS client handshake, first to trigger `(*tls.Config).GetCertificate` and populate rest of the certificates on every new TLS connection, even when client SNI is empty (e.g. cert only includes IPs).

Fix commit was authored by @roboll https://github.com/coreos/etcd/pull/9542, and I am adding related integration test fixes and documentation.

### CODE REVIEW

**Comment by roboll** [comment]
Thanks @gyuho - I will run this build on Monday and verify.

**Comment by roboll** [comment]
:+1: Working as expected.

**Comment by roboll** [comment]
@gyuho when can we expect a release that incorporates this?

**Comment by gyuho** [comment]
@roboll Yes, we will release this in next 3.2 and 3.3. Hopefully, by next week. Thanks!

**Pull request merged**
