### PR TITLE
Documentation: remove replace non-recoverable member

### PR DESCRIPTION
**Pull request by philips**
This is not really the common case at all and I don't know how useful it
is to document it here instead of pointing people at the disaster docs
instead.

### CODE REVIEW

**Comment by robszumski** [comment]
Agree. If you want to cycle through machines due to maintenance, this is the first thing you encounter on the page. It leads you to believe this is the best way to do that, but it's not and it takes longer + requires more steps.

**Comment by xiang90** [comment]
@philips This is different from disaster recovery. Your cluster is still running at this point. I do not think increase/decrease the cluster size should be frequent than this.

@robszumski  

> If you want to cycle through machines due to maintenance, this is the first thing you encounter on the page.

You do not need to do runtime-reconfiguration for scheduled maintenance.

**Comment by robszumski** [comment]
@xiang90 If you are decommissioning a zone that has two of your 5 machines in it, wouldn't you follow the steps to remove a member and then add a member for each of the 2 machines? It seems silly to move the data directory around when etcd will do all of that cleanly and automatically.

**Comment by xiang90** [comment]
@robszumski 

>  If you are decommissioning a zone that has two of your 5 machines in it, wouldn't you follow the steps to remove a member and then add a member for each of the 2 machines? It seems silly to move the data directory around when etcd will do all of that cleanly and automatically.

No. We should recommend people move the data-dir and update the peer url. It is not silly. It is safe.

**Comment by philips** [comment]
It does seem rather complicated compared to removing and adding. I am fine
documenting it but it is not really a common case.

**Comment by xiang90** [comment]
@philips 
> It does seem rather complicated compared to removing and adding. I am fine
documenting it but it is not really a common case.

1. Remove; Add; Start with configuration.

2. Copy data; Update url; Start with configuration.

They all have 3 steps. I think it does not increase complexity a lot.

There are exact 3 cases we recommend people to use reconfiguration to solve:

1. replace non-recoverable member
2. increase size
3. decrease size

I am fine with move 1 to the last one, but not remove it.

**Comment by philips** [comment]
On Wed, Jan 28, 2015 at 8:47 PM, Xiang Li <notifications@github.com> wrote:
>
> It does seem rather complicated compared to removing and adding. I am fine
> documenting it but it is not really a common case.
>
> Remove; Add; Start with configuration.
>
> Copy data; Update url; Start with configuration.
>
> They all have 3 steps. I think it does not increase complexity a lot.

In almost all cases the data will no longer exist:

- cloud: the host's disks will be destroyed,
- physical: pulling disks from failed server is more complicated than
just starting a new one

What I am trying to say is that "copy the data" is either impossible
or more difficult than just removing the member and adding a new one
and letting etcd take care of getting the data to the new member.

Brandon

**Comment by xiang90** [comment]
> - cloud: the host's disks will be destroyed,
- physical: pulling disks from failed server is more complicated than
just starting a new one

If the data is lost or impossible to be recovered, people can follow `replace non-recoverable member`. And as you mentioned, this might be the most common case. So we should still put it at the first instead of removing it.

etcd is not suitable for replicating a large amount of data and we should not recommend people to use run time reconfiguration when it is not necessary. Replicating a lot of entries at once might create problems. Also we will do lazy-snapshoting soon. If people can copy the local data and replicate it outside etcd, we should recommend it.

> more difficult than just removing the member and adding a new one
and letting etcd take care of getting the data to the new member.

In my opinion, keeping etcd as stable as possible is more important than doing some cumbersome things manually.

**Comment by philips** [comment]
On Wed, Jan 28, 2015 at 9:34 PM, Xiang Li <notifications@github.com> wrote:
>
> If the data is lost or impossible to be recovered, people can follow replace non-recoverable member. And as you mentioned, this might be the most common case. So we should still put it at the first instead of removing it.
>
> etcd is not suitable for replicating a large amount of data and we should not recommend people to use run time reconfiguration when it is not necessary. Replicating a lot of entries at once might create problems. Also we will do lazy-snapshoting soon. If people can copy the local data and replicate it outside etcd, we should recommend it.

I understand but this feels like an "advanced topic" for users that
have so much data that it would put strain on their system to
replicate a full log and snapshot. Most logs are under a few megabytes
and large users are likely a few hundred megabytes at most at this
point.

Brandon

**Comment by xiang90** [comment]
> I understand but this feels like an "advanced topic" for users that
have so much data that it would put strain on their system to
replicate a full log and snapshot. Most logs are under a few megabytes
and large users are likely a few hundred megabytes at most at this
point.

For the user who has a few megabytes of data, I would say "do which you feel is easier". I am fine with rewrite this section instead of removing it. I will try to clarify the problem.

**Comment by yichengq** [comment]
I am agree with @xiang90 on this.

@philips 
Replace a non-recoverable member is as frequent as increase/decrease size. When etcd runs in production environment, it is in a dedicated cluster. 1 in 3 laptops fail over 3 years, which means that this case happens once per several year. This should be the same frequency with cluster change, which happens only when the size of the whole cluster changes dramatically.

@robszumski 
It is easy to remove and add back, but it may cause trouble in a production env.
1. We don't want user to rely on runtime reconfiguration heavily because there must be something wrong if so. As the above says, runtime reconfiguration should happen at most several times per year.
2. Add back implies the transmission of latest snapshot.
(a) User is able to specify a better way to do so. For example, if it is a global cluster, user may select high-throughput way to transmit data.
(b) For maintenance, replace can result in nearly zero downtime of the replaced machine because the transmission of snapshot can happen before the switch, when remove and add back may use much more time because it needs to transmit the full snapshot.

We definitely support these features, and are also doing our best to find and recommend the best way.

**Comment by xiang90** [comment]
@philips covered by @2193

**Pull request closed without merging**
