### PR TITLE
WIP, DO NOT MERGE, RFC, *: do permission check in raft leader

### PR DESCRIPTION
**Pull request by mitake**
I'm working on the permission checking mechanism of the v3 API auth. As described in the design doc, the checking mechanism will be added to Raft leader node logic, stepLeader().

I'd like to hear opinions about how to drop requests that is denied because of permission. Will the best way of dropping be something like sending a vote rejection message to a campaigning node?

In addition, how should we treat a message that has both of entries with valid permissions and others with invalid permission? Is simply applying valid entries ok?

/cc @xiang90 @ark76r

### CODE REVIEW

**Comment by xiang90** [comment]
> the checking mechanism will be added to Raft leader node logic, stepLeader().

I am still not convinced that raft needs to understand auth.

**Comment by xiang90** [comment]
>  add a permission checking mechanism to the raft leader for linearizable read and write

Those requests will go through raft and be serialized. So we do not need to do anything with them. We just need to check the permission at the apply phase instead of when they arrive at API layer.

**Comment by mitake** [comment]
Maybe the checking can be done in the log entry applying mechanism. If we do this, needless (invalid permission) log entries would be replicated to followers but the raft isn't needed to be modified.

How do you think? Modifying the raft would be costly so checking in the apply phase would be simpler.

**Comment by mitake** [comment]
OK, I'll add the checking mechanism in the apply phase.

**Comment by xiang90** [comment]
https://github.com/coreos/etcd/blob/master/etcdserver/apply.go#L114 -> here for txn, put, delete, range, etc.

**Comment by mitake** [comment]
Yes, the functions seem to be suitable places for the checking. I'll open another PR for that.

**Comment by xiang90** [comment]
> If we do this, needless (invalid permission) log entries would be replicated 

If we want to provide "ddos" for bad users, we can add a fast-fail auth check at API layer.

**Comment by mitake** [comment]
> If we want to provide "ddos" for bad users, we can add a fast-fail auth check at API layer.

I agree. It would be also interesting from the perspective of quoting physical disk consumption of log entries. It would be worth to discuss in the future.

**Pull request closed without merging**
