### PR TITLE
test: Run integration pass in series

### PR DESCRIPTION
**Pull request by glevand**
I split these two patches out from https://github.com/coreos/etcd/pull/6486.

### CODE REVIEW

**Comment by heyitsanthony** [comment]
I guess this is OK as a stop-gap for forcing the tests to be serial but I'm kind of leaning toward having separate passes (`e2e_pass` and `integration_pass` to get serialized, `integration_e2e_pass` to get parallel) instead of the one-off `SERIAL_TESTS` flag. What do you think?

**Comment by glevand** [comment]
That seems better.  I don't like this flag.

**Comment by glevand** [comment]
Rebased to latest and changed to ```e2e_pass``` and ```integration_pass``` and ```integration_e2e_pass```.

**Comment by glevand** [comment]
Fixed double integration run.

**Comment by heyitsanthony** [comment]
lgtm

**Comment by glevand** [comment]
Once this is merged we'll need to update the semaphore job to add back the e2e test.

**Pull request merged**
