### PR TITLE
*: fix watch full key range

### LINKED ISSUE #4697: watch prefix issues
In client library and storage range/delete, we treat `/x00` as the largest key if it is in "end".

However in interval tree, we treat empty as the largest key.https://github.com/coreos/etcd/blob/master/pkg/adt/interval_tree.go#L474

So now watch("", WithPrefix()) does not work.

@heyitsanthony What is your opinion on this one? Shall we convert /x00 to empty string and empty string to /x00 before pass into watch? This seems to be the easies fix, but it also makes range/delete and watch different.

### PR DESCRIPTION
**Pull request by xiang90**
Fix #4697 

/cc @heyitsanthony

### CODE REVIEW

**Comment by heyitsanthony** [comment]
should this do something about end "\x00" => "" too?

Probably needs a unit test.

**Comment by xiang90** [comment]
> should this do something about end "\x00" => "" too?

I think you already did this check line 118 right after my change.

I will add test.

**Comment by heyitsanthony** [comment]
Oops, you're right.

**Comment by xiang90** [comment]
@heyitsanthony PTAL.

**Comment by heyitsanthony** [comment]
lgtm

**Pull request merged**
