### PR TITLE
v3rpc: fix race on ctrl channel when watcher stream closes

### PR DESCRIPTION
**Pull request by heyitsanthony**

### CODE REVIEW

**Comment by gyuho** [comment]
lgtm. defer to @xiang90

**Comment by gyuho** [comment]
How about this https://github.com/coreos/etcd/blob/master/clientv3/watch.go#L558? Could `ws.lastRev` be under race condition in the same manner?

**Comment by heyitsanthony** [comment]
@gyuho it looks like a deadlock there-- the write to `resumec` could block forever if the `serveStream` reading it is canceled via the `ctx` passed through `Watch(ctx, ...)`.

**Comment by xiang90** [comment]
lgtm

**Pull request merged**
