### PR TITLE
etcdserver: check index of the kv when restarting

### PR DESCRIPTION
**Pull request by xiang90**
/cc @heyitsanthony @gyuho

### CODE REVIEW

**Comment by heyitsanthony** [comment]
lgtm

**Comment by gyuho** [comment]
lgtm. thanks!

**Comment by binwiederhier** [comment]
Hey @xiang90 would you mind looking at this if you find the time: https://github.com/coreos/etcd/pull/5780 -- This pull seems to have added the db corruption check, but that now leads to unrecoverable scenarios if the machine reboots, e.g. due to a power outage.

**Comment by xiang90** [comment]
> but that now leads to unrecoverable scenarios if the machine reboots, e.g. due to a power outage.

Can you give me more details? Have you met this issue in practice, or in theory?

Power outage should be fine. The index checking should be OK since we sync the db before sync the metatdata for matching.

**Pull request merged**
