### PR TITLE
ctlv3: fix line parsing for Windows

### PR DESCRIPTION
**Pull request by sinsharat**
#6385

### CODE REVIEW

**Comment by xiang90** [comment]
lgtm. Defer to @heyitsanthony

**Comment by heyitsanthony** [comment]
lgtm

**Comment by xiang90** [comment]
@sinsharat Thank you!

**Comment by sinsharat** [comment]
@xiang90 i am actually thankful to you for helping me out. I will always try to contribute to etcd in whichever way i can.
Thanks once again.

**Pull request merged**
