### PR TITLE
Documentation/security: Fix links about tls keygen.

### PR DESCRIPTION
**Pull request by joshix**
Edit to replace a relative link (won't work with that target) with
an absolute link.
Heading 1 Title Case.
Polish graf 3.

Fixes https://github.com/coreos/docs/issues/662

### CODE REVIEW

**Comment by yichengq** [comment]
LGTM

**Comment by kayrus** [comment]
Should we use a link to [this doc](https://github.com/coreos/docs/blob/master/os/generate-self-signed-certificates.md) instead of http://www.g-loaded.eu/2005/11/10/be-your-own-ca/?

**Comment by yichengq** [comment]
@kayrus We have mentioned cfssl way in the first sentence in the paragraph. This link is to provide another way to generate certificates.

**Comment by kayrus** [comment]
Should we provide some kind of official way on how to generate tls certs and avoid external links?

**Comment by joshix** [comment]
@kayrus Yes, but I wasn't worried about it when merging this. The CA-based directions linked to are preferable to the self-signed stuff we currently have, so I let the link stand until we can change our docs to push the CA method.

**Pull request merged**
