### PR TITLE
extend hardcoded timeout for globally-deployed etcd cluster

### PR DESCRIPTION
**Pull request by yichengq**
I have manually set three physical machines and let messages from one peer to another have 2.5s delay. After applying this PR, a 3-member cluster could work well, including bootstrap, catch-up leader, client boom requests.

for #964

### CODE REVIEW

**Comment by yichengq** [comment]
PTAL

**Comment by xiang90** [comment]
We should not encourage people to do global deployment. We just make sure it works...

**Comment by yichengq** [comment]
@xiang90 My thought is that global deployment should be rare, and the fact that etcd could run smoothly in this case is good enough.

**Comment by xiang90** [comment]
LGTM

**Pull request merged**
