### PR TITLE
RFC: proxy: basic proxy status/stats

### PR DESCRIPTION
**Pull request by bakins**
request for comment.

Simple start of proxy specific status/stats. Currently, just show the current endpoint the proxy is using. This may be useful as the list can change through the lifetime of the proxy.

We do not have a way to see the list of endpoints except by looking at the proxy's "state file". This is a rough start, but demonstrates the idea.  We could add some counters/timings which may be helpful to find a misbehaving proxy and/or server.

### CODE REVIEW

**Comment by yichengq** [comment]
I like this general idea. The endpoint could also shows the number of connections to each endpoint, the latency and throughput of each endpoint in the futre.

**Comment by bakins** [comment]
We would have to refactor a few internal things in the cluster, but that is the general idea.  Just number of requests/errors would be helpful.

**Comment by mx2323** [comment]
yeah that one looks about right.

michael

On Tue, Aug 25, 2015 at 5:02 PM, Xiang Li <notifications@github.com> wrote:

> /cc @mx2323 <https://github.com/mx2323> You also want this one, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/coreos/etcd/pull/2727#issuecomment-134773960>.
>



-- 
Michael Xu
(770)634-1738
Computer Science
Georgia Tech

**Comment by xiang90** [comment]
Close in favor of #3533

**Pull request closed without merging**
