### PR TITLE
Correct calculation of fault tolerance of an etcd cluster

### PR DESCRIPTION
**Pull request by raoofm**
Correct calculation of fault tolerance of an etcd cluster.

### CODE REVIEW

**Comment by raoofm** [comment]
fixes #3369

**Comment by xiang90** [comment]
Can you change the commit message to `doc: correct calculation of fault tolerance of an etcd cluster in cluster.md`? Thanks!

/cc @yichengq

**Comment by yichengq** [comment]
lgtm after updating the commit title

**Comment by raoofm** [comment]
@xiang90 you mean admin_guide.md right?

**Comment by xiang90** [comment]
@raoofm Yes. My mistake. Sorry.

**Comment by raoofm** [comment]
Done

**Comment by xiang90** [comment]
@raoofm Can you do a rebase instead of merging with the master? Now there are two commits.

**Comment by xiang90** [comment]
@raoofm Kindly ping.

**Comment by xiang90** [comment]
Closed in favor of #3387. Thanks for your contribution.

**Comment by raoofm** [comment]
Thanks

**Pull request closed without merging**
