### PR TITLE
doc/libraries-and-tools.md: add .net client library

### PR DESCRIPTION
**Pull request by wangjia184**

### CODE REVIEW

**Comment by xiang90** [comment]
Can you change the commit message to `doc/libraries-and-tools.md: add .net client library`?

We want to follow subsystem: commit message format.

**Comment by wangjia184** [comment]
Update doc, add link to EtcdNet, which is client library for .NET https://github.com/wangjia184/etcdnet

**Comment by xiang90** [comment]
@wangjia184 I mean the commit message of git. You can do `git commit --amend` to modify the commit message and then do a force push `git push -f`

**Comment by wangjia184** [comment]
Done

**Comment by xiang90** [comment]
Thanks.

**Pull request merged**
