### PR TITLE
migrate/starter: fix v2 data dir checking

### PR DESCRIPTION
**Pull request by yichengq**
/cc @jedsmith @barakmich

### CODE REVIEW

**Comment by barakmich** [comment]
I believe this is right, but why are we duplicating this logic here and in etcdserver?

**Comment by yichengq** [comment]
@barakmich I have no way to detect proxy through wal.DetectVersion, which is only used in etcdserver.

**Comment by barakmich** [comment]
it could be added to wal.DetectVersion. Regardless, the two exit points are technically not the same version -- they're slightly different, but (in the case of the calling function) are treated the same. Or at least that's how I'd make the funciton work.

**Comment by yichengq** [comment]
@barakmich  PTAL

**Comment by barakmich** [comment]
LGTM (also nice that it's now a net negative code change :) )

**Pull request merged**
