### PR TITLE
proxy: shorter refresh interval for initial set-up

### PR DESCRIPTION
**Pull request by gyuho**
This is a hacky way to expedite some proxy refresh for https://github.com/coreos/etcd/issues/3647.

The current default proxy refresh interval is [30 seconds](https://github.com/coreos/etcd/blob/master/etcdmain/config.go#L192). If the director has
no endpoint list yet, it has to wait 30 seconds to refresh. For the initial
iterations, we can shorten the intervals to decrease the wait time.

/cc @yichengq 

I couldn't reproduce the delay as described in the issue. Do you know the cause of the issue?
Please let me know if you have any feedback!

### CODE REVIEW

**Comment by yichengq** [comment]
@gyuho You should reproduce it before actually fixing it. For me, it happens if run `goreman start` in local machine.

**Comment by gyuho** [comment]
@yichengq do you have commit sha that has this issue? I built from latest master branch but cannot reproduce. (I go build in master branch and updated Procfile with `./etcd`)


```
15:17:57 etcd2 | Starting etcd2 on port 5001
15:17:57 etcd3 | Starting etcd3 on port 5002
15:17:57 proxy | Starting proxy on port 5003
15:17:57 etcd1 | Starting etcd1 on port 5000
15:17:57 etcd2 | 2015-10-23 15:17:57.615381 I | etcdmain: etcd Version: 2.2.0+git
15:17:57 etcd2 | 2015-10-23 15:17:57.615461 I | etcdmain: Git SHA: Not provided (use ./build instead of go build)
15:17:57 etcd2 | 2015-10-23 15:17:57.615477 I | etcdmain: Go Version: go1.5.1
15:17:57 etcd2 | 2015-10-23 15:17:57.615486 I | etcdmain: Go OS/Arch: linux/amd64
15:17:57 etcd2 | 2015-10-23 15:17:57.615494 I | etcdmain: setting maximum number of CPUs to 8, total number of available CPUs is 8
15:17:57 etcd2 | 2015-10-23 15:17:57.615505 W | etcdmain: no data-dir provided, using default data-dir ./infra2.etcd
15:17:57 etcd2 | 2015-10-23 15:17:57.615606 I | etcdmain: listening for peers on http://127.0.0.1:22380
15:17:57 etcd2 | 2015-10-23 15:17:57.615649 I | etcdmain: listening for client requests on http://127.0.0.1:22379
15:17:57 etcd2 | 2015-10-23 15:17:57.616206 I | etcdserver: name = infra2
15:17:57 etcd2 | 2015-10-23 15:17:57.616218 I | etcdserver: data dir = infra2.etcd
15:17:57 etcd2 | 2015-10-23 15:17:57.616224 I | etcdserver: member dir = infra2.etcd/member
15:17:57 etcd2 | 2015-10-23 15:17:57.616229 I | etcdserver: heartbeat = 100ms
15:17:57 etcd2 | 2015-10-23 15:17:57.616236 I | etcdserver: election = 1000ms
15:17:57 etcd2 | 2015-10-23 15:17:57.616243 I | etcdserver: snapshot count = 10000
15:17:57 etcd2 | 2015-10-23 15:17:57.616257 I | etcdserver: advertise client URLs = http://127.0.0.1:22379
15:17:57 etcd2 | 2015-10-23 15:17:57.616267 I | etcdserver: initial advertise peer URLs = http://127.0.0.1:22380
15:17:57 etcd2 | 2015-10-23 15:17:57.616290 I | etcdserver: initial cluster = infra1=http://127.0.0.1:12380,infra2=http://127.0.0.1:22380,infra3=http://127.0.0.1:32380
15:17:57 etcd1 | 2015-10-23 15:17:57.616314 I | etcdmain: etcd Version: 2.2.0+git
15:17:57 etcd3 | 2015-10-23 15:17:57.616374 I | etcdmain: etcd Version: 2.2.0+git
15:17:57 etcd3 | 2015-10-23 15:17:57.616435 I | etcdmain: Git SHA: Not provided (use ./build instead of go build)
15:17:57 etcd3 | 2015-10-23 15:17:57.616444 I | etcdmain: Go Version: go1.5.1
15:17:57 etcd3 | 2015-10-23 15:17:57.616453 I | etcdmain: Go OS/Arch: linux/amd64
15:17:57 etcd3 | 2015-10-23 15:17:57.616461 I | etcdmain: setting maximum number of CPUs to 8, total number of available CPUs is 8
15:17:57 etcd3 | 2015-10-23 15:17:57.616480 W | etcdmain: no data-dir provided, using default data-dir ./infra3.etcd
15:17:57 etcd3 | 2015-10-23 15:17:57.616579 I | etcdmain: listening for peers on http://127.0.0.1:32380
15:17:57 etcd3 | 2015-10-23 15:17:57.616616 I | etcdmain: listening for client requests on http://127.0.0.1:32379
15:17:57 etcd1 | 2015-10-23 15:17:57.616483 I | etcdmain: Git SHA: Not provided (use ./build instead of go build)
15:17:57 etcd1 | 2015-10-23 15:17:57.616523 I | etcdmain: Go Version: go1.5.1
15:17:57 etcd1 | 2015-10-23 15:17:57.616534 I | etcdmain: Go OS/Arch: linux/amd64
15:17:57 etcd1 | 2015-10-23 15:17:57.616542 I | etcdmain: setting maximum number of CPUs to 8, total number of available CPUs is 8
15:17:57 etcd1 | 2015-10-23 15:17:57.616552 W | etcdmain: no data-dir provided, using default data-dir ./infra1.etcd
15:17:57 etcd1 | 2015-10-23 15:17:57.616630 I | etcdmain: listening for peers on http://127.0.0.1:12380
15:17:57 etcd1 | 2015-10-23 15:17:57.616665 I | etcdmain: listening for client requests on http://127.0.0.1:12379
15:17:57 proxy | 2015-10-23 15:17:57.616176 I | etcdmain: etcd Version: 2.2.0+git
15:17:57 proxy | 2015-10-23 15:17:57.616227 I | etcdmain: Git SHA: Not provided (use ./build instead of go build)
15:17:57 proxy | 2015-10-23 15:17:57.616235 I | etcdmain: Go Version: go1.5.1
15:17:57 proxy | 2015-10-23 15:17:57.616242 I | etcdmain: Go OS/Arch: linux/amd64
15:17:57 proxy | 2015-10-23 15:17:57.616250 I | etcdmain: setting maximum number of CPUs to 8, total number of available CPUs is 8
15:17:57 proxy | 2015-10-23 15:17:57.616260 W | etcdmain: no data-dir provided, using default data-dir ./infra-proxy1.etcd
15:17:57 proxy | 2015-10-23 15:17:57.616379 I | etcdmain: proxy: using peer urls [http://127.0.0.1:12380 http://127.0.0.1:22380 http://127.0.0.1:32380] 
15:17:57 proxy | 2015-10-23 15:17:57.616537 W | etcdserver: could not get cluster response from http://127.0.0.1:12380: Get http://127.0.0.1:12380/members: dial tcp 127.0.0.1:12380: getsockopt: connection refused
15:17:57 etcd2 | 2015-10-23 15:17:57.623975 I | etcdserver: starting member 91bc3c398fb3c146 in cluster ef37ad9dc622a7c4
15:17:57 etcd2 | 2015-10-23 15:17:57.624029 I | raft: 91bc3c398fb3c146 became follower at term 0
15:17:57 etcd2 | 2015-10-23 15:17:57.624041 I | raft: newRaft 91bc3c398fb3c146 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
15:17:57 etcd2 | 2015-10-23 15:17:57.624046 I | raft: 91bc3c398fb3c146 became follower at term 1
15:17:57 etcd2 | 2015-10-23 15:17:57.632001 I | etcdserver: starting server... [version: 2.2.0+git, cluster version: to_be_decided]
15:17:57 etcd2 | 2015-10-23 15:17:57.632599 N | etcdserver: added member 8211f1d0f64f3269 [http://127.0.0.1:12380] to cluster ef37ad9dc622a7c4
15:17:57 etcd2 | 2015-10-23 15:17:57.632666 N | etcdserver: added local member 91bc3c398fb3c146 [http://127.0.0.1:22380] to cluster ef37ad9dc622a7c4
15:17:57 etcd2 | 2015-10-23 15:17:57.632727 N | etcdserver: added member fd422379fda50e48 [http://127.0.0.1:32380] to cluster ef37ad9dc622a7c4
15:17:57 proxy | 2015-10-23 15:17:57.632984 I | etcdmain: proxy: listening for client requests on http://127.0.0.1:2379
15:17:57 etcd1 | 2015-10-23 15:17:57.632763 I | etcdserver: name = infra1
15:17:57 etcd1 | 2015-10-23 15:17:57.632779 I | etcdserver: data dir = infra1.etcd
15:17:57 etcd1 | 2015-10-23 15:17:57.632788 I | etcdserver: member dir = infra1.etcd/member
15:17:57 etcd1 | 2015-10-23 15:17:57.632794 I | etcdserver: heartbeat = 100ms
15:17:57 etcd1 | 2015-10-23 15:17:57.632799 I | etcdserver: election = 1000ms
15:17:57 etcd1 | 2015-10-23 15:17:57.632804 I | etcdserver: snapshot count = 10000
15:17:57 etcd1 | 2015-10-23 15:17:57.632815 I | etcdserver: advertise client URLs = http://127.0.0.1:12379
15:17:57 etcd1 | 2015-10-23 15:17:57.632822 I | etcdserver: initial advertise peer URLs = http://127.0.0.1:12380
15:17:57 etcd1 | 2015-10-23 15:17:57.632860 I | etcdserver: initial cluster = infra1=http://127.0.0.1:12380,infra2=http://127.0.0.1:22380,infra3=http://127.0.0.1:32380
15:17:57 etcd1 | 2015-10-23 15:17:57.640306 I | etcdserver: starting member 8211f1d0f64f3269 in cluster ef37ad9dc622a7c4
15:17:57 etcd1 | 2015-10-23 15:17:57.640346 I | raft: 8211f1d0f64f3269 became follower at term 0
15:17:57 etcd1 | 2015-10-23 15:17:57.640356 I | raft: newRaft 8211f1d0f64f3269 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
15:17:57 etcd1 | 2015-10-23 15:17:57.640360 I | raft: 8211f1d0f64f3269 became follower at term 1
15:17:57 etcd2 | 2015-10-23 15:17:57.641957 I | rafthttp: the connection with 8211f1d0f64f3269 became active
15:17:57 etcd1 | 2015-10-23 15:17:57.642059 I | rafthttp: the connection with 91bc3c398fb3c146 became active
15:17:57 etcd1 | 2015-10-23 15:17:57.648153 I | etcdserver: starting server... [version: 2.2.0+git, cluster version: to_be_decided]
15:17:57 etcd1 | 2015-10-23 15:17:57.650134 N | etcdserver: added local member 8211f1d0f64f3269 [http://127.0.0.1:12380] to cluster ef37ad9dc622a7c4
15:17:57 etcd1 | 2015-10-23 15:17:57.650901 N | etcdserver: added member 91bc3c398fb3c146 [http://127.0.0.1:22380] to cluster ef37ad9dc622a7c4
15:17:57 etcd1 | 2015-10-23 15:17:57.651006 N | etcdserver: added member fd422379fda50e48 [http://127.0.0.1:32380] to cluster ef37ad9dc622a7c4
15:17:57 etcd3 | 2015-10-23 15:17:57.651011 I | etcdserver: name = infra3
15:17:57 etcd3 | 2015-10-23 15:17:57.651025 I | etcdserver: data dir = infra3.etcd
15:17:57 etcd3 | 2015-10-23 15:17:57.651032 I | etcdserver: member dir = infra3.etcd/member
15:17:57 etcd3 | 2015-10-23 15:17:57.651038 I | etcdserver: heartbeat = 100ms
15:17:57 etcd3 | 2015-10-23 15:17:57.651044 I | etcdserver: election = 1000ms
15:17:57 etcd3 | 2015-10-23 15:17:57.651050 I | etcdserver: snapshot count = 10000
15:17:57 etcd3 | 2015-10-23 15:17:57.651061 I | etcdserver: advertise client URLs = http://127.0.0.1:32379
15:17:57 etcd3 | 2015-10-23 15:17:57.651068 I | etcdserver: initial advertise peer URLs = http://127.0.0.1:32380
15:17:57 etcd3 | 2015-10-23 15:17:57.651096 I | etcdserver: initial cluster = infra1=http://127.0.0.1:12380,infra2=http://127.0.0.1:22380,infra3=http://127.0.0.1:32380
15:17:57 etcd3 | 2015-10-23 15:17:57.656426 I | etcdserver: starting member fd422379fda50e48 in cluster ef37ad9dc622a7c4
15:17:57 etcd3 | 2015-10-23 15:17:57.656466 I | raft: fd422379fda50e48 became follower at term 0
15:17:57 etcd3 | 2015-10-23 15:17:57.656476 I | raft: newRaft fd422379fda50e48 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
15:17:57 etcd3 | 2015-10-23 15:17:57.656480 I | raft: fd422379fda50e48 became follower at term 1
15:17:57 etcd1 | 2015-10-23 15:17:57.660894 I | rafthttp: the connection with fd422379fda50e48 became active
15:17:57 etcd3 | 2015-10-23 15:17:57.661369 I | rafthttp: the connection with 8211f1d0f64f3269 became active
15:17:57 etcd3 | 2015-10-23 15:17:57.666161 I | etcdserver: starting server... [version: 2.2.0+git, cluster version: to_be_decided]
15:17:57 etcd3 | 2015-10-23 15:17:57.666985 N | etcdserver: added member 8211f1d0f64f3269 [http://127.0.0.1:12380] to cluster ef37ad9dc622a7c4
15:17:57 etcd3 | 2015-10-23 15:17:57.667120 N | etcdserver: added member 91bc3c398fb3c146 [http://127.0.0.1:22380] to cluster ef37ad9dc622a7c4
15:17:57 etcd3 | 2015-10-23 15:17:57.667254 N | etcdserver: added local member fd422379fda50e48 [http://127.0.0.1:32380] to cluster ef37ad9dc622a7c4
15:17:57 etcd3 | 2015-10-23 15:17:57.667585 I | rafthttp: the connection with 91bc3c398fb3c146 became active
15:17:57 etcd2 | 2015-10-23 15:17:57.667543 I | rafthttp: the connection with fd422379fda50e48 became active
15:17:58 etcd3 | 2015-10-23 15:17:58.056741 I | raft: fd422379fda50e48 is starting a new election at term 1
15:17:58 etcd3 | 2015-10-23 15:17:58.056769 I | raft: fd422379fda50e48 became candidate at term 2
15:17:58 etcd3 | 2015-10-23 15:17:58.056774 I | raft: fd422379fda50e48 received vote from fd422379fda50e48 at term 2
15:17:58 etcd3 | 2015-10-23 15:17:58.056782 I | raft: fd422379fda50e48 [logterm: 1, index: 3] sent vote request to 8211f1d0f64f3269 at term 2
15:17:58 etcd3 | 2015-10-23 15:17:58.056789 I | raft: fd422379fda50e48 [logterm: 1, index: 3] sent vote request to 91bc3c398fb3c146 at term 2
15:17:58 etcd1 | 2015-10-23 15:17:58.062865 I | raft: 8211f1d0f64f3269 [term: 1] received a MsgVote message with higher term from fd422379fda50e48 [term: 2]
15:17:58 etcd1 | 2015-10-23 15:17:58.062888 I | raft: 8211f1d0f64f3269 became follower at term 2
15:17:58 etcd1 | 2015-10-23 15:17:58.062921 I | raft: 8211f1d0f64f3269 [logterm: 1, index: 3, vote: 0] voted for fd422379fda50e48 [logterm: 1, index: 3] at term 2
15:17:58 etcd2 | 2015-10-23 15:17:58.062865 I | raft: 91bc3c398fb3c146 [term: 1] received a MsgVote message with higher term from fd422379fda50e48 [term: 2]
15:17:58 etcd2 | 2015-10-23 15:17:58.062888 I | raft: 91bc3c398fb3c146 became follower at term 2
15:17:58 etcd2 | 2015-10-23 15:17:58.062921 I | raft: 91bc3c398fb3c146 [logterm: 1, index: 3, vote: 0] voted for fd422379fda50e48 [logterm: 1, index: 3] at term 2
15:17:58 etcd3 | 2015-10-23 15:17:58.072206 I | raft: fd422379fda50e48 received vote from 8211f1d0f64f3269 at term 2
15:17:58 etcd3 | 2015-10-23 15:17:58.072223 I | raft: fd422379fda50e48 [q:2] has received 2 votes and 0 vote rejections
15:17:58 etcd3 | 2015-10-23 15:17:58.072253 I | raft: fd422379fda50e48 became leader at term 2
15:17:58 etcd3 | 2015-10-23 15:17:58.072269 I | raft: raft.node: fd422379fda50e48 elected leader fd422379fda50e48 at term 2
15:17:58 etcd2 | 2015-10-23 15:17:58.076446 I | raft: raft.node: 91bc3c398fb3c146 elected leader fd422379fda50e48 at term 2
15:17:58 etcd1 | 2015-10-23 15:17:58.076450 I | raft: raft.node: 8211f1d0f64f3269 elected leader fd422379fda50e48 at term 2
15:17:58 etcd3 | 2015-10-23 15:17:58.080564 I | etcdserver: setting up the initial cluster version to 2.2
15:17:58 etcd3 | 2015-10-23 15:17:58.087437 I | etcdserver: published {Name:infra3 ClientURLs:[http://127.0.0.1:32379]} to cluster ef37ad9dc622a7c4
15:17:58 etcd3 | 2015-10-23 15:17:58.107606 N | etcdserver: set the initial cluster version to 2.2
15:17:58 etcd1 | 2015-10-23 15:17:58.111934 I | etcdserver: published {Name:infra1 ClientURLs:[http://127.0.0.1:12379]} to cluster ef37ad9dc622a7c4
15:17:58 etcd1 | 2015-10-23 15:17:58.116244 N | etcdserver: set the initial cluster version to 2.2
15:17:58 etcd2 | 2015-10-23 15:17:58.125954 N | etcdserver: set the initial cluster version to 2.2
15:17:58 etcd2 | 2015-10-23 15:17:58.126025 I | etcdserver: published {Name:infra2 ClientURLs:[http://127.0.0.1:22379]} to cluster ef37ad9dc622a7c4
```

**Comment by yichengq** [comment]
If you try the redirect feature of proxy just after starting the cluster, it doesn't work:
```
unihorn@CoreOS ~/g/src> curl http://127.0.0.1:2379/v2/keys/foo                                     7
{"message":"proxy: zero endpoints currently available"}%
```

**Comment by gyuho** [comment]
@yichengq 
I got the same error message. I will look into it. Thanks!

**Pull request closed without merging**
