### PR TITLE
etcdserver: improved discard of previous uncommitted entries

### PR DESCRIPTION
**Pull request by sinsharat**
The earler processing was matching entries for index in a for loop which
would have taken longer if commited entires present were a lot more and
led to unnecessary taking more time for removing uncommited entries.
For example if st.commit = 100 and entries present in ents from index 1
to 105 then the for loop will run 101 times before it removes the 5
uncommited entries.

### CODE REVIEW

**Comment by xiang90** [comment]
I am not sure if this is necessary. Usually etcd has at most 1000s of uncommitted entries. Scanning them takes <10ms. This scan only happens once in a recovery startup phase. This patch adds complexity. Do you see any performance issue with this code in practice?

**Comment by sinsharat** [comment]
@xiang90 actually while going through this code it didn't feel right to me searching for an index in a for loop. i felt its doing too much iterations which can be got in one step. Also the logic which i put is straight forward, its just substracting the commit index with the first entry index to find the entries to keep and adding 1 to it since index starts from 0.
But ultimately you know whats best, just thought of putting my view for the code i suggested to merge.

**Comment by sinsharat** [comment]
@xiang90 what do you suggest shall i close the pull request?

**Comment by xiang90** [comment]
@sinsharat 

There are a few differences: for example, with your patch the reader needs to know that the index of the entries in the slice are increasing continuously, which is true today.  Also we need additional logic to handle < 0 index. 

I do not really have strong opinion on this change. I just do not think this is a significant improvement.

/cc @heyitsanthony opinion?

**Comment by sinsharat** [comment]
@xiang90 I totally agree with the points you put. My code is based on the assumption that the index will always be consistent, as i thought thats the behavious of raft. But if it can change in future my code will not work. Also since you mentioned that the entries will not exceed 1000 entries, i also agree with you that there will not be much difference in performance. 
Hence closing the pull request. 
Thanks for explaining your views.

**Pull request closed without merging**
