### PR TITLE
fix upgrade link and add v0.4.6 to be update

### PR DESCRIPTION
**Pull request by mingqing**

### CODE REVIEW

**Comment by yichengq** [comment]
i think it is better to keep them separated, and each document has more details about what should care when upgrade. So one document focuses on one problem. I would like to change it this way:

```
diff --git a/README.md b/README.md
index 39501f4..49ec725 100644
--- a/README.md
+++ b/README.md
@@ -79,6 +79,7 @@ Now it's time to dig into the full etcd API and other guides.
 - Use TLS to [secure an etcd cluster][security].
 - [Tune etcd][tuning].
 - [Upgrade from 0.4.6 to 2.0.0][upgrade].
+- [Upgrade from 2.0 to 2.1][upgrade2.1].

 [api]: ./Documentation/api.md
 [clustering]: ./Documentation/clustering.md
@@ -87,6 +88,7 @@ Now it's time to dig into the full etcd API and other guides.
 [security]: ./Documentation/security.md
 [tuning]: ./Documentation/tuning.md
 [upgrade]: ./tools/etcd-migrate/README.md
+[upgrade2.1]: ./Documentation/upgrade_2_1.md

 ## Contact

```

**Comment by xiang90** [comment]
@mingqing @yicheng This should be sent to 2.1 release branch, not master branch.

**Comment by yichengq** [comment]
@mingqing Are you still working on this one?

**Comment by mingqing** [comment]
@yichengq Sorry, you can close it, i thought you had fix it. Etcd is a great project, but i current work busy and not ensure enough time to contribution.

**Comment by xiang90** [comment]
@mingqing OK. Thanks!

**Pull request closed without merging**
