### PR TITLE
*: add bill of materials

### PR DESCRIPTION
**Pull request by heyitsanthony**
This does not cover all the packages in etcd.

/cc @robszumski

### CODE REVIEW

**Comment by heyitsanthony** [comment]
@robszumski it doesn't like the second [] so I manually folded the error data into the first []

**Comment by gyuho** [comment]
Do we have some script to generate this file? Or just comment here for future reference?

**Comment by heyitsanthony** [comment]
@gyuho `license-bill-of-materials github.com/coreos/etcd github.com/coreos/etcd/etcdctl`

**Comment by xiang90** [comment]
lgtm

**Comment by heyitsanthony** [comment]
A few of these are still wrong (https://github.com/coreos-inc/coreos-pages/pull/1504). I can manually fix these but now it seems like the bom stuff won't be amenable to automation any time soon. 
/cc @euank @xiang90

**Comment by heyitsanthony** [comment]
updated broken detected license, revendored gopkg.in/yaml.v2 so it has the latest / more permissive license

**Comment by philips** [comment]
These can be overridden using an override file: https://github.com/coreos/license-bill-of-materials#what-is-it

**Comment by heyitsanthony** [comment]
@philips doesn't seem to work; it only hits error/no license cases and even then I'm not seeing it show up in the list. Including an override file anyway, though.

**Comment by heyitsanthony** [comment]
Going to open an issue about automating this, but otherwise seems like if there's anything else that needs fixing it can be addressed in another PR. Merging.

**Pull request merged**
