### PR TITLE
etcdserver: preallocate slices

### PR DESCRIPTION
**Pull request by gyuho**

### CODE REVIEW

**Comment by gyuho** [comment]
/cc @heyitsanthony @xiang90 
Thanks.

**Comment by heyitsanthony** [comment]
lgtm

**Comment by xiang90** [comment]
I do not feel they actually matters since these are not on the performance path. Without adding the capacity is more readable in my opinion. (line 449 one is fine though)

**Comment by gyuho** [comment]
ok, will revert `membership` part.

**Comment by xiang90** [comment]
lgtm

**Comment by gyuho** [comment]
thanks. merging in greens.

**Pull request merged**
