### PR TITLE
etcdctl: member add command argusage to help

### LINKED ISSUE #4021: etcd member add help is not helpful
```
$ etcdctl member add --help
NAME:
   add - add a new member to the etcd cluster

USAGE:
   command add [arguments...]
```

Needs to expand to show the actual arguments and use. Or point to documentation.

### PR DESCRIPTION
**Pull request by heyitsanthony**
Fixes #4021

### CODE REVIEW

**Comment by xiang90** [comment]
also check https://github.com/coreos/etcd/pull/3912

**Comment by jonboulle** [comment]
While we're here perhaps you could add argsusage for the other subcommands too?

**Comment by heyitsanthony** [comment]
added argsusage for etcdctl commands /cc @xiangli90 @jonboulle

**Comment by xiang90** [comment]
LGTM

**Pull request merged**
