### PR TITLE
rafthttp: backoff error printout and log stream start

### PR DESCRIPTION
**Pull request by yichengq**
from #2367

### CODE REVIEW

**Comment by kelseyhightower** [comment]
@yichengq I think this change can use a better commit message. Once this change is merged what is the net result? Will etcd gain better error reporting of streaming raft messages? Or all peer messages in general.

**Comment by yichengq** [comment]
the output of a cluster that lacks one member is as this:
```
23:11:39 etcd2 | 2015/02/28 23:11:39 etcdserver: added local member 6e3bd23ae5f1eae0 [http://localhost:7002] to cluster e9c7614f68f35fb2
23:11:39 etcd1 | 2015/02/28 23:11:39 etcdserver: added member 6e3bd23ae5f1eae0 [http://localhost:7002] to cluster e9c7614f68f35fb2
23:11:39 etcd2 | 2015/02/28 23:11:39 etcdserver: added member 924e2e83e93f2560 [http://localhost:7003] to cluster e9c7614f68f35fb2
23:11:39 etcd2 | 2015/02/28 23:11:39 etcdserver: added member a8266ecf031671f3 [http://localhost:7001] to cluster e9c7614f68f35fb2
23:11:39 etcd1 | 2015/02/28 23:11:39 etcdserver: added member 924e2e83e93f2560 [http://localhost:7003] to cluster e9c7614f68f35fb2
23:11:39 etcd1 | 2015/02/28 23:11:39 etcdserver: added local member a8266ecf031671f3 [http://localhost:7001] to cluster e9c7614f68f35fb2
23:11:39 etcd2 | 2015/02/28 23:11:39 rafthttp: failed to connect 924e2e83e93f2560 in stream message: dial tcp 127.0.0.1:7003: connection refused
23:11:39 etcd2 | 2015/02/28 23:11:39 rafthttp: failed to connect 924e2e83e93f2560 in stream msgapp: dial tcp 127.0.0.1:7003: connection refused
23:11:39 etcd1 | 2015/02/28 23:11:39 rafthttp: start sending messages in stream message to 6e3bd23ae5f1eae0
23:11:39 etcd2 | 2015/02/28 23:11:39 rafthttp: start receiving messages in stream message from a8266ecf031671f3
23:11:39 etcd1 | 2015/02/28 23:11:39 rafthttp: start sending messages in stream msgapp to 6e3bd23ae5f1eae0
23:11:39 etcd2 | 2015/02/28 23:11:39 rafthttp: start sending messages in stream msgapp to a8266ecf031671f3
23:11:39 etcd2 | 2015/02/28 23:11:39 rafthttp: start receiving messages in stream msgapp from a8266ecf031671f3
23:11:39 etcd1 | 2015/02/28 23:11:39 rafthttp: failed to connect 924e2e83e93f2560 in stream message: dial tcp 127.0.0.1:7003: connection refused
23:11:39 etcd1 | 2015/02/28 23:11:39 rafthttp: failed to connect 924e2e83e93f2560 in stream msgapp: dial tcp 127.0.0.1:7003: connection refused
23:11:39 etcd1 | 2015/02/28 23:11:39 rafthttp: start receiving messages in stream msgapp from 6e3bd23ae5f1eae0
23:11:39 etcd1 | 2015/02/28 23:11:39 rafthttp: start receiving messages in stream message from 6e3bd23ae5f1eae0
23:11:39 proxy | 2015/02/28 23:11:39 proxy: listening for client requests on 127.0.0.1:8080
23:11:39 etcd2 | 2015/02/28 23:11:39 rafthttp: start sending messages in stream message to a8266ecf031671f3
23:11:41 etcd2 | 2015/02/28 23:11:41 raft: 6e3bd23ae5f1eae0 is starting a new election at term 6
23:11:41 etcd2 | 2015/02/28 23:11:41 raft: 6e3bd23ae5f1eae0 became candidate at term 7
23:11:41 etcd2 | 2015/02/28 23:11:41 raft: 6e3bd23ae5f1eae0 received vote from 6e3bd23ae5f1eae0 at term 7
23:11:41 etcd2 | 2015/02/28 23:11:41 raft: 6e3bd23ae5f1eae0 [logterm: 6, index: 329] sent vote request to 924e2e83e93f2560 at term 7
23:11:41 etcd2 | 2015/02/28 23:11:41 raft: 6e3bd23ae5f1eae0 [logterm: 6, index: 329] sent vote request to a8266ecf031671f3 at term 7
23:11:41 etcd1 | 2015/02/28 23:11:41 raft: a8266ecf031671f3 [term: 6] received a MsgVote message with higher term from 6e3bd23ae5f1eae0 [term: 7]
23:11:41 etcd1 | 2015/02/28 23:11:41 raft: a8266ecf031671f3 became follower at term 7
23:11:41 etcd1 | 2015/02/28 23:11:41 raft: a8266ecf031671f3 [logterm: 6, index: 329, vote: 0] voted for 6e3bd23ae5f1eae0 [logterm: 6, index: 329] at term 7
23:11:41 etcd2 | 2015/02/28 23:11:41 rafthttp: failed to post 924e2e83e93f2560 in pipeline: dial tcp 127.0.0.1:7003: connection refused
23:11:41 etcd2 | 2015/02/28 23:11:41 raft: 6e3bd23ae5f1eae0 received vote from a8266ecf031671f3 at term 7
23:11:41 etcd2 | 2015/02/28 23:11:41 raft: 6e3bd23ae5f1eae0 [q:2] has received 2 votes and 0 vote rejections
23:11:41 etcd2 | 2015/02/28 23:11:41 raft: 6e3bd23ae5f1eae0 became leader at term 7
23:11:41 etcd2 | 2015/02/28 23:11:41 raft.node: 6e3bd23ae5f1eae0 elected leader 6e3bd23ae5f1eae0 at term 7
23:11:41 etcd1 | 2015/02/28 23:11:41 raft.node: a8266ecf031671f3 elected leader 6e3bd23ae5f1eae0 at term 7
23:11:41 etcd1 | 2015/02/28 23:11:41 raft: a8266ecf031671f3 [logterm: 0, index: 333] rejected msgApp [logterm: 7, index: 333] from 6e3bd23ae5f1eae0
23:11:41 etcd2 | 2015/02/28 23:11:41 raft: 6e3bd23ae5f1eae0 received msgApp rejection(lastindex: 330) from a8266ecf031671f3 for index 333
23:11:41 etcd2 | 2015/02/28 23:11:41 raft: 6e3bd23ae5f1eae0 decreased progress of a8266ecf031671f3 to [next = 331, match = 330, wait = 0]
23:11:41 etcd2 | 2015/02/28 23:11:41 rafthttp: start sending messages in stream msgapp to a8266ecf031671f3
23:11:41 etcd1 | 2015/02/28 23:11:41 rafthttp: start receiving messages in stream msgapp from 6e3bd23ae5f1eae0
23:11:41 etcd2 | 2015/02/28 23:11:41 etcdserver: published {Name:infra2 ClientURLs:[http://localhost:4002]} to cluster e9c7614f68f35fb2
23:11:41 etcd1 | 2015/02/28 23:11:41 etcdserver: published {Name:infra1 ClientURLs:[http://localhost:4001]} to cluster e9c7614f68f35fb2
23:11:49 etcd2 | 2015/02/28 23:11:49 rafthttp: failed to connect 924e2e83e93f2560 in stream message: dial tcp 127.0.0.1:7003: connection refused
23:11:49 etcd2 | 2015/02/28 23:11:49 rafthttp: failed to connect 924e2e83e93f2560 in stream msgapp: dial tcp 127.0.0.1:7003: connection refused
23:11:49 etcd1 | 2015/02/28 23:11:49 rafthttp: failed to connect 924e2e83e93f2560 in stream message: dial tcp 127.0.0.1:7003: connection refused
23:11:49 etcd1 | 2015/02/28 23:11:49 rafthttp: failed to connect 924e2e83e93f2560 in stream msgapp: dial tcp 127.0.0.1:7003: connection refused
23:11:51 etcd2 | 2015/02/28 23:11:51 rafthttp: failed to post 924e2e83e93f2560 in pipeline: dial tcp 127.0.0.1:7003: connection refused
23:11:59 etcd2 | 2015/02/28 23:11:59 rafthttp: failed to connect 924e2e83e93f2560 in stream msgapp: dial tcp 127.0.0.1:7003: connection refused
23:11:59 etcd2 | 2015/02/28 23:11:59 rafthttp: failed to connect 924e2e83e93f2560 in stream message: dial tcp 127.0.0.1:7003: connection refused
23:11:59 etcd1 | 2015/02/28 23:11:59 rafthttp: failed to connect 924e2e83e93f2560 in stream message: dial tcp 127.0.0.1:7003: connection refused
23:11:59 etcd1 | 2015/02/28 23:11:59 rafthttp: failed to connect 924e2e83e93f2560 in stream msgapp: dial tcp 127.0.0.1:7003: connection refused
23:12:01 etcd2 | 2015/02/28 23:12:01 rafthttp: failed to post 924e2e83e93f2560 in pipeline: dial tcp 127.0.0.1:7003: connection refused
23:12:09 etcd2 | 2015/02/28 23:12:09 rafthttp: failed to connect 924e2e83e93f2560 in stream msgapp: dial tcp 127.0.0.1:7003: connection refused
23:12:09 etcd2 | 2015/02/28 23:12:09 rafthttp: failed to connect 924e2e83e93f2560 in stream message: dial tcp 127.0.0.1:7003: connection refused
23:12:10 etcd1 | 2015/02/28 23:12:10 rafthttp: failed to connect 924e2e83e93f2560 in stream message: dial tcp 127.0.0.1:7003: connection refused
23:12:10 etcd1 | 2015/02/28 23:12:10 rafthttp: failed to connect 924e2e83e93f2560 in stream msgapp: dial tcp 127.0.0.1:7003: connection refused
23:12:11 etcd2 | 2015/02/28 23:12:11 rafthttp: failed to post 924e2e83e93f2560 in pipeline: dial tcp 127.0.0.1:7003: connection refused
```

Before this PR, the disconnection will result in 20 error messages per second. This PR decreases the duplicate error message output, and backoff them to one per 10 seconds.

This helps to gain better logging for rafthttp-package message sending.

Will add commit after the format is good to all.

**Comment by xiang90** [comment]
need rebase

**Comment by yichengq** [comment]
rebased.

**Comment by yichengq** [comment]
fixes #2197 
/cc @kelseyhightower @barakmich

**Comment by yichengq** [comment]
use new way to print out connection status well. will link the new PR to here.

**Pull request closed without merging**
