### PR TITLE
benchmark: watch, key-space-size(max possible key)

### PR DESCRIPTION
**Pull request by gyuho**
By specifying 'key-space-size', we can test min/max-key-range
of keys to watch.

For https://github.com/coreos/etcd/issues/3863.

### CODE REVIEW

**Comment by xiang90** [comment]
have you tried to run some benchmark with different key-space-size and total?

**Comment by gyuho** [comment]
@xiang90 Was about to try it out. Will post results shortly. Thanks.

**Comment by gyuho** [comment]
@xiang90 

```
gyuho@gyuho:~$ benchmark --endpoints="10.240.0.7:2378,10.240.0.9:2378,10.240.0.10:2378" --conns=1 --clients=10 watch --total=1000 --watched-key-total=1000 --put-total=1000 --key
-space-size=1
1000 / 1000 Boooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 100.00 % 0
Watch creation summary:
 Requests/sec:  2351.0765
1000 / 1000 Boooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 100.00 % 0
Watch events received summary:
 Requests/sec:  9918.7972
gyuho@gyuho:~$ benchmark --endpoints="10.240.0.7:2378,10.240.0.9:2378,10.240.0.10:2378" --conns=1 --clients=10 watch --total=1000 --watched-key-total=1000 --put-total=1000 --key
-space-size=1000
1000 / 1000 Booooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 100.00 % 5s
Watch creation summary:
 Requests/sec:  191.8548
1000 / 1000 Booooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 100.00 % 4s
Watch events received summary:
 Requests/sec:  202.0299
```

**Comment by xiang90** [comment]
@gyuho Do you know why the second case is much slower than the first one?

**Comment by gyuho** [comment]
`--key-space-size=1` (watching on 1 key) is obviously faster. I am trying with different key-size but current benchmark tool panics. Will look into more.

**Comment by xiang90** [comment]
@gyuho Why it is faster?

**Comment by gyuho** [comment]
Another run and same results:

```
benchmark --endpoints="10.240.0.7:2378,10.240.0.9:2378,10.240.0.10:2378" --conns=1 --clients=50 \
	watch --watchers=1000 --total=1000 --watched-key-total=1000 --put-total=1000 --key-space-size=1 > a.log 2>&1

benchmark --endpoints="10.240.0.7:2378,10.240.0.9:2378,10.240.0.10:2378" --conns=1 --clients=50 \
	watch --watchers=1000 --total=1000 --watched-key-total=1000 --put-total=1000 --key-space-size=1000 > a.log 2>&1
```

@xiang90  `key-space=1` of the same key triggers all watchers in the first put request.
And if you look at the code on how we measure the time:

```go
func recvWatchChan(wch v3.WatchChan) {
	for range wch {
		st := time.Now()
		results <- result{duration: time.Since(st)}
		bar.Increment()
		atomic.AddInt32(&nrRecvCompleted, 1)
		if atomic.LoadInt32(&nrRecvCompleted) == int32(eventsTotal) {
			recvCompletedNotifier <- struct{}{}
		}
	}
}
```

With 1 key, `wch` can receive all events from the first Put request here:

```go
	go func() {
		for i := 0; i < eventsTotal; i++ {
			putreqc <- v3.OpPut(watched[i%(len(watched))], "data")
			// TODO: use a real rate-limiter instead of sleep.
			time.Sleep(time.Second / time.Duration(watchPutRate))
		}
		close(putreqc)
	}()
```


However, if we put more than 1 key, it needs to wait until all the sequential put requests are done.

Please correct me if I am wrong.

**Comment by xiang90** [comment]
@gyuho Let's try to clarify the issues one by one.

So we have two numbers. One is Watch creation, the other one is Watch events received. 

Can we make sure we understand the reason of the first difference (watch creation)?

**Comment by gyuho** [comment]
@xiang90 Sure, I ran several times more specifically to see numbers on `watch creation time`.
So in theory, there shouldn't be difference in creating watchers because regardless of key size, it merely sends watch request through grpc. So results are:

```
# key-space-size=1
Watch creation summary:
 Requests/sec:  12331.4148
7049.8591
12269.2156
7421.1023

# key-space-size=10000
Watch creation summary:
 Requests/sec:  13893.7305
8899.0470
6701.6147
12529.6941
```

You can see there's not much difference. They are just noisy numbers because it depends on the grpc, I believe.

**Comment by xiang90** [comment]
> And if you look at the code on how we measure the time:

This is probably wrong. We do not really measure time. That time thing is for latency calculation. And we never print out latency summary in this case since it does not make sense as you just suggested.

**Comment by gyuho** [comment]
@xiang90 Actually I think I missed the conversation when we update this code:

```go
    for range wch {
        st := time.Now()
        results <- result{duration: time.Since(st)}
```

So should we do something like

```go
st := time.Now()
<-wch
time.Since(st)
```

Would it give us more accurate latency metrics?

Thanks.

**Comment by xiang90** [comment]
@gyuho We do not want to calculate latency, thus we do not do it. Watch latency depends on the input, it is not worth to measure. Say you watch on key foo, and I wait for 10 minutes to update the key foo. So the latency is 10 minutes. Does that mean the actual end to end latency to propagate the update is 10 minute? Not really

**Comment by gyuho** [comment]
Right. It doesn't tell anything about watch performance. Should we delete?

**Comment by xiang90** [comment]
@gyuho Probably not. That channel is used for calculation throughput. Latency is just a metadata if I remember correctly.

**Comment by gyuho** [comment]
Ok got it.

**Comment by xiang90** [comment]
@gyuho OK. Can you try to help understand the throughput difference in the second part?

**Comment by xiang90** [comment]
Let's say if the put rate is 1 put for second.

If all watchers watching on one key. the throughput should be 1000 / second.
If all watchers watching on 1000 different keys. the throughput should be 1 / second.

So it should be 1000x difference, but now it is 50x.

**Comment by gyuho** [comment]
@xiang90 

Another run:

```
1 key       = 46513.8649  (230X difference)
1000 key = 202.0674
```

The throughput is `time.Sleep(time.Second / time.Duration(watchPutRate))` where we have 100 default `watchPutRate` value. So if we put 1000 keys, it's  0.01 key / second. But I think since we share one channel to receive all events, the performance difference got much smaller (230x, not 1000x).

**Comment by xiang90** [comment]
@gyuho Can you try to make the put rate 1/second and check the difference again?

**Comment by gyuho** [comment]
@xiang90 

```
# 1 key
1145.8492    (1000x faster)

# 1000 key
1.4273
```

Here are commands:

```
benchmark --endpoints="10.240.0.7:2378,10.240.0.9:2378,10.240.0.10:2378" --conns=1 --clients=50 \
	watch --watchers=10 --total=10 --watched-key-total=10 --put-total=10 --put-rate=1 --key-space-size=1 > a.log 2>&1

benchmark --endpoints="10.240.0.7:2378,10.240.0.9:2378,10.240.0.10:2378" --conns=1 --clients=50 \
	watch --watchers=10 --total=10 --watched-key-total=10 --put-total=10 --put-rate=1 --key-space-size=1000 > b.log 2>&1
```

Now it shows as we expect?

**Comment by xiang90** [comment]
@gyuho OK. So why when we increase the put rate, it is not 1000x anymore?

**Comment by xiang90** [comment]
> # 1 key 1145.8492    (1000x faster)

Also this is not 1000x faster. The speed is probably slower. Just the throughput is 1000x since etcd delivers updates to 1000 more receivers.

**Comment by gyuho** [comment]
@xiang90 Right.

So I ran small keys with `put-rate` 100.

```
1318.8847  (only 10x when 1 key)
132.1870
```

You can see the number differs from the amount of time we sleep per each Put request.
`put-rate` 100 makes each Put request wait `10ms` while `1 key watcher` only needs the first `Put` to get triggered. 1000 key watcher with put total 10 waits 10ms * 10 (100ms total sleep time).
So 1000 / 100 is 10x.

```
benchmark --endpoints="10.240.0.7:2378,10.240.0.9:2378,10.240.0.10:2378" --conns=1 --clients=50 \
	watch --watchers=10 --total=10 --watched-key-total=10 --put-total=10 --put-rate=100 --key-space-size=1 > a.log 2>&1

benchmark --endpoints="10.240.0.7:2378,10.240.0.9:2378,10.240.0.10:2378" --conns=1 --clients=50 \
	watch --watchers=10 --total=10 --watched-key-total=10 --put-total=10 --put-rate=100 --key-space-size=1000 > b.log 2>&1
```

**Comment by gyuho** [comment]
So if we gave `put-rate` 1, we would have got the same result (+/- 1000x).
We just have to wait 1000s to get the results. That's why I pass small key flags.

**Comment by gyuho** [comment]
So [`printRate`](https://github.com/coreos/etcd/blob/master/tools/benchmark/cmd/report.go#L62) does not include the sleep seconds that I was mentioning. So theoretically, it should be 1000x but with other factors, it could be slow down with higher `put-rate`, which we need to clearly understand.

I will do more extensive analysis in terms of `put-rate`, `key-space-size`, `watcher-size`
and post it here.

Thanks.

**Comment by xiang90** [comment]
This pr looks good to me. We just need to do more work to understand the result.

**Comment by gyuho** [comment]
Merging first, and will share more results through google docs.
Thanks.

**Pull request merged**
