### PR TITLE
*: clean up if, bool comparison

### PR DESCRIPTION
**Pull request by gyuho**
With help from https://github.com/dominikh/go-simple.

### CODE REVIEW

**Comment by heyitsanthony** [comment]
lgtm but please squash

Is `go-simple` worth adding to ./test?

**Comment by gyuho** [comment]
@heyitsanthony Yeah but I think it would be useful. I found a bunch in other packages.

Wanted to try github's new squash feature but guess it doesn't work in this case.

Just squashed all. Will merge in greens. Thanks!

**Comment by heyitsanthony** [comment]
@gyuho I believe it squashes on the merge pull. I think we should disable merge squashing (github helpfully set it to the default) though since sometimes it's cleaner to have a patchset instead of one monolithic super-commit all the time. /cc @xiang90

**Comment by xiang90** [comment]
@heyitsanthony Yes. We should not force people to squash or squash by default. We should squash when necessary.

**Pull request merged**
