### PR TITLE
Documentation: add encryption wrapper to integrations

### PR DESCRIPTION
**Pull request by lumjjb**
Added to `Documentation/integrations.md` from discussion of https://github.com/coreos/etcd/issues/7542

### CODE REVIEW

**Comment by heyitsanthony** [comment]
@lumjjb please amend the commit message so the first line is `Documenation: add encryption wrapper to integrations` so this passes the [commit format](https://github.com/coreos/etcd/blob/master/CONTRIBUTING.md#format-of-the-commit-message) check that's [failing in CI](https://travis-ci.org/coreos/etcd/jobs/217201116#L875) and move the entry to the `go libraries` list? Then this should be good to merge. Thanks!

**Comment by heyitsanthony** [comment]
squash into a single commit?

**Comment by lumjjb** [comment]
ok will do

**Comment by heyitsanthony** [comment]
lgtm

**Pull request merged**
