### PR TITLE
Automated cherry pick of #9415

### PR DESCRIPTION
**Pull request by jpbetz**
Cherry pick of #9415 on release-3.1.

#9415: rafthttp: add "ActivePeers" to "Transport"

### CODE REVIEW

**Comment by jpbetz** [comment]
Fixed mistake merge conflict.

**Comment by jpbetz** [comment]
Looks like there is some additional code that cannot be cleanly merged, semantically merging it manually now.

**Comment by gyuho** [comment]
@jpbetz Yeah, could have been easier to cherry-pick individual commits or edit directly in the branch :0

This is missing `adjustTicks` https://github.com/coreos/etcd/pull/9415/files#diff-971f6af906b31cc86efd71aff56aa96bR533?

**Comment by jpbetz** [comment]
@gyuho Yep, that auto-merge didn't work out. I've manually applied the changes that didn't auto merge. Everything should be in place now, but please double check me!

**Pull request merged**
