### PR TITLE
scripts: fix update dep 

### LINKED ISSUE #6834: scripts: ./updatedep.sh experiences error
Setup:
```
OS: OS X El Capitan 10.11.6
Processor Name:	Intel Core i7
Processor Speed:	2.5 GHz
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/fanminshi/work"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.3/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bk/ph52lmzd5hxcx_0jvqr3rh5h0000gn/T/go-build558053824=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

run `./scripts/updatedep.sh` on my mac experience following error.

```
[ERROR]	Error scanning github.com/spf13/cobra/doc: open /Users/fanminshi/.glide/cache/src/https-github.com-spf13-cobra/doc: no such file or directory
[ERROR]	This error means the referenced package was not found.
[ERROR]	Missing file or directory errors usually occur when multiple packages
[ERROR]	share a common dependency and the first reference encountered by the scanner
[ERROR]	sets the version to one that does not contain a subpackage needed required
[ERROR]	by another package that uses the shared dependency. Try setting a
[ERROR]	version in your glide.yaml that works for all packages that share this
[ERROR]	dependency.
[INFO]	--> Fetching updates for github.com/matttproud/golang_protobuf_extensions.
[INFO]	--> Fetching updates for github.com/pelletier/go-buffruneio.
[INFO]	--> Fetching updates for golang.org/x/text.
[INFO]	--> Fetching updates for github.com/shurcooL/sanitized_anchor_name.
[ERROR]	Failed to retrieve a list of dependencies: Error resolving imports
copying github.com/stretchr/testify/assert
removing test files
exit status 1recreating symlink to etcd
done
```

### PR DESCRIPTION
**Pull request by fanminshi**
I update cobra and pflag version.
the updates fix #6834

### CODE REVIEW

**Comment by fanminshi** [comment]
PTAL @xiang90 @heyitsanthony @gyuho 

I am not too sure why so many files are created.

**Comment by xiang90** [comment]
@gyuho might know it better than me.

**Comment by heyitsanthony** [comment]
For cobra, it looks like it's updating a lot of dependencies it doesn't need to (e.g., glog). 

Can this patch set please be organized so the vendored deps are committed along with the corresponding glide file changes? Otherwise there are commits where the glide files and the associated vendored files are inconsistent.

**Comment by gyuho** [comment]
Yeah looks like new cobra now depends on bunch of extra features. Not sure how we can avoid that. And as Anthony suggests, let's organize commits more readable.

**Comment by gyuho** [comment]
Or can you try to delete cobra from glide.yaml and add it back by passing arg to our script? Think we only need cobra and pflag.

**Comment by fanminshi** [comment]
@heyitsanthony I re-organizes the commits.
@gyuho I'll try the the second option too.

**Comment by fanminshi** [comment]
@gyuho I tried your second suggestion. still the same.

**Comment by gyuho** [comment]
I have other projects with `pflag` and `cobra` and they don't have this much dependencies.

- https://github.com/coreos/etcdlabs/blob/master/glide.yaml
- https://github.com/coreos/dbtester/pull/65

**Comment by fanminshi** [comment]
@gyuho could you try to update cobra,pflag for this project from you local repo. I want to see if you are getting a lot of file changes.

**Comment by gyuho** [comment]
```diff
diff --git a/glide.lock b/glide.lock
index 01d419c..57000c1 100644
--- a/glide.lock
+++ b/glide.lock
@@ -1,5 +1,5 @@
-hash: 93d5ee1318c98aca7c4b42e057239806a565e5aadebdd79e260f95c206098358
-updated: 2016-11-10T12:00:18.624405955-08:00
+hash: c7001e49df78e2297642bfe301213badae9ac8c4a770b8aaa3ba3bfabd951f63
+updated: 2016-11-11T09:47:37.196338117-08:00
 imports:
 - name: bitbucket.org/ww/goautoneg
   version: 75cd24fc2f2c2a2088577d12123ddee5f54e0675
@@ -28,12 +28,6 @@ imports:
   subpackages:
   - capnslog
   - dlopen
-- name: github.com/cpuguy83/go-md2man
-  version: 71acacd42f85e5e82f70a55327789582a5200a90
-  subpackages:
-  - md2man
-- name: github.com/dghubble/sling
-  version: c961a4334054e64299d16f8a31bd686ee2565ae4
 - name: github.com/dustin/go-humanize
   version: 8929fe90cee4b2cb9deb468b51fb34eba64d1bf0
 - name: github.com/ghodss/yaml
@@ -41,51 +35,7 @@ imports:
 - name: github.com/gogo/protobuf
   version: 8d70fb3182befc465c4a1eac8ad4d38ff49778e2
   subpackages:
-  - gogoproto
-  - io
-  - jsonpb
-  - jsonpb/jsonpb_test_proto
-  - plugin/compare
-  - plugin/defaultcheck
```

@fanminshi

**Pull request closed without merging**
