### PR TITLE
index is incremented in Watcher; remove double-increment

### LINKED ISSUE #5741: etcdctl watch-exec off-by-one error
I'm using the etcd release 2.3.7 version on RHEL7 on all systems in the below situation.  The etcdctl client connects through an etcd proxy on localhost with three etcd member servers.

The `watch-exec` command seems to skip the next event when a start index is specified.

Note here that event `1339527` doesn't get picked up by the watch starting at the event just prior; the first event which should be emitted is skipped and the output starts with the second one.

    17:43:49 [user@host:0 ~/]
    $ /srv/etcd/bin/etcdctl -o json set /testdir/a value --ttl 45
    {"action":"set","node":{"key":"/testdir/a","value":"value","nodes":null,"createdIndex":1339527,"modifiedIndex":1339527,"expiration":"2016-06-21T22:44:46.066827272Z","ttl":45},"prevNode":{"key":"/testdir/a","value":"value","nodes":null,"createdIndex":1339526,"modifiedIndex":1339526,"expiration":"2016-06-21T22:44:27.644736837Z","ttl":27}}
    17:44:01 [user@host:0 ~/]
    $ /srv/etcd/bin/etcdctl -o json set /testdir/b value --ttl 45
    {"action":"set","node":{"key":"/testdir/b","value":"value","nodes":null,"createdIndex":1339528,"modifiedIndex":1339528,"expiration":"2016-06-21T22:44:58.694372512Z","ttl":45},"prevNode":null}
    17:44:13 [user@host:0 ~/]
    $ /srv/etcd/bin/etcdctl exec-watch --recursive --after-index 1339526 /testdir --
    /bin/sh -c 'env | grep ^ETCD_WATCH'
    ETCD_WATCH_ACTION=set
    ETCD_WATCH_MODIFIED_INDEX=1339528
    ETCD_WATCH_VALUE=value
    ETCD_WATCH_KEY=/testdir/b
    ETCD_WATCH_ACTION=expire
    ETCD_WATCH_MODIFIED_INDEX=1339529
    ETCD_WATCH_VALUE=
    ETCD_WATCH_KEY=/testdir/a
    ETCD_WATCH_ACTION=expire
    ETCD_WATCH_MODIFIED_INDEX=1339530
    ETCD_WATCH_VALUE=
    ETCD_WATCH_KEY=/testdir/b

Consistently, watch-exec on the *27 skips *28, starting with *29 (and, oddly, does so out-of-order):

    $ /srv/etcd/bin/etcdctl exec-watch --recursive --after-index 1339527 /testdir --
    /bin/sh -c 'env | grep ^ETCD_WATCH'
    ETCD_WATCH_ACTION=expire
    ETCD_WATCH_MODIFIED_INDEX=1339530
    ETCD_WATCH_VALUE=
    ETCD_WATCH_KEY=/testdir/b
    ETCD_WATCH_ACTION=expire
    ETCD_WATCH_MODIFIED_INDEX=1339529
    ETCD_WATCH_VALUE=
    ETCD_WATCH_KEY=/testdir/a

However, the `watch` command works as expected, starting with the very next key

    $ /srv/etcd/bin/etcdctl watch --forever --recursive --after-index 1339527 /testdir
    [set] /testdir/b
    value
    [expire] /testdir/a
    
    [expire] /testdir/b

### PR DESCRIPTION
**Pull request by dannysauer**
Remove double-increment, closes #5741.

Watch index is incremented in both etcd-watch client and in Watcher method from keys.go.  It makes more sense in Watcher(), so removed from etcd-watch.

### CODE REVIEW

**Comment by xiang90** [comment]
Can you please resolve the merge conflict?

**Comment by dannysauer** [comment]
I thought that was a weird permission warning - I didn't realize that I already had a fork of etcd which was super old (why doesn't github warn me that the fork I'm creating already exists?). :)

I'm pretty sure this is fixed now.

**Comment by xiang90** [comment]
can you do  git reset --soft HEAD~2; git commit -am "etcdctl: index is incremented in Watcher; remove double-increment" to squash the commits?

**Comment by dannysauer** [comment]
My employer's data exfiltration controls prevent pushing up to github from work, so it'll have to be done this evening when I'm back at home.  Maybe I'll spend the day reading about git so I can stop being the only caveman left on the Internet with no git skills. :)

**Comment by dannysauer** [comment]
I think this is better now. :)

**Comment by xiang90** [comment]
@dannysauer Sorry. There are still 4 commits in this one pull requests. 

Now you need to do

```bash
git reset --soft HEAD~4

git commit -am "etcdctl: index is incremented in Watcher; remove double-increment"
```

**Comment by dannysauer** [comment]
Every time I run that, I get two more commits, which doesn't seem to make things better.  I tried to rebase, and got lots of frownie faces.  So, I just started over on a clean fork with pull request #5758. :)

Closing this request.

**Pull request closed without merging**
