### PR TITLE
*: mv etcdhttp into api pkg

### PR DESCRIPTION
**Pull request by xiang90**
/cc @heyitsanthony

### CODE REVIEW

**Comment by heyitsanthony** [comment]
lgtm

**Comment by gyuho** [comment]
LGTM.

Is this for dependency management?

Btw we might also want to rename `v3demo_server.go` to `server_v3.go` when we do this cleaning up.

**Comment by xiang90** [comment]
@gyuho No. Just to make things more organized.

**Comment by gyuho** [comment]
@xiang90 Ok got it.

**Comment by xiang90** [comment]
Merging anyway since the known race issue.

**Pull request merged**
