### PR TITLE
RequestOp, ResponseOp

### PR DESCRIPTION
**Pull request by gyuho**
- `RequestUnion` to `RequestOp`
- `ResponseUnion` to `ResponseOp`

Fix https://github.com/coreos/etcd/issues/5504.

### CODE REVIEW

**Comment by heyitsanthony** [comment]
s/Set/Op? Set sounds like it can hold more than one op at once.

**Comment by gyuho** [comment]
Sure, will fix. Change it to `Op`

**Comment by gyuho** [comment]
@heyitsanthony PTAL. Now they are `~Op`, instead of `~Union`.

**Comment by heyitsanthony** [comment]
lgtm

**Comment by gyuho** [comment]
thanks. merging in greens.

**Comment by mitake** [comment]
@gyuho after this commit, `script/genproto.sh` introduces changes in `*.pb.go` files. Maybe should I update protoc things? Which version should I use?

**Comment by gyuho** [comment]
@mitake Can you paste diff? Try `scripts/genproto.sh -g`.

I think it should be fine. The script always runs the same version of protoc-gen-go. `protoc` should be fine as long as you run version 3 of protoc.

**Pull request merged**
