### PR TITLE
etcdctl: Added tree command

### PR DESCRIPTION
**Pull request by mickep76**
Added tree command to etcdctl.

### CODE REVIEW

**Comment by mickep76** [comment]
Ping

**Comment by yichengq** [comment]
Any reasons that you want to add `tree` command? We simulate shell commands around file system in etcdctl, and `tree` is not a pre-installed program in linux.

**Comment by mickep76** [comment]
Mostly because it's useful.

**Comment by yichengq** [comment]
We need to balance the complicity of etcdctl and how useful it could be. I think `tree` is a little overkill subcommand, but maybe i am too conservative. @xiang90 @jonboulle Any thoughts?

**Comment by mickep76** [comment]
I build it as a separate Go binary at the moment etcd-tree, but I find it useful for getting a quick overview of available directories and entries.

As for complexity it doesn't add a lot of code.

**Comment by mickep76** [comment]
So yes/no go? Should I just ditch the pull req.?

**Pull request closed without merging**
