### PR TITLE
etcdserver: fix govet error

### PR DESCRIPTION
**Pull request by gyuho**

### CODE REVIEW

**Comment by gyuho** [comment]
/cc @xiang90 @heyitsanthony 

Fix:

```
gopath/src/github.com/coreos/etcd/etcdserver/raft_test.go:161: literal copies lock value from r: etcdserver.raftNode contains sync.Mutex
```

https://travis-ci.org/coreos/etcd/jobs/120193226

**Comment by heyitsanthony** [comment]
lgtm

**Comment by xiang90** [comment]
lgtm

**Comment by gyuho** [comment]
thanks. merging in greens.

**Pull request merged**
