### PR TITLE
ctlv3/command: auto compact and defrag after "check perf"

### PR DESCRIPTION
**Pull request by gyuho**
```
$ ETCDCTL_API=3 ./bin/etcdctl endpoint status -w table                                                                                 
+----------------+------------------+-----------+---------+-----------+-----------+------------+--------------------+--------+                                         
|    ENDPOINT    |        ID        |  VERSION  | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |                                         
+----------------+------------------+-----------+---------+-----------+-----------+------------+--------------------+--------+                                         
| 127.0.0.1:2379 | 8e9e05c52164694d | 3.3.0+git |   20 kB |      true |         2 |          4 |                  4 |        |                                         
+----------------+------------------+-----------+---------+-----------+-----------+------------+--------------------+--------+                                         

$ ETCDCTL_API=3 ./bin/etcdctl check perf --auto-compact --auto-defrag                                                                  
 60 / 60 Boooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 100.00%1m0s
Compacting with revision 8994            
Compacted with revision 8994             
Defragmenting "127.0.0.1:2379"           
Defragmented "127.0.0.1:2379"            
PASS: Throughput is 150 writes/s         
PASS: Slowest request took 0.146769s     
PASS: Stddev is 0.002704s                
PASS                                     

$ ETCDCTL_API=3 ./bin/etcdctl endpoint status -w table                                                                                 
+----------------+------------------+-----------+---------+-----------+-----------+------------+--------------------+--------+                                         
|    ENDPOINT    |        ID        |  VERSION  | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |                                         
+----------------+------------------+-----------+---------+-----------+-----------+------------+--------------------+--------+                                         
| 127.0.0.1:2379 | 8e9e05c52164694d | 3.3.0+git |   20 kB |      true |         2 |       8998 |               8998 |        |                                         
+----------------+------------------+-----------+---------+-----------+-----------+------------+--------------------+--------+      
```

/cc @raoofm @spzala 

For https://github.com/coreos/etcd/issues/9326.

### CODE REVIEW

**Comment by gyuho** [comment]
@raoofm I added `--auto-compact` flag, as an option. It will discards all entries before the revision from last delete operation. It's optional, in case `check perf` commands are run mixed with other data (it will discards previous keys with previous revisions).

**Comment by spzala** [comment]
@gyuho this is very useful and it looks great. Couple of comments - 1. can we have both of these as a func on its own in util.go or at least in check.go if you think it's a good idea for re-usability? I believe I should use these options with ```check datascale``` as a follow up PR on my PR under review too and can simply call these functions. 2. I have noticed in few place in doc, that compact and defrag typically follow up with ```etcdctl alarm disarm```, we may not need it here but just a thought if it's good to add ```disalarm``` as an option too. Thanks!

**Comment by gyuho** [comment]
@spzala I separated as a function (let's keep them in `check.go` for now).

Can you create a follow-up PR to use this in other commands?

Thanks!

**Comment by spzala** [comment]
@gyuho yup, that's perfect. Thanks!! 
lgtm

**Comment by raoofm** [comment]
@gyuho is there a plan to backport to 3.1 and 3.2, if not can we?

**Comment by danbeaulieu** [comment]
@gyuho Is this expected?

```
# docker exec 4a5ce770e887 sh -c 'ETCDCTL_API=3 etcdctl --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/etcd/peer.crt --key=/etc/kubernetes/pki/etcd/peer.key --endpoints=127.0.0.1:2379 version'
etcdctl version: 3.3.9
API version: 3.3
```

```
# docker exec 4a5ce770e887 sh -c 'ETCDCTL_API=3 etcdctl --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/etcd/peer.crt --key=/etc/kubernetes/pki/etcd/peer.key --endpoints=127.0.0.1:2379 check perf --auto-compact --auto-defrag'
Error: unknown flag: --auto-compact
```

```
docker exec 4a5ce770e887 sh -c 'ETCDCTL_API=3 etcdctl --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/etcd/peer.crt --key=/etc/kubernetes/pki/etcd/peer.key --endpoints=127.0.0.1:2379 check perf  --auto-defrag'
Error: unknown flag: --auto-defrag
```

**Comment by dreambo8563** [comment]
@danbeaulieu I got the same error, can not use flag --auto-compact and --auto-defrag

**Comment by wangsong93** [comment]
@danbeaulieu @dreambo8563 
Changes about `--auto-compact` is in `etcdctl/ctlv3/command/check.go`. You can view source code. The changes are not in branch `release-3.x` but `master`.

**Pull request merged**
