### PR TITLE
v3rpc: only fill lease grant header if no error

### PR DESCRIPTION
**Pull request by heyitsanthony**
Was panicking under cluster fault injection.

### CODE REVIEW

**Comment by heyitsanthony** [comment]
Saw:
```
16:22:03          etcd1 | panic(0xa54ce0, 0x82139c0d0)
16:22:03          etcd1 | 	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
16:22:03          etcd1 | github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.(*LeaseServer).LeaseGrant(0x82180d7c0, 0x88213f0680, 0x821986cf0, 0x821877ee0, 0x821877ee0, 0x0, 0x0)
16:22:03          etcd1 | 	/Users/anthony/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/lease.go:41 +0x113
16:22:03          etcd1 | github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.(*quotaLeaseServer).LeaseGrant(0x82180d840, 0x88213f0680, 0x821986cf0, 0x821877ee0, 0x821877eb0, 0x0, 0x0)
16:22:03          etcd1 | 	/Users/anthony/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/quota.go:81 +0x106
16:22:03          etcd1 | github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb._Lease_LeaseGrant_Handler(0xaa3c60, 0x82180d840, 0x88213f0680, 0x821986cf0, 0x8215ea000, 0x0, 0x0, 0x0, 0x0, 0x0)
16:22:03          etcd1 | 	/Users/anthony/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:2392 +0x168
16:22:03          etcd1 | github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0x821583cb0,
```

/cc @xiang90

**Comment by xiang90** [comment]
LGTM

**Comment by xiang90** [comment]
Can we cover this by a test?

**Comment by heyitsanthony** [comment]
@xiang90 not easily. It needs to hit the `ctx.Done()` or `s.done` path in `processInternalRaftRequest`

**Comment by xiang90** [comment]
OK. We will make this easy to test eventually...

**Comment by heyitsanthony** [comment]
@xiang90 it would be easy with failpoints...

**Pull request merged**
