### PR TITLE
RFC: *: a new option for configuring a coefficient of randomized election …

### PR DESCRIPTION
**Pull request by mitake**
…timeout

This commit adds a new option --randomized-election-coefficient. The
value specified with the option will be used for calculating the
randomized election timeout in
raft.resetRandomizedElectionTimeout(). If the coefficient is low
(e.g. 0), randomness of the election will become low and split
vote will likely happen.

Of course, the split vote decreases availability and nobody wants
it. However, if we can cause the situation intentionally, it will be
useful for debugging the candidate state that is ephemeral in
realistic deployments.

Actually, letting the coefficient 0 in testing on a single machine
(just adding --randomized-election-coefficient 0.0 to entries of
Procfile) shows lots of split vote situation after killing a leader
node.

/cc @gyuho how do you think about this? I thought it would be useful for reproducing problems like https://github.com/coreos/etcd/issues/7239, those relate to the candidate state (the callstack of the issue shows `stepCandidate()`). Also, using this option from functional tester would increase a chance of hitting such bugs?

### CODE REVIEW

**Comment by heyitsanthony** [comment]
This is a lot of code churn for a debugging option. Maybe this can be done by checking an environment variable (`RAFT_DEBUG_NORAND`?) and overriding `globalRand` in the raft package's `init()`? /cc @xiang90

**Comment by mitake** [comment]
@heyitsanthony I feel using a special environmental variable is a little bit dangerous because accidentally turning on it harms availability. But if the new option isn't acceptable, I'll use the env var.

**Comment by mitake** [comment]
On the second thought, the split vote was invoked accidentally by my mistake in the change. It seems that reducing the election timeout doesn't cause the split vote on my environment (and possibly on realistic test environments). So I'm closing this.

**Pull request closed without merging**
