### PR TITLE
etcdserver, clientv3: add "!=" to txn

### LINKED ISSUE #6719: clientv3: will Compare support "!=" ?
In a transaction, the `if` support Compare condition.

In my case I want to confirm some k/v is not a specified value, but in [compare](https://github.com/coreos/etcd/blob/master/clientv3/compare.go#L36) the `result` don't support `!=`. So is there any way to make it possible?

And this is what I want:

```
txn.If(
    clientv3.Compare(
        clientv3.Value(someKey),
        "!=",
        someValue,
    )
).Then(
    clientv3.OpPut(otherKey, othervalue),
)
```

### PR DESCRIPTION
**Pull request by fanminshi**
adding != to compare is a requested functionality from a etcd user

FIX #6719

### CODE REVIEW

**Comment by fanminshi** [comment]
I used protoc version 3.1.0 to recompile the .proto files.

**Comment by xiang90** [comment]
LGTM. defer to @heyitsanthony

**Comment by heyitsanthony** [comment]
change the commit title to `etcdserver, clientv3: add "!=" to txn` and it's lgtm

**Comment by fanminshi** [comment]
ALL fixed. I am going to wait CI to complete before I merge.

**Pull request merged**
