### PR TITLE
clientv3/namespace: fixed an error in the doc.go

### PR DESCRIPTION
**Pull request by ka1em**

### CODE REVIEW

**Comment by hexfusion** [comment]
@ka1em thank you for the PR can you resolve the Travis failure?

**Comment by hexfusion** [comment]
@ka1em in future no need to open new pull request. You can just rebase and push -f.

**Comment by hexfusion** [comment]
https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by ka1em** [comment]
@hexfusion Thank you very much.

**Pull request closed without merging**
