### PR TITLE
Correct defaults for heartbeat and election

### PR DESCRIPTION
**Pull request by peterrosell**
Defaults for hearbeat-interval and election-timeout is updated according to configuration documentation.

### CODE REVIEW

**Comment by xiang90** [comment]
lgtm. thanks.

**Comment by xiang90** [comment]
@peterrosell one small problem. can you please rename the commit message to `Documentation: correct...`? Thanks!

**Comment by peterrosell** [comment]
Now the message is updated.

**Comment by xiang90** [comment]
thanks!

**Pull request merged**
