### PR TITLE
*: etcdserver State in Member (replace IsLeader)

### PR DESCRIPTION
**Pull request by gyuho**

### CODE REVIEW

**Comment by xiang90** [comment]
This is incorrect. The local member does not know the exact state of other nodes. It does not know if the other member is candidate or leader when it is a follower.

**Comment by gyuho** [comment]
@xiang90 I see. I will rework on this. Thanks.

**Comment by gyuho** [comment]
`becameCandidate` method is not exposed and used only as an internal method inside `raft` package, so unless we send messages for every `becameCandidate` calls using `raftpb` it seems hard to get the states of the server.

**Comment by xiang90** [comment]
I do not think this actually worth the effort.

**Comment by gyuho** [comment]
@xiang90 Agree. Let's keep `IsLeader` for now. Thanks!

**Pull request closed without merging**
