### PR TITLE
etcdctl: don't crash on duplicate role in user grant

### PR DESCRIPTION
**Pull request by heyitsanthony**

### CODE REVIEW

**Comment by xiang90** [comment]
So sever-side already returns duplicated role as an error? If yes, then lgtm.

**Comment by gyuho** [comment]
lgtm.

**Comment by heyitsanthony** [comment]
@xiang90 yeah, it already gets an error from https://github.com/coreos/etcd/blob/master/etcdserver/auth/auth.go#L465

**Pull request merged**
