### PR TITLE
raft: add features section to readme file

### PR DESCRIPTION
**Pull request by xiang90**
/cc @bdarnell @philips @heyitsanthony @gyuho Please take a look. Thanks!

### CODE REVIEW

**Comment by xiang90** [comment]
also /cc @siddontang @ngaut

**Comment by gyuho** [comment]
Awesome. LGTM.

**Comment by ngaut** [comment]
Awesome.

**Comment by siddontang** [comment]
should add leader lease supplied by @swingbach ?

**Comment by xiang90** [comment]
@siddontang will add.

**Pull request merged**
