### PR TITLE
build: build etcdctlv3 by default

### PR DESCRIPTION
**Pull request by philips**
Any reason not to? It makes demoing etcd easier with the V3 procfile.

### CODE REVIEW

**Comment by gyuho** [comment]
lgtm. defer to @xiang90 @heyitsanthony

**Comment by xiang90** [comment]
lgtm

**Comment by philips** [comment]
@heyitsanthony Semaphore is complaining about missing packages... https://semaphoreci.com/coreos/etcd/branches/pull-request-4826/builds/1

**Comment by heyitsanthony** [comment]
@philips fixed by #4827 I think

**Comment by xiang90** [comment]
This is on a old branch so build fails. We can just merge this I believe.

**Comment by gyuho** [comment]
Merging because it's fixed by https://github.com/coreos/etcd/pull/4827.

**Pull request merged**
