### PR TITLE
etcdctl/ctlv2: error when TLS certs not specified

### PR DESCRIPTION
**Pull request by gyuho**
Fix https://github.com/coreos/etcd/issues/3586.

### CODE REVIEW

**Comment by gyuho** [comment]
Before

```
./bin/etcdctl --endpoints=https://localhost:2379,https://localhost:22379,https://localhost:32379 cluster-health
cluster may be unhealthy: failed to list members
Error:  client: etcd cluster is unavailable or misconfigured
error #0: x509: certificate signed by unknown authority
error #1: x509: certificate signed by unknown authority
error #2: x509: certificate signed by unknown authority

./bin/etcdctl --endpoints=https://localhost:2379,https://localhost:22379,https://localhost:32379 --cert-file=integration/fixtures/server.crt --key-file=integration/fixtures/server.key.insecure --ca-file=integration/fixtures/ca.crt cluster-health
member 8211f1d0f64f3269 is healthy: got healthy result from https://127.0.0.1:2379
member 91bc3c398fb3c146 is healthy: got healthy result from https://127.0.0.1:22379
member fd422379fda50e48 is healthy: got healthy result from https://127.0.0.1:32379
cluster is healthy
```

After

```
./bin/etcdctl --endpoints=https://localhost:2379,https://localhost:22379,https://localhost:32379 cluster-health
Error:  Please specify TLS certs.

./bin/etcdctl --endpoints=https://localhost:2379,https://localhost:22379,https://localhost:32379 --cert-file=integration/fixtures/server.crt --key-file=integration/fixtures/server.key.insecure --ca-file=integration/fixtures/ca.crt cluster-health
member 8211f1d0f64f3269 is healthy: got healthy result from https://127.0.0.1:2379
member 91bc3c398fb3c146 is healthy: got healthy result from https://127.0.0.1:22379
member fd422379fda50e48 is healthy: got healthy result from https://127.0.0.1:32379
cluster is healthy
```

/cc @xiang90 @raoofm

**Comment by xiang90** [comment]
@gyuho Actually I feel the previous output is good enough.
```
Error:  client: etcd cluster is unavailable or misconfigured
error #0: x509: certificate signed by unknown authority
error #1: x509: certificate signed by unknown authority
error #2: x509: certificate signed by unknown authority
```

It points out the cert verification fails clearly. I am not sure why #3586 prints out something different.

Your change is not not correct since accessing HTTPs do not necessarily require key/cert or cacert unless you want to verify the remote server or do client auth.

**Comment by gyuho** [comment]
@xiang90 You are right. And also agree that original error message is clear enough. Cannot get the `10.11.14.19:2379: getsockopt: connection refused`. Think this is something different.

**Comment by xiang90** [comment]
I am closing this one since we actually do not need it.

**Pull request closed without merging**
