### PR TITLE
lease: Add clockwork

### PR DESCRIPTION
**Pull request by lorneli**
Replace time.Now with clockwork.Clock.Now. Speed up lease expiring in
test.

### CODE REVIEW

**Comment by lorneli** [comment]
I didn't monify `time.After(500 * time.Millisecond)` in [lessor.runLoop](https://github.com/coreos/etcd/blob/master/lease/lessor.go#L499) function. Because it's a trigger for period function `runLoop`, not related to expiry.

**Comment by heyitsanthony** [comment]
I don't think this is a worthwhile optimization given the increased complexity of having to instrument with clockwork since the tests take under 4 seconds on my machine.

**Comment by lorneli** [comment]
@heyitsanthony  

Expiry releted tests (`TestLessorExpire` and `TestLessorExpireAndDemote`) grant lease for 1s, not a long time indeed.

There'a comment `TODO: use clockwork for testability.` in lease code. Since clockwork just helps advancing expiry here, maybe remove this comment?

**Comment by heyitsanthony** [comment]
TODOs are more of a note of something to possibly do later; the issue tracker is more reliable for finding worthwhile things to add to the code. If there were tests that would be too slow without clockwork, then the TODO would be more relevant here...

**Comment by lorneli** [comment]
@heyitsanthony Thanks for your detailed explication.

**Pull request closed without merging**
