### PR TITLE
pkg/expect: fix deadlock in macOS

### PR DESCRIPTION
**Pull request by gyuho**
bufio.NewReader.ReadString blocks even
when the process received syscall.SIGKILL.
Remove ptyMu mutex and make ReadString return
when *os.File is closed.

File read polling in Go still seems leaky.

```
Too many goroutines running after all test(s).
2 instances of:
internal/poll.runtime_pollWait(...)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(...)
	/usr/local/go/src/internal/poll/fd_unix.go:135 +0x1dc
os.(*File).read(...)
	/usr/local/go/src/os/file_unix.go:230 +0x4e
os.(*File).Read(...)
	/usr/local/go/src/os/file.go:106 +0x6a
bufio.(*Scanner).Scan(...)
	/usr/local/go/src/bufio/scan.go:208 +0xbf
github.com/coreos/etcd/pkg/expect.(*ExpectProcess).read(...)
	/pkg/expect/expect.go:78 +0x108
created by github.com/coreos/etcd/pkg/expect.NewExpectWithEnv
	/pkg/expect/expect.go:70 +0x215
```

Fix https://github.com/coreos/etcd/issues/9050.

### CODE REVIEW

**Comment by xiang90** [comment]
i do not really know why do we put a lock around pty. is it for making the read sequential? no two concurrent readline can happen? if we remove the mu, will we call readline concurrently? if it will, maybe simply remove the lock around closing is good enough?

**Comment by gyuho** [comment]
@xiang90 Yeah there's no concurrent `read` on that reader. So should be safe to just close the `*os.File` and let `ReadString` return (will get `already closed` or `signal: killed` error). No need mutex.

**Comment by xiang90** [comment]
lgtm

**Comment by fanminshi** [comment]
@gyuho do you know if `r.ReadString('\n')` and `ep.fpty.Close()` can happen at same time?

**Comment by gyuho** [comment]
@fanminshi On MacOS, it was blocking on `ReadString` while holding mutex. So it was never happening at the same time.

**Pull request merged**
