### PR TITLE
raft: add test case for leader transfer from follower

### PR DESCRIPTION
**Pull request by hhkbp2**
Hi there,

This PR adds a test case for PR #6155

### CODE REVIEW

**Comment by gyuho** [comment]
@hhkbp2 Could you change your commit title to `raft: add test case for leader transfer from follower`?

**Comment by hhkbp2** [comment]
@gyuho Sure.

**Comment by gyuho** [comment]
LGTM. /cc @xiang90

**Comment by xiang90** [comment]
lgtm

**Pull request merged**
