### PR TITLE
Update libraries-and-tools.md

### PR DESCRIPTION
**Pull request by shafreeck**
Add cetcd as a C library

### CODE REVIEW

**Comment by yichengq** [comment]
looks pretty nice. could you update the commit message to `docs: add cetcd into libraries-and-tools.md`? so the commit history could be more readable.

**Comment by shafreeck** [comment]
NP

**Comment by shafreeck** [comment]
I did a force update (I think no one has pulled shafreeck/etcd) but  failed the travis-ci's checking. I don't know why.

**Comment by yichengq** [comment]
travis may fail in low ratio because sometimes it has rather slow IO or halt for a while.
lgtm

**Comment by yichengq** [comment]
Thanks for the contribution!

**Pull request merged**
