### PR TITLE
etcdserver: set backend to cluster

### PR DESCRIPTION
**Pull request by xiang90**

### CODE REVIEW

**Comment by xiang90** [comment]
@heyitsanthony OK... Finally get this working...

**Comment by heyitsanthony** [comment]
should this update `err` on every error path in `NewServer` that follows backend initialization? a lot of error paths are returning `fmt.Errorf`s and leaving err set to nil...

**Comment by xiang90** [comment]
@heyitsanthony I think go will do auto assigning since the returned value is called err, no? I will give it a try.

**Comment by heyitsanthony** [comment]
@xiang90 you're right. lgtm

**Comment by xiang90** [comment]
@heyitsanthony After we get this merged, the snapshot needs to remove member and removed member bucket to remove the cluster configuration from backend.

**Comment by heyitsanthony** [comment]
@xiang90 I'll just fold it into this one...

**Comment by xiang90** [comment]
@heyitsanthony Sure. I will let you merge yours first then. Then I will do it in this pr.

**Comment by heyitsanthony** [comment]
fixed a bug in 3-cluster restore and added support for deleting member bucket contents. ptal /cc @xiang90

**Pull request merged**
