### PR TITLE
etcdserver: move the auth mechanism to etcdserver

### PR DESCRIPTION
**Pull request by mitake**
It is required for tight integration between the auth and the server
that enables efficient caching of the auth flag.

### CODE REVIEW

**Comment by mitake** [comment]
cc @xiang90 
This moving itself is so large. So I'm creating a PR before reviving the auth flag cache.

**Comment by mitake** [comment]
@xiang90 added a separated new commit for reviving the cached flag. If it should be in an individual PR, I'll remove it from this PR.

**Comment by xiang90** [comment]
@mitake After your benchmark, I feel there is not much performance gain here. So do we really need to enable the caching again?

**Comment by mitake** [comment]
@xiang90 for the obtaining consistent flag state, the commit turns on Quorum flag in `requestResource()`. Therefore its cost is now high and the caching would be effective.

**Comment by mitake** [comment]
@xiang90 on the second though, I think the auth mechanism should be merged with the raft side. There would be a request sequence like this:

1. client A issues request for getting or setting value X
2. for handling the request, etcdserver checks values related to auth (e.g. /2/enabled, /2/users/...).
3. client B changes the values related to auth
4. requests in 2nd step completes successfully (that shouldn't because of 3rd step), and getting or setting value X is done

The problem is 2nd (checking) and 3rd (updating) step can be done in parallel. I think they should be executed in a serialized manner by the raft leader for safety.

That would be a very big change e.g. auth and stale (Quorum == false) request isn't allowed anymore. How about doing it in v3 protocol?

**Comment by xiang90** [comment]
@mitake I think we do not really need to care about the racy behavior around auth. If you really care about the security at second level, you should probably pre-set all the rules before making etcd public.

**Comment by xiang90** [comment]
@mitake In the case you described, even the operator do not know which happened first or which should happen first. So it just does not matter... If the operator press the enter button late for 1 second, a few request can go through anyway... This problems happen a lot in distributed system where we just do not really care about the sequence in terms of wall time.

**Comment by mitake** [comment]
@xiang90 I think it is a matter of logical order, not just wall time. For example, even after completion of `etcdctl auth enable` command by operator, unauthorized commands requests (that issued after the completion) can be processed by etcd.

An important point is that we don't have a way to know how long this transitive state continues. For many practical cases, it would be short. But it depends on load of etcd and might be long in some cases.

But if updating permissions dynamically and frequently isn't suggested, it wouldn't be a serious problem at all and integrating auth to raft is an overkill.

Anyway, if the strict auth isn't required, integrating the auth mechanism to etcdserver wouldn't be required. How do you think? If you agree, I'll close this PR.

**Comment by xiang90** [comment]
>  For example, even after completion of etcdctl auth enable command by operator,

That is why I said for security reason, operator should turn deny on for all requests and then set open rules. They should not do the opposite. Also this is not a huge problem in reality since even if "get" request goes through, it will not able to see any value set after the auth enabled.

**Comment by mitake** [comment]
@xiang90 thanks a lot for your explanation (I'm still trying to understand e.g. for a case of multiple grants). BTW, how do you think about this PR? Should I close it?

**Comment by xiang90** [comment]
Let's close this for now. We can revisit this if needed. I do think we need a more careful auth design for v3, especially for the consistency guarantees.

**Comment by mitake** [comment]
>  I do think we need a more careful auth design for v3, especially for the consistency guarantees.

@xiang90 then how about serialize the auth mechanism to the raft? It would enable serializing auth checking and other requests in a leader node. Fortunately v3 API is ongoing so it would be a good timing for the integration.

**Comment by xiang90** [comment]
@mitake We probably will not enable that. It requires all read requests to go through raft.

**Comment by mitake** [comment]
@xiang90 sure but the cost is already required for consistent read. And `client.EndpointSelectionPrioritizeLeader` will reduce the cost (if we have a same thing in v3).

**Comment by xiang90** [comment]
@mitake Well... The problem is that if the user choose to read from other nodes, then there is no guarantees. It is just like a theft can choose a insecure door to break in... We have to ensure ALL requests to go through raft, even go through the leader is not good enough since there might be two concurrent leader for raft. 

The true issue here is to set the correct expectation for users.

**Comment by mitake** [comment]
@xiang90 Of course the leader should use the values (e.g. enabling flag, grants) that already have consensus of the entire cluster. And users can also send their requests to followers. In such a case, followers simply forwards the requests to the leader. It would be secure, just introduce an overhead that can be reduced by the endpoint selection policy.

The drawback of my scheme would not providing Quorum == false requests (v3 range API seems not providing it). IIUC, the lease mechanism will provide better solution for low cost read.

**Comment by mitake** [comment]
@xiang90 I'm writing a rough implementation of the above strategy (very early stage) here: https://github.com/mitake/etcd/tree/auth-v3. It will take more few days to complete. I have a question about it: is it allowed to create another bucket (like "key" and "meta") for storing auth information in store?

**Pull request closed without merging**
