### PR TITLE
docs: add etcd-viewer into libraries-and-tools.md

### PR DESCRIPTION
**Pull request by nikfoundas**
I've been working on this project for a few weeks and I believe it has some features that could assist maintaining etcd registries. Please check it out and I hope you would like to include it in your list of etcd tools.
I will upload a couple of screenshots ASAP...
Kind regards,
Nikos

### CODE REVIEW

**Comment by yichengq** [comment]
A couple of screenshots could make it totally different. :)

Could you update the title of your commit to be `docs: add etcd-viewer into libraries-and-tools.md`?

**Comment by nikfoundas** [comment]
I know ... I'm working on it ... :)

**Comment by yichengq** [comment]
@nikfoundas could you change the git commit title too?

**Comment by nikfoundas** [comment]
I have uploaded a couple of screenshots ... you so can check them out...

About the git commit title? Is it changed as expected?

**Comment by yichengq** [comment]
The screenshot looks pretty nice. i like the cluster monitor page.

the second commit is fine now, but there should be only one instead of three. Could you squash them into one?

**Comment by nikfoundas** [comment]
@yichengq Can you check it once more? Please forgive my inexperience with github and your procedures.

**Comment by yichengq** [comment]
lgtm. Thanks for your contribution!

**Pull request merged**
