### PR TITLE
clientv3: fix dialer for maintenance API

### PR DESCRIPTION
**Pull request by gyuho**
Without patch

```
=== RUN   TestMaintenanceStatus
dial proto "unix" host "localhost:39491187763008498080" | dialEp "unix://localhost:39491187763008498080" | target "endpoint://client-bmdwzcpdjwn8/localhost:39491187763008498080" | ep "localhost:39491187763008498080"
dial proto "unix" host "localhost:57863826249668888540" | dialEp "unix://localhost:57863826249668888540" | target "endpoint://client-bmdwzcpe4ao8/localhost:57863826249668888540" | ep "localhost:57863826249668888540"
dial proto "unix" host "localhost:33033510950554123550" | dialEp "unix://localhost:33033510950554123550" | target "endpoint://client-bmdwzcpeiijr/localhost:33033510950554123550" | ep "localhost:33033510950554123550"
dial proto "unix" host "localhost:57863826249668888540" | dialEp "unix://localhost:57863826249668888540" | target "endpoint://client-bmdwzcpg64tf/localhost:39491187763008498080" | ep "localhost:39491187763008498080"
dial proto "unix" host "localhost:33033510950554123550" | dialEp "unix://localhost:33033510950554123550" | target "endpoint://client-bmdwzcpg64tf/localhost:39491187763008498080" | ep "localhost:39491187763008498080"
dial proto "unix" host "localhost:39491187763008498080" | dialEp "unix://localhost:39491187763008498080" | target "endpoint://client-bmdwzcpg64tf/localhost:39491187763008498080" | ep "localhost:39491187763008498080"
dial proto "unix" host "localhost:39491187763008498080" | dialEp "unix://localhost:39491187763008498080" | target "endpoint://client-bmdwzcpg64tf/localhost:39491187763008498080" | ep "localhost:39491187763008498080"
dial proto "unix" host "localhost:39491187763008498080" | dialEp "unix://localhost:39491187763008498080" | target "endpoint://client-bmdwzcpg64tf/localhost:57863826249668888540" | ep "localhost:57863826249668888540"
dial proto "unix" host "localhost:39491187763008498080" | dialEp "unix://localhost:39491187763008498080" | target "endpoint://client-bmdwzcpg64tf/localhost:33033510950554123550" | ep "localhost:33033510950554123550"
--- FAIL: TestMaintenanceStatus (0.17s)
	maintenance_test.go:102: #1: status returned duplicate member ID with 0eb083ea01d9b6c4
	maintenance_test.go:102: #2: status returned duplicate member ID with 0eb083ea01d9b6c4
	maintenance_test.go:112: no leader found
```

So gRPC is passing the endpoint used for initial client connection to the custom dialer, not the endpoint target that client passes to the dial method. So, we need special handling when two given hosts are different.

/cc @jpbetz

### CODE REVIEW

**Comment by gyuho** [comment]
Oh, some network partition tests still fail. Will investigate more!

**Comment by gyuho** [comment]
Found some issues with current picker generator. Will investigate more.

**Comment by gyuho** [comment]
@jpbetz Think we need improve picker generator logic. Let me create a separate issue to explain the root cause and proposed solution.

**Comment by jpbetz** [comment]
@gyuho Sounds good. Let me know if you need me to pitch in on any code changes.

**Pull request closed without merging**
