### PR TITLE
Drop go1.4 support for development

### PR DESCRIPTION
**Pull request by gyuho**
Fix: https://github.com/coreos/etcd/issues/4790

### CODE REVIEW

**Comment by gyuho** [comment]
/cc @xiang90 @heyitsanthony 

Thanks.

Won't merge until we figure out our branch versioning.

**Comment by xiang90** [comment]
@gyuho Rebase with master, which drops the 1.4 build for travis?

**Comment by gyuho** [comment]
@xiang90 Will do shortly.

**Comment by gyuho** [comment]
@xiang90 https://travis-ci.org/coreos/etcd/builds/117052033  PTAL. Thanks.

**Comment by xiang90** [comment]
lgtm

**Comment by gyuho** [comment]
thanks.

**Pull request merged**
