### PR TITLE
storage: add tests for RangeEvents and its underlying functions

### PR DESCRIPTION
**Pull request by yichengq**
To help make watch work correctly.

The first commit improves keyIndex built for better testing, which helps to test keyIndex.since better.

### CODE REVIEW

**Comment by xiang90** [comment]
Some of the commits are pretty independent. Can we separate them out into a few pull requests next time?

**Comment by yichengq** [comment]
> Can we separate them out into a few pull requests next time?

Sure. Will take care of it next time.

**Comment by xiang90** [comment]
LGTM except the last comment.

**Comment by yichengq** [comment]
Thanks for the patient review!

**Pull request merged**
