### PR TITLE
grpcproxy: fix recursive Context method

### PR DESCRIPTION
**Pull request by gyuho**

### CODE REVIEW

**Comment by xiang90** [comment]
lgtm

**Comment by gyuho** [comment]
Btw, I am tracking down `go test -v -tags cluster_proxy -run TestGRPCStreamRequireLeader` hanging forever. grpcproxy is not getting `HasLeader` context metadata. Will investigate.

**Comment by heyitsanthony** [comment]
lgtm

**Comment by xiang90** [comment]
@gyuho Seem like clientv3 test fails?

**Comment by gyuho** [comment]
@xiang90 Re-ran the tests and now passed. It was a failure from 32-bit ARCH, with leaky goroutines in lease tests. I will investigate separately.

**Pull request merged**
