### PR TITLE
Documentation: add Grab etcd use case

### PR DESCRIPTION
**Pull request by reterVision**
# Contributing guidelines

Please read our [contribution workflow][contributing] before submitting a pull request.

[contributing]: https://github.com/coreos/etcd/blob/master/CONTRIBUTING.md#contribution-flow

### CODE REVIEW

**Comment by gyuho** [comment]
Can you fix the commit title to `Documentation: add Grab etcd use case`?
Thanks.

**Comment by reterVision** [comment]
@gyuho Fixed, thanks

**Comment by gyuho** [comment]
LGTM. Thanks!

**Comment by xiang90** [comment]
Merging.

**Pull request merged**
