### PR TITLE
pkg/fileutil: fall back to truncate() if fallocate is interrupted

### LINKED ISSUE #5558: tmpfs: create wal error: interrupted system call
When using the `tmpfs` as the data-dir for etcd, the result is:

```
C0603 17:10:17.795926 347 raft.go:296] 2016/06/3 17:10:17 etcdserver: create wal error: interrupted system call
```

I saw a recent changes to fallocate() done here: https://github.com/coreos/etcd/pull/4785
This might be a regression. (this is a RHEL7 with `3.10.0-229.7.2.el7.x86_64` kernel)

@heyitsanthony FYI

### PR DESCRIPTION
**Pull request by heyitsanthony**
Fixes #5558

### CODE REVIEW

**Comment by mfojtik** [comment]
@heyitsanthony I think you have to fallback in the preallocFixed() as well.

**Comment by mfojtik** [comment]
@heyitsanthony I think this fixed stuff for me: https://github.com/openshift/origin/pull/8856/commits/a9c6dc4a387c232f97454609047317c6a9133bb0

**Comment by heyitsanthony** [comment]
@mfojtik the calls to preallocFixed will corrupt the tail on EINTR (leading to crc mismatches) because of that kernel bug so I removed it entirely from wal. The preallocExtend calls should be OK even if EINTR'd since there's no data yet.

**Comment by gyuho** [comment]
lgtm. defer to @xiang90

**Comment by xiang90** [comment]
lgtm

**Pull request merged**
