### PR TITLE
fileutil: avoid double preallocation

### LINKED ISSUE #5616: Initial WAL file preallocates twice the segment size
Starting up a new etcd cluster, two files are allocated, each at the segment size. The comments around the commit that added preallocation seemed to indicate they intended to preallocate a file equal to the segment size.

### PR DESCRIPTION
**Pull request by liggitt**
fixes #5616

### CODE REVIEW

**Comment by liggitt** [comment]
nm, misread disk usage reports

**Comment by heyitsanthony** [comment]
@liggitt this patch does the right thing. Reopen?

**Comment by heyitsanthony** [comment]
@liggitt can you change the commit message to `fileutil: Avoid double preallocation`? then I can merge it. Thanks!

**Comment by liggitt** [comment]
done

**Comment by heyitsanthony** [comment]
lgtm, merging on ci greenlight

**Pull request merged**
