### PR TITLE
Added more lines of comments into rpc.proto

### PR DESCRIPTION
**Pull request by ychen11**
# Why

As I talked to @heyitsanthony on irc today, this rpc.proto is the only one doc we can read to figure out how the v3 api works.

So I added these two lines of comments to explain the range_end field in watch create request is totally same as in range request.

### CODE REVIEW

**Comment by gyuho** [comment]
@ychen11 Also update the generated code by running `./scripts/genproto.sh`?

**Comment by ychen11** [comment]
@gyuho Re-generated the code, but CI still failed. Not sure if it is because my go version is 1.6.2, not as same as 1.7.1 on CI

**Comment by gyuho** [comment]
@ychen11  Please

1. update your local branch with latest commits to avoid merge conflict
2. squash all commits into one
3. push force to your local branch from this PR

**Comment by ychen11** [comment]
@gyuho Travis still failed....

**Comment by ychen11** [comment]
@gyuho RFR, thanks

**Comment by gyuho** [comment]
lgtm. Thanks.

**Pull request merged**
