### PR TITLE
Procfile, V3DemoProcfile: add default endpoint of v3 to Procfile remo…

### PR DESCRIPTION
**Pull request by mitake**
…ve V3DemoProcfile

The flag --experimental-v3demo is already removed so V3DemoProcfile
cannot be used. This commit removes it and adds a default v3 endpoint
to Procfile for easy testing.

### CODE REVIEW

**Comment by mitake** [comment]
Same port can be used for both of http request and gRPC thanks to cmux, so providing dedicated endpoints isn't required? Should I change the default endpoint in etcdctlv3 instead of Procfile?

**Comment by mitake** [comment]
@xiang90 How do you think about this change and the default endpoint for gRPC? I think simply changing the default endpoint of etcdctlv3 from 2379 to 12379 is fine.

**Comment by xiang90** [comment]
@mitake We cannot do this right now since the proxy does not support v3. You have to start v3 with goreman -f V3DemoProfie start for dev for now.

**Comment by mitake** [comment]
@xiang90 then only removing the obsolete flag from V3DemoProcfile is acceptable? The file cannot launch etcd processes now.

**Comment by xiang90** [comment]
@mitake Yea. Please do that. Thanks!

**Comment by mitake** [comment]
@xiang90 removed the flag, PTAL.

**Comment by xiang90** [comment]
lgtm

**Pull request merged**
