### PR TITLE
clientv3: added IsDelete to watch events

### PR DESCRIPTION
**Pull request by luedigernet**
watch Events: added IsDelete to watch events

To get the eventhandling straight forward.

This is my first contribution please be lenient if the form is not yet 100%.

# Contributing guidelines

Please read our [contribution workflow][contributing] before submitting a pull request.

[contributing]: https://github.com/coreos/etcd/blob/master/CONTRIBUTING.md#contribution-flow

### CODE REVIEW

**Comment by luedigernet** [comment]
I can't see any relation to my pull request.
I'll realy appreciate it if someone could point me to the right direction to fix that issue.

**Comment by heyitsanthony** [comment]
Is there a reason why using `e.Type == EventTypeDelete` isn't enough? would like to keep the API minimal...

**Comment by luedigernet** [comment]
For sure that would be enough but from my point of view it feels not good.

For example having code that uses the clientv3 stuff and has to distinguish between all 3 cases it would be fine if you could identify the type of an event in the exact same way. At least in my mind the question popped up immediately why are there IsModify and IsCreate but no IsDelete.

**Comment by heyitsanthony** [comment]
> the question popped up immediately why are there IsModify and IsCreate but no IsDelete.

Because the first two are composite operations that have to check revisions but the last one isn't.

**Comment by luedigernet** [comment]
Hmm indeed IsPut is nonsense, over IsDelete I hat my own opinion even if I understand what you mean.

My intention was if they offer convenient functions like IsModify & IsCreate why not offer full convenient set of functions for the Customer especially when the change is so simple as this one.

But I'm not a maintainer so it is your decision if you accept it or not.

Not big deal if not I could live with it 

Kind regards 
Reinhard

**Comment by xiang90** [comment]
it does seem like this is a frequent user requirement. so i am closing it. if it pops up again, we might consider to add this kind of utilities func.

**Pull request closed without merging**
