### PR TITLE
Automated cherry pick of detailed "took too long" warnings to release-3.2

### PR DESCRIPTION
**Pull request by jpbetz**
Cherry pick request "took too long" warning improvements to release-3.2.

To improve debuggability of etcd.  This is important since etcd 3.1+ no longer appended quorum writes to WAL log, and this will the only record expensive requests.

#9288: etcdserver: improve request took too long warning
#9661: etcdserver: not print password in the warning message of expensive request
#9822: etcdserver: Replace value contents with value_size in request took too long warning
#9826: etcdserver: Add response byte size and range response count to took too long warning
#9835: etcdserver: Fix txn request 'took too long' warnings to use loggable request stringer

### CODE REVIEW

**Comment by jpbetz** [comment]
After discussing with @gyuho, we'd like to only log the payload size, and not the payload contents, so we'll first fix that on master and then cherrypick it back.

This PR will be on hold until we sort that out.

**Comment by gyuho** [comment]
@jpbetz Sounds good. Right now, we manually redact password field only for etcd https://github.com/coreos/etcd/pull/9661 but user may have sensitive data in its payload. And I notice these warnings are really hard to read with large values (dumping 1 MB plaintext to stderr). /cc @xiang90

**Comment by jpbetz** [comment]
d@gyuho Ah, I need that as well. I'll augment `raft_internal_stringer.go` to also replace `value` fields (of type []byte) with `value_size` (of type int64).

**Comment by gyuho** [comment]
@jpbetz Do we also want https://github.com/coreos/etcd/pull/9835 to be backported? Otherwise, lgtm?

**Comment by jpbetz** [comment]
@gyuho Thanks, yes, I had manually fixed this backport with the same fix as in #9835, but it's cleaner to actually cherrypick that exact #9835 fix back so all the attribution and future backports are as clean as possible, so I've done that.

**Comment by jpbetz** [comment]
I'll send out a 3.3 backport shortly.

**Comment by gyuho** [comment]
@jpbetz Oh, those are already backported to 3.3 yesterday :)

LGTM. thanks!

**Pull request merged**
