### PR TITLE
raft: Set the RecentActive flag for newly added nodes

### PR DESCRIPTION
**Pull request by aaronlehmann**
I found that enabling the `CheckQuorum` flag led to spurious leader elections when new nodes joined. It looks like in the time between a new node joining the cluster, and that node first communicating with the leader, the quorum check could fail because the new node looks inactive. To solve this, set the `RecentActive` flag when nodes are first added. This gives a grace period for the node to communicate before it causes the quorum check to fail.

This seems like a decent way to solve the problem, but please feel free to suggest other approaches instead.

### CODE REVIEW

**Comment by aaronlehmann** [comment]
Any thoughts on this propsed change? The extra leader elections when `CheckQuorum` is enabled are a bit of a pain point for me.

**Comment by xiang90** [comment]
can you write a test for this?

**Comment by xiang90** [comment]
this change looks reasonable.

**Comment by aaronlehmann** [comment]
Thanks. I've added a test.

**Comment by xiang90** [comment]
LGTM.

**Comment by xiang90** [comment]
@aaronlehmann Thanks.

**Pull request merged**
