### PR TITLE
client: follow golint notice change errors.New to fmt.Errorf 

### PR DESCRIPTION
**Pull request by davygeek**

### CODE REVIEW

**Comment by xiang90** [comment]
lgtm. Thanks for the contribution!

**Comment by davygeek** [comment]
@xiang90  why "Some checks were not successful" ?

**Comment by gyuho** [comment]
@davygeek Sorry, could you create another branch to push this commit? `git` seems working weird with commit title checking when someone pushes commit from master branch.

**Comment by davygeek** [comment]
@gyuho ok, I create another one, thanks.

**Pull request closed without merging**
