### PR TITLE
etcdserver: v2api refactor

### PR DESCRIPTION
**Pull request by heyitsanthony**
Splits out V2 operations similar to how it's done with V3. Eventually the interfaces could be implemented to use V3 `storage` instead of `store`.

### CODE REVIEW

**Comment by gyuho** [comment]
Since it's refactoring, can we also change `v3demo_server.go` to `v3_server.go` with another commit?

**Comment by gyuho** [comment]
lgtm. defer to @xiang90 

thanks.

**Comment by xiang90** [comment]
LGTM. Thanks. Much cleaner...

**Comment by heyitsanthony** [comment]
folded the v3demo_server rename into this pr; merging on greenlight

**Pull request merged**
