### PR TITLE
embed: reject domain names before binding

### LINKED ISSUE #6336: Listen peer URLs accepts domain names incorrectly
From the docs: https://github.com/coreos/etcd/blob/master/Documentation/op-guide/configuration.md#--listen-peer-urls etcd should not allow domain names in listen-peer-urls, but I'm finding that it does.

I don't actually know if this causes any problems, but it seems like it shouldn't be allowed regardless if it does work.

Unfortunately, this was found in my setup of etcd 2.3.2 so I didn't test with 3.0.0 nor 2.3.7 since neither are included in the CoreOS image and I didn't have time to check if this is true of the latest releases. However, I believe it does work, as @dghubble's examples in coreos-baremetal set up etcd using the domain name as peer URLs, which he says has been working.

My etcd2.service is located in the gist along with logs. As you can see, I'm getting no validation errors, and etcd proudly proclaims it's listening on a domain name + port. 

https://gist.github.com/chancez/2b97ae9d2b0c225e98ac964e740f27bd

### PR DESCRIPTION
**Pull request by heyitsanthony**
Fixes #6336

### CODE REVIEW

**Comment by xiang90** [comment]
lgtm

**Comment by richinsr** [comment]
FYI, anyone using domain names and upgrading to the published 3.0.8 release will have their cluster break.  Thoughts about cutting a new release with the reverted merge included?

**Comment by heyitsanthony** [comment]
@richinsr the revert will be in 3.0.9 this Friday. How is it breaking the cluster on upgrade? It will only reject the flags starting an upgraded member-- the cluster can stay on 3.0.7 if the 3.0.8 upgrade doesn't take.

**Comment by richinsr** [comment]
@heyitsanthony I was working on upgrading a cluster today for someone else and the first node that was upgraded to 3.0.8 failed to start given the config uses a domain name for listen-peer-urls.  It took a bit to track down this thread to realize that the config is wrong in the fist place (cluster was setup by someone else).  If enforcement of not using domain names will be addressed in 3.1 then anyone in my same boat who upgrades to 3.0.8 will encounter a failure but every other release in the 3.0.x family will work.   Maybe it is as simple as adding a note to https://github.com/coreos/etcd/blob/master/NEWS

**Comment by heyitsanthony** [comment]
@richinsr it'll be enforced in 3.2. 3.1 will just have a warning.

**Pull request merged**
