### PR TITLE
v3api, rpctypes: add ErrUnhealthy

### PR DESCRIPTION
**Pull request by heyitsanthony**
/cc @hongchaodeng

### CODE REVIEW

**Comment by xiang90** [comment]
lgtm

**Comment by gyuho** [comment]
LGTM.

Where is this error type used? Is it just for external project?

**Comment by hongchaodeng** [comment]
Let me try this patch tomorrow

**Comment by hongchaodeng** [comment]
@gyuho 
If we just changed membership, second AddMember() will encounter this failure.
From user's perspective, we can retry on such transient error.

@heyitsanthony 
Thanks for the quick fix!

**Comment by hongchaodeng** [comment]
Verified.
LGTM

**Pull request merged**
