### PR TITLE
/health endpoint behavior in case of failure

### PR DESCRIPTION
**Pull request by Bhaal22**
Hi,

This pull request to differentiate health status from a regular Raft fail and a Raft in progress process from whom the client exceeds the maximum number of retries.
## Noticed Behavior :
- Internally I have a kubernetes cluster and I associated one single etcd server.
- On top of that I monitor healtchchecks by runnning on a regular basis : **kubectl get cs** and get results.

Frequently I see this status :

```
etcd-0               Unhealthy   {"health": "false"}
                     unhealthy http status code: 503
```

I have the same output by doing a curl command when etcd is in that state, of course.

While reading the /health endpoint code, I was not able to fully determine which part of the /health failed.

It can makes sense to have :
-  HTTP 500 : when raft fails
-  HTTP 503 : when the service is really not available

Moreover, it seems the raft process takes more than 1 second to proceed, I think it could be advised to increment the number of retries of the time to wait for the process to finish.

Bhaal22.

### CODE REVIEW

**Comment by xiang90** [comment]
How will your service react differently if etcd returns different http code for no leader and leader fails to commit a proposal for the given amount of time?

**Comment by Bhaal22** [comment]
From what I see every 20-25 rounds of call to /health this one is failing and a few milliseconds after it is back.
I am not a raft expert, but doing differentation could help in monitoring.
I say again, I have a single etcd node cluster and I noticed this weird issue.

I am not sure how kubernetes handle etcd status when calling kubectl get cs or internally checks for etcd0, but we would generate a log of warnings.

Client code could rely on http error code to perform retries and be sure in which condition etcd is.
Using the same error code and same content, how a client call could make differentation.

**Comment by xiang90** [comment]
> From what I see every 20-25 rounds of call to /health this one is failing and a few milliseconds after it is back.
I am not a raft expert, but doing differentation could help in monitoring.
I say again, I have a single etcd node cluster and I noticed this weird issue.

This is strange. Can you reliable reproduce this? If you can, we would like to look into it.

**Comment by Bhaal22** [comment]
sure. i'll be off a couple of days. I'll do it as soon as I come back next week.

**Comment by xiang90** [comment]
@Bhaal22 Thanks!

**Comment by xiang90** [comment]
@Bhaal22 kindly ping.

**Comment by heyitsanthony** [comment]
Closing due to lack of activity. Thanks!

**Pull request closed without merging**
