### PR TITLE
etcdserver: make serialized txns auth-aware

### PR DESCRIPTION
**Pull request by heyitsanthony**
/cc @mitake

### CODE REVIEW

**Comment by heyitsanthony** [comment]
After looking at the Range serialized request code again, I see that it's really racey with the way the auth applier handles usernames. I'll fix that here too.

**Comment by mitake** [comment]
@heyitsanthony thanks for doing this! Do you mean we need to protect cached range permission information? If you didn't start it, I can do this. Are you already working on it?

**Comment by heyitsanthony** [comment]
@mitake two concurrent serialized requests would go through Apply(), but since there's no locking on the shared field `aa.user`, there's a data race. I added a lock to authApplier to fix it for the time being.

It's possible to avoid the lock if it turns out to be a performance problem (there's already a big lock around mvcc now so it may not make much of a difference). However, there can be a TOCTOU data leak if auth perms are updated concurrently with the serialized read. The schedule would be: get auth for serialized request at rev=0 and yield thread, revoke auth perms at rev=n, write to a key at rev=n+1, serialized request thread wakes up and fetches key at rev=n+1. The way around this is to track the last auth update revision and retry the request if the revision changes.

**Comment by xiang90** [comment]
lgtm

**Comment by mitake** [comment]
@heyitsanthony yes, the revision of auth information must be considered. Currently authStore is using backend directly for using special bucket names so it isn't revision aware. Maybe just adding a new key of integer for representing auth revision would be ok?

**Comment by mitake** [comment]
@heyitsanthony on the second thought, the real source of the TOCTOU problem would be that permission checking and access is not processed atomically (these are divided in the schedule). Integrating authStore to mvcc or having a big lock that protect both of them seems to be required. How do you think?

**Comment by heyitsanthony** [comment]
@mitake yeah, auth could maintain its own internal revision sequence that's distinct from the kv store revision. Full mvcc or mvcc integration for auth seems like there could be circular dependency issues / a high degree of coupling.

I don't think a big lock (i.e., right now, the authApplier mutex) is necessary with an internal auth revision scheme. Writes/permission updates are already processed in-order by the raft apply loop. Serialized reads/txns are out-of-order but can retry/recheck permissions if the auth revision changes since reads are idempotent.

May be overthinking this. If serialized reads are too slow it might be simpler to handle it by offloading to a proxy instead of optimizing this path in the core etcd server.

**Comment by mitake** [comment]
@heyitsanthony I'm still not sure we don't need the big lock for preventing TOCTOU problem for serialized read:
> serialized request thread wakes up and fetches key at rev=n+1.

Actually the above step will have two individual steps: validating auth revision of the request + fetching a key. For avoiding the separation, the big lock or integration of auth + mvcc would be required?

\# I agree with that it is overthinking. serializable read would be attractive feature because read request would dominate etcd traffic. However, improving read performance with serializable read sacrifices write performance. The approach of proxy will be the correct way for read performance improvement (in addition, no proxy approach wouldn't be able to support enough clients because of the exaustion of TCP port numbers). Will serialized requests be obsolete after completion of v3 proxy implementation?

Anyway auth revision is required for avoiding another TOCTOU problem: checking permission of linearizable requests is done in the apply phase based on its user name but looking up the user name is done in the API layer. As we discussed in the design doc, I'll add the revision number to authStore and the request header for avoiding the problem.

**Comment by heyitsanthony** [comment]
@mitake sure, there would have to be a big lock or mvcc integration to avoid the validation/fetch split, but it seems more complicated than just fetching the key then pessimistically retrying if the auth revision changed. Is this approach broken?

Serialized request performance probably won't be as important with the proxy, but the facility is still necessary for accessing keys when the cluster can't reach quorum.

**Comment by mitake** [comment]
@heyitsanthony ah, I understand what you mean. Fetching a key -> checking auth revision seems to be completely fine for me!

And yes, serializable read is important for the purpose.

**Pull request merged**
