### PR TITLE
Documentation/v2: remove implementation detail

### PR DESCRIPTION
**Pull request by gyuho**
`etcd init` command does not exist.

### CODE REVIEW

**Comment by heyitsanthony** [comment]
should the `etcd init` stuff be removed entirely? I don't think it was ever in 2.x and 0.4 is officially deprecated

**Comment by gyuho** [comment]
Just removed the whole doc. Would it break anything? I don't see anywhere it's referenced.

**Comment by heyitsanthony** [comment]
I think it's fine to remove since it's disconnected form the rest of the docs. However, it's also explaining design choices for the boot ux (e.g., why etcd doesn't have `etcd init``), should the content be preserved / moved somewhere more sensible?  /cc @xiang90

**Comment by xiang90** [comment]
lgtm

**Pull request merged**
