### PR TITLE
v3: allow more ops in txns

### PR DESCRIPTION
**Pull request by xiang90**
@blp 

There is an additional txn number checking. Probably now we can make is larger since we already set the 1MB txn size limit.

### CODE REVIEW

**Comment by xiang90** [comment]
@heyitsanthony

**Comment by heyitsanthony** [comment]
context?

**Comment by xiang90** [comment]
@heyitsanthony 

```
etcd 3.0 implements transactions.  A testing report from Andy
      Zhou indicates that the size of a transaction is limited to
      about 100 keys, although it wasn't clear to him whether that was
      a limit or a bug.  If this is a limit, it would disqualify etcd
      unless we layered some kind of higher-level transaction system
      on top of it or dropped the need for transactions.
```

ovs might want more ops in one txn. Applying a small op takes less than 50us in normal cases. Supporting 512 or even 1024 ops per txn is not a concern in my opinion.

**Comment by heyitsanthony** [comment]
@xiang90 Sure, I'm mainly curious what the desired number of ops per txn would be for their use case. Is 1024 enough?

**Comment by xiang90** [comment]
@blp Can you provide more information here?

Also for transnational read, etcd support consistent snapshot + pagination. You can do multiple txns over multiple keys on one consistent snapshot.

**Comment by blp** [comment]
@xiang90 It is really amazing that you submitted a pull request on the basis of a report on Twitter.  Thank you very much!

We are currently just trying to figure out whether etcd is suitable for our use case.  We do not have a specific number yet.  Since now I know that this limit is adjustable, I have enough information to continue investigating.  I'll come back when I know more.

**Comment by purpleidea** [comment]
FWIW I will have use cases which will hit 1024 ops. So I appreciate this feature, and would gladly welcome 1024 or more. When I have some production code demonstrating this we can always revisit and increase if needed, but this is a good start :)

**Comment by heyitsanthony** [comment]
Superseded by #7976. Closing

**Comment by purpleidea** [comment]
Awesome work!

**Pull request closed without merging**
