### PR TITLE
concurrency: use current revisions for election

### LINKED ISSUE #7815: Observe() can't retrieve leader information if leader's ModRevision < compacted revision for election api.
In the case that when `Observe()` on a leader and its [`ModRevision`](https://github.com/coreos/etcd/blob/master/clientv3/concurrency/election.go#L203) < `Compacted Revision`(due to compaction), Observe() closes and doesn't return any leader information. It will be impossible to retrieve the leader information using `Observe()` in this situation.

### PR DESCRIPTION
**Pull request by heyitsanthony**
Watching from the leader's ModRevision could cause live-locking on
observe retry loops when the ModRevision is less than the compacted
revision. Instead, start watching the leader from at least the store
revision of the linearized read used to detect the current leader.
    
Fixes #7815

### CODE REVIEW

**Comment by fanminshi** [comment]
lgtm

**Comment by xiang90** [comment]
the fix looks good to me.

i am thinking:

1. if we can merge the two watch code path in observe func.

2. do we really need to return ANY historical proposals. or just observe from current is good enough for users.

**Comment by heyitsanthony** [comment]
1. yeah, that should be do-able.
2. most recent is probably good enough. Relying on historical election data seems like broken app logic.

**Comment by heyitsanthony** [comment]
@xiang90 I gave the watch path merging another thought. The most obvious way to do it would be to open a watch on the prefix, but that will cause extra traffic from events that can be ignored (e.g., campaigner leaves before ever winning election). Not sure what should/would be simplified exactly.

**Comment by xiang90** [comment]
> Not sure what should/would be simplified exactly.

OK. I am not super worried about it. Just one random thought. I am OK with merging this pr as it is. We need to put some thought into my second point though.

**Comment by heyitsanthony** [comment]
OK merging since failures are unrelated.

**Pull request merged**
