### PR TITLE
Fix typos one commit

### PR DESCRIPTION
**Pull request by jeis2497052**
Markdown: fixed typos

just a documentation change.

### CODE REVIEW

**Comment by gyuho** [comment]
@jeis2497052 We have tests to check git commit titles. It must be formatted `package: commit message`. In this case, we can format the git commit title to `*: commit message`.

**Comment by jeis2497052** [comment]
so it should be
etcd: fix typos

?

**Comment by gyuho** [comment]
@jeis2497052 Yes, that should work as long as we have some top level package or name in front with colon(:).

**Comment by jeis2497052** [comment]
got it, sorry it took me so long

**Comment by hexfusion** [comment]
@jeis2497052 not to muddy the waters but this is how I do what your trying to do. I use the interactive feature of rebase.

so in the case, you have a single commit you want to change.

```
commit 61bc0678e2cefae0ead5d664855ccdacac0b4e95 (HEAD -> e2e-member, origin/e2e-member)
Author: Sam Batschelet <samb@endpoint.com>
Date:   Sat Jan 20 12:22:46 2018 -0500

    Fix typos one commit
 
[...]

$ git log
```
Notice the number after the tilde that is the number of commits I want to include in this case 1 or the last commit in my log.

```
$ git rebase -i HEAD~1
```

This will pop you into a screen that looks like this. It gives you a few options. You can see `pick` to the left of the commit. If you were to leave it as is it would just use the same commit or basically do nothing.

```
pick 61bc0678e Fix typos one commit                             
                                                                              
# Rebase 0b9dc9ccd..61bc0678e onto 0b9dc9ccd (1 command)                      
#                                                                             
# Commands:                                                                   
# p, pick = use commit                                                        
# r, reword = use commit, but edit the commit message                         
# e, edit = use commit, but stop for amending                                 
# s, squash = use commit, but meld into previous commit                       
# f, fixup = like "squash", but discard this commit's log message             
# x, exec = run command (the rest of the line) using shell                    
# d, drop = remove commit 
```

 but if you change pick to `reword` or the letter `r`.

```
reword 61bc0678e Fix typos one commit                             
                                                                              
# Rebase 0b9dc9ccd..61bc0678e onto 0b9dc9ccd (1 command)                      
#                                                                             
# Commands:                                                                   
# p, pick = use commit                                                        
# r, reword = use commit, but edit the commit message                         
# e, edit = use commit, but stop for amending                                 
# s, squash = use commit, but meld into previous commit                       
# f, fixup = like "squash", but discard this commit's log message             
# x, exec = run command (the rest of the line) using shell                    
# d, drop = remove commit 
```

your next screen will allow you to update your commit message.

```
Fix typos one commit                                           
                                                                              
# Please enter the commit message for your changes. Lines starting            
# with '#' will be ignored, and an empty message aborts the commit.           
#                                                                             
# Date:      Sat Jan 20 12:22:46 2018 -0500                                   
#                                                                             
# interactive rebase in progress; onto 0b9dc9ccd                              
# Last command done (1 command done):                                         
#    reword 61bc0678e e2e: improve Member TLS coverage.                       
# No commands remaining.                                                      
# You are currently editing a commit while rebasing branch 'e2e-member' on '0b9dc9ccd'
```

Then you change `Fix typos one commit` to `etcd: fix typos`

and finally

`$ push -f`

Now I know this is a lot and there are simpler ways to do this as @gyuho pointed out. But if you learn how to use `rebase -i` your life will be much easier in the long run. I hope this is helpful.

good doc in general
https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history

**Comment by jeis2497052** [comment]
very helpful.  I will give this a shot

**Comment by hexfusion** [comment]
@jeis2497052 going to close this as it is a dupe effort of https://github.com/coreos/etcd/pull/9268 please let us know if you need any more help rebasing.

**Pull request closed without merging**
