### PR TITLE
Update freebsd.md

### PR DESCRIPTION
**Pull request by skarekrow**
Packages have changed names.

### CODE REVIEW

**Comment by xiang90** [comment]
doc change looks good to me. Can you please update the commit message to `doc: Update freebsd.md`?

Thanks!

**Comment by skarekrow** [comment]
To clarify, you want the *message* to say `doc: Update freebsd.md` correct? Not the title of the commit?

**Comment by xiang90** [comment]
@skarekrow Yes commit message. So git commit --amend. Then change the commit message. :) Thanks!

**Comment by skarekrow** [comment]
All good to go :)

**Comment by xiang90** [comment]
@skarekrow Sorry. I should have been more explicit. I assumed the title you referred to is the pull request title on github. git only has message, no title. So I expect to see 

```
doc: Update freebsd.md

Packages have changed names from coreosetcd to coreos-etcd
```

**Comment by skarekrow** [comment]
That's why I was a bit confused :+1:. All fixed.

**Comment by xiang90** [comment]
Thanks

**Comment by skarekrow** [comment]
No problem

**Pull request merged**
