### PR TITLE
*: gRPC + HTTP on the same port

### PR DESCRIPTION
**Pull request by xiang90**
We use cmux to do this since we want to do http+https on the same
port in the near future too.

Plan:
  l -> cmux: 

1. if insecure http2 with grpc header -> grpc
2. if insecure http1 -> v2 handler
3. others (secure http1 or http2): go http server.

go's http server is able to mux secure http1 and http2 (both grpc and other handlers)

/cc @philips

### CODE REVIEW

**Comment by xiang90** [comment]
@heyitsanthony I am still trying to figure out which cmux (cockroach fork or the original one) should we use.

**Comment by heyitsanthony** [comment]
@xiang90 looks like whatever file that has `serve` is missing

**Comment by xiang90** [comment]
@heyitsanthony PTAL.

**Comment by heyitsanthony** [comment]
lgtm

**Comment by gyuho** [comment]
lgtm. Can we still do `curl ~:2379/v2/metrics` ?

**Comment by gyuho** [comment]
tested and curl worked.

**Pull request merged**
