### PR TITLE
Fixes a issue that caused panic due to write on a closed channel.

### PR DESCRIPTION
**Pull request by SuhasAnand**
Problem:

121	r := report.NewReportRate("%4.4f")
122	for i := range streams {
123	go doWatch(streams[i], requests, r.Results()) <- The Results sent here is also propagated to the goroutines in the doWatch function:

188 bar.Increment()
189	go recvWatchChan(wch, results) <- Notice the results chan being sent here.

The channel is how ever closed when watchCompletedNotifier notifies,
136	<-watchCompletedNotifier
137	bar.Finish()
138	close(r.Results())

The fix should involve two separate report instantiation.

 #8056

### CODE REVIEW

**Comment by heyitsanthony** [comment]
@SuhasAnand how can I trigger the `panic: send on closed channel` so I can confirm this fixes it?

**Comment by SuhasAnand** [comment]
@heyitsanthony its quite easy just run the benchmark tool benchmark --endpoints <endpoints here>  watch 

It will crash... also from the logic its quite evident...

**Comment by heyitsanthony** [comment]
@SuhasAnand yes it's hanging using master, but not crashing. I tried it with this patch and it's still hanging, which is why I'm asking how to demonstrate this fixes something.

**Comment by SuhasAnand** [comment]
@heyitsanthony could you try master and watch with following option : 

benchmark --endpoints <your endpoints here> watch --clients 1 --put-total 10 --total 10 --watchers 4

**Comment by heyitsanthony** [comment]
ok but it still hangs with the defaults... I'm going to fix this for good since there's been no progress on #7922

**Comment by SuhasAnand** [comment]
@heyitsanthony imho the hang on the default is possibly needs to be tracked as a different issue... Its not related to the report channel being closed while there are writers active on the chanel..

**Comment by heyitsanthony** [comment]
@SuhasAnand I'm restructuring it. This has been broken too long.

**Comment by SuhasAnand** [comment]
@heyitsanthony agree

**Comment by heyitsanthony** [comment]
superseded by #8069. closing

**Pull request closed without merging**
