### PR TITLE
raft: attach commit index into the heartbeat response

### PR DESCRIPTION
**Pull request by xiang90**
@yichengq @bdarnell

### CODE REVIEW

**Comment by yichengq** [comment]
Could you add some commit body about the reasons of the change?

**Comment by bdarnell** [comment]
What do you intend to do with this information? This is the first time we send the Commit index from follower to leader. In multiraft we want to avoid per-group information like this in heartbeat requests and responses.

**Comment by xiang90** [comment]
@yichengq @bdarnell 

Follower attaches commit index in heartbeat message. This is a preparation for
not resending snapshot until the pending one is failed. There is a case that
the snapshot is received successfully but the response is lost. The only active
channel between the leader and the follower at this point is the heartbeat, since
the snapshot resending is disabled. We need to attach some information into the
heartbeat to ack the leader that the snapshot is actually received.

**Comment by yichengq** [comment]
An alternative is to let raft resend snapshot message after the old snapshot message has been sent and it has waited for some ticks. It can wait a long time for the response considering the cost of resending can be huge.

If we do this PR, how could we determine which heartbeat response implies that the snapshot is lost?

**Comment by xiang90** [comment]
> An alternative is to let raft resend snapshot message after the old snapshot message has been sent and it has waited for some ticks. It can wait a long time for the response considering the cost of resending can be huge.

That is almost impossible and still involves some random ticks inside raft. Current a snapshot resend waits for a leader election timeout, which does not work well for large snapshot.

**Comment by xiang90** [comment]
@bdarnell 

> In multiraft we want to avoid per-group information like this in heartbeat requests and responses.

I understand your concern. However, we have to find a way to piggy back the current raft state machine information of the followers when there is a pending snapshot sent. Or the leader has to re-trigger the snapshot based on some estimated timeout.

**Comment by bdarnell** [comment]
Even with the commit index in the heartbeat response, don't you have to use timeouts in the leader? How do you tell that a heartbeat response came after the failure of a snapshot instead of crossing in the network?

**Comment by xiang90** [comment]
@bdarnell 

If the commit index is greater than the pending snapshot, the leader should be safe to start appending logic.

If the commit index is smaller than the pending snapshot and link layer does not report a failure, the leader should not resend snapshot.

If the commit index is smaller than the pending snapshot and link layer has reported a failure, the leader need to resend the snapshot for sure.

**Comment by bdarnell** [comment]
But the link layer cannot necessarily track success or failure. Because of their size, snapshots may be transmitted on separate channels from regular messages. I think the leader needs to use a timeout to detect failed snapshots (the follower can send a MsgAppResp on success). On a timeout, however, it shouldn't immediately resend the snapshot. Instead, send an MsgApp and don't retry the snapshot unless it is rejected.

**Comment by xiang90** [comment]
> But the link layer cannot necessarily track success or failure.

We plan to have a separate transport just for snapshot. :(

> On a timeout, however, it shouldn't immediately resend the snapshot. Instead, send an MsgApp and don't retry the snapshot unless it is rejected.

Hmm... Ok. I can try with the probing approach.

**Comment by xiang90** [comment]
> On a timeout, however, it shouldn't immediately resend the snapshot. Instead, send an MsgApp and don't retry the snapshot unless it is rejected.

Say if we have a 1 second timeout, a snapshot might take 3 minutes to send. After 1 second, we send out a MsgApp and follower rejected since it has not received a snapshot. Then it triggers a unwanted resending logic. 

Basically, 1) we need to report the snapshot sending failure or 2) we need to tell raft follower it is receiving a snapshot from the leader and please hold off the rejection for that leader.

**Comment by bdarnell** [comment]
If you expect it to take 3 minutes to send a snapshot then you'd have to set the timeout to 3 minutes, not 1 second. 

I don't see how you get around using timeouts on the leader. If you split up the snapshot processing (say an MsgSnapshotBegin followed by one or more MsgSnapshotData and an MsgSnapshotEnd), the follower would know that a snapshot is in progress but there is no guarantee that this process once started will proceeded to the end without retries from the leader. You can require that snapshots be sent over a reliable stream so errors can be reported (and there are still timeouts, but they are hidden in the TCP stack instead of exposed to raft), but this is at odds with the datagram-like nature of the rest of the messages.

**Comment by xiang90** [comment]
> If you expect it to take 3 minutes to send a snapshot then you'd have to set the timeout to 3 minutes, not 1 second.

How shall we communicate the expectation to raft?

> You can require that snapshots be sent over a reliable stream so errors can be reported (and there are still timeouts, but they are hidden in the TCP stack instead of exposed to raft), but this is at odds with the datagram-like nature of the rest of the messages.

If the link layer does not have the detection/retry ability, then there is no way to reliably trigger the retry logic without the interference of the resource of the data. The leader has to trigger the resend. 

We do want to hand off the responsibility to link layer for this case. 

If we are OK with raft to be aware of the size of the snapshot and have a estimate resend timeout (in terms of ticks, not real time), I am OK with it.

**Comment by bdarnell** [comment]
Well, if we split the snapshot up into multiple smaller messages, then each message should be acknowledged within the regular heartbeat timeout. But the more I think about this the more it sounds like just reimplementing TCP, so maybe it is better to just rely on the underlying transport layer.

**Comment by yichengq** [comment]
@xiang90 Maybe our raft transport can drop the retry snapshot message to avoid the additional send cost, because it has the exact information about whether the message send is still in progress. When it reaches the remote machine, it can probe the progress then.

**Comment by bdarnell** [comment]
Dropping the outgoing MsgSnap is too late - by that time we've already called Storage.Snapshot, which may be expensive.

**Comment by xiang90** [comment]
> But the more I think about this the more it sounds like just reimplementing TCP, so maybe it is better to just rely on the underlying transport layer.

Totally agree. That is the first approach I thought. And I do not want to implement TCP again. 

Seems like the best approach so far is to dynamically decide the snapshot retry timeout. Any idea? @yichengq @bdarnell

**Comment by bdarnell** [comment]
If we assume a reliable transport, then maybe we don't need the timeout at the raft level. Just leave it up to the transport to either deliver the snapshot or report failure back to the raft state machine, and the transport can decide about timeouts on its own.

**Comment by xiang90** [comment]
> Just leave it up to the transport to either deliver the snapshot or report failure back to the raft state machine

So basically a snapshot sending disables the replication. A link layer snapshot delivery/failure notification will re-enable the replication mechanism?

**Comment by bdarnell** [comment]
Yes, exactly.

FWIW, in Cockroach, we're going to try to deliver snapshots to new nodes in advance of actually adding them to raft, so the node will hopefully be ready to accept MsgApp as soon as it joins the group.

**Comment by xiang90** [comment]
> FWIW, in Cockroach, we're going to try to deliver snapshots to new nodes in advance of actually adding them to raft, so the node will hopefully be ready to accept MsgApp as soon as it joins the group.

That is what we are going to do. We are also thinking of catching up entries before entering raft world.

**Comment by xiang90** [comment]
@bdarnell The runtime snapshot sending is a big hole... Hopefully we can avoid that for 99% cases.

**Pull request closed without merging**
