### PR TITLE
etcdserver, api, membership: don't race on setting version

### LINKED ISSUE #6029: "Not Capable" errors after getting "3.0 version"
When doing
```sh
curl http://${ETCD_HOST}:${ETCD_PORT}/version
```

It gives output:
```
{"etcdserver":"3.0.3","etcdcluster":"3.0.0"}
```

Nonetheless, client still gets "not capable" error. The client is fine after retrying, which means etcd cluster has negotiated 3.0 version thereafter.

This "/version" endpoint is useful for bootstrapping servers after etcd.

### PR DESCRIPTION
**Pull request by heyitsanthony**
Fixes #6029

/cc @hongchaodeng @xiang90

### CODE REVIEW

**Comment by hongchaodeng** [comment]
With this fix, what's the output if we have v2 enabled? What if v3 enabled? How long does it take in between?

**Comment by heyitsanthony** [comment]
@hongchaodeng v2 will be `not_decided` or some 2.x in `etcdcluster`; basic v2 functionality should work regardless if you can fetch the version. If curl gives `etcdcluster` as >`3.0.0`, there shouldn't be any capability errors when using v3 api; this PR gets rid of that 500ms delay that we were discussing the other day.

**Comment by hongchaodeng** [comment]
Sounds good.
LGTM after test passed.

**Comment by xiang90** [comment]
lgtm

**Pull request merged**
