### PR TITLE
functional-tester: run locally

### PR DESCRIPTION
**Pull request by heyitsanthony**
Added support for launching etcd servers with separate ports and running the agent without root permissions. Includes a Procfile.

/cc @fanminshi @gyuho

### CODE REVIEW

**Comment by gyuho** [comment]
LGTM. Thanks!

**Comment by gyuho** [comment]
@heyitsanthony I don't see Procfile?

**Comment by heyitsanthony** [comment]
@gyuho good catch; forgot to add. All fixed.

**Comment by gyuho** [comment]
LGTM. Thanks.

**Comment by xiang90** [comment]
lgtm

**Pull request merged**
