### PR TITLE
backend: update db.size after defrag

### LINKED ISSUE #5132: etcdserver: defrag does not reclaim space as expected
Starting from a fresh single-node cluster with `--quota-backend-bytes=16777216`,

Fill the store:
```sh
$ while [ 1 ]; do ETCDCTL_API=3 dd if=/dev/urandom bs=1024 count=1024  | ./bin/etcdctl put key  || break; done 
...
Error:  rpc error: code = 8 desc = etcdserver: storage: database space exceeded
```
get the revision (9), compact (wait), defrag:
```
$ ETCDCTL_API=3 ./bin/etcdctl -w json endpoint status
[{"Endpoint":"127.0.0.1:2379","Status":{"header":{"cluster_id":8925027824743593106,"member_id":13803658152347727308,"revision":9,"raft_term":2},"version":"2.3.0+git","dbSize":16842752,"leader":13803658152347727308,"raftIndex":187,"raftTerm":2}}]
$ ETCDCTL_API=3 ./bin/etcdctl -w json compact 9
compacted revision 9
$ sleep 5s
$ ETCDCTL_API=3 ./bin/etcdctl defrag
Finished defragmenting etcd member[127.0.0.1:2379]
```

Checking db size, it's the same:
```
ETCDCTL_API=3 ./bin/etcdctl endpoint status
+----------------+------------------+-----------+---------+-----------+-----------+------------+
|    ENDPOINT    |        ID        |  VERSION  | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+----------------+------------------+-----------+---------+-----------+-----------+------------+
| 127.0.0.1:2379 | bf9071f4639c75cc | 2.3.0+git | 17 MB   | true      |         2 |        437 |
+----------------+------------------+-----------+---------+-----------+-----------+------------+
```

Once boltdb is modified (via `etcdctl alarm disarm`), it seems to take:
```
+----------------+------------------+-----------+---------+-----------+-----------+------------+
|    ENDPOINT    |        ID        |  VERSION  | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+----------------+------------------+-----------+---------+-----------+-----------+------------+
| 127.0.0.1:2379 | bf9071f4639c75cc | 2.3.0+git | 1.1 MB  | true      |         2 |        535 |
+----------------+------------------+-----------+---------+-----------+-----------+------------+
```

### PR DESCRIPTION
**Pull request by xiang90**
Fix #5132

### CODE REVIEW

**Comment by xiang90** [comment]
I am adding a test. Hold on.

**Comment by xiang90** [comment]
@heyitsanthony Added a test. This should work.

**Comment by heyitsanthony** [comment]
lgtm

**Comment by gyuho** [comment]
LGTM. Thanks.

**Pull request merged**
