### PR TITLE
CHANGELOG: Add 3.4 changelog entry for snapshot file permissions change

### PR DESCRIPTION
**Pull request by dlipovetsky**

### CODE REVIEW

**Comment by dlipovetsky** [comment]
I'm a little unsure as to where to put the release note. Please let me know if I should move this note--or add another note--to a different section. Thanks!

**Comment by hexfusion** [comment]
https://github.com/coreos/etcd/pull/9977

**Comment by gyuho** [comment]
Agree with @hexfusion. Let's also mention this in breaking changes section, to be safe.

**Comment by hexfusion** [comment]
@dlipovetsky, ust add this note to the client-v3 section of the doc rebase and we are good. Thanks!

https://github.com/coreos/etcd/blob/master/CHANGELOG-3.4.md#client-v3

**Comment by dlipovetsky** [comment]
@hexfusion and @gyuho Thanks for reviewing.

I put the note in both the "breaking changes" and "client v3" sections.

**Pull request merged**
