### PR TITLE
XXX: do not merge, test

### PR DESCRIPTION
**Pull request by purpleidea**

### CODE REVIEW

**Comment by purpleidea** [comment]
testing something, please ignore, sorry for the noise.

**Comment by xiang90** [comment]
Sorry. I have to close this one. Please do not use etcd repo for testing. There are a few hundreds people watching this repo. This is a spam for them.

**Comment by purpleidea** [comment]
gah, i was trying to get the test output to compare to my other branch. oh well. i guess that's as good a reason as any to shelf the debugging for tonight

**Comment by xiang90** [comment]
@purpleidea You can setup a CI on your own branch or you can rebase the existing pr you sent to etcd repo. :)

**Pull request closed without merging**
