### PR TITLE
osutil: fix InterruptHandler comment position

### PR DESCRIPTION
**Pull request by mateusbraga**

### CODE REVIEW

**Comment by xiang90** [comment]
LGTM

**Comment by mateusbraga** [comment]
One question: when we have two different files for two different build, like interrupt_unix.go and interrupt_win.go, should we duplicate the function documentation comments of the functions that are duplicated?

**Comment by xiang90** [comment]
@mateusbraga Good question. So in golang, a more elegant way to deal with this is to write a public function wrapper in xx.go around all the evn dependent private code in x_win.go; x_unix.go.... So you only need to document onec.

**Comment by xiang90** [comment]
@mateusbraga Good question. So in golang, a more elegant way to deal with this is to write a public function wrapper in xx.go around all the evn dependent private code in x_win.go; x_unix.go.... So you only need to document onec.

**Pull request merged**
