### PR TITLE
etcdmain: --unsupported flag for running etcd on unsupported platforms

### PR DESCRIPTION
**Pull request by heyitsanthony**

### CODE REVIEW

**Comment by gyuho** [comment]
lgtm. defer to @xiang90

**Comment by luxas** [comment]
What's the timeframe for `v2.3`? This seems like a resonable compromise. 
I thank you for your re-evaluation, and hope we may get a more stable 32-bit etcd from now on.
I will help with everything I can.

**Comment by gyuho** [comment]
@luxas We are planning to release `v2.3.0` with the current master branch, *sometime next week*. Once we publish the release binary, we can go forward merging related PRs. Thanks.

**Comment by xiang90** [comment]
@heyitsanthony Merge?

**Comment by luxas** [comment]
@hongchaodeng Can we proceed with this one or totally remove the blocker?
`v2.3.1` is released and this isn't in. 
This PR makes it hard anyway, 'cause we would have to `sed` in the `--unsupported` flag in etcd manifests, but we may fix that.

We need `etcd` for `arm`, `arm64` and `ppc64le` for Kubernetes, it's very experimental of course, but anyway.
So it would be great to get some support from you in this.

I've tested `v2.3.0` on 32-bit intel, and it fails with ~940 MB data in it, probably a boltdb issue or boltdb implementation issue. We could fix that by adding a `900MB` quota for `arm` (I think that's really good). 
I do not think `arm64` or `ppc64le` will suffer from the same limitations, and I'll test the same benchmark on `arm64` soon.

**Comment by hongchaodeng** [comment]
I don't handle etcd specifically. @heyitsanthony should be able to provide more information on the release, platform support plan, or that we are not sure either.

**Comment by luxas** [comment]
I'm asking @heyitsanthony then. It would be kind to answer.

**Comment by heyitsanthony** [comment]
@luxas I didn't see the merge comment from forever ago and github wasn't sending emails on the comments. Sorry! The OS guys suggested a few days ago that a flag is probably a bad idea for testing. I'm going to close this PR and redo as an env variable.

**Comment by luxas** [comment]
...or maybe just set a limit for `arm` and `386`. Can't we just do that?

No one will be angry at you for not commercially supporting 32-bit, they just might be thankful for not adding blockers. Folks might create issues, and in that case you already say that "`32-bit` isn't supported", but someone might help to fix it anyway

**Comment by xiang90** [comment]
Close in favor of #5028

**Pull request closed without merging**
