### PR TITLE
doc: fix etcd docker startup commands

### PR DESCRIPTION
**Pull request by bart2**
This fixes failure to start etcd node(s) when following https://coreos.com/etcd/docs/latest/docker_guide.html ;The error message is: "docker: Error response from daemon: Container command '-name' not found or does not exist.."

### CODE REVIEW

**Comment by gyuho** [comment]
@bart2 What version of etcd are you running? This won't work

```
sudo docker run --name etcd quay.io/coreos/etcd:v2.3.7 etcd;
Unable to find image 'quay.io/coreos/etcd:v2.3.7' locally
v2.3.7: Pulling from coreos/etcd
baa54a8d5296: Pull complete 
1b7cd7bbed2b: Pull complete 
Digest: sha256:797c185fcf07f1fecf228665ebf8cf7f1b2172853e9dfc02d2d718c582c77493
Status: Downloaded newer image for quay.io/coreos/etcd:v2.3.7
2016-11-28 19:17:06.351508 E | etcdmain: error verifying flags, 'etcd' is not a valid flag. See 'etcd --help'.
```

**Comment by gyuho** [comment]
v3 docker guides can be found at https://github.com/coreos/etcd/blob/master/Documentation/op-guide/container.md.

Have you tried?

**Comment by bart2** [comment]
I'm using latest tag, as the procedure from https://coreos.com/etcd/docs/latest/docker_guide.html does not specify any tag. Right now it is:
```
core1 ~ # docker run quay.io/coreos/etcd:latest etcd --version
etcd Version: 3.0.15
Git SHA: fc00305
Go Version: go1.6.3
Go OS/Arch: linux/amd64
```

If that documentation is version specific, then maybe it should explicitly use specific version number? 

BTW, the link says "docs/**latest**/...", so I would assume that it will work with **latest** version of etcd. Also, this doc is referenced by the Kubernetes on CoreOS guide: https://coreos.com/kubernetes/docs/latest/getting-started.html and it kind of looks bad to have non-working procedure there.

**Comment by gyuho** [comment]
@bart2 Yeah agree.

@xiang90 @robszumski Any thoughts?

https://coreos.com/etcd/docs/latest seems outdated.
Could we redirect Docker guides to our latest container docs?

Thanks!

**Comment by robszumski** [comment]
@joshix  Looks like we can do two things, use the v2 guide for this:

 - Add tag to https://github.com/coreos/etcd/blob/v3.0.13/Documentation/v2/docker_guide.md
 - Update the link on https://coreos.com/kubernetes/docs/latest/getting-started.html to the new location
 - Delete https://coreos.com/etcd/docs/latest/docker_guide.html from the bucket

Or push people towards this new container doc:
 - Remove and redirect https://coreos.com/etcd/docs/latest/docker_guide.html to https://github.com/coreos/etcd/blob/master/Documentation/op-guide/container.md
 - Update the link on https://coreos.com/kubernetes/docs/latest/getting-started.html to the new location
 - Delete https://coreos.com/etcd/docs/latest/docker_guide.html from the bucket

**Comment by heyitsanthony** [comment]
@gyuho is this also fixed by 066f9bf7e38398bb67736edc0be68923af8048de?

**Comment by gyuho** [comment]
Yes. Let's close this. Thanks.

**Pull request closed without merging**
