### PR TITLE
ctlv3: fix migration

### PR DESCRIPTION
**Pull request by xiang90**
/cc @wojtek-t @hongchaodeng 

I tested the example data @wojtek-t provided. It fixed the problem. I do not really have time to test this with more extensive data set now.

Please try with more data set.

WAL + no snap (new k8s cluster); WAL+snap (long running k8s cluster); fresh snap (new cluster data forced by --snapshot-count==1)

Thanks!

### CODE REVIEW

**Comment by xiang90** [comment]
also cc @timothysc

**Comment by hongchaodeng** [comment]
Tested and verified all three cases.

Code also LGTM.

**Comment by wojtek-t** [comment]
OK - I also did some tests and it seems to fix my problems

@xiang90 - however, we need backport to 3.0 branch (fortunately backport seems to be trivial)

**Comment by xiang90** [comment]
@wojtek-t After we merge in this and https://github.com/coreos/etcd/pull/6793, we will do a new release.

**Comment by wojtek-t** [comment]
Cool - that would be great.

**Pull request merged**
