### PR TITLE
Documentation: fix "Missing infra1="

### PR DESCRIPTION
**Pull request by mikael84**
Documentation: fix "Missing infra1="

### CODE REVIEW

**Comment by xiang90** [comment]
Thanks! Can you please update the commit message to: "Documentation: fix ..."

**Comment by yichengq** [comment]
ping @mikael84

**Comment by mikael84** [comment]
I think I did change it, didn't I?

**Comment by yichengq** [comment]
https://github.com/mikael84/etcd/commit/381c03c6ca14a9b1d949b7b2d068a783d8d4cb68
The commit name is still `Update clustering.md`. could you change it to "Documentation: fix ..."?

**Comment by mikael84** [comment]
Oh, I edited the wrong box. Sorry.

**Comment by yichengq** [comment]
@mikael84 and the commit name. you can use `git commit --amend` to edit the title of the commit, and `git push -f` to `patch-1`.

**Pull request closed without merging**
