### PR TITLE
auth: improve 'removeSubsetRangePerms' to O(n)

### PR DESCRIPTION
**Pull request by gyuho**
Clean up TODOs

### CODE REVIEW

**Comment by heyitsanthony** [comment]
lgtm

**Comment by mitake** [comment]
Thanks @gyuho . BTW, I was planning to rework the range permissions with interval tree (http://www.geeksforgeeks.org/interval-tree/), because it enables O(lg n) lookup for intervals. Do you have any comments or suggestions about the idea (e.g. it's overkill, if you do this, separate repository of the implementation, etc).

**Comment by gyuho** [comment]
@mitake We already have interval tree implementation here https://github.com/coreos/etcd/tree/master/pkg/adt.

/cc @heyitsanthony

**Comment by mitake** [comment]
@gyuho sorry for my late reply and thanks for your pointer. I didn't notice the package. I'd like to rework the permission checking mechanism after finishing some ongoing auth tasks.

**Pull request merged**
