### PR TITLE
contrib - V2 Benchmark script

### PR DESCRIPTION
**Pull request by nrshrivatsan**
#Gist

This is a load script for V2 apis.

It performs following operations on keys in parallel

+ POST
+ GET
+ PUT
+ DELETE

#UX Screenshot

ux

### CODE REVIEW

**Comment by gyuho** [comment]
@nrshrivatsan We currently focus on V3 performance, and we already have benchmark tools here https://github.com/coreos/etcd/tree/master/tools/benchmark.

Defer to @xiang90.

**Comment by nrshrivatsan** [comment]
@jonboulle had [stated](https://github.com/coreos/etcd/pull/3932#issuecomment-160794099) that a similar UX and load script would be useful.

Hence the PR.

**Comment by jonboulle** [comment]
I did, but this PR isn't quite at a place yet where it resembles the V3 one.

**Comment by xiang90** [comment]
v2 API development is freeze. Now we focus more on v3. We already have a v3 bench tool at tools/benchmark. Please help to improve that one instead. Thanks for your contribution!

**Pull request closed without merging**
