### PR TITLE
Changed default "endpoint" servers order

### PR DESCRIPTION
**Pull request by kayrus**
And added "DEPRECATED" note to a "peers" option (relates to https://github.com/coreos/etcd/commit/d685135832677a8ebf97ea88fdd7ac7fe7c2aa2f)

@yichengq @yifan-gu

### CODE REVIEW

**Comment by gyuho** [comment]
LGTM. Defer to @xiang90  as well.

Thanks,

**Comment by xiang90** [comment]
@kayrus Lgtm. But please update the commit message to `etcdctl: Changee default "endpoint" servers order`

**Comment by joshix** [comment]
+1. Thank you @kayrus 

(Related to docs-wide https://github.com/coreos/etcd/issues/3480)

**Comment by xiang90** [comment]
@kayrus kindly ping.

**Comment by joshix** [comment]
Closed in favor of #4359 which changes commit message only.

**Pull request closed without merging**
