### PR TITLE
raft: fix typo in test

### PR DESCRIPTION
**Pull request by zhaohaidao**
fix typo in test

### CODE REVIEW

**Comment by gyuho** [comment]
can you change git commit title to `raft: fix typo in test`?

**Comment by zhaohaidao** [comment]
@gyuho could you tell me how to correct commit message properly? It seems that my latest commit still does not match your format. The failed message is as followed
``` 
02e90e0 fix typo in test...
Expected commit title format '<package>{", "<package>}: <description>'
Got: 02e90e0 fix typo in test
```

And my steps is as followed
```
git commit --amend -m "raft: fix typo in test"
git merge origin/master
git push -u origin HEAD:master 
```

**Comment by hexfusion** [comment]
@zhaohaidao you have a bunch of merges in there which are not required and you need to rebase. I would do this.

`git rebase -i HEAD~6`

This will bring up a list of commits appended with `pick` change all of the `picks` to `drop` execpt 
`raft: fix typo in test` if the rebase works as expected then `git push -f` should clear you up.

**Comment by hexfusion** [comment]
@zhaohaidao nice work on the rebase, thanks you!

**Pull request merged**
