### PR TITLE
functional tests for storage package and some related fixes

### PR DESCRIPTION
**Pull request by yichengq**
for #3306

### CODE REVIEW

**Comment by yichengq** [comment]
The commit needs another review:

- 	storage: fix TestKeyIndexCompact

I correct the way to fix it.

- 	storage: keyIndex.get returns err when key is tombstoned

It lets findGeneration return error when rev is at the gap of two generations now.

**Comment by xiang90** [comment]
Test failed. And it looks like a new bug. https://s3.amazonaws.com/archive.travis-ci.org/jobs/76915977/log.txt

**Comment by xiang90** [comment]
LGTM

**Comment by yichengq** [comment]
The bug is the same one as https://github.com/coreos/etcd/issues/3076. It happens at restartMember and hangs forever when being restarted.

**Comment by yichengq** [comment]
It does need to stop printing log in integration test, so we can see the final error.

**Pull request merged**
