### PR TITLE
typo in metrics.go

### PR DESCRIPTION
**Pull request by ashmere**

### CODE REVIEW

**Comment by xiang90** [comment]
@ashmere LGTM. Can you change the commit message to "etcdserver: fix ..." by adding a subsystem prefix? 

Thanks.

**Comment by xiang90** [comment]
@ashmere ping

**Comment by ashmere** [comment]
@xiang90 sorry didn't see this should be done now

**Comment by xiang90** [comment]
@ashmere Thanks! But actually this has been fixed by https://github.com/coreos/etcd/commit/52c2a5731f308ebe6998792a4c7785c8e2f37412. Sorry!

**Pull request closed without merging**
