### PR TITLE
etcdmain: delete member dir falling back to proxy

### PR DESCRIPTION
**Pull request by gyuho**
This fixes https://github.com/coreos/etcd/issues/3827 where member falls to
back to proxy successfully at first, but fails in subsequent tries.
It fails when there are 'member' and 'proxy' directory in the same place,
one of which did not get cleaned up from failure and causes this conflict
error message: 'invalid datadir. Both member and proxy directories exist.'

### CODE REVIEW

**Comment by gyuho** [comment]
Kindly ping @xiang90 @jonboulle 

Please review and let me know if you have any other suggestion to resolve https://github.com/coreos/etcd/issues/3827. Thanks!

**Comment by xiang90** [comment]
@gyuho Can we stop etcd from creating member dir if it does not start as an etcd member?

**Comment by gyuho** [comment]
@xiang90 Ok, I will try that approach! Thanks

**Comment by gyuho** [comment]
@xiang90 I looked at the code again, and I think the issue matter only when a member **falls back to proxy**.

```
Code1. https://github.com/coreos/etcd/blob/master/etcdmain/etcd.go#L198
Code2. https://github.com/coreos/etcd/blob/master/etcdserver/server.go#L184-L205
Code3. https://github.com/coreos/etcd/blob/master/etcdserver/storage.go#L107-L125
```

Code1's `startEtcd` calls Code2's `etcdserver.NewServer`, which then calls `upgradeDataDir` in Code3. But `startEtcd` does not get called if it starts as a proxy (https://github.com/coreos/etcd/blob/master/etcdmain/etcd.go#L113-L137), which means we already do not create member dir if it does not start as an etcd member (it does when it starts as a member but falls back to proxy).

Please let me know if you have any feedback.

**Comment by gyuho** [comment]
I think we either allow member to have both `proxy` and `member` directories for this case, or delete the `member` directory when a member falls back to proxy. BTW, why we do not allow both `proxy` and `member` in the first place?

**Comment by xiang90** [comment]
@gyuho My question is when the will the user have both dir? That should not happen.

**Comment by gyuho** [comment]
@xiang90 Please correct me if I am wrong.

https://github.com/coreos/etcd/blob/c0353697da1216fd0555928efb53f4134a2b5ab4/etcdmain/etcd.go#L124-L136

shows if `startEtcd` returns `discovery` error, it tries to start as a proxy.
I think `startEtcd` could try to create both `member` and `proxy` directory in this case:

1. `startEtcd` succeeds creating its `member` directory`
2. This member crashes and tries to rererun `startEtcd`
3. But this time, `discovery` fails in the function `getPeerURLsMapAndToken` returning `discovery` type error
4. The logic at https://github.com/coreos/etcd/blob/c0353697da1216fd0555928efb53f4134a2b5ab4/etcdmain/etcd.go#L127-L132 detects this and tries to fall back to proxy
5. But before the crash, it was an etcd member with `member` directory, so now `startProxy` fails.

**Comment by xiang90** [comment]
> I think startEtcd could try to create both member and proxy directory in this case:

etcd should probably ONLY create member dir after it finishes bootstrapping, not before.

**Comment by xiang90** [comment]
In the discovery case, etcd should create member dir after it finishes discovery and finds all its peers.

**Comment by gyuho** [comment]
Thanks. I will investigate more.

Sincerely,
Gyu-Ho Lee

**Comment by gyuho** [comment]
Closing this in favor of https://github.com/coreos/etcd/pull/4087.

**Pull request closed without merging**
