### PR TITLE
store: fix modifiedindex in node clone

### PR DESCRIPTION
**Pull request by xiang90**
Only snapshot use the clone function.

### CODE REVIEW

**Comment by yichengq** [comment]
lgtm

**Comment by crawford** [comment]
Why wasn't it fixed [here](https://github.com/coreos/etcd/blob/master/store/node.go#L63) and [here](https://github.com/coreos/etcd/blob/9776e6d082791c380fe6221ec21368ca8bab75a1/store/node.go#L79) instead?

**Comment by xiang90** [comment]
@crawford Why fix there? A newly created kv should have the modified index as same as the created index.

**Comment by crawford** [comment]
OK, I see where you are coming from. I would have called that function "CreateKV" vs. "NewKV". Thanks.

**Pull request merged**
