### PR TITLE
client: fix SRV discovery

### LINKED ISSUE #3620: etcdctl doesn't honor dns discovery flag
I had opened this in #3244 but at that time I was not using the latest code.

[Documentation](https://github.com/coreos/etcd/tree/release-2.2/etcdctl#dns-discovery) says --discovery-srv flag can be used instead of --endpoint but it doesn't seem to work.

$ ./etcdctl --peers="https://node01.etcd.dev.com:2379,https://node02.etcd.dev.com:2379,https://node03.etcd.dev.com:2379" --cert-file=/var/home/rm/node01.etcd.dev.com.cert.pem --key-file=/var/home/rm/node01.etcd.dev.com.pem --ca-file=/var/home/rm/ca.cert.pem cluster-health
member 4c5854cca2fdc9c is healthy: got healthy result from https://node03.etcd.dev.com:2379
member 5f97c3330e24a56d is healthy: got healthy result from https://node02.etcd.dev.com:2379
member f95caeae097ab105 is healthy: got healthy result from https://node01.etcd.dev.com:2379
cluster is healthy

$ ./etcdctl --discovery-srv="etcd.dev.com" --cert-file=/var/home/rm/node01.etcd.dev.com.cert.pem --key-file=/var/home/rm/node01.etcd.dev.com.pem --ca-file=/var/home/rm/ca.cert.pem cluster-health
cluster may be unhealthy: failed to list members
Error:  unexpected status code 404

$ export ETCDCTL_DISCOVERY_SRV=etcd.dev.com
$ echo $ETCDCTL_DISCOVERY_SRV
etcd.dev.com

$ ./etcdctl --cert-file=/var/home/rm/node01.etcd.dev.com.cert.pem --key-file=/var/home/rm/node01.etcd.dev.com.pem --ca-file=/var/home/rm/ca.cert.pem cluster-health        
cluster may be unhealthy: failed to list members
Error:  unexpected status code 404

### PR DESCRIPTION
**Pull request by MSamman**
clean SRV target before constructing discovery endpoints

### CODE REVIEW

**Comment by yichengq** [comment]
Is this the only part that we miss? Would Target have other special format that we may meet?

Reference about our doc on SRV usage: https://github.com/coreos/etcd/blob/master/Documentation/clustering.md#dns-discovery

**Comment by MSamman** [comment]
I don't think so. Looks like target should be the hostname followed by a dot. I see no other examples or notes otherwise in the spec.

https://tools.ietf.org/html/rfc2782

**Comment by yichengq** [comment]
LGTM. It doesn't fix the issue 3620 because etcdctl still cannot work with peer urls, so you need to change the comment.

defer to @xiang90

**Comment by MSamman** [comment]
Updated comment and commit message.

**Comment by MSamman** [comment]
Im gonna close this since removing the dot at the end of the url returned by SRV is not the correct behavior. I'll add the changes I made to the test in the PR I will make to fix #3620.

**Pull request closed without merging**
