### PR TITLE
etcd-tester: return error if first compaction times out

### LINKED ISSUE #5081: functional-tester: different storage hash in case 0
```
2016-04-14 09:30:25.678051 I | etcd-tester: [round#255 case#0] start failure kill all members
2016-04-14 09:30:25.678088 I | etcd-tester: [round#255 case#0] start injecting failure...
2016-04-14 09:30:25.742142 I | etcd-tester: [round#255 case#0] injected failure
2016-04-14 09:30:25.742180 I | etcd-tester: [round#255 case#0] start recovering failure...
2016-04-14 09:30:28.601684 I | etcd-tester: [round#255 case#0] recovered failure
2016-04-14 09:30:28.601721 I | etcd-tester: [round#255 case#0] canceling the stressers...
2016-04-14 09:30:28.604002 I | etcd-tester: [round#255 case#0] canceled stressers
2016-04-14 09:30:28.604020 I | etcd-tester: [round#255 case#0] checking current revisions...
2016-04-14 09:30:29.736208 I | etcd-tester: [round#255 case#0] all members are consistent with current revisions
2016-04-14 09:30:29.736263 I | etcd-tester: [round#255 case#0] checking current storage hashes...
2016-04-14 09:30:29.736294 I | etcd-tester: [round#255 case#0] checking current storage hashes failed (map[10.240.0.2:2379:4050619795 10.240.0.3:2379:2305646342 10.240.0.4:2379:2305646342])
2016-04-14 09:30:29.736317 I | etcd-tester: [round#255 case#0] cleaning up...
2016-04-14 09:30:32.752815 I | etcd-tester: [round#255 case#1] start failure kill majority of the cluster

```

More details coming.

### PR DESCRIPTION
**Pull request by heyitsanthony**
Fixes #5081

### CODE REVIEW

**Comment by heyitsanthony** [comment]
The response for agent-1 comes back in exactly 10 seconds-- it timed out. The other clients fail because they've already seen the compaction and then mask agent-1's error with nil. /cc gyuho

**Comment by gyuho** [comment]
ah, I see. Thanks a lot. LGTM.

**Comment by gyuho** [comment]
@heyitsanthony We can just merge this as long as it compiles. I will redeploy the testing cluster once you merge it. Thanks

**Comment by heyitsanthony** [comment]
ok skipping semaphore

**Pull request merged**
