### PR TITLE
*: fix typos in markdown docs

### PR DESCRIPTION
**Pull request by jeis2497052**
# Contributing guidelines

just some doc updates

Please read our [contribution workflow][contributing] before submitting a pull request.

[contributing]: https://github.com/coreos/etcd/blob/master/CONTRIBUTING.md#contribution-flow

### CODE REVIEW

**Comment by hexfusion** [comment]
@jeis2497052, thanks for working through this! One final note. To keep your fork clean for future use always put your work into a branch. This way when you make PR and it's closed you can simply remove the branch. 

A nice article to review if your interested. https://rhonabwy.com/2016/04/04/how-to-maintain-a-git-remote-fork/

**Comment by jeis2497052** [comment]
@hexfusion thanks for the article.  The last thing I wish to accomplish is add work for others.  I just wish to contribute even if it is only fixing typos.

**Comment by hexfusion** [comment]
@jeis2497052 your efforts are appreciated, and we all are here to help each other learn. Thanks again!

**Comment by gyuho** [comment]
Thanks @hexfusion @jeis2497052 !

**Pull request merged**
