### PR TITLE
auth: make naming consistent

### PR DESCRIPTION
**Pull request by xiang90**
@mitake

### CODE REVIEW

**Comment by mitake** [comment]
@xiang90 thanks for fixing! Your intention of changing looks good to me but I saw some build errors. Could you pick my commit in the branch and squash in your commit? https://github.com/mitake/etcd/tree/xiang-auth

Also for cli, the above commit also has a change for `user grant` -> `user grant-role` and `role grant` -> `role grant-permission`.

**Comment by xiang90** [comment]
@mitake I will fix the build errors tomorrow. Thanks.

**Comment by xiang90** [comment]
@mitake I fixed the build. PTAL.

**Comment by mitake** [comment]
@xiang90 lgtm, thanks!

**Pull request merged**
