### PR TITLE
client/v2: regenerate with latest ugorji/go/codec

### PR DESCRIPTION
**Pull request by andrewmeissner**
Updating the github.com/ugorji/go/codec dependency to the latest and regenerates the keys.[generated].go file with the updated codecgen executable.

### CODE REVIEW

**Comment by gyuho** [comment]
@andrewmeissner Could you format your commit titles to something like

```
glide: update github.com/ugorji/go/codec
client: regenerate
```

And does client build after your patch?

**Comment by andrewmeissner** [comment]
@gyuho I updated the commit messages.  I ran a `go build -o client *.go` inside the client dir and it seemed to build just fine.  If I need to build it another way let me know and I'll do that as well.

**Comment by gyuho** [comment]
@andrewmeissner It doesn't build in our CIs. Did you run `./scripts/updatedep.sh` in your first commit?

**Comment by andrewmeissner** [comment]
@gyuho I was not aware (hahaha).  Just ran it and committed the files it modified.  :)

**Comment by gyuho** [comment]
Thanks! We will merge this when CI passes.

**Comment by gyuho** [comment]
@ugorji We had to manually patch the generated code to pass our linting tests. Please see last two commits if interested. Thanks!

**Comment by ugorji** [comment]
@gyuho thanks much for the heads up. I will look into why the redundant stuff was there, and the yhnn2=0 one also.

**Pull request merged**
