### PR TITLE
functional-tester: add design doc about lease stresser.

### PR DESCRIPTION
**Pull request by fanminshi**
the design document describe what is a lease stresser, why we want it, and how it works.

### CODE REVIEW

**Comment by fanminshi** [comment]
This is a Rough Draft. probably needs format and grammar check.

**Comment by heyitsanthony** [comment]
This has the precision of prose and the tedium of reading code; a lot of this should just be comments. I don't feel like the lease testing code is close to a state where it's ready to be enshrined in documentation.

**Comment by fanminshi** [comment]
@heyitsanthony should I transfer the content from design doc to comments in my code?

**Comment by xiang90** [comment]
@fanminshi We probably should keep high level concepts here. remove all implementation related details.

**Pull request closed without merging**
