### PR TITLE
clientv3: do not retry on mutable operations

### PR DESCRIPTION
**Pull request by xiang90**
/cc @heyitsanthony @yudai 

We should not retry on mutable operations, since it might cause side effect. Retrying on Put might put the same key twice and save to revisions into etcd. Retrying on member add might cause the RPC to return member already exists error if the first request actually goes through.

### CODE REVIEW

**Comment by heyitsanthony** [comment]
lgtm after removing FailFast=false from `Compact`

**Comment by yudai** [comment]
Oops, sorry about that.

Feeling like #6681 could be solved by this PR.

**Comment by yudai** [comment]
```
--- FAIL: TestCtlV3WatchTimeout (30.39s)
	ctl_v3_watch_test.go:75: watchTest #0-0: ctlV3Put error (read /dev/ptmx: input/output error (expected "OK", got ["Error:  rpc error: code = 2 desc = there is no address available\r\n"]))
	ctl_v3_test.go:166: test timed out after 30s
```

Without, `FailFast(false)`, the balancer immediately return this error.

**Comment by xiang90** [comment]
@yudai I will look into it and get it fixed.

**Comment by yudai** [comment]
FYI:

[1] We once added `FastFail(false)` to all gPRC calls:
https://github.com/coreos/etcd/commit/d8f0ef0e800d86e6343b073c406b7fe0e2cb3940

[2] And removed some of them:
https://github.com/coreos/etcd/commit/3eadf964f4c41301f15fe687d43e4f6c2dfeab9f

[3] Then I added it again in the my previous PR with the balancer change:
https://github.com/coreos/etcd/commit/6a33f0ffd56004d5a4490f3a0191146d69a57f73

(I'm wondering if at the point [2], removing `FastFail(false)` actually took effect? As I addressed in #6656, `FastFail(false)` didn't look working.)

**Comment by xiang90** [comment]
@heyitsanthony @yudai OK. I got tests fixed. Previously it failed mainly because:

1. balancer does not return with correct gRPC codes

2. retry wrap does not respect one of the context.Done

3. retry wrap masks errors from context.

**Comment by heyitsanthony** [comment]
lgtm

**Pull request merged**
