### PR TITLE
raft: A removed node can no longer be leader.

### PR DESCRIPTION
**Pull request by bdarnell**
Fixes another panic in MultiNode.Propose.

@xiang90 @yichengq @mrtracy

### CODE REVIEW

**Comment by bdarnell** [comment]
Don't merge this yet; I need to think more about how it interacts with multiraft. The tricky thing is that a leader may step down, but the followers don't yet know about this because the MsgApp that tells them the new commit index was dropped due to a network error. Normally these followers would recover because the leader that stepped down would stop sending heartbeats, but in multiraft our heartbeats are less specific. The node-level heartbeats would say that the node is still up, but the node itself would believe it is no longer a participant in the group.

**Comment by xiang90** [comment]
> The tricky thing is that a leader may step down, but the followers don't yet know about this because the MsgApp that tells them the new commit index was dropped due to a network error. 

Another tricky part is to remove a peer from a two nodes cluster. Currently we rely on this behavior to let the "leader" update the commit index. I have to think about this more carefully too.

**Comment by bdarnell** [comment]
I've made this PR a little more narrow in scope: now we fix the nil pointer panic by dropping proposals if this node is not in `r.prs`, but the node is still the leader so it can perform its other duties including sending `MsgApp` to its peers.

**Comment by xiang90** [comment]
LGTM.

/cc @yichengq

**Comment by yichengq** [comment]
LGTM

**Pull request merged**
