### PR TITLE
build: implemented build shell-script for Windows

### PR DESCRIPTION
**Pull request by SamuelMarks**
Ported your bash [build](https://github.com/offscale/etcd/blob/master/build) to Windows Batch.

### CODE REVIEW

**Comment by yichengq** [comment]
This looks pretty nice! Could you rename the commit title to `build: implemented build shell-script for Windows`
BTW, Have you tested it?

**Comment by SamuelMarks** [comment]
@yichengq Thanks, yeah I've tested it.

A few caveats:
  - Depending on your configuration, `mklink` needs to be run in an elevated way
  - Although I confirmed that `%GIT_SHA%` is being set correctly, the binary it produces still says:

  > Git SHA: Not provided (use ./build instead of go build)

**Comment by yichengq** [comment]
Could you change the commit title too? This helps to make commit history more readable.

> Although I confirmed that %GIT_SHA% is being set correctly, the binary it produces still says:

I don't have windows on my hand. I check the [Go link doc](http://golang.org/cmd/ld/):
```
-X symbol value
	Set the value of a string variable. The symbol name
	should be of the form importpath.name, as displayed
	in the symbol table printed by "go tool nm".
```
Maybe you can try to `go build` and `go tool nm` first and check out what the importpath.name is.

**Comment by yichengq** [comment]
Does GIT_SHA work in current version? If not, could you add a comment TODO in the bash?

**Comment by SamuelMarks** [comment]
Running go1.4.2 windows/amd64. Here's what the `GIT_SHA` line expands to:

```
go build -a -installsuffix cgo -ldflags "-s -X github.com\coreos\etcd\version.GitSHA 33f2e30" -o bin\etcd.exe "github.com\coreos\etcd
```

I'll add a TODO.

**Comment by yichengq** [comment]
lgtm

**Pull request merged**
