### PR TITLE
clientv3: use FromOutgoingContext to bucket watches

### LINKED ISSUE #8338: etcdv3.client.Watch is not thread safe
clientv3.Client.Watch(ctx, ...) is not thread safe when ctx is CancellableContext.
https://github.com/coreos/etcd/blob/master/clientv3/watch.go#L216 can panic on "concurrent map iteration and map write". I think we should take address of that `inctx`.

### PR DESCRIPTION
**Pull request by heyitsanthony**
Watches were bucketed on string(ctx) for historical reasons;
metadata.FromOutgoingContext should be enough to key watches now.

Fixes #8338

### CODE REVIEW

**Comment by stefan-improbable** [comment]
> That data is sent over the wire already; it's grpc metadata. Using the ctx point means there will be a separate grpc stream for each watch, which is inefficient.

My use case is that I have a set of different clients that connect to my server via gRPC and I call watch for each client:

```
func gRPCMethod(ctx *context.Context, ...) (grpcResp, error) {
    c := m.client.Watch(ctx, ...)
    for resp := range c {
      ...
    }
}
```

So should I give to client.Watch context that is unique for the whole server so that it reuses one connection to etcd?

**Comment by heyitsanthony** [comment]
@stefan-improbable not necessarily-- if the watch is not opened with the right context, it will mask away the grpc metadata.

**Comment by stefan-improbable** [comment]
@heyitsanthony 
What is the correct behaviour in my usecase, should I have one grpc Watch connection for all clients or one Watch per client? Or if I call Watch on the same clientv3 multiple times, is there any reason not to reuse the same gRPC connection in all the requests?

**Comment by heyitsanthony** [comment]
@stefan-improbable it only matters if there's grpc metadata in the context. If there's no grpc metadata then one stream can serve everything. Otherwise, there should be a stream per unique set of metadata.

**Pull request merged**
