### PR TITLE
docs:small fix

### PR DESCRIPTION
**Pull request by zhangbaitong**
Signed-off-by: zhangbaitong <zhangbaitong@163.com>

### CODE REVIEW

**Comment by xiang90** [comment]
lgtm. Thanks!

**Comment by yshahin** [comment]
Should this be closed?

**Comment by xiang90** [comment]
@yshahin What do you mean?

**Comment by yshahin** [comment]
@xiang90 It seems that a commit was merged and I'm assuming the problem solved
so I was asking if this issue should be closed?

**Comment by xiang90** [comment]
@yshahin This is a pull request not an issue. and it is merged.

**Comment by yshahin** [comment]
@xiang90  :smile: my bad

**Pull request merged**
