### PR TITLE
travis: Catch compilation errors in CI for arm and ppc64le

### PR DESCRIPTION
**Pull request by luxas**
This way we'll catch compile errors easily.

@glevand @xiang90 @heyitsanthony @gyuho

### CODE REVIEW

**Comment by heyitsanthony** [comment]
It's great to catch compilation errors, but I really don't want to wait 54 minutes for travis to finish.

**Comment by xiang90** [comment]
@luxas Can you search around to see if travis can run these tests in parallel?

**Comment by gyuho** [comment]
@xiang90 Seems it depends on what plan CoreOS has for etcd https://travis-ci.com/plans

**Comment by luxas** [comment]
It might be just me, but aren't they running in parallel right now with this PR?
Seems like the time taken for all tests are 54 minutes, but travis ran them in parallel (@gyuho said 5) so it only took ~20 minutes.
>  Elapsed time 20 min 53 sec
Total time 54 min 39 sec

What do you think? 
I'm going to update this one to only build `arm` and `ppc64le` for `go1.6`, so it'll speed up the build

**Comment by gyuho** [comment]
@luxas It was 3 previously. I just changed it to 5, but this build has been tried with 5.

Defer to @xiang90 and @heyitsanthony for final decision.

Thanks.

**Comment by luxas** [comment]
Updated, now `arm` and `ppc64le` only is tested against `go1.6`, which should make it much faster than the previous run.

You may choose if you want to run `arm64` compilation tests for all go versions, or if it's okay with only `go1.6`

Also, I came across this option: https://docs.travis-ci.com/user/customizing-the-build/#Fast-Finishing, which I think would be a perfect fit for you.

**Comment by luxas** [comment]
>  Elapsed time 10 min 23 sec
Total time 38 min 4 sec

It would be even faster with `fast_finish: true`. 
Now semaphoreci is the bottleneck

**Comment by glevand** [comment]
I think it is OK to just do go1.5 for arm64.  That is the version CoreOS is currently at.

**Comment by luxas** [comment]
Okay, I'll update to build to just build with `go1.5` for `arm64` then, and I'll add the fast_finish: true option

**Comment by gyuho** [comment]
[`fast_finish: true`](https://blog.travis-ci.com/2013-11-27-fast-finishing-builds/) sounds good to me.

**Comment by luxas** [comment]
ping @heyitsanthony @xiang90 
This does now speed up your travis build with about a minute
It would be great to get in

**Comment by glevand** [comment]
@luxas Please add a better commit comment that describes what changed, and why.

**Comment by luxas** [comment]
updated

**Comment by heyitsanthony** [comment]
lgtm /cc @xiang90

**Comment by xiang90** [comment]
lgtm

**Pull request merged**
