### PR TITLE
store: only update CurrentIndex in CompareAndDelete if Remove succeeds

### PR DESCRIPTION
**Pull request by heyitsanthony**
/cc @xiang90

### CODE REVIEW

**Comment by xiang90** [comment]
Is there a reported issue for this?

**Comment by heyitsanthony** [comment]
No, noticed it when looking over the store.go code. Seems broken when compared to `Delete`, though.

**Comment by xiang90** [comment]
@heyitsanthony I am aware of this. The problem is that if we change this then etcd might have inconsistency issue when replaying the log with a new version.

**Comment by heyitsanthony** [comment]
ack. closing

**Pull request closed without merging**
