### PR TITLE
Use ugorji codec for unmarshalling key responses in client

### LINKED ISSUE #3193: use fast unmarshalJson code in etcd/client
from https://github.com/coreos/go-etcd/pull/218

`ugorji codec` is a preferred choice.

It is critical for latency requirement in k8s scenario. We plan to let k8s use etcd/client instead of go-etcd, so this needs to be improved.

/cc @fgrzadkowski @bcwaldon

### PR DESCRIPTION
**Pull request by yichengq**
This change speeds up response unmarshal ~2x:

BEFORE:

```
BenchmarkSmallResponseUnmarshal	  10000	   164524 ns/op
BenchmarkManySmallResponseUnmarshal	    100	 13916636 ns/op
BenchmarkMediumResponseUnmarshal	   1000	  1974295 ns/op
BenchmarkLargeResponseUnmarshal	     20	 80462001 ns/op
```

AFTER:

```
BenchmarkSmallResponseUnmarshal	   20000	     75243 ns/op
BenchmarkManySmallResponseUnmarshal	     200	   6629661 ns/op
BenchmarkMediumResponseUnmarshal	    1000	   1359041 ns/op
BenchmarkLargeResponseUnmarshal	      20	  61600978 ns/op
```

Its performance is nearly the same as the one benchmarked in https://github.com/coreos/go-etcd/pull/218. So two packages perform similarly.

@wojtek-t 
I have attempted to use ffjson, but it doesn't perform as well as codec. Here is its benchmark:
```
BenchmarkSmallResponseUnmarshal	  10000	   117718 ns/op
BenchmarkManySmallResponseUnmarshal	    100	 10459107 ns/op
BenchmarkMediumResponseUnmarshal	   1000	  1659496 ns/op
BenchmarkLargeResponseUnmarshal	     20	 74711133 ns/op
```
So I still use codec in etcd/client pkg.

/cc @fgrzadkowski @wojtek-t @timothysc

fixes #3193 
ref https://github.com/kubernetes/kubernetes/issues/11962

### CODE REVIEW

**Comment by wojtek-t** [comment]
Thanks for comparison of ffjson & ugorij - this is really useful.

@fgrzadkowski - since you added that codec to the previous client, can you please take a look?

**Comment by wojtek-t** [comment]
Since @fgrzadkowski is OOO, I think it doesn't make sence to block on him.

I looked into it and it LGTM.

**Comment by timothysc** [comment]
@yichengq just checking in on the status here...

**Comment by wojtek-t** [comment]
Yes - I think it would be great if you could merge it soon - I will be trying to use new etcd client in kubernetes soon.

**Comment by xiang90** [comment]
LGTM

**Pull request merged**
