### PR TITLE
Documentation/demo: add member, auth example

### PR DESCRIPTION
**Pull request by gyuho**

### CODE REVIEW

**Comment by gyuho** [comment]
/cc @xiang90 @heyitsanthony @mitake  Please review.

By next quarter, I will separate this out to a web page, like http://redis.io/commands.

**Comment by xiang90** [comment]
lgtm

**Comment by gyuho** [comment]
thanks.

**Comment by mitake** [comment]
@gyuho lgtm, thanks. Nice gif animation :)

**Pull request merged**
