### PR TITLE
testutil: fix typo in comment

### PR DESCRIPTION
**Pull request by shawnps**

### CODE REVIEW

**Comment by xiang90** [comment]
LGTM. Can you fix all typos in one commit if possible?

**Comment by shawnps** [comment]
@xiang90 sorry, I was using the links on http://goreportcard.com/report/coreos/etcd and editing the files in GitHub's UI. I'll edit them locally next time and push them all up at once.

**Comment by xiang90** [comment]
@shawnps Ah... We are very interested in goreportcard. We will improve golint soon. : ). Thanks for your awesome product.

**Comment by xiang90** [comment]
@shawnps It would be great if it can bypass generated code like /github.com/coreos/etcd/client/keys.generated.go

**Comment by shawnps** [comment]
@xiang90 it should be able to. Let me take a look.

**Comment by shawnps** [comment]
@xiang90 https://github.com/gojp/goreportcard/commit/aa605c53f7843b9171c8407ae02d4ad2bab5ebb6

`.generated.go` files should no longer be checked

**Pull request merged**
