### PR TITLE
raft: allow built-in snapshot repair to be disabled

### PR DESCRIPTION
**Pull request by jaricftw**
This adds a boolean option `disableSnapshotMsg` in raft to prevent leader from sending snapshot to a slow follower. 

Snapshot repair is a heavy work. Instead of purely relying on the built-in mechanism in etcd-raft, this allows the users to disable it, and flexibly built their own out-of-band repair strategy. 

For example, after detecting the slow follower, an outside observing process could simply ask a new host to pull (instead of push-based) a snapshot of the leader's state machine and install it there, without going through raft at all. Then creates a new raft replica on top of the snapshot and ask it to join the group.

### CODE REVIEW

**Comment by xiang90** [comment]
right now the snapshot mechanism does not need to go through raft at all. etcd uses an out of band approach already. i assume cockroachdb and tikv does so. i am not sure why you think the snapshot has to go through raft, only the metadata needs to go through raft. and no matter what, it has to.

**Comment by jaricftw** [comment]
@xiang90 thanks for the comments. 

But let me clarify a bit.  So there are too parts of the snapshot: snapshot metadata and data. The etcd-raft code currently clearly allows [both](https://github.com/coreos/etcd/blob/master/raft/raftpb/raft.proto#L30) parts to be shipped via raft messages. Having said that, I agree that it's possible the leader just make the data payload empty (a placeholder), and ship the data out of band, but it'll require additional logic to closely work with the metadata that's shipped over raft. 

Based on what I read from cockroachDB a while ago, they had to [intercept](https://forum.cockroachlabs.com/t/how-does-cockroachdb-repair-a-slow-raft-replica/837) the snapshot message and use their own grpc streaming endpoint to repair the slow replica. Not sure how etcd or tidb do it. 

Instead, this `disableSnapshotMsg` is intended to allow disabling both the metadata and data part, so that we don't have to land in the middle. I also don't see why the metadata has to go through raft --- when the leader takes a snapshot locally, these metadata are persisted locally as well, so they can be shipped together to a new remote node, out of band. When both snapshot data and metadata are installed, a new replica can be created from the snapshot appropriately and join the group.

**Comment by xiang90** [comment]
>  I also don't see why the metadata has to go through raft

raft leader needs to track the progress of the follower. The snapshot metadata is for that purpose. The leader has to know somehow what to send and when. Also sending the metadata is not a heavy work. I do not think you really want that least from what you said originally.

**Comment by jaricftw** [comment]
> The leader has to know somehow what to send and when.

Yeah, the leader still knows all that, it's just with `disableSnapshotMsg` set to true, it's a no-op. As a result, leader won't send any additional messages to the follower, and follower just stay as it is. Then like my original description says, we could ask the leader to remove the slow follower, install snapshot out-of-band on a new node and create a new replica there. 

This should not affect the quorum progress, did I miss anything?

> Also sending the metadata is not a heavy work. I do not think you really want that least from what you said originally.

You are right if it's just metadata, my original assumption was that snapshot data will be streamed over raft as well (which is still allowed). But now my real concern is, if we ONLY send the metadata over, the receiving follower will restore its raft log based on the metadata, and its actual snapshot data is empty. I am not sure how to handle that properly afterwards, and ideally we don't wanna tie ourself to this mechanism. So a natural question is ask is, if we can disable sending snapshot data over raft, can we add an option to disable the metadata as well, wdyt?

**Pull request closed without merging**
