### PR TITLE
clientv3: add grpc naming resolver

### PR DESCRIPTION
**Pull request by xiang90**
/cc @iamqizhao

### CODE REVIEW

**Comment by gyuho** [comment]
lgtm. defer to @heyitsanthony

**Comment by heyitsanthony** [comment]
lgtm

**Comment by mwitkow** [comment]
@xiang90 this looks pretty cool. Will this also be used to drive the gRPC proxy clients to appropriate members? :)

**Comment by xiang90** [comment]
@mwitkow Yes. etcd client itself might support discover etcd members using this.

**Pull request merged**
