### PR TITLE
Add lucas to integrations.md

### PR DESCRIPTION
**Pull request by ringtail**
lucas is etcd v3 api browser,You can use lucas to operate kubernetes service discovery conveniently.

### CODE REVIEW

**Comment by gyuho** [comment]
Can you amend your git commit title to `Documentation: ...`?

**Comment by ringtail** [comment]
Add lucas to Document: integrations.md?

**Comment by gyuho** [comment]
`Document: add ...`

**Comment by ringtail** [comment]
Document: add lucas to integrations.md?

**Comment by gyuho** [comment]
@ringtail Yes

**Comment by ringtail** [comment]
@gyuho Thank you!☺

**Pull request closed without merging**
