### PR TITLE
clientv3: return closed channel on Watch() cancel

### LINKED ISSUE #4626: Watch won't close channel if cancel before
The scenario goes as:

- I had `ctx, cancel =context.WithCancel(...)`
- cancel() was called
- Then the `wch = Watch(ctx, key)`
- `resp, ok = <-wch` is blocked. I'm expecting that it should close and returns !ok.

### PR DESCRIPTION
**Pull request by heyitsanthony**
was returning nil; difficult to use correctly

Fixes #4626

### CODE REVIEW

**Comment by xiang90** [comment]
add a test for this?

**Comment by xiang90** [comment]
LGTM. defer to @hongchaodeng

**Comment by hongchaodeng** [comment]
LGTM

**Pull request merged**
