### PR TITLE
benchmark ask for password is not supplied

### PR DESCRIPTION
**Pull request by harryge00**
# Contributing guidelines

Please read our [contribution workflow][contributing] before submitting a pull request.

[contributing]: https://github.com/coreos/etcd/blob/master/CONTRIBUTING.md#contribution-flow

Solves https://github.com/coreos/etcd/issues/8706

### CODE REVIEW

**Comment by xiang90** [comment]
seem fine to me in general. defer to @jpbetz or @gyuho for a final review.

**Comment by jpbetz** [comment]
LGTM

Thanks! I'm not a fan of passwords in args from a security perspective because they can show up in `ps` output of other system users, so providing password as prompted input is a welcome change.

**Comment by xiang90** [comment]
@harryge00 can you rebase your pr against master so tests can pass? thank you.

**Comment by xiang90** [comment]
@harryge00 can you also update the commit to `tools/benchmark: ask for password when it is not supplied`

**Comment by harryge00** [comment]
@xiang90 rebased

**Comment by xiang90** [comment]
lgtm

**Pull request merged**
