### PR TITLE
mvcc: set bolt options to nil for non-linux systems

### PR DESCRIPTION
**Pull request by mischief**

### CODE REVIEW

**Comment by mischief** [comment]
fixes build on OpenBSD.

**Comment by heyitsanthony** [comment]
There should probably be one file like `boltoption_default.go` with a `// +build !linux` that has this instead of all the duplicate files so dragonfly/netbsd/plan9 build too.

**Comment by mischief** [comment]
ok, i've made the default options file and fixed the build tags.

ptal

**Comment by heyitsanthony** [comment]
lgtm

**Comment by heyitsanthony** [comment]
thanks!

**Pull request merged**
