### PR TITLE
wal: PrivateFileMode/DirMode as in pkg/fileutil

### PR DESCRIPTION
**Pull request by gyuho**
To make it consistent with pkg/fileutil

/cc @heyitsanthony

### CODE REVIEW

**Comment by heyitsanthony** [comment]
should this just be exported by fileutil instead of duplicating the constant?

**Comment by gyuho** [comment]
@heyitsanthony Yeah that's better. I will change that. Thanks.

**Comment by xiang90** [comment]
lgtm

**Comment by heyitsanthony** [comment]
lgtm

**Comment by gyuho** [comment]
thanks. merging in greens.

**Pull request merged**
