### PR TITLE
*: update pb generated files

### PR DESCRIPTION
**Pull request by mitake**
It seems that protobuf output style is changed (not essential).

### CODE REVIEW

**Comment by xiang90** [comment]
What is the script you ran to update the proto? Or you updated your protoc?

**Comment by mitake** [comment]
I used `scripts/genproto.sh`, and I thought some of protoc stuff or goimports were updated. But on another environment, the change wasn't generated. I'm checking why this happened, please wait for a while.

**Comment by xiang90** [comment]
@mitake No problem. Thanks.

**Comment by xiang90** [comment]
@mitake Kindly ping on this one.

**Comment by mitake** [comment]
@xiang90 I tested `scripts/genproto.sh` on another machine but I couldn't find the diff. My current machine (that produces the diff) and the machine have protoc stuff of the same version, so currently I don't know what is the source of the diff.

Anyway, it seems that nobody other than me is facing the diff and this PR requires rebasing. So I'm closing it. I'll reopen a new PR when I can find the source.

**Pull request closed without merging**
