### PR TITLE
raft: Remove the applied argument to newRaft and RestartNode.

### PR DESCRIPTION
**Pull request by bdarnell**
I added this but no longer need it; it is never used with any value
but zero.

### CODE REVIEW

**Comment by xiang90** [comment]
@bdarnell If we remove the applied index, the stateful application need to make sure each command is idempotent. 

raft will recover from the latest snapshot and apply to the commit index. The stateful application might have applied some entries between snapshot index and the commit index before restart.

**Comment by bdarnell** [comment]
OK. I thought you were cautious about adding this in the first place, and neither of us has used it yet, so I thought we could get rid of it. But if it's still useful it's fine to keep it around.

**Comment by xiang90** [comment]
@bdarnell I am cautious. As we have added it and raft interface is not fixed. How about keeping it there for a while?

**Comment by bdarnell** [comment]
OK

**Pull request closed without merging**
