### PR TITLE
rafthttp: add unit tests and SendMsgApp benchmark

### PR DESCRIPTION
**Pull request by yichengq**
compared with master branch.
from #2388

### CODE REVIEW

**Comment by kelseyhightower** [comment]
@yichengq This change can use a better commit message. What tests are being added? What benchmarks are being added?

**Comment by xiang90** [comment]
@kelseyhightower this pull request has 6 commits and each has a clear commit message in my opinion.

but it wont hurt to have a better pull request summary on github.

**Comment by kelseyhightower** [comment]
@xiang90 Ah, good point.

**Comment by xiang90** [comment]
@yichengq There are still some issues that I have mentioned in the original pull request remaining unsolved.

**Comment by yichengq** [comment]
> recording the number of byte written is more desirable.

i think the test on number of byte written has been covered by encoder & decoder testings. There is no need to test them here again.

> have we tested the link heartbeat message somewhere?

No. I plan to add link heartbeat message test in follow-ups because it needs some changes on argument list of function.

Are comments all covered now?

**Comment by xiang90** [comment]
> i think the test on number of byte written has been covered by encoder & decoder testings. There is no need to test them here again.

I do not think so. written bool is very wired, since people expect to see the bytes written. i still think we need to follow what makes other people feel familiar rather than if it is necessary.

**Comment by yichengq** [comment]
all comments are addressed.

**Comment by yichengq** [comment]
ready for review

**Comment by xiang90** [comment]
lgtm

**Pull request merged**
