### PR TITLE
clientv3: optimize func NewFromURL

### PR DESCRIPTION
**Pull request by jiaxuanzhou**
# Contributing guidelines

fixes: #9488

### CODE REVIEW

**Comment by gyuho** [comment]
This should be a separate method

```go
func NewFromURLs(urls []string) (*Client, error) {
```
?

**Comment by jiaxuanzhou** [comment]
@gyuho yes， it is separate, I searched the whole project, no where else called the method but in one md:
https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/grpc_naming.md#grpc-naming-and-discovery
if you agree with the change, i will also modify it in `grpc_naming.md`.

**Comment by yudai** [comment]
It's a client library, so users are third party projects. 

You can find some of them by:
https://github.com/search?q=clientv3.NewFromURL&type=Code&utf8=%E2%9C%93

To keep backward compatibility in v3 releases, we cannot change the signatures of existing functions. A new separate function is required not to break code found from the above link.

**Comment by jiaxuanzhou** [comment]
@yudai good suggestion, will change it soon

**Comment by xiang90** [comment]
lgtm

**Pull request merged**
