### PR TITLE
Revert "Treat URLs have same IP address as same"

### LINKED ISSUE #2815: netutil.URLsEqual may return wrong result
I go through the code, and think this is a bug.

In function(https://github.com/coreos/etcd/blob/master/pkg/netutil/netutil.go#L63), it compares the element of two URL slices(we sorted them before passing into function) one by one, but it may resolve TCP address when comparing them.

For example, `http://a.com == http://10.0.0.2` and `http://b.com == http://10.0.0.1`, so I pass in []{`http://a.com`, `http://b.com`} and []{`http://10.0.0.1`, `http://10.0.0.2`}, and they are not equal then.

possible solution is mentioned here: https://github.com/coreos/etcd/pull/2150#issuecomment-71507580
take care of hostname for TLS: https://github.com/coreos/etcd/pull/2150#issuecomment-71525602

@sorah : do i read your code correctly?

### PR DESCRIPTION
**Pull request by yichengq**
This reverts commit f8ce5996b0566619fde8cca431890a49c52cf3d6.

etcd no longer resolves TCP addresses passed in through flags,
so there is no need to compare hostname and IP slices anymore.
(for more details: a3892221eea4804f58ce83934c91964e83f4f30c)

Conflicts:
	etcdserver/cluster.go
	etcdserver/config.go
	pkg/netutil/netutil.go
	pkg/netutil/netutil_test.go

fixes #2815 
@sorah : Could you validate whether etcd still works in your environment after this change?

### CODE REVIEW

**Comment by sorah** [comment]
Seems ok, but I'll check on Monday.

**Comment by xiang90** [comment]
@sorah Have you gave this a try? Thanks!!

**Comment by sorah** [comment]
oh, sorry for late...

I didn't see any problem on this branch!

**Comment by xiang90** [comment]
@sorah Thanks. Merging.

**Pull request merged**
