### PR TITLE
etcdserver: wait for snapshots before closing raft

### LINKED ISSUE #5374: etcdserver: save snapshot error: write [...].wal: bad file descriptor
I changed TestIssue2746 to use only 3 members (instead of 5) and sometimes the test fails in the wal:
```
etcdserver: saved snapshot at index 33
etcdserver: save snapshot error: write /tmp/etcd831755140/member/wal/0000000000000000-0000000000000000.wal: bad file descriptor
```
I thought it may have been due to the atomic wal init patch from last week, but the error shows up in the commit before it as well.

/cc @AkihiroSuda

### PR DESCRIPTION
**Pull request by heyitsanthony**
Fixes #5374

Probably should be backported to 2.3?

### CODE REVIEW

**Comment by gyuho** [comment]
LGTM. Sure, think we should backport this too? /cc @xiang90

**Comment by xiang90** [comment]
lgtm

**Comment by gyuho** [comment]
@heyitsanthony @xiang90 Can't backport this because 2.3 is before we have `sync.WaitGroup` https://github.com/coreos/etcd/blob/release-2.3/etcdserver/server.go#L205

**Comment by heyitsanthony** [comment]
Looks like it depends on 4991cda20297860a58b8fda34062e2d16e767c62 and 08d87934.

**Pull request merged**
