### PR TITLE
*: print 'does not exist' for non-existent key

### PR DESCRIPTION
**Pull request by gyuho**

### CODE REVIEW

**Comment by gyuho** [comment]
@xiang90 @heyitsanthony Currently if key does not exist, the get command does not return anything.

Could you take a look?

Thanks.

**Comment by gyuho** [comment]
And also changed the file name if it's ok.

**Comment by heyitsanthony** [comment]
@gyuho If etcdctl is going to do any special handling for non-existent keys I think it should exit with an error exit code instead of writing an error to stdout

**Comment by gyuho** [comment]
@heyitsanthony Agree. Let me try that approach. Thanks.

**Comment by gyuho** [comment]
@heyitsanthony Just fixed up to exit with exit code. Please note that I used `0 (ExitSuccess)` because the previous code didn't error out either.

PTAL. Thanks.

**Comment by heyitsanthony** [comment]
lgtm
defer to @xiang90 on the etcdctl output

**Comment by xiang90** [comment]
I feel we should just general an empty output instead of returning error.

**Comment by gyuho** [comment]
@xiang90 The reason I think this would be useful is for e2e tests for `lease` API.
I would like to test if the lease feature correctly expires the keys. To test this, I can call
`get` command and check the `does not exist` string with lease expiration.

**Comment by xiang90** [comment]
@gyuho You can expect to read nothing from etcdctl as output for testing.

**Comment by gyuho** [comment]
@xiang90 Current `expect` pkg matches by sub-string https://github.com/coreos/etcd/blob/master/pkg/expect/expect.go#L89-L92.

So we cannot match by empty string, unless we add a method to `expect` package.

I was talking about lease tests like this https://github.com/gyuho/etcd/commit/2eb9aead8b609d2c579c2e1567d86986949dc481.

**Comment by heyitsanthony** [comment]
@gyuho probably better to extend the expect package than to mess with the command outputs

**Comment by gyuho** [comment]
Sure, I will try to add a method to `expect` to check empty output. Thanks all!

**Pull request closed without merging**
