### PR TITLE
etcdctlv3: snapshot restore works with lease key

### PR DESCRIPTION
**Pull request by xiang90**
Fix https://github.com/coreos/etcd/issues/7192

### CODE REVIEW

**Comment by gyuho** [comment]
LGTM /cc @heyitsanthony @fanminshi

**Comment by heyitsanthony** [comment]
lgtm

**Comment by xiang90** [comment]
CI test is irrelevant. see https://github.com/coreos/etcd/issues/7204

**Comment by xiang90** [comment]
@gyuho This needs to back port to both 3.0, 3.1.

**Pull request merged**
