### PR TITLE
pkg/mflag: add modified flag package

### LINKED ISSUE #3141: improve flag validate output
it print the whole usage currently, the exact useful first line is two screen above.
Propose to do it like this
```
$ ./etcd -proxy on -listen-client-urls 127.0.0.1:8080 -initial-cluster "infra0=http://10.66.11.39:2380,infra1=http://10.66.11.70:2380,infra2=http://10.66.102.87:2380"
invalid value "127.0.0.1:8080" for flag -listen-client-urls: URL scheme must be http or https: 127.0.0.1:8080
See 'etcd -h | --help'
```

Original output
```
$ ./etcd -proxy on -listen-client-urls 127.0.0.1:8080 -initial-cluster "infra0=http://10.66.11.39:2380,infra1=http://10.66.11.70:2380,infra2=http://10.66.102.87:2380"
invalid value "127.0.0.1:8080" for flag -listen-client-urls: URL scheme must be http or https: 127.0.0.1:8080
usage: etcd [flags]
       start an etcd server

       etcd --version
       show the version of etcd

       etcd -h | --help
       show the help information about etcd
	

member flags:

	--name 'default'
		human-readable name for this member.
	--data-dir '${name}.etcd'
		path to the data directory.
	--snapshot-count '10000'
		number of committed transactions to trigger a snapshot to disk.
	--heartbeat-interval '100'
		time (in milliseconds) of a heartbeat interval.
	--election-timeout '1000'
		time (in milliseconds) for an election to timeout.
	--listen-peer-urls 'http://localhost:2380,http://localhost:7001'
		list of URLs to listen on for peer traffic.
	--listen-client-urls 'http://localhost:2379,http://localhost:4001'
		list of URLs to listen on for client traffic.
	-cors ''
		comma-separated whitelist of origins for CORS (cross-origin resource sharing).


clustering flags:

	--initial-advertise-peer-urls 'http://localhost:2380,http://localhost:7001'
		list of this member's peer URLs to advertise to the rest of the cluster.
	--initial-cluster 'default=http://localhost:2380,default=http://localhost:7001'
		initial cluster configuration for bootstrapping.
	--initial-cluster-state 'new'
		initial cluster state ('new' or 'existing').
	--initial-cluster-token 'etcd-cluster'
		initial cluster token for the etcd cluster during bootstrap.
	--advertise-client-urls 'http://localhost:2379,http://localhost:4001'
		list of this member's client URLs to advertise to the public.
		The client URLs advertised should be accessible to machines that talk to etcd cluster. etcd client libraries parse these URLs to connect to the cluster.
	--discovery ''
		discovery URL used to bootstrap the cluster.
	--discovery-fallback 'proxy'
		expected behavior ('exit' or 'proxy') when discovery services fails.
	--discovery-proxy ''
		HTTP proxy to use for traffic to discovery service.
	--discovery-srv ''
		dns srv domain used to bootstrap the cluster.


proxy flags:

	--proxy 'off'
		proxy mode setting ('off', 'readonly' or 'on').
	--proxy-failure-wait 5000
		time (in milliseconds) an endpoint will be held in a failed state.
	--proxy-refresh-interval 30000
		time (in milliseconds) of the endpoints refresh interval.
	--proxy-dial-timeout 1000
		time (in milliseconds) for a dial to timeout.
	--proxy-write-timeout 5000
		time (in milliseconds) for a write to timeout.
	--proxy-read-timeout 0
		time (in milliseconds) for a read to timeout.


security flags:

	--ca-file '' [DEPRECATED]
		path to the client server TLS CA file.
	--cert-file ''
		path to the client server TLS cert file.
	--key-file ''
		path to the client server TLS key file.
	--client-cert-auth 'false'
		enable client cert authentication.
	--trusted-ca-file ''
		path to the client server TLS trusted CA key file.
	--peer-ca-file '' [DEPRECATED]
		path to the peer server TLS CA file.
	--peer-cert-file ''
		path to the peer server TLS cert file.
	--peer-key-file ''
		path to the peer server TLS key file.
	--peer-client-cert-auth 'false'
		enable peer client cert authentication.
	--peer-trusted-ca-file ''
		path to the peer server TLS trusted CA file.

logging flags

	--debug 'false'
		enable debug-level logging for etcd.
	--log-package-levels ''
		set individual packages to various log levels (eg: 'etcdmain=CRITICAL,etcdserver=DEBUG')

unsafe flags:

Please be CAUTIOUS when using unsafe flags because it will break the guarantees
given by the consensus protocol.

	--force-new-cluster 'false'
		force to create a new one-member cluster.
```

### PR DESCRIPTION
**Pull request by gouyang**
Currently etcd is using the standard flag package, which cannot
customize it. Add a modifed version to improve the flexibility.

Fixes #3141.

Signed-off-by: Guohua Ouyang <gouyang@redhat.com>

### CODE REVIEW

**Comment by yichengq** [comment]
I don't want to customize the standard library. Does setting flagSet.Usage to nil could make us get rid of the long output? (http://godoc.org/flag#FlagSet)

**Comment by gouyang** [comment]
> I don't want to customize the standard library. Does setting flagSet.Usage to nil could make us get rid of the long output? (http://godoc.org/flag#FlagSet)

I'm not sure how to do this,
```
$ git diff
diff --git a/etcdmain/config.go b/etcdmain/config.go
index aacc450..e960e87 100644
--- a/etcdmain/config.go
+++ b/etcdmain/config.go
@@ -135,10 +135,10 @@ func NewConfig() *config {
 
        cfg.FlagSet = flag.NewFlagSet("etcd", flag.ContinueOnError)
        fs := cfg.FlagSet
-       fs.Usage = func() {
-               fmt.Println(usageline)
-               fmt.Println(flagsline)
-       }
+       //fs.Usage = func() {
+       //      fmt.Println(usageline)
+       //      fmt.Println(flagsline)
+       //}
 
        // member
        fs.Var(cfg.corsInfo, "cors", "Comma-separated white list of origins for CORS (cross-origin resource sharing).")
```
it not work.

**Comment by yichengq** [comment]
Try to set it to empty function instead of nil function.

**Comment by gouyang** [comment]
> Try to set it to empty function instead of nil function.

it does suppress the whole usage, but "etcd -h | --help " not work.

**Comment by yichengq** [comment]
parse may produce ErrHelp, which indicates the help flag is set. we could print out help message there.

**Comment by gouyang** [comment]
By removing the flagsline, it looks much better now.
```
$ ./etcd -name
flag needs an argument: -name
usage: etcd [flags]
       start an etcd server

       etcd --version
       show the version of etcd

       etcd -h | --help
       show the help information about etcd
	
```

**Comment by yichengq** [comment]
Could you clean up this PR? I am fine with this output.

**Comment by xiang90** [comment]
@gouyang

LGTM. Please clean up this pull request (It might be easier to close this one and open up a new one with your 1 line change).

**Comment by gouyang** [comment]
@xiang90 @yichengq 
Sorry, I'm just aware of that `etcd -h` still could not print the flags, so it's not the solution.

To use a customized flag package is seems the better to way to do this, I can see that Docker is using this way as well.

**Comment by yichengq** [comment]
I tried to write it as we discussed:
```
diff --git a/etcdmain/config.go b/etcdmain/config.go
index aacc450..e1cd17f 100644
--- a/etcdmain/config.go
+++ b/etcdmain/config.go
@@ -137,7 +137,6 @@ func NewConfig() *config {
        fs := cfg.FlagSet
        fs.Usage = func() {
                fmt.Println(usageline)
-               fmt.Println(flagsline)
        }

        // member
@@ -225,6 +224,7 @@ func (cfg *config) Parse(arguments []string) error {
        switch perr {
        case nil:
        case flag.ErrHelp:
+               fmt.Println(flagsline)
                os.Exit(0)
        default:
                os.Exit(2)
```
and `etcd -h` does print both usage and flags part. What is your problem?

**Comment by gouyang** [comment]
@yichengq 
your code works perfect, no problem now.

**Comment by yichengq** [comment]
could you update the PR?

**Comment by gouyang** [comment]
@yichengq 
The PR is updated, please review.

**Comment by xiang90** [comment]
Look good to me. Defer to @yichengq

**Comment by yichengq** [comment]
the code lgtm. Could you update the commit title to `etcdmain: don't print flag usage when flag parse error`? This could help commit history more readable.

**Comment by gouyang** [comment]
@yichengq 
Updated again.

**Comment by yichengq** [comment]
lgtm. Thanks for the contribution!

**Pull request merged**
