### PR TITLE
e2e: check etcdctlv3 get output by value

### PR DESCRIPTION
**Pull request by gyuho**
/cc @heyitsanthony @xiang90 

I was trying to avoid using regex but it is a good choice for this case.

Thanks.

### CODE REVIEW

**Comment by heyitsanthony** [comment]
why is regex necessary?

**Comment by gyuho** [comment]
@heyitsanthony When I just grab it by string I get somethings like:

```
["\x00foo\r" "\x00o\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00bar\r"])
```

Or 

```
(read /dev/ptmx: input/output error)  # with multiple ProceLine call
```

Or

```
["foo" "obar"]   # when I try to remove all \x00 and \r 
```

**Comment by heyitsanthony** [comment]
The first one is fixed in gexpect as of last night. Maybe we should update?

**Comment by gyuho** [comment]
@heyitsanthony That's great. Could you update godep? Then I can rework on this whenever the gexpect code is ready. Thanks.

**Comment by heyitsanthony** [comment]
@gyuho ok sure

**Comment by gyuho** [comment]
@heyitsanthony Just rebased. Think this doesn't need to be blocked on gexpect? PTAL. Thanks.

**Comment by heyitsanthony** [comment]
@gyuho gexpect seems really broken both in the coreos fork and mainline; I'm not confident that is the right way to handle it. /cc @xiang90

**Pull request closed without merging**
