### PR TITLE
Does not work in etcd 0.4.6

### PR DESCRIPTION
**Pull request by rhiann0n**
Does not work in etcd 0.4.6

### CODE REVIEW

**Comment by rhiann0n** [comment]
https://github.com/kelseyhightower/confd/issues/195

**Comment by yichengq** [comment]
@rhiann0n This is master branch, and it is etcd 2.0. We release the doc that has the same version with the code.

**Comment by yichengq** [comment]
The member endpoint change is mentioned here: https://github.com/coreos/etcd/blob/master/Documentation/backward_compatibility.md#http-admin-api

**Comment by rhiann0n** [comment]
makes sense, thank you @yichengq !

**Comment by rhiann0n** [comment]
I was referencing etcd version as referenced by:
 curl http://127.0.0.1:<port>/version

curl http://127.0.0.1:<port>/v2/machines seems to work!  Thank you for pointing me to the endpoint change docs. :)

**Comment by yichengq** [comment]
@rhiann0n Good to know that you get it. :) Another way is to use release-0.4 branch for doc browsing. And i strongly recommend to upgrade to etcd 2.0 because it is better.

**Comment by rhiann0n** [comment]
Thank you, kind sir. :)

**Pull request closed without merging**
