### PR TITLE
[BugFix] fix the write to the closed channel

### PR DESCRIPTION
**Pull request by arthurkiller**
fix the write to closed channel
#8171 to see the detail

### CODE REVIEW

**Comment by heyitsanthony** [comment]
@arthurkiller can you try building the benchmark using master? this should already be fixed by #8069

**Comment by arthurkiller** [comment]
I thing you'd better checkout a new branch based on release3.2 as 3.2.1 to fix this bug.

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by arthurkiller** [comment]
Cause bug found on release should be fixed

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by arthurkiller** [comment]
A bug fix patch may be better

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by arthurkiller** [comment]
@heyitsanthony this bug will not be fixed with release 3.2? Perhaps a bug fixing patch could be better

**Comment by heyitsanthony** [comment]
The fix will be backported into 3.2. Closing.

**Pull request closed without merging**
