### PR TITLE
vendor: update 'google/btree'

### PR DESCRIPTION
**Pull request by gyuho**
Backporting some minor improvements in btree iteration + glide updates

/cc @xiang90 @heyitsanthony @fanminshi

### CODE REVIEW

**Comment by gyuho** [comment]
recent glide breaks deps. Will fix.

**Comment by gyuho** [comment]
Now fixed.

**Comment by heyitsanthony** [comment]
lgtm, any perf improvements?

**Comment by gyuho** [comment]
Small performance gain from this PR

Before (current master branch)

```
$ $HOME/go/bin/benchmark --endpoints=${CLIENT_ENDPOINTS} --conns=100 --clients=1000 put --key-size=8 --val-size=8 --key-space-size=2000000 --total=10000
 10000 / 10000 Booooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 100.00%0s

Summary:
  Total:	0.2542 secs.
  Slowest:	0.0981 secs.
  Fastest:	0.0029 secs.
  Average:	0.0225 secs.
  Stddev:	0.0119 secs.
  Requests/sec:	39336.8229

Response time histogram:
  0.003 [1]	|
  0.012 [1338]	|∎∎∎∎∎∎∎∎∎∎
  0.022 [5009]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.031 [1981]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.041 [983]	|∎∎∎∎∎∎∎
  0.051 [261]	|∎∎
  0.060 [207]	|∎
  0.070 [149]	|∎
  0.079 [51]	|
  0.089 [12]	|
  0.098 [8]	|

Latency distribution:
  10% in 0.0117 secs.
  25% in 0.0155 secs.
  50% in 0.0185 secs.
  75% in 0.0271 secs.
  90% in 0.0378 secs.
  95% in 0.0466 secs.
  99% in 0.0649 secs.

$ $HOME/go/bin/benchmark --endpoints=${CLIENT_ENDPOINTS} --conns=100 --clients=1000 range foo --total=100000 --consistency=s
bench with serializable range
 100000 / 100000 Booooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 100.00%0s

Summary:
  Total:	0.8419 secs.
  Slowest:	0.0463 secs.
  Fastest:	0.0003 secs.
  Average:	0.0053 secs.
  Stddev:	0.0042 secs.
  Requests/sec:	118781.0232

Response time histogram:
  0.000 [1]	|
  0.005 [58504]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.009 [26545]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.014 [10822]	|∎∎∎∎∎∎∎
  0.019 [2979]	|∎∎
  0.023 [771]	|
  0.028 [240]	|
  0.033 [87]	|
  0.037 [34]	|
  0.042 [14]	|
  0.046 [3]	|

Latency distribution:
  10% in 0.0013 secs.
  25% in 0.0023 secs.
  50% in 0.0040 secs.
  75% in 0.0075 secs.
  90% in 0.0108 secs.
  95% in 0.0134 secs.
  99% in 0.0195 secs.
```

After patch

```
$ $HOME/go/bin/benchmark --endpoints=${CLIENT_ENDPOINTS} --conns=100 --clients=1000 put --key-size=8 --val-size=8 --key-space-size=2000000 --total=10000
 10000 / 10000 Booooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 100.00%0s

Summary:
  Total:	0.2272 secs.
  Slowest:	0.0793 secs.
  Fastest:	0.0033 secs.
  Average:	0.0209 secs.
  Stddev:	0.0109 secs.
  Requests/sec:	44010.9001

Response time histogram:
  0.003 [1]	|
  0.011 [817]	|∎∎∎∎∎∎∎
  0.019 [4359]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.026 [2726]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.034 [1237]	|∎∎∎∎∎∎∎∎∎∎∎
  0.041 [260]	|∎∎
  0.049 [246]	|∎∎
  0.056 [121]	|∎
  0.064 [142]	|∎
  0.072 [80]	|
  0.079 [11]	|

Latency distribution:
  10% in 0.0116 secs.
  25% in 0.0138 secs.
  50% in 0.0181 secs.
  75% in 0.0246 secs.
  90% in 0.0317 secs.
  95% in 0.0451 secs.
  99% in 0.0637 secs.

$ $HOME/go/bin/benchmark --endpoints=${CLIENT_ENDPOINTS} --conns=100 --clients=1000 range foo --total=100000 --consistency=s
bench with serializable range
 100000 / 100000 Booooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 100.00%0s

Summary:
  Total:	0.7997 secs.
  Slowest:	0.0338 secs.
  Fastest:	0.0002 secs.
  Average:	0.0048 secs.
  Stddev:	0.0034 secs.
  Requests/sec:	125046.7201

Response time histogram:
  0.000 [1]	|
  0.004 [47559]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.007 [26523]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.010 [18719]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.014 [5499]	|∎∎∎∎
  0.017 [1253]	|∎
  0.020 [365]	|
  0.024 [46]	|
  0.027 [26]	|
  0.030 [7]	|
  0.034 [2]	|

Latency distribution:
  10% in 0.0013 secs.
  25% in 0.0022 secs.
  50% in 0.0038 secs.
  75% in 0.0071 secs.
  90% in 0.0096 secs.
  95% in 0.0111 secs.
  99% in 0.0150 secs.
```

Soon, I will do performance analysis more in depth.

At least this doesn't introduce regression :)

Merging.

**Pull request merged**
