### PR TITLE
*: fix shadowed variables

### PR DESCRIPTION
**Pull request by gyuho**
This fixes for shadowed error variables found by go tip go tool vet.
Fixes for https://github.com/coreos/etcd/issues/3954.

### CODE REVIEW

**Comment by gyuho** [comment]
Will separate per package.

**Comment by xiang90** [comment]
@gyuho I gave some comments in commits. 

I feel the error handling a little bit inconsistent. I would suggest that if err is declared perviously, we always do 
``` go
err = A()
if err != nil {
...
}
```  

If the err is not declared previously, we always do
```go
if err := A(); err != nil {
...
}
```

In some concern cases, we do not have to follow this. The main goal is to improve the code consistency and readability.

**Comment by gyuho** [comment]
@xiang90 I understand. Yeah I agree. We should make it consistent
going forward, thanks to the strict `go vet`. And regarding `index` variables,
we still have some `windex`, etc, in `storage` package tests, but they all
pass `go vet shadow` testing.

Just pushed changes based on your comments. PTAL.

**Comment by xiang90** [comment]
> And regarding index variables, we still have some windex.

Can we also change this?

**Comment by gyuho** [comment]
@xiang90 Just changed variable names for `index`. PTAL. Thanks

**Comment by gyuho** [comment]
Just changed variable name as xiang suggested. Will improve test utilities in a separate PR. PTAL.

Thanks,

**Comment by xiang90** [comment]
LGTM

**Comment by gyuho** [comment]
Thanks!

Sincerely,
Gyu-Ho Lee

**Pull request merged**
