### PR TITLE
pkg/transport: don't set certificates on tls config

### LINKED ISSUE #9541: etcd doesn't reload certs from disk when using ip address
When certificates change on disk, etcd should pick up new certificates on the next client/peer request. This does not always happen.

Based on the code here, if we set `Certificates` and `clientHello.ServerName` is empty (which is true when addressed via ip address), it will fall back to the first element of `Certificates` instead of calling `GetCertificate`.
https://github.com/golang/go/blob/master/src/crypto/tls/common.go#L716

According to this comment, the `Certificates` field needs to be set for integration tests to pass. I don't know why, but this is the cause of the issue. We should always be calling `GetCertificates` if certs should always be reloaded, never falling back to the certificate that was loaded at startup.
https://github.com/coreos/etcd/pull/7784#issuecomment-297565717

### PR DESCRIPTION
**Pull request by roboll**
Fixes #9541

### CODE REVIEW

**Comment by roboll** [comment]
Yeah in my tests here it definitely fixes the issue. I haven't looked at the CI failures yet.

**Comment by gyuho** [comment]
Our TLS reload was introduced since 3.2 and the go runtime logic works that way with Go 1.8 as well. So, we will backport this to 3.2 and 3.3.

**Comment by roboll** [comment]
:+1: Let me know what you need from me.

**Comment by roboll** [comment]
hey @gyuho anything I can do to help out here?

**Comment by gyuho** [comment]
@roboll Sorry, I looked into it and found this breaks other TLS reload tests. But, still think this is the right approach. Just want to take some time to understand how Go TLS works with this change, and fix the test failures. I had to work on something else, but I should be able to get back to this by this week and plan is release this patch by next week. I will give you more updates as I investigate further.

**Comment by roboll** [comment]
@gyuho sounds good, ping me if you need a hand otherwise I'll check back in a few days :+1:.

**Comment by gyuho** [comment]
Test failures happen in our `integration` testing, where Go `httptest` defaults to its internal test certs if initial `Certificates` is empty as with this patch. Will see if we can work around it.

**Comment by gyuho** [comment]
@roboll Can you try https://github.com/coreos/etcd/pull/9570? Just cherry-picked your commit with test fixes. Thanks!

**Pull request closed without merging**
