### PR TITLE
etcdmain: explicitly set gomaxprocs and log its value

### PR DESCRIPTION
**Pull request by bprashanth**
Indirectly addresses https://github.com/coreos/etcd/issues/2794.

### CODE REVIEW

**Comment by xiang90** [comment]
@bprashanth 
The approach looks good to me. 
Can you please also change the commit message to `etcdmin:...`. We add package prefix to commit message. Thanks!

**Comment by bprashanth** [comment]
@xiang90 PTAL

**Comment by xiang90** [comment]
LGTM

**Comment by xiang90** [comment]
@bprashanth Thanks!

**Pull request merged**
