### PR TITLE
raft: Rename q() to quorum() which is more readable

### PR DESCRIPTION
**Pull request by ngaut**

### CODE REVIEW

**Comment by xiang90** [comment]
I have no strong opinion on this one. q or quorum just seems to be fine.

@heyitsanthony @gyuho Any opinion?

**Comment by gyuho** [comment]
For me, `quorum` reads better, even though the function is obvious enough to have one letter name.

**Comment by heyitsanthony** [comment]
It doesn't seem as though `q` is conventional notation for quorum, so `quorum` is more descriptive. If this is renamed, the (imo, cryptic) `[q:%d]` info strings should change to `[quorum:%d]` as well to be consistent.

**Comment by xiang90** [comment]
@ngaut OK. Let's change q to quorum and also in the print. Thanks!

**Comment by ngaut** [comment]
Fixed! @xiang90 @heyitsanthony

**Comment by gyuho** [comment]
@ngaut Thanks. Could you squash two commits into one?

**Comment by ngaut** [comment]
Done! Thanks  @gyuho

**Comment by gyuho** [comment]
Thanks!
lgtm. Defer to @xiang90

**Pull request merged**
