### PR TITLE
*: add log rotator for functional-tester

### PR DESCRIPTION
**Pull request by gyuho**
Fix https://github.com/coreos/etcd/issues/5680.

I tested `logrotate` but they keep corrupting the log files. It seems fine when I just cat the log files inside the VMs but when we move those directories or copy to cloud storage, they all seem broken (e.g. Broken files are here https://console.cloud.google.com/storage/browser/etcd-functional-tester/test/?project=etcd-development&authuser=1)

My logrotate config was 

```
/home/gyuho/etcd-log/etcd.log {
	size 500k
	daily
	missingok
	notifempty
	rotate 50000
	copytruncate
}
```

We don't need advanced log rotation. We just need to segment log files, and I think just implementing log rotation is much simpler which requires no operational cost.

/cc @heyitsanthony @xiang90

### CODE REVIEW

**Comment by xiang90** [comment]
Who is the consumer of this pkg? Right now, we just introduce the pkg without any consumer?

**Comment by gyuho** [comment]
Should I move this to etcd-agent? I only need it for etcd-agent. Thanks.

**Comment by xiang90** [comment]
you can move to etcd-agent.

**Comment by gyuho** [comment]
Ok, will move and use the formatter inside etcd-agent. thanks.

**Comment by gyuho** [comment]
@xiang90 @heyitsanthony 

On second thought...

Wrapping log formatter in cmd level doesn't play well. I tried to overwrite `io.Writer` with rotate logger here https://github.com/coreos/etcd/blob/master/tools/functional-tester/etcd-agent/agent.go#L70-L72, but logs were missing not correctly piping to the logger. Not sure why yet...

As an alternative, I propose adding log related flags to etcdmain, as in this PR. 

This branch has been running here http://dash.etcd.io/dashboard/db/functional-tests-1, and seems working well. Example logs are here https://console.cloud.google.com/storage/browser/etcd-functional-tester/test1.

What do you think? Or any better suggestion?

Thanks!

**Comment by xiang90** [comment]
I feel all we need is a simple program that reads from its stdin and writes to segmented log files. It can be done outside etcd or etcd-agent.

**Comment by gyuho** [comment]
@xiang90 Agree... I will give logrotate another try, or write simple CLI outside of etcd.

**Comment by xiang90** [comment]
ok

**Pull request closed without merging**
