### PR TITLE
ctlv3: make flags, commands formats consistent

### PR DESCRIPTION
**Pull request by gyuho**
1. Capitalize first letter
2. Remove period at the end

(followed the pattern in linux coreutil man page)

```diff
diff --git a/a.txt b/a.txt
index 162d3db..8c75d13 100644
--- a/a.txt
+++ b/a.txt
@@ -1,44 +1,43 @@
-COMMANDS:
-	get			Get gets the key or a range of keys.
-	put			Put puts the given key into the store.
-	del			Removes the specified key or range of keys [key, range_end).
-	txn			Txn processes all the requests in one transaction.
-	compaction		Compaction compacts the event history in etcd.
-	alarm disarm		disarm all alarms
-	alarm list		list all alarms
-	defrag			defrag defragments the storage of the etcd members with given endpoints.
-	endpoint health		health checks the healthiness of endpoints specified in `--endpoints` flag
-	endpoint status		status prints out the status of endpoints specified in `--endpoints` flag
-	watch			Watch watches events stream on keys or prefixes.
-	version			Print the version of etcdctl.
-	lease grant		grant is used to create leases.
-	lease revoke		revoke is used to revoke leases.
-	lease keep-alive	keep-alive is used to keep leases alive.
-	member add		add is used to add a member into the cluster
-	member remove		remove is used to remove a member from the cluster
-	member update		update is used to update a member in the cluster
-	member list		list is used to list all members in the cluster
-	snapshot save		save stores an etcd node backend snapshot to a given file.
-	snapshot restore	restore an etcd member snapshot to an etcd directory
-	snapshot status		status gets backend snapshot status of a given file.
-	make-mirror		make-mirror makes a mirror at the destination etcd cluster
-	migrate			migrates keys in a v2 store to a mvcc store
-	lock			lock acquires a named lock
-	elect			elect observes and participates in leader election
-	auth enable		enable authentication
-	auth disable		disable authentication
-	user add		add a new user
-	user delete		delete a user
-	user get		get detailed information of a user
-	user list		list up all users
-	user passwd		change password of user
-	user grant-role		grant a role to a user
-	user revoke-role	revoke a role from a user
-	role add		add a new role
-	role delete		delete a role
-	role get		get detailed information of a role
-	role list		list up all roles
-	role grant-permission	grant a key to a role
-	role revoke-permission	revoke a key from a role
+	get			Gets the key or a range of keys
+	put			Puts the given key into the store
+	del			Removes the specified key or range of keys [key, range_end)
+	txn			Txn processes all the requests in one transaction
+	compaction		Compacts the event history in etcd
+	alarm disarm		Disarms all alarms
+	alarm list		Lists all alarms
+	defrag			Defragments the storage of the etcd members with given endpoints
+	endpoint health		Checks the healthiness of endpoints specified in `--endpoints` flag
+	endpoint status		Prints out the status of endpoints specified in `--endpoints` flag
+	watch			Watches events stream on keys or prefixes
+	version			Prints the version of etcdctl
+	lease grant		Creates leases
+	lease revoke		Revokes leases
+	lease keep-alive	Keeps leases alive (renew)
+	member add		Adds a member into the cluster
+	member remove		Removes a member from the cluster
+	member update		Updates a member in the cluster
+	member list		Lists all members in the cluster
+	snapshot save		Stores an etcd node backend snapshot to a given file
+	snapshot restore	Restores an etcd member snapshot to an etcd directory
+	snapshot status		Gets backend snapshot status of a given file
+	make-mirror		Makes a mirror at the destination etcd cluster
+	migrate			Migrates keys in a v2 store to a mvcc store
+	lock			Acquires a named lock
+	elect			Observes and participates in leader election
+	auth enable		Enables authentication
+	auth disable		Disables authentication
+	user add		Adds a new user
+	user delete		Deletes a user
+	user get		Gets detailed information of a user
+	user list		Lists all users
+	user passwd		Changes password of user
+	user grant-role		Grants a role to a user
+	user revoke-role	Revokes a role from a user
+	role add		Adds a new role
+	role delete		Deletes a role
+	role get		Gets detailed information of a role
+	role list		Lists all roles
+	role grant-permission	Grants a key to a role
+	role revoke-permission	Revokes a key from a role
 	help			Help about any command
 ```

### CODE REVIEW

**Comment by xiang90** [comment]
lgtm

**Comment by gyuho** [comment]
Thanks! Merging in greens.

@xiang90 Should we backport this to release-3.0?

**Comment by xiang90** [comment]
sure. let's backport it.

**Comment by gyuho** [comment]
ok will do after merge.

**Pull request merged**
