### PR TITLE
Docs analytics

### PR DESCRIPTION
**Pull request by ElijahCaine**
refs https://github.com/coreos/docs/pull/913, https://github.com/coreos/rkt/pull/3508

This Pull Request adds the following:

- A Google Analytics beacon pixel to the `.md` documentation (`.md`) files in the etcd repository.
- A script to automate the addition and removal of this pixel.

This pixel gives helps us figure out just who and how many people are reading our docs in GitHub as compared with coreos.com. Essentially revealing which docs developers are reading.

Knowing this information helps us figure out who is reading our docs so we can make sure those stay accurate and up to date.

CC: @joshix @robszumski

### CODE REVIEW

**Comment by heyitsanthony** [comment]
I have to echo the concerns raised in the rkt issue. It will certainly upset etcd users in exchange for only /potentially/ improving documentation (after paying off the initial debt of gunking up the md files).

How will that improvement be measured, so if it turns out to offer no benefit in terms of documentation quality, the tracking can be removed? There are different classes of users accessing different types of documentation, how will they be bucketed? If a page is popular, does that mean it deserves more focus (and what, precisely should that focus be?) or just that it's the first thing people click because it has a good page rank? etc etc

> Knowing this information helps us figure out who is reading our docs so we can make sure those stay accurate and up to date.

I feel that all the docs in the etcd repo should be accurate and up to date, not just what's popular (and it's easy to let even the popular stuff get out of date-- this won't tell you whether it is)

I'm skeptical.

/cc @xiang90

**Comment by xiang90** [comment]
As you already have the doc data on CoreOS.com, can you take about how you utilize that data? Any concrete examples would be helpful. 

Also who will have accessibility to the data?

**Comment by polvi** [comment]
@ElijahCaine I'm supportive of you trying this out. If the data is not useful or actionable (i.e. it is never used for anything) please come back and remove it. If there are user issues with this we will have to revisit our privacy/data policy overall as this would fall within that. 

Thank you for trying to gather data to try to make things better.

**Comment by gyuho** [comment]
@ElijahCaine I are closing this for this now.
Let's revisit in the future.

Thanks!

**Pull request closed without merging**
