### PR TITLE
raft: Fix a nil-pointer panic in MultiNode.Propose.

### PR DESCRIPTION
**Pull request by bdarnell**
@xiang90 @yichengq 

CC @mrtracy

### CODE REVIEW

**Comment by xiang90** [comment]
The fix LGTM. But this change might cause a silent drop of proposal. Not sure you are OK with it. But I do not have a better solution at this moment.

**Comment by mrtracy** [comment]
Agreed that this is probably better than an NPE, but a silent drop also leaves room for further improvement (or at least an investigation of alternatives).

**Comment by bdarnell** [comment]
We already have the possibility of silent drops (see the comment just above the changed lines in multinode.go: the single-node version blocks the channel if it doesn't know the leader; the multi-node version has to read from the channel and drops the message instead). We work around these drops at a higher level (the `pending` list in multiraft).

FYI there's a second related panic that I'm trying to narrow down, so expect another PR soon. I'm not sure which one is the one @mrtracy has run in to.

**Comment by xiang90** [comment]
@bdarnell I am aware of that one too. Just want to give you guys a reminder. Merging...

**Pull request merged**
