### PR TITLE
update commands used in admin_guide.md

### PR DESCRIPTION
**Pull request by yichengq**
docs/admin_guide: update migration example on CoreOS …
It points out that the example workflow is on CoreOS, and updates the
command to match the case.

docs/admin_guide: decouple recovery from CoreOS specific path …
This makes the example commands general, while keeping it easy to
understand.

It is updated based on user feedback. /cc @kayrus

### CODE REVIEW

**Comment by xiang90** [comment]
Why do we need to mention CoreOS? This is not a CoreOS specific thing in my opinion.

**Comment by yichengq** [comment]
The original example is based on CoreOS: it uses systemd, 'core' username, '/var/lib/etcd' as data directory. It could be clear and easy to write commands for the example if it is under certain environment.

I am neutral on this considering this is an example. If you think this is not good, I could change it totally to a general one.

**Comment by yichengq** [comment]
Updated to remove all CoreOS specific things.

**Comment by xiang90** [comment]
LGTM

**Pull request merged**
