### PR TITLE
Reconfiguration for raftexample (#4018)

### PR DESCRIPTION
**Pull request by adamwg**
I'm doing a project using etcd/raft and have been trying to get configuration changes working. Since I was having trouble with it in my own project, I figured I'd try it in raftexample as a simplification (with the added bonus of potentially fulfilling the request in issue #4018), but I'm hitting the same problem. Posting this PR in hopes of getting some guidance on what I'm doing wrong.

With the current code I'm able to start two nodes, make an HTTP request to add a third node, and have the third node join the cluster. However, when the leader tries to catch up the new node's log, the new node continuously rejects the AppendEntries RPC, and they go back and forth forever, so the new node never gets caught up and becomes fully functional.

With debugging on, I see the following on the leader:
```
2016-02-05 13:50:53.331050 I | rafthttp: the connection with 3 became active
raft2016/02/05 13:50:53 DEBUG: 1 received msgApp rejection(lastindex: 3) from 3 for index 4
raft2016/02/05 13:50:53 DEBUG: 1 decreased progress of 3 to [next = 4, match = 0, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
raft2016/02/05 13:50:53 DEBUG: 1 received msgApp rejection(lastindex: 3) from 3 for index 3
raft2016/02/05 13:50:53 DEBUG: 1 decreased progress of 3 to [next = 3, match = 0, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
raft2016/02/05 13:50:53 DEBUG: 1 received msgApp rejection(lastindex: 3) from 3 for index 3
raft2016/02/05 13:50:53 DEBUG: 1 received msgApp rejection(lastindex: 3) from 3 for index 4
raft2016/02/05 13:50:53 DEBUG: 1 decreased progress of 3 to [next = 4, match = 3, state = ProgressStateReplicate, waiting = false, pendingSnapshot = 0]
raft2016/02/05 13:50:53 DEBUG: 1 received msgApp rejection(lastindex: 3) from 3 for index 3
raft2016/02/05 13:50:53 DEBUG: 1 decreased progress of 3 to [next = 3, match = 3, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
raft2016/02/05 13:50:53 DEBUG: 1 received msgApp rejection(lastindex: 3) from 3 for index 3
raft2016/02/05 13:50:53 DEBUG: 1 decreased progress of 3 to [next = 3, match = 3, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
raft2016/02/05 13:50:53 DEBUG: 1 received msgApp rejection(lastindex: 3) from 3 for index 3
raft2016/02/05 13:50:53 DEBUG: 1 decreased progress of 3 to [next = 3, match = 3, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
```

And this on the new node:
```
raft2016/02/05 13:50:53 INFO: 3 became follower at term 0
raft2016/02/05 13:50:53 INFO: newRaft 3 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
raft2016/02/05 13:50:53 INFO: 3 became follower at term 1
2016-02-05 13:50:53.331061 I | rafthttp: the connection with 1 became active
2016-02-05 13:50:53.335394 I | rafthttp: the connection with 2 became active
raft2016/02/05 13:50:53 INFO: 3 [term: 1] received a MsgHeartbeat message with higher term from 1 [term: 4]
raft2016/02/05 13:50:53 INFO: 3 became follower at term 4
raft2016/02/05 13:50:53 INFO: raft.node: 3 elected leader 1 at term 4
raft2016/02/05 13:50:53 DEBUG: 3 [logterm: 0, index: 4] rejected msgApp [logterm: 4, index: 4] from 1
raft2016/02/05 13:50:53 DEBUG: 3 [logterm: 1, index: 3] rejected msgApp [logterm: 4, index: 3] from 1
raft2016/02/05 13:50:53 DEBUG: 3 [logterm: 1, index: 3] rejected msgApp [logterm: 4, index: 3] from 1
raft2016/02/05 13:50:53 DEBUG: 3 [logterm: 0, index: 4] rejected msgApp [logterm: 4, index: 4] from 1
raft2016/02/05 13:50:53 DEBUG: 3 [logterm: 1, index: 3] rejected msgApp [logterm: 4, index: 3] from 1
raft2016/02/05 13:50:53 DEBUG: 3 [logterm: 1, index: 3] rejected msgApp [logterm: 4, index: 3] from 1
raft2016/02/05 13:50:53 DEBUG: 3 [logterm: 1, index: 3] rejected msgApp [logterm: 4, index: 3] from 1
```

Can anyone spot what I'm missing here?

Thanks!

### CODE REVIEW

**Comment by xiang90** [comment]
Awesome! I will give this a look soon.

also cc @heyitsanthony

**Comment by heyitsanthony** [comment]
General comment-- I think this would be cleaner with a separate `ConfC` channel for configuration requests instead of wrapping everything in a `Proposal` type (serveChannels could select on both propc and confc to handle this)

I'll try to debug the problem in a bit.

**Comment by xiang90** [comment]
@adamwg How did you start with the just joined node?

**Comment by heyitsanthony** [comment]
@adamwg 
I believe I've found your problem. The joining node is populating the raft log with ConfChanges that won't match the cluster's log.

I used `goreman start` to start a 3 node cluster.

I added a new member:
```sh
curl 127.0.0.1:12380/4 -XPOST -dhttp://127.0.0.1:42379
```

I implemented a command line option `--join` to the code and started a fourth node:
```sh
 ./raftexample --id 4 --cluster http://127.0.0.1:12379,http://127.0.0.1:22379,http://127.0.0.1:32379,http://127.0.0.1:42379 --port 42380 --join
```

which clears out `rpeers` so the log is initialized with nothing:
```go
        if oldwal {                                                                          
                rc.node = raft.RestartNode(c)
        } else {
                startPeers := rpeers                                                         
                if rc.join {
                        startPeers = nil
                }
                rc.node = raft.StartNode(c, startPeers)                                      
        }
```

Then tested:
```sh
$ curl -L http://127.0.0.1:32380/my-key -XPUT -d foo
$ curl -L http://127.0.0.1:42380/my-key
foo
```

Works great!

**Comment by adamwg** [comment]
@heyitsanthony Thanks for the help! As expected, something small I was missing. I'll fix that issue and get everything cleaned up, then push a new version and remove the WIP tag on this.

Any opinion on the HTTP API? I was thinking of using DELETE to remove nodes from the cluster. I'm tempted to have a separate HTTP server for conf changes, since it's a bit confusing to use POST/DELETE for conf changes on the same endpoint that accepts key/value operations via PUT/GET. But, given that this is just an example application, maybe it's Good Enough™.

**Comment by heyitsanthony** [comment]
@adamwg I think it's fine to keep everything in one HTTP handler; seems simpler. Thanks!

**Comment by adamwg** [comment]
OK, in the latest version of the branch I made the following changes:

* Implemented the --join option as suggested by @heyitsanthony so that conf changes actually work.
* Added handling for ConfChangeRemoveNode and a DELETE handler that proposes such changes.
* Replaced the Proposal wrapper struct with a separate conf change channel, as suggested.

I've tested it by starting two nodes, adding a third, removing node 2, and adding node 4. Everything seems to work.

One ugliness that's still here: there's no way in the existing code to stop the HTTP API server, so I just have raft call `os.Exit(0)` when a node is removed, after shutting down its state machine cleanly. I figured this is probably good enough for the example, but let me know if you have any suggestions.

**Comment by xiang90** [comment]
> One ugliness that's still here: there's no way in the existing code to stop the HTTP API server, so I just have raft call os.Exit(0) when a node is removed, after shutting down its state machine cleanly. I figured this is probably good enough for the example, but let me know if you have any suggestions.

I feel this is good enough for the example code, since we want to show mostly how raft works not the application. Thanks!

**Comment by xiang90** [comment]
defer to @heyitsanthony.

**Comment by heyitsanthony** [comment]
code looks great; please update the README.md too (nuke the TODO, add an example if you want, put fixes #4018 in the commit message) and I think this should be good to go

**Comment by adamwg** [comment]
Done! Thanks so much for your help.

**Pull request merged**
