### PR TITLE
*: fix many typos

### PR DESCRIPTION
**Pull request by heyitsanthony**
wrote a spellchecker

### CODE REVIEW

**Comment by xiang90** [comment]
lgtm

**Comment by gyuho** [comment]
Lgtm.

**Comment by jonboulle** [comment]
@heyitsanthony where's this mythical spell checker of which you speak? can
we use it elsewhere too? :-)

**Comment by heyitsanthony** [comment]
@jonboulle https://github.com/chzchzchz/goword a work in progress

**Pull request merged**
