### PR TITLE
etcdctlv3: get supports lease printing

### PR DESCRIPTION
**Pull request by xiang90**
/cc @heyitsanthony @gyuho

### CODE REVIEW

**Comment by gyuho** [comment]
lgtm. defer to @heyitsanthony

**Comment by heyitsanthony** [comment]
The guy asking for this wanted it in the json. Does anyone actually want this?

**Comment by xiang90** [comment]
> The guy asking for this wanted it in the json. Does anyone actually want this?

Hex in json will not happen.

I think he use json format since there is no way to get the lease in normal get as it is today.

**Comment by heyitsanthony** [comment]
Yes, I know that. But by that reasoning, why not have a `simple-full` printer that dumps everything instead of adding extra specialized flags that only apply to the simple printer?

**Comment by xiang90** [comment]
> dumps everything 

I think the goal of `simple printer` is to ease scripting against the output. So user should explicit tell etcd what to print. Or we have to add tag for each line to make parse easier.

key: XXX
value: XXX
lease: XXX

**Comment by heyitsanthony** [comment]
OK can that be done with another printer, then? These specialized flags that only apply to the simple printer are really goofy and it's not so simple if I have to specify a flag on top of the output format to get the output I want.

**Comment by sinsharat** [comment]
I think we should print lease by default if lease is attached to a key. That way we don't need explicit flag for it and also users will get all the desired information by default. But then this should happen for watch as well i guess?

**Comment by xiang90** [comment]
> I think we should print lease by default 

This breaks the compatibility unfortunately. Also I am not convinced that we should do that by default. I would argue that most keys do not have lease attached.

**Comment by sinsharat** [comment]
My point to that way, by default on getting key we should provide the info associated with it. Since its not associated with majority of keys the it becomes more important to specify it so that users clearly know which keys are lease based by default. As far as backward compatibility is concerned i agree that's an issue. I am not an expert in go but will having an extra new param cause backward compatibility issue, since i think the additional param in json if not parsed should get ignored?

**Comment by xiang90** [comment]
@heyitsanthony recently added a fields printer. So closing this one in favor of that format.

**Pull request closed without merging**
