### PR TITLE
pkg/fileutil: fix linux file locks over NFS

### LINKED ISSUE #4853: etcd data cannot be located on NFS storage.
I want to put etcd data on NFS storage. It fails. The output message is below. 

root@edo7:~/etcd-v2.3.0-linux-amd64# ./etcd  --data-dir '/mnt/etcd.etcd' -advertise-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 -listen-peer-urls http://0.0.0.0:2380
2016-03-24 10:26:32.436906 I | etcdmain: etcd Version: 2.3.0
2016-03-24 10:26:32.436973 I | etcdmain: Git SHA: 5e6eb7e
2016-03-24 10:26:32.436988 I | etcdmain: Go Version: go1.5.3
2016-03-24 10:26:32.437001 I | etcdmain: Go OS/Arch: linux/amd64
2016-03-24 10:26:32.437020 I | etcdmain: setting maximum number of CPUs to 2, total number of available CPUs is 2
2016-03-24 10:26:32.437695 I | etcdmain: listening for peers on http://0.0.0.0:2380
2016-03-24 10:26:32.437757 I | etcdmain: listening for client requests on http://0.0.0.0:2379
2016-03-24 10:26:32.437805 I | etcdmain: listening for client requests on http://0.0.0.0:4001
2016-03-24 10:26:32.444151 I | etcdserver: name = default
2016-03-24 10:26:32.444189 I | etcdserver: data dir = /mnt/etcd.etcd
2016-03-24 10:26:32.444205 I | etcdserver: member dir = /mnt/etcd.etcd/member
2016-03-24 10:26:32.444218 I | etcdserver: heartbeat = 100ms
2016-03-24 10:26:32.444230 I | etcdserver: election = 1000ms
2016-03-24 10:26:32.444242 I | etcdserver: snapshot count = 10000
2016-03-24 10:26:32.444259 I | etcdserver: advertise client URLs = http://0.0.0.0:2379,http://0.0.0.0:4001
2016-03-24 10:26:32.444298 I | etcdserver: initial advertise peer URLs = http://localhost:2380,http://localhost:7001
2016-03-24 10:26:32.444322 I | etcdserver: initial cluster = default=http://localhost:2380,default=http://localhost:7001
2016-03-24 10:26:32.451317 C | etcdserver: create wal error: bad file descriptor

My NFS storage is mounted on /mnt directory. It looks that etcd cannot create and write some data on NFS. I make sure that any user has write permission on /mnt directory. I could create files on /mnt except etcd. If etcd data is located on local disk, such as ext4 or btrfs, etcd is running well. 

Is etcd data able to located on NFS storage? I test etcd-2.3.0 and 2.0.1. It does not work.

### PR DESCRIPTION
**Pull request by heyitsanthony**
Fixes #4853

### CODE REVIEW

**Comment by heyitsanthony** [comment]
Failing CI because of outdated kernels...

**Comment by gyuho** [comment]
Test just passed? How outdated is that kernel? If that's too old, we can ignore right?

**Comment by heyitsanthony** [comment]
@gyuho semaphore is on 3.13.0-12. OFD support is 3.15. Not sure what travis is running. It would probably be good to have the compatibility check / flock fallback for a while (at least for CI).

**Comment by gyuho** [comment]
Current CoreOS distributions are being shipped with kernel 4.x, so this should be ok? @xiang90 ?

**Comment by xiang90** [comment]
@heyitsanthony I think we can merge this now. We have a the backup plan for linux anyway.

**Pull request merged**
