### PR TITLE
docs: add node-etcd-config to libs and tools doc

### PR DESCRIPTION
**Pull request by stongo**

### CODE REVIEW

**Comment by yichengq** [comment]
could you change the commit title to `docs: add node-etcd-config to libs and tools doc`?

**Comment by stongo** [comment]
Changed

**Comment by yichengq** [comment]
lgtm. it will be fantastic if you could rebase it.

**Comment by yichengq** [comment]
merged at https://github.com/coreos/etcd/commit/b3e6ad136a184afbffd1a803f75955d393c53e21.

**Pull request closed without merging**
