### PR TITLE
clientv3: fill in kv ops

### PR DESCRIPTION
**Pull request by xiang90**
/cc @heyitsanthony @mitake

### CODE REVIEW

**Comment by mitake** [comment]
@xiang90 looks good to me. But I could find some `context.TODO()`s. Is there a plan for providing a way of configuring user specified timeout like `client/`?

**Comment by heyitsanthony** [comment]
@xiang90 might as well fill in the rangereq sort options here too

@mitake yes, it will be configurable through clientv3.Config

**Comment by xiang90** [comment]
@heyitsanthony What go/context suggests is to have a fine grained per request. We might need to be able to pass in context for each request instead of one per config.

**Comment by xiang90** [comment]
@heyitsanthony 

> might as well fill in the rangereq sort options here too

Done.

**Pull request merged**
