### PR TITLE
return leaderTransferee at raft status

### PR DESCRIPTION
**Pull request by YuleiXiao**
return leaderTransferee when get raft status

get more detail information about raft status

### CODE REVIEW

**Comment by xiang90** [comment]
Can you explain your use case to justify this additional information?

**Comment by YuleiXiao** [comment]
Node A is leader, B and C is follower.
If B's logs is behind A a lot, transfer leader from A to B need more time when we set election timeout for  long time. When A is transferring, it can not work. So we can know the exact state of node A if we found it not work.

**Comment by xiang90** [comment]
OK. can you also add transferee into the json marshal func?

**Comment by YuleiXiao** [comment]
@xiang90 sure, glad to do it.

**Comment by YuleiXiao** [comment]
@xiang90 I have add transferee into json marshal, PTAL

**Comment by xiang90** [comment]
@YuleiXiao Have you checked the json output is valid? can you give me an example output?

**Comment by YuleiXiao** [comment]
@xiang90 

test code:
```
p := make(map[uint64]Progress)
	p[2] = Progress{
		Match: 3,
		Next:  4,
		State: ProgressStateReplicate,
	}
	s := Status{
		ID: uint64(1),
		HardState: pb.HardState{
			Term:   5,
			Vote:   6,
			Commit: 7,
		},
		SoftState: SoftState{
			Lead:      1,
			RaftState: StateLeader,
		},
		Applied:        100,
		Progress:       p,
		LeadTransferee: 2,
	}

	data, _ := s.MarshalJSON()
```

print date and check result:
```
{
	"id": "1",
	"term": 5,
	"vote": "6",
	"commit": 7,
	"lead": "1",
	"raftState": "StateLeader",
	"applied": 100,
	"progress": {
		"2": {
			"match": 3,
			"next": 4,
			"state": "ProgressStateReplicate"
		}
	},
	"leadtransferee": "2"
}
```

**Comment by xiang90** [comment]
lgtm

**Pull request merged**
