### PR TITLE
Godep: upgrade gexpect

### PR DESCRIPTION
**Pull request by heyitsanthony**
Has ReadLine buffer corruption fixes

### CODE REVIEW

**Comment by gyuho** [comment]
awesome. lgtm.

**Comment by heyitsanthony** [comment]
seeing `read /dev/ptmx: input/output error)` now... will test more

**Comment by heyitsanthony** [comment]
Tried replacing `ExpectRegex` with `Expect` in `newEtcdProcessCluster` as part of this patch... ended up finding more buffer corruption (https://github.com/ThomasRooney/gexpect/pull/20)

**Comment by heyitsanthony** [comment]
and there's a regression https://github.com/ThomasRooney/gexpect/commit/b6b347cdd581face74745523800e4a7484fe2e4b that causes it to leak goroutines

**Comment by gyuho** [comment]
@heyitsanthony Close this?

**Comment by heyitsanthony** [comment]
Closing in favor of #4909

**Pull request closed without merging**
