### PR TITLE
storage: add missing return for unsafeAddWatching

### PR DESCRIPTION
**Pull request by xiang90**
/cc @gyuho @jonboulle @eyakubovich

### CODE REVIEW

**Comment by gyuho** [comment]
Ah I totally missed this part. LGTM. Thanks for fixing.

**Comment by xiang90** [comment]
@gyuho No problem

**Comment by xiang90** [comment]
@gyuho It would be great if you can write a test to cover this case.

**Comment by gyuho** [comment]
@xiang90 Sure, I will write test cases that could have been missed without this fix (in a separate PR).

**Pull request merged**
