### PR TITLE
travis: disable email notifications

### PR DESCRIPTION
**Pull request by heyitsanthony**
Was spamming security@coreos.com

Alternative is to have it spam team-etcd, but that seems kind of noisy.

/cc @crawford @xiang90

### CODE REVIEW

**Comment by gyuho** [comment]
LGTM. Thanks!

**Comment by crawford** [comment]
Can you just reconfigure Travis to send it to a different address? My projects send it to me directly.

**Comment by heyitsanthony** [comment]
@crawford sure, but it's unclear where to point it, if not team-etcd; defer to @xiang90

**Comment by xiang90** [comment]
i do not think we need Travis notification. It does send to my email, but I usually just look the status on pr

**Comment by xiang90** [comment]
Lgtm

**Pull request merged**
