### PR TITLE
clientv3: include a context in Client

### PR DESCRIPTION
**Pull request by heyitsanthony**
Useful for clean up tasks

### CODE REVIEW

**Comment by gyuho** [comment]
Is that only for election and locks?

**Comment by heyitsanthony** [comment]
@gyuho Those are the bits that use it now, yes. They have out-of-band clean up phases that need a context which isn't the request context since the request context may be cancelled. Aside from what's done now (passing in an extra context which is kind of ugly), the alternative is to use `context.TODO()` and rely on `client.Close()` to force the connection to error out, but that seems somewhat tortuous to me.

**Comment by gyuho** [comment]
Ok got it. thanks.

lgtm. defer to @xiang90.

**Comment by xiang90** [comment]
LGTM

**Pull request merged**
