### PR TITLE
clientv3: optionize put and delete

### PR DESCRIPTION
**Pull request by heyitsanthony**

### CODE REVIEW

**Comment by xiang90** [comment]
LGTM. Maybe we can add DeleteOp/PutOp type.

**Comment by heyitsanthony** [comment]
I added a bunch of panics. A separate option type means there have to be two distinct functions for `WithRange` (one for get, one for delete) which seems ugly to me.

**Comment by xiang90** [comment]
LGTM

**Comment by heyitsanthony** [comment]
ok merging on greenlight

**Pull request merged**
