### PR TITLE
etcdserver: fix go vet. Fixes #2859

### LINKED ISSUE #2859: go vet from test fails
gopath/src/github.com/coreos/etcd/etcdserver/cluster_util.go:235: version.Versions composite literal uses unkeyed fields

Revision 0ad6d7e3babb7667b24ca15ef8d54cfc870eff51

### PR DESCRIPTION
**Pull request by barakmich**

### CODE REVIEW

**Comment by xiang90** [comment]
@barakmich We did run `go vet` in the testing script. Do you know why it reports success to us?

**Comment by barakmich** [comment]
No idea. It failed first time for me.

**Comment by xiang90** [comment]
Is it because of different version of `go vet` we are using. Travis is probably using an old version?

**Comment by xiang90** [comment]
This pr looks good to me. But we still need to dig into the go vet (or test script) on travis.

**Comment by xiang90** [comment]
@barakmich We figured out it is the go ver issue on travis. I am going to merge this and fix travis configuration shortly.

**Pull request merged**
