### PR TITLE
clientv3: change Close() to close() for keepAlive and watchGrpcStream

### PR DESCRIPTION
**Pull request by fanminshi**
private structs such as keepAlive and watchGrpcStream shouldn't expose a public Close() method.

### CODE REVIEW

**Comment by xiang90** [comment]
Can you explain why we need this change in the commit message?

**Comment by heyitsanthony** [comment]
this isn't being exported into godocs and there's no way to access this function, is this really fixing anything?

**Comment by fanminshi** [comment]
@xiang90 added commit msg `keepAlive is a private struct that belongs to clientv3 pkg and shouldn't expose a public Close() method.`

**Comment by xiang90** [comment]
> this isn't being exported into godocs and there's no way to access this function, is this really fixing anything?

it is an aesthetics change I believe. but I am ok with it as long as the commit message is clear.

**Comment by fanminshi** [comment]
yeah, it makes code look better. Having a public method on a private struct doesn't seem right to me.

**Comment by heyitsanthony** [comment]
there be some kind of linting to find these if it's important

**Comment by heyitsanthony** [comment]
this patch should also cover watchGrpcStream.Close instead of doing it piecewise

**Comment by fanminshi** [comment]
@heyitsanthony will add watchGrpcStream.Close () to this patch

**Pull request merged**
