### PR TITLE
mvcc: set db size metric on restore

### LINKED ISSUE #8080: ETCD DB size metrics is not correct sometimes
We encountered this issue while the DB size is larger than 5GB when re-adding members back to the cluster.

The follow I have is:
 1. Start one ETCD cluster(3 members)
 2. Bump >5GB to the ETCD cluster
 3. Remove one member from the cluster
 4. Stop all members from the cluster
 5. Restart all members

The DB size reported by ETCD servers is 0.

After taking one snapshot, all the DB size is back to normal.

screen shot 2017-06-12 at 10 32 31 am

Here are the metrics I `curl` from one of the member

 - Before the snapshot

```
# HELP etcd_debugging_mvcc_db_total_size_in_bytes Total size of the underlying database in bytes.
# TYPE etcd_debugging_mvcc_db_total_size_in_bytes gauge
etcd_debugging_mvcc_db_total_size_in_bytes 0
```
[metrics-before-snapshot.txt.zip](https://github.com/coreos/etcd/files/1066994/metrics-before-snapshot.txt.zip)

 - After the snapshot

```
# HELP etcd_debugging_mvcc_db_total_size_in_bytes Total size of the underlying database in bytes.
# TYPE etcd_debugging_mvcc_db_total_size_in_bytes gauge
etcd_debugging_mvcc_db_total_size_in_bytes 7.014617088e+09
```
[metrics-after-snapshot.txt.zip](https://github.com/coreos/etcd/files/1066995/metrics-after-snapshot.txt.zip)

Cluster endpoint status
```
+-------------------------------------------------+------------------+---------+---------+-----------+-----------+------------+
|                    ENDPOINT                     |        ID        | VERSION | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+-------------------------------------------------+------------------+---------+---------+-----------+-----------+------------+
| https://tess-node-p4hnm-1189140.33.tess.io:4001 | 416b952ae811a0d7 | 3.0.15  | 7.0 GB  | false     |       378 |    1670896 |
| https://tess-node-nf3nq-1189139.33.tess.io:4001 | c0fc36cf224bac7c | 3.0.15  | 7.0 GB  | false     |       378 |    1670896 |
| https://tess-node-phkwk-1189138.33.tess.io:4001 | f9d31f1cd85ee669 | 3.0.15  | 7.0 GB  | true      |       378 |    1670897 |
+-------------------------------------------------+------------------+---------+---------+-----------+-----------+------------+
```

### PR DESCRIPTION
**Pull request by heyitsanthony**
Fixes #8080

### CODE REVIEW

**Comment by xiang90** [comment]
lgtm

**Comment by xiang90** [comment]
even if there is nothing changed, we still close/reopen a txn every 100ms, right? i thought the db size should get updated at that time.

**Comment by heyitsanthony** [comment]
@xiang90 it's an mvcc metric so the backend doesn't have any control over it; the mvcc code only sets the metric after processing a write

**Comment by heyitsanthony** [comment]
failing on https://github.com/grpc/grpc-go/issues/1316 and #5847. Jumping the gate and merging since this is low risk.

**Pull request merged**
