### PR TITLE
docs/security: fix peer TLS communication example

### PR DESCRIPTION
**Pull request by yichengq**
I think the command line in the example is wrong.

/cc @kelseyhightower

### CODE REVIEW

**Comment by kelseyhightower** [comment]
lgtm

**Comment by yichengq** [comment]
The example is just to support Transport security & client certificates in peer communications, so I think there is no need to add TLS flags for etcd clients.

**Comment by yichengq** [comment]
ping @kelseyhightower

**Comment by kelseyhightower** [comment]
lgtm

**Pull request merged**
