### PR TITLE
add etcdtop

### PR DESCRIPTION
**Pull request by xiang90**
libpcap tool for analyzing popular commands on a production etcd server.

### CODE REVIEW

**Comment by xiang90** [comment]
@jonboulle @yichengq etcd-top requires libcap-dev to be installed on travis and other CI since introduces cgo. What do you think? Shall we just make it a separate thing or move this into etcd repo?

**Comment by jonboulle** [comment]
It's probably easy enough to get libcap-dev on semaphore and just run the tests there.
Re: your other question - is this a tool that we want to bless/officially maintain?

**Comment by jonboulle** [comment]
For Travis I think we can add an install step to stop it from doing the `go get -t -v ./...`

**Comment by xiang90** [comment]
@jonboulle 
Yea. I know how to solve the issue.

Personally, I think the runtime analysis tool worth official support. But I do not think we have full bandwidth to support it and keep it updated with v3 right now.

**Comment by jonboulle** [comment]
Let's ship it.

**Pull request merged**
