### PR TITLE
etcd-runner: make all flags as global vars

### PR DESCRIPTION
**Pull request by sinsharat**
The flags initially were being created as a global flag with arguments being passed to functions. With more flags being added, it will lead to having too many arguments in the function.  Hence its recommended to use these flags as global variables.

### CODE REVIEW

**Comment by heyitsanthony** [comment]
Put them in a `type Config struct` or something? Globals are a last resort.

**Comment by sinsharat** [comment]
@heyitsanthony Sure will do that. From what i understand is you want me to make a config type struct and initialize it in main method, and pass it as an argument to all callers. right?

**Comment by heyitsanthony** [comment]
not really keen on having a mega config structure either; I'm not convinced the arguments are much of a problem...

**Comment by sinsharat** [comment]
@heyitsanthony Actually passing too many arguments is what i feel is not a good practice. So for me Config creation was fine. These changes make it similar to the way we have it for etcdctl commands. Also @xiang90 wanted me to make them global variables and make them uniform hence i had done the changes. Please refer to the PR #6727 for the same.
Also need to know what exactly you want me to do here, as i am confused now :-(

**Comment by sinsharat** [comment]
@xiang90 @heyitsanthony Please suggest if the current PR is fine or need some modifications to be done to it. 
Thank you!

**Comment by xiang90** [comment]
@heyitsanthony These are flag vars. We already make flag vars global vars in etcdctl. Also I guess this is a go style: see examples in https://golang.org/pkg/flag/ and https://golang.org/src/cmd/vet/main.go.

**Comment by heyitsanthony** [comment]
@xiang90 OK, `vet` has a global for `verbose` and `tags`; I still don't believe making everything global really addresses soaring program complexity (which this PR claims to help) in a satisfactory manner. It's a problem of insufficient program structure.

**Comment by sinsharat** [comment]
@heyitsanthony In the present code can you suggest a better way to handle it. Since with more test cases and flags being added and test cases using many of these flags, passing arguments cannot be an option.
Will be glad if you could provide a better way to improve the code.
Thank you!

**Comment by heyitsanthony** [comment]
@sinsharat, yes, I already suggested adding more structure to the system.

**Comment by sinsharat** [comment]
@heyitsanthony yes i had got that, but the problem is having a struct for each test case will make it messy, as some flags will be used by some will be common for few test cases and another set of flags will be common to some other set of test cases.
Also as you had suggested earlier having a config struct with too many values is also not a good option.
Generally what we used to do is when a variable is used by multiple func performing independent operations is to make it a common variable for all as @xiang90 had suggested.
So would request you to add a bit more clarity to it to make it clear in way how exactly you want it to be done.

**Comment by xiang90** [comment]
@sinsharat OK.

From my understanding, @heyitsanthony thinks the current arg list is actually OK.

> I'm not convinced the arguments are much of a problem...

He does not really like a mega struct

> not really keen on having a mega config structure either;

But he wants more structure, which usually separate the mega config into pieces.

I do not really have a strong opinion on this small issue. I do not think global var for flags are so bad. I want to make sure how we handle flags are consistent please. In this file, we have both global var and local var. And they are chose randomly.

**Comment by heyitsanthony** [comment]
@xiang90 @sinsharat I think the global handling would be at least somewhat manageable if the command line handling is done with cobra so there's some enforcement over which commands use which flags. I'm mostly concerned about removing arguments from functions because it reduces the flexibility to some extent (e.g., calling `someFunction(globalValue)` seems better in my opinion than having `someFunction() { ... globalValue ... }`).

**Comment by sinsharat** [comment]
@heyitsanthony I get your point. May be i would have preferred that if it was a case when we had exactly certain set of flags for a particular func and another set of flags for another func, then it would have been followed exactly the way you suggested or even having struct for each func should not be a problem. But the problem if you see now especially for watcherRunner is that it may have a lot of flags if we make some hardcoded values as flags. In this case it will become a problem passing 6-7 args to a func. Since its also not advisable to pass too many arguments as it eats up the readability and making a copy of variables for so many variables is also not a good idea.
On top of this it makes it more complicated when all flags are not required for different methods and its a random thing which intersect into one another.
For the above reasons we thought of having it as a global variable.
If you could show how we can achieve all of this, without readability will be grateful to you.
Thank you!

**Comment by heyitsanthony** [comment]
@sinsharat tools/benchmark is a good example

**Comment by sinsharat** [comment]
@heyitsanthony sure will check it out and if possible to incorporate it here will definitely do that.
Thank you!

**Comment by sinsharat** [comment]
@heyitsanthony i checked out tools/benchmarks, its exactly same as the etcdctl commands, and the code here has a completely different design. Also if you see all the flasgs under tools/benchmarks are global vars only.

**Comment by xiang90** [comment]
@sinsharat 

Two things:

1. global vars

2. func only uses local vars

Now we have global vars (not that good) and the watcherrunner func in tester code uses global vars directly (not good again).

Benchmark or etcdctl tools have global vars, but the business logic func does not use them directly. it uses passed in args. There is a difference, right?

If the func only use local vars, then it is more portable and maintainable. For example, if we want to move watcher runner into a sub pkg, it will not be able to access global vars anymore, bad.

**Comment by sinsharat** [comment]
@xiang90 Right so do you want something similar to be done for this as well?

**Pull request closed without merging**
