### PR TITLE
etcdmain: only get initial cluster setting if the member is not initi…

### PR DESCRIPTION
**Pull request by xiang90**
fix https://github.com/coreos/etcd/issues/5444

@raoofm can you give this a try?

### CODE REVIEW

**Comment by raoofm** [comment]
@xiang90 lgtm

backporting to v2?

**Comment by xiang90** [comment]
@raoofm Is there a reason that prevents you from upgrading to etcd 3.0? We will probably keep back-porting bug fixes to 2.3 branch until 3.0 is stable. But once we feel 3.0 is stable, we wont back port any.

**Comment by xiang90** [comment]
@heyitsanthony rebased. ptal.

**Comment by heyitsanthony** [comment]
lgtm

**Comment by raoofm** [comment]
>  Is there a reason that prevents you from upgrading to etcd 3.0?

@xiang90 Nope, just waiting for v3 to stabilize as we are running in prod. Need to evaluate and plan the migration which seems a lot as a number of clients (java based) needs to be changed to support v3.

Oh wait, so as I read the v2-migration guide, I think there is no need to migrate the clients unless I want the clients to use v3 features. So even after upgrading, both v2 and v3 should be available and the clients should work as is. Right?

So upgrade of clients (read only) is not directly linked to upgrade of etcd from v2 to v3, and the write ones might need some planning (with/without downtime and migration mode) Right?

**Comment by xiang90** [comment]
> So even after upgrading, both v2 and v3 should be available and the clients should work as is. Right?

Yes

> So upgrade of clients (read only) is not directly linked to upgrade of etcd from v2 to v3, and the write ones might need some planning (with/without downtime and migration mode) Right?

You can still write to v2 after migration.

**Comment by raoofm** [comment]
:clap: great, thanks much @xiang90

**Pull request merged**
