### PR TITLE
etcdctl: restore should create a snapshot

### PR DESCRIPTION
**Pull request by xiang90**
Restore should create a snapshot. So the new db file
can be sent to newly joined member.

/cc @hongchaodeng Can you please give this a try?

### CODE REVIEW

**Comment by hongchaodeng** [comment]
Fixes https://github.com/coreos/etcd/issues/6361

**Comment by xiang90** [comment]
@hongchaodeng I will write a few tests around this today + tomorrow.

**Comment by hongchaodeng** [comment]
Not working..

**Comment by xiang90** [comment]
@hongchaodeng It works for me. At least for the example you provided in that issue. One thing I noticed is that you use etcdctl instead of ./etcdctl in your example. Probably you did not update etcdctl but still used old etcdctl in your GOPATH or BIN PATH?

**Comment by hongchaodeng** [comment]
Correct. Works now.

**Comment by hongchaodeng** [comment]
@xiang90 
I will try to test it on etcd controller tomorrow.
Need to figure out docker image :)

**Comment by xiang90** [comment]
@gyhuo it seems that there is no easy way to test snapshot restore with today's e2e testing infra. Can you find a way to test what #6361 does?

**Comment by gyuho** [comment]
@xiang90 Sure, I will add e2e test to address https://github.com/coreos/etcd/issues/6361

**Comment by xiang90** [comment]
@gyuho It seems to me that we have a bad abstraction in e2e testing around etcd process. etcdProcess should understand all its configuration. However, now we construct all args in the cluster conf. And then we pass the agrs into etcd process. So now it is very hard for us to just start on etcd process instead of creating a cluster. We should make etcd process be able to construct the args.

**Comment by gyuho** [comment]
@xiang90 `args` you mean flags to `etcd` binary, or args + flags to `etcdctl`?

**Comment by xiang90** [comment]
@gyuho

Now we create args here https://github.com/coreos/etcd/blob/master/e2e/etcd_test.go#L243-L304 in etcdProcessClusterConfig.

The created arg is here: https://github.com/coreos/etcd/blob/master/e2e/etcd_test.go#L130 which is totally obscure to etcd process. 

However, etcd process SHOULD understand all flags given to it. It should not be obscure. Or we cannot easily create an etcd process by giving it config. 

What we should do is to make etcd process understands ALL configuration. We should covert these configuration fields into args in etcd process, not etcdClusterConfiguration.

**Comment by xiang90** [comment]
If you try to test #6361, you will probably see the same issue.

**Comment by gyuho** [comment]
Ok, I will see if we can make it more configurable.

**Comment by xiang90** [comment]
I manually tested this in a few cases. Will add test cases to e2e later on, since we need quite a few changes to e2e to make testing easier. I want to unblock @hongchaodeng's work on the controller.

**Pull request merged**
