### PR TITLE
storage: add mock tests for store struct

### LINKED ISSUE #3306: test plan for v3 stroage
v3 storage is a more complicated than v2 one.

We should have a test plan to cover most of the basic functionalities and corner cases.

### PR DESCRIPTION
**Pull request by yichengq**
fixes #3306

### CODE REVIEW

**Comment by xiang90** [comment]
@yichengq I have a few questions for you. The code looks pretty good. Just want to make sure we have the test coverage.

**Comment by yichengq** [comment]
Have passed travis.

storage: coverage: 90.4% of statements
storage/backend: coverage: 85.9% of statements

The most of uncovered part in backend pkg is fatal and panic lines.

**Comment by xiang90** [comment]
LGTM

**Comment by xiang90** [comment]
BTW, I do not trust the line coverage. We need to improve logic coverage instead.

**Comment by yichengq** [comment]
agree. This is also these tests targeting for. will keep improving.

**Pull request merged**
