### PR TITLE
[WIP] *: events slice for watch

### PR DESCRIPTION
**Pull request by gyuho**

### CODE REVIEW

**Comment by gyuho** [comment]
tests hanging... I need to figure out. But approach is correct.

**Comment by gyuho** [comment]
I also got:

```
./scripts/genproto.sh 
~/go/src/github.com/coreos/etcd/gopath/src/github.com/gogo/protobuf ~/go/src/github.com/coreos/etcd
HEAD is now at 932b70a fixed bug where big uint64s wrap to negative numbers when cast to int
go install ./proto
go install ./gogoproto
go install ./jsonpb
go install ./protoc-gen-gogo
go install ./protoc-gen-gofast
go install ./protoc-gen-gogofast
go install ./protoc-gen-gogofaster
go install ./protoc-gen-gogoslick
go install ./fieldpath/fieldpath-gen
go install ./fieldpath
go install ./pbpath
go install ./protoc-gen-gogo/version/protoc-min-version
go install ./protoc-gen-gogo/protoc-gen-combo
~/go/src/github.com/coreos/etcd
~/go/src/github.com/coreos/etcd/wal/walpb ~/go/src/github.com/coreos/etcd
~/go/src/github.com/coreos/etcd
~/go/src/github.com/coreos/etcd/etcdserver/etcdserverpb ~/go/src/github.com/coreos/etcd
rpc.proto:48:19: "LeaseCreateRequest" is not defined.
rpc.proto:48:48: "LeaseCreateResponse" is not defined.
rpc.proto:51:19: "LeaseRevokeRequest" is not defined.
rpc.proto:51:48: "LeaseRevokeResponse" is not defined.
rpc.proto:54:29: "LeaseKeepAliveRequest" is not defined.
rpc.proto:54:68: "LeaseKeepAliveResponse" is not defined.
raft_internal.proto: Import "rpc.proto" was not found or had errors.
raft_internal.proto:18:3: "RangeRequest" is not defined.
raft_internal.proto:19:3: "PutRequest" is not defined.
raft_internal.proto:20:3: "DeleteRangeRequest" is not defined.
raft_internal.proto:21:3: "TxnRequest" is not defined.
raft_internal.proto:22:3: "CompactionRequest" is not defined.
```

**Comment by xiang90** [comment]
@gyuho Sorry. I guess I broke the proto when doing the api clean up... I will fix it soon.

**Comment by gyuho** [comment]
@xiang90 Np. I will be working to fix tests meantime. Thanks,

**Pull request closed without merging**
