### PR TITLE
clientv3: fix txn example code

### PR DESCRIPTION
**Pull request by gyuho**

### CODE REVIEW

**Comment by heyitsanthony** [comment]
@gyuho Would it be OK if this example didn't use number strings for values (e.g., "abc" instead)? I think it would be clearer the comparisons are lexical if there are no numbers.

**Comment by gyuho** [comment]
Agree. Will fix. Thanks!

**Comment by gyuho** [comment]
@heyitsanthony PTAL. Thanks!

**Comment by heyitsanthony** [comment]
lgtm

**Comment by xiang90** [comment]
lgtm

**Comment by gyuho** [comment]
thanks. merging in green lights.

**Pull request merged**
