### PR TITLE
glide: pin transitive dependency "sirupsen/logrus"

### PR DESCRIPTION
**Pull request by gyuho**

### CODE REVIEW

**Comment by xiang90** [comment]
what is the motivation of this one?

**Comment by gyuho** [comment]
@xiang90 When we run `./scripts/updatedep.sh`, it changes the `glide.lock` depending on your `GOPATH`. We have few other transitive deps already in glide.yaml (e.g. `github.com/prometheus/procfs`) to prevent that diff in `glide.lock`.

**Comment by xiang90** [comment]
can we pin to a release version? say https://github.com/sirupsen/logrus/releases/tag/v1.0.3?

**Comment by gyuho** [comment]
@xiang90 PTAL.

**Comment by xiang90** [comment]
lgtm

**Pull request merged**
