### PR TITLE
integration: make clusterMustProgress retry on lost leader

### LINKED ISSUE #5022: test: TestIssue2746
```
=== RUN   TestIssue2746
--- FAIL: TestIssue2746 (1.67s)
	cluster_test.go:360: #1: watch on http://127.0.0.1:20114 error: client: etcd cluster is unavailable or misconfigured
```

### PR DESCRIPTION
**Pull request by heyitsanthony**
Fixes #5022

### CODE REVIEW

**Comment by gyuho** [comment]
lgtm.

**Comment by heyitsanthony** [comment]
I could somewhat reliably reproduce the failure (~10%) by using 11 nodes on a spinning disk and this seems to fix it even with several elections. /cc @AkihiroSuda

**Comment by heyitsanthony** [comment]
Discussed this a bit with @xiang90. It seems semaphore is seeing this problem because it's not setting ETCD_ELECTION_TIMEOUT_TICKS like travis. I tried to repro with the election ticks set to 600 and the test seems to work OK.

**Comment by xiang90** [comment]
So probably just add this env into semaphore as well?

**Comment by heyitsanthony** [comment]
@xiang90 added

**Comment by xiang90** [comment]
@heyitsanthony OK. let's close this one and #5022?

**Pull request closed without merging**
