### PR TITLE
 interacting_v3.md: fix typo

### PR DESCRIPTION
**Pull request by es-chow**

### CODE REVIEW

**Comment by gyuho** [comment]
Can you change the commit title to `interacting_v3.md: fix typo`?

**Comment by gyuho** [comment]
@es-chow I meant your git commit title? You can rebase and git push to your branch with correct commit title. Thanks

**Comment by es-chow** [comment]
sorry, I don't read it correctly. Done now.

**Comment by gyuho** [comment]
LGTM. Thanks!

**Pull request merged**
