### PR TITLE
integration: stop cluster after Campaign exits in TestElectionOnSessionRestart

### LINKED ISSUE #7259: grpcproxy: data race on TestElectionOnSessionRestart
```
TestElectionOnSessionRestart
==================
WARNING: DATA RACE
Read at 0x00c43a4c7f20 by goroutine 85:
  runtime.chansend()
      /usr/lib/go-1.7/src/runtime/chan.go:122 +0x0
  github.com/karlseguin/ccache.(*Cache).Delete()
      /home/jenkins/workspace/etcd-proxy/gopath/src/github.com/karlseguin/ccache/cache.go:103 +0xbb
  github.com/coreos/etcd/proxy/grpcproxy/cache.(*cache).Invalidate()
      /home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/proxy/grpcproxy/cache/store.go:152 +0x350
  github.com/coreos/etcd/proxy/grpcproxy.(*kvProxy).DeleteRange()
      /home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/proxy/grpcproxy/kv.go:80 +0xd7
  github.com/coreos/etcd/proxy/grpcproxy.(*kvs2kvc).DeleteRange()
      /home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/proxy/grpcproxy/kv_client_adapter.go:38 +0x73
  github.com/coreos/etcd/clientv3.(*kv).do()
      /home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/clientv3/kv.go:159 +0x1ab
  github.com/coreos/etcd/clientv3.(*kv).Do()
      /home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/clientv3/kv.go:124 +0x8d
  github.com/coreos/etcd/clientv3.(*kv).Delete()
      /home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/clientv3/kv.go:103 +0xf2
  github.com/coreos/etcd/clientv3/concurrency.(*Election).Resign()
      /home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/clientv3/concurrency/election.go:113 +0x139
  github.com/coreos/etcd/clientv3/concurrency.(*Election).Campaign()
      /home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/clientv3/concurrency/election.go:77 +0xa12

Previous write at 0x00c43a4c7f20 by goroutine 990:
  runtime.closechan()
      /usr/lib/go-1.7/src/runtime/chan.go:303 +0x0
  github.com/karlseguin/ccache.(*Cache).worker()
      /home/jenkins/workspace/etcd-proxy/gopath/src/github.com/karlseguin/ccache/cache.go:169 +0x520

Goroutine 85 (running) created at:
  github.com/coreos/etcd/integration.TestElectionOnSessionRestart()
      /home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/integration/v3_election_test.go:255 +0x47f
  testing.tRunner()
      /usr/lib/go-1.7/src/testing/testing.go:610 +0xc9

Goroutine 990 (finished) created at:
  github.com/karlseguin/ccache.New()
      /home/jenkins/workspace/etcd-proxy/gopath/src/github.com/karlseguin/ccache/cache.go:37 +0x53b
  github.com/coreos/etcd/proxy/grpcproxy/cache.NewCache()
      /home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/proxy/grpcproxy/cache/store.go:57 +0x119
  github.com/coreos/etcd/proxy/grpcproxy.NewKvProxy()
      /home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/proxy/grpcproxy/kv.go:33 +0x4e
  github.com/coreos/etcd/integration.toGRPC()
      /home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/integration/cluster_proxy.go:47 +0x1b1
  github.com/coreos/etcd/integration.newClientV3()
      /home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/integration/cluster_proxy.go:79 +0xdb
  github.com/coreos/etcd/integration.NewClientV3()
      /home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/integration/cluster.go:553 +0x223
  github.com/coreos/etcd/integration.NewClusterV3()
      /home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/integration/cluster.go:843 +0x1b0
  github.com/coreos/etcd/integration.TestElectionOnSessionRestart()
      /home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/integration/v3_election_test.go:233 +0xf0
  testing.tRunner()
      /usr/lib/go-1.7/src/testing/testing.go:610 +0xc9
==================
panic: send on closed channel

goroutine 159695 [running]:
panic(0x10d3780, 0xc4252ad510)
	/usr/lib/go-1.7/src/runtime/panic.go:500 +0x1ae
github.com/karlseguin/ccache.(*Cache).Delete(0xc42c508820, 0xc42125a8a0, 0x24, 0xc42d237408)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/karlseguin/ccache/cache.go:103 +0xbc
github.com/coreos/etcd/proxy/grpcproxy/cache.(*cache).Invalidate(0xc42c7094c0, 0xc4278d8a80, 0x1b, 0x20, 0x0, 0x0, 0x0)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/proxy/grpcproxy/cache/store.go:152 +0x351
github.com/coreos/etcd/proxy/grpcproxy.(*kvProxy).DeleteRange(0xc42ac36640, 0x7fc367de13b8, 0xc42c708f80, 0xc42647ea40, 0xc42d237628, 0x4128d8, 0x40)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/proxy/grpcproxy/kv.go:80 +0xd8
github.com/coreos/etcd/proxy/grpcproxy.(*kvs2kvc).DeleteRange(0xc42692a2d0, 0x7fc367de13b8, 0xc42c708f80, 0xc42647ea40, 0x0, 0x0, 0x0, 0xc42d237718, 0x412248, 0xc420080c00)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/proxy/grpcproxy/kv_client_adapter.go:38 +0x74
github.com/coreos/etcd/clientv3.(*kv).do(0xc42692a300, 0x7fc367de13b8, 0xc42c708f80, 0x3, 0xc4278d8a80, 0x1b, 0x20, 0x0, 0x0, 0x0, ...)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/clientv3/kv.go:159 +0x1ac
github.com/coreos/etcd/clientv3.(*kv).Do(0xc42692a300, 0x7fc367de13b8, 0xc42c708f80, 0x3, 0xc4278d8a80, 0x1b, 0x20, 0x0, 0x0, 0x0, ...)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/clientv3/kv.go:124 +0x8e
github.com/coreos/etcd/clientv3.(*kv).Delete(0xc42692a300, 0x7fc367de13b8, 0xc42c708f80, 0xc42480cca0, 0x1b, 0x0, 0x0, 0x0, 0xc439f6a6c0, 0xc423e52de0, ...)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/clientv3/kv.go:103 +0xf3
github.com/coreos/etcd/clientv3/concurrency.(*Election).Resign(0xc42c59cbc0, 0x7fc367de13b8, 0xc42c708f80, 0xc42693ca01, 0xb)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/clientv3/concurrency/election.go:113 +0x13a
github.com/coreos/etcd/clientv3/concurrency.(*Election).Campaign(0xc42c59cbc0, 0x7fc367de1148, 0xc43a1dd7a0, 0x11f80b5, 0x3, 0xc42973e5c0, 0xc4201b49b8)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/clientv3/concurrency/election.go:77 +0xa13
created by github.com/coreos/etcd/integration.TestElectionOnSessionRestart
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/integration/v3_election_test.go:255 +0x480
exit status 2
```

### PR DESCRIPTION
**Pull request by heyitsanthony**
The delete from the campaign resignation was racing with proxy teardown, causing
a data race on the kv cache.

Fixes #7259

### CODE REVIEW

**Comment by xiang90** [comment]
@heyitsanthony I do not quite understand this fix. It seems to me that no matter what the external system does, the proxy should be unaffected? The proxy should not depend on the external system behaviors to be thread safe.

**Comment by heyitsanthony** [comment]
@xiang90 what's happening is the proxy is stopped on cluster termination via client context cancelation. However, the resignation's delete can still be inflight, so proxy the will try to process the request even after tearing down its cache. The only way I can think of making this totally safe is to wrap every kv rpc with a select/waitgroup/lock pattern like watch creation in the proxy. This seems like a lot of extra overhead just to handle the shutdown path.

**Comment by xiang90** [comment]
ok. lgtm

**Comment by heyitsanthony** [comment]
superseded by ccache removal. Closing

**Pull request closed without merging**
