### PR TITLE
client: keys.go minor typo

### PR DESCRIPTION
**Pull request by gyuho**
@xiang90

### CODE REVIEW

**Comment by xiang90** [comment]
LGTM

**Comment by jonboulle** [comment]
cancelled is fine ;(

**Comment by gyuho** [comment]
@jonboulle Will change. I think my vim spell check is different. Thanks!

**Comment by jonboulle** [comment]
it's not a big deal, just unnecessary americanisation ;-)

**Comment by gyuho** [comment]
Got it :) Thanks! Merging after CI passes.

**Pull request merged**
