### PR TITLE
build: add etcdctlv3 for etcdctlv3 e2e test

### PR DESCRIPTION
**Pull request by gyuho**
/cc @jonboulle @xiang90 @heyitsanthony 

Can we also build `etcdctlv3`? We need it to test v3 features in e2e.

### CODE REVIEW

**Comment by xiang90** [comment]
we should not build etcdctlv3 for now. I am not sure how to make it happen. Ideally we should only build one ctl tool that works with both v2 and v3.

**Comment by gyuho** [comment]
@xiang90 Got it. Maybe when we release v3, we can ship integrated ctl. Thanks

**Comment by xiang90** [comment]
@gyuho If you want to write some tests, probably we should write test for clientv3 first. You can start with integration test under clientv3. Basically setup a real cluster and then use client library to interact with it.

**Comment by gyuho** [comment]
Ok that sounds better. Will take a look. Thanks.

**Comment by jonboulle** [comment]
do we need to start designing a UX for a tool that would talk to both?

**Comment by xiang90** [comment]
@jonboulle I have been discussing this with @gyuho. We plan to come up with something next week or the week after next week. We are busy working on the clientv3 and setup testing environment for v3 cluster this week.

**Comment by jonboulle** [comment]
cool, thanks for the update!

**Pull request closed without merging**
