### PR TITLE
change lessor Mutex to RWMutex

### PR DESCRIPTION
**Pull request by ximenzaoshi**
# Contributing guidelines
When the lease gets huge, etcd costs too much time on lease map ranging, leading to updating requests timeout. Change the Mutex to RWMutex may be helpful.

Please read our [contribution workflow][contributing] before submitting a pull request.

[contributing]: https://github.com/coreos/etcd/blob/master/CONTRIBUTING.md#contribution-flow

### CODE REVIEW

**Comment by xiang90** [comment]
how would change from lock to rlock help the case you described? do you have any benchmark result to show the difference?

**Comment by ximenzaoshi** [comment]
We did not do the detailed benchmark, just did some simple testing. After writing about 5000K lease, the updating operation costs more than 1s with Mutex, the more leases written, the more time updating costs. Changing to RWMutex is much more better.
Anyway, a RWMutex is more reasonable I think. But it only become a big problem when the leases getting huge. @xiang90

**Comment by xiang90** [comment]
> We did not do the detailed benchmark, just did some simple testing. After writing about 5000K lease, the updating operation costs more than 1s with Mutex, the more leases written, the more time updating costs. Changing to RWMutex is much more better.

Do you have a script to test this? How much improvement can you see with RWMutex. I am trying to understand the problem better, and see if there is a better solution.

**Comment by ximenzaoshi** [comment]
```
package main
import (
        "github.com/coreos/etcd/clientv3"
        "time"
        "log"
        "context"
	"sync"
	"flag"
	"strings"
)

var endpoints = flag.String("e", "localhost:2379", "etcd endpoints")
var num4zero = flag.Int("n", 1000, "num of lease to write")
var procs = flag.Int("p", 1000, "num of goroutine to write")
func init() {
    flag.Parse()
}

func create(wg *sync.WaitGroup) {
    defer wg.Done()
    log.Println(*endpoints, *num4zero, *procs)
    es := make([]string, 0)
    for _, e := range strings.Split(*endpoints, ",") {
        es = append(es, e)
    }
    cli, err := clientv3.New(clientv3.Config{
        Endpoints:   es,
        DialTimeout: 5 * time.Second,
    })
    if err != nil {
        log.Println("error to new etcd client", err)
        panic("exit")
    }
    log.Println("success to new client")
    i := 0
    for {
        resp, err := cli.Grant(context.TODO(), 6 * 600)
        if err != nil {
            log.Fatal(err)
        }

        lttl, err := cli.TimeToLive(context.TODO(), resp.ID)
        if err != nil {
            log.Fatal(err)
        }
        log.Println(lttl.ID, lttl.GrantedTTL, lttl.TTL, i)
        i = i + 1
        if i == *num4zero {
            break
        }
    }
    defer cli.Close()
}

func main() {
	var wg sync.WaitGroup
	for i:=0;i<*procs;i++ {
		wg.Add(1)
		go create(&wg)
	}
	wg.Wait()
}
```
We used this program to write huge leases to etcd. The updating time goes up as the written leases goes more. @xiang90

**Pull request closed without merging**
