### PR TITLE
clientv3/integration: test leasing txn invalidates deleted cache

### PR DESCRIPTION
**Pull request by lorneli**
Test cache invalidating in [txnLeasing.commitToCache](https://github.com/coreos/etcd/blob/master/clientv3/leasing/txn.go#L164) function.

### CODE REVIEW

**Comment by xiang90** [comment]
@lorneli 

the test looks good. but can you fix the fmt error reported in the travis CI? thank you.

**Comment by lorneli** [comment]
jenkins-ppc64le failure:
> Build timed out (after 30 minutes). Marking the build as aborted.

many tests in semaphoreci fails for:
>--- FAIL: TestCtlV3SnapshotCorrupt (0.04s)
>	ctl_v3_test.go:137: could not start etcd process cluster (read /dev/ptmx: input/output error)

Seems irrelevant to this patch.

**Comment by xiang90** [comment]
@lorneli can you rebase with master and trigger the test again?

**Comment by xiang90** [comment]
CI failure is irrelevant. merging.

**Pull request merged**
