### PR TITLE
auth: changes of managing roles and users

### PR DESCRIPTION
**Pull request by mitake**
- The 1st commit adds a new flag `--revoke` to `etcdctl role delete`. If the flag is passed, the role will be revoked from all users. The 2nd commit adds an e2e test case for this.
- The 3rd commit forbids deleting the role root and revoking the role from the user root if auth is enabled. The 4th commit adds an e2e test case for this.

### CODE REVIEW

**Comment by heyitsanthony** [comment]
Is there a reason why roles should only be optionally revoked if deleted? `UserGrantRole` will reject non-existent roles, but letting users retain deleted roles defeats that check. Seems inconsistent?

**Comment by mitake** [comment]
@heyitsanthony yes... revoking the deleted roles unconditionally would be reasonable. I couldn't find or recall the discussion behind the current behavior, but it would have some reasons. If there's no motivations of keeping it, I agree with changing the behavior of the revoking. /cc @xiang90

**Comment by mitake** [comment]
@heyitsanthony I changed the default behaviour of the role deletion. Now it revokes the role from all users unconditionally. PTAL.

**Comment by heyitsanthony** [comment]
lgtm. Thanks! Defer to @xiang90 on the new behavior. The old behavior seemed more like a bug than a desirable use case...

**Comment by xiang90** [comment]
lgtm

**Pull request merged**
