### PR TITLE
benchmark: change complete notifier first 

### PR DESCRIPTION
**Pull request by gyuho**
Fix coreos#4708.

### CODE REVIEW

**Comment by gyuho** [comment]
Panics can be reproduced with:

```
./benchmark --endpoints="localhost:2378,localhost:22378,localhost:32378" 
--conns=30 --clients=1500 
watch --watchers=10 --total=1000 
--watched-key-total=1000 
--put-rate=100 --put-total=1000 --key-space-size=100
```

**Comment by heyitsanthony** [comment]
I feel like this is just masking the bug; what happens to the results that are never received?

**Comment by gyuho** [comment]
@heyitsanthony Right. This would miss some results, the one that would have come after closing the channel. I will think more on this. Thanks.

**Comment by gyuho** [comment]
/cc @xiang90 @heyitsanthony PTAL. Just tried the same command without panic.

Thanks.

**Comment by heyitsanthony** [comment]
lgtm

**Comment by gyuho** [comment]
Thanks.

**Pull request merged**
