### PR TITLE
etcdv2: encode Event just once before distribute to watchers

### PR DESCRIPTION
**Pull request by mqliang**
# Contributing guidelines

Please read our [contribution workflow][contributing] before submitting a pull request.

[contributing]: https://github.com/coreos/etcd/blob/master/CONTRIBUTING.md#contribution-flow

… of  encode for each watcher

### CODE REVIEW

**Comment by xiang90** [comment]
Can you keep this change set minimal? This commit changes more than just what described in the commit message.

Also do you have any benchmark numbers to show the improvement?

**Comment by mqliang** [comment]
> Can you keep this change set minimal? This commit changes more than just what described in the commit message.

The reason I move `const StoreKeysPrefix ` and `const StoreKeysPrefix ` form `etcdserver/server.go` to `store/store.go` is that when `watch_hub` encode Event, it need "trimEventPrefix", I move the two const ro `store/store.go` to aviod cycle import. So, it a part of this commit.

**Comment by xiang90** [comment]
Can you get some benchmark number?

To be honest, we are not super interested in optimizing etcd2. Do you mind sharing your goal here?

**Comment by xiang90** [comment]
@mqliang Similar issue exists for etcd3 though. We would like someone to investigate into that. https://github.com/coreos/etcd/issues/4627.

1. measure overhead
2. try to fix it if the overhead is significant.

**Comment by mqliang** [comment]
> Can you get some benchmark number?

I benchmarked 100, 1000, 10000, 100000, 1000000 watchers, result is as follows:

```
100
BenchmarkEventMarsh-4                  	2000000000	         0.00 ns/op	       0 B/op	       0 allocs/op
BenchmarkEventMarsh-4                  	2000000000	         0.00 ns/op	       0 B/op	       0 allocs/op


1000
before:
BenchmarkEventMarsh-4                  	2000000000	         0.01 ns/op	       0 B/op	       0 allocs/op
after:
BenchmarkEventMarsh-4                  	2000000000	         0.01 ns/op	       0 B/op	       0 allocs/op

10000
before:
BenchmarkEventMarsh-4                  	1000000000	         0.11 ns/op	       0 B/op	       0 allocs/op
after:
BenchmarkEventMarsh-4                  	2000000000	         0.08 ns/op	       0 B/op	       0 allocs/op

100000
before:
BenchmarkEventMarsh-4                  	1	         		1791906046 ns/op	217701472 B/op	 1097620 allocs/op
after
BenchmarkEventMarsh-4                  	1	         		1860174846 ns/op	384462144 B/op	 1099354 allocs/op


1000000
before
BenchmarkEventMarsh-4                  	1	         		20795525659 ns/op	2177594664 B/op	10995767 allocs/op
after
BenchmarkEventMarsh-4                  	1	         		50022956594 ns/op	3842379144 B/op	11000028 allocs/op

```

Seems only make sense if we have a huge number of watcher(>1 millions)

**Comment by mqliang** [comment]
Post my benchmark code for reference:

``` golang
package store

import (
	"sync"
	"testing"
	"encoding/json"
)

func BenchmarkEventMarsh(b *testing.B) {
	hub := newWatchHub(1000)

	e := &Event{
		Action: Create,
		Node: &NodeExtern{
			Key:           "foo",
			ModifiedIndex: 1,
			CreatedIndex:  1,
		},
		EtcdIndex: 1,
		Refresh: false,
	}

	b.StopTimer()
	b.StartTimer()

	hub.notify(e)

	const num = 1000000

	wg := sync.WaitGroup{}
	wg.Add(num)
	for i := 0; i < num; i++ {
		go func() {
			defer wg.Done()
			w, err := hub.watch("foo", false, false, 1, 1)
			if err != nil {

				b.Fatal(err)
			}

			select {
			case e := <- w.EventChan():
				//before
				data, _ := json.Marshal(e)
				var _ = data
				//after
				// var _ = e

			}
		}()
	}
	wg.Wait()
}

```

**Comment by mqliang** [comment]
@xiang90 feel free to close this if my benchmark code is right.

**Comment by xiang90** [comment]
ok. closing.

**Pull request closed without merging**
