### PR TITLE
wal: simplify boolean return

### PR DESCRIPTION
**Pull request by gyuho**
Some minor clean up, simplification

### CODE REVIEW

**Comment by xiang90** [comment]
lgtm. defer to @heyitsanthony

**Comment by heyitsanthony** [comment]
@gyuho This style is intentional since the locks slice is being updated-- using `w.tail()` makes it clear ensures there's always a reference to the file in the wal structure.

**Comment by gyuho** [comment]
Ok will revert. Thanks!

Sincerely,
Gyu-Ho Lee

**Comment by gyuho** [comment]
@heyitsanthony Just simplified boolean part. PTAL. Thanks.

**Comment by heyitsanthony** [comment]
lgtm

**Pull request merged**
