### PR TITLE
clientv3: lease initial api

### PR DESCRIPTION
**Pull request by xiang90**
/cc @heyitsanthony @gyuho @mitake @barakmich

### CODE REVIEW

**Comment by barakmich** [comment]
LGTM on the lease side, though it might be nice to  see attaching the lease to Ops; I imagine it something like grpc's new Dial, eg
 
`OpPut(foo, bar, WithLease(id))`

**Comment by xiang90** [comment]
@barakmich 

> though it might be nice to see attaching the lease to Ops

https://github.com/coreos/etcd/pull/4316/files#diff-454274f2bd57b4aba9d48436b9a833a1R80

So you want both OpPut(foo, bar) and OpPut(foo, bar, WithLease(id)) to work? Now you need to do OpPut(foo, bar, NoLease).

**Comment by barakmich** [comment]
Not necessarily. The signature is `OpPut([]byte,[]byte, ...OpOption)`

http://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis

**Comment by xiang90** [comment]
@barakmich I know how to achieve it. Just trying to understand why do you want it or why do we want to support it. For extensibility reasons, we might want to do it probably.

**Comment by barakmich** [comment]
If I can't attach a lease to a key, what good is having a lease?

 If there's a field in the proto I can't access through the client API, that field and its functionality are completely useless to me, and I have to write my own client wrapper API around the proto.

This goes for OpRange(key, WithLimit(50), AtRevision(2)) as well. 

Doesn't have to be this PR. But the client won't be useful until this sort of thing exists.

**Comment by xiang90** [comment]
> So you want both OpPut(foo, bar) and OpPut(foo, bar, WithLease(id)) to work? Now you need to do OpPut(foo, bar, NoLease).

OK. So basically you want `OpPut(foo, bar) and OpPut(foo, bar, WithLease(id)) to work` to work. And you do not want to fill in some additional fields that you do not need like OpPut(foo, bar, NoLease).

**Comment by barakmich** [comment]
Exactly.

**Comment by xiang90** [comment]
@barakmich Yea. Thanks. I think we probably should make it happen.

**Comment by gyuho** [comment]
LGTM. Thanks!

**Pull request merged**
