### PR TITLE
contrib/recipes/key.go : fixed comment in method newSequentialKV

### PR DESCRIPTION
**Pull request by vimalk78**
fixed comment in method newSequentialKV

### CODE REVIEW

**Comment by vimalk78** [comment]
also, i was wondering how to fix the following TODO, is this still applicable? the `Get` will result in either 1 `mvccpb.KeyValue` or none, since the `WithFirstKey()` will limit the result to 1. 
also, is checking `resp.More` needed ?

or, have i misunderstood something.

if some change is needed, i will modify and update this PR.

```
contrib/recipes/priority_queue.go
 46 func (q *PriorityQueue) Dequeue() (string, error) {
 47     // TODO: fewer round trips by fetching more than one key
 48     resp, err := q.client.Get(q.ctx, q.key, v3.WithFirstKey()...)
 49     if err != nil {
 50         return "", err
 51     }
 52 
 53     kv, err := claimFirstKey(q.client, resp.Kvs)
 54     if err != nil {
 55         return "", err
 56     } else if kv != nil {
 57         return string(kv.Value), nil
 58     } else if resp.More {
 59         // missed some items, retry to read in more
 60         return q.Dequeue()
 61     }

```

**Comment by heyitsanthony** [comment]
lgtm

It's not clear if the best thing for performance is to fetch multiple keys, that's why it's a TODO...

**Comment by xiang90** [comment]
lgtm

**Comment by vimalk78** [comment]
@heyitsanthony ok, more round trips would be needed if some other concurrent `Dequeue()` already removed the `FirstKey` and there are more keys in the range, i.e. `resp.More` is true. so need to repeat the same process again.

thats where fetching a bunch of keys will help.

so, add an option like `WithFirstNKeys(10)` ?

**Comment by heyitsanthony** [comment]
@vimalk78 I'd rather not add more helper functions to the client if it's not necessary (it can already be implemented as a composite of With* functions). The performance benefits aren't even clear at this point.

**Comment by vimalk78** [comment]
ok

**Pull request merged**
