### PR TITLE
raft: resume paused followers on receipt of MsgHeartbeatResp

### LINKED ISSUE #7037: raft: resume a paused follower after receiving a heartbeat
Currently, `bcastHeartbeatWithCtx` resumes any paused follower:

```
func (r *raft) bcastHeartbeatWithCtx(ctx []byte) {
	for id := range r.prs {
		if id == r.id {
			continue
		}
		r.sendHeartbeat(id, ctx)
		r.prs[id].resume()
	}
}
```

The upshot of doing this is that any subsequent activity on the Raft group which results in a call to `raft.sendAppend` (such as a proposal) will generate a `MsgApp` for the follower even though the Raft group hasn't received a heartbeat response yet. In CockroachDB we've noticed that an active Raft group with one follower on a temporarily down node will generate a significant amount of `MsgApp` traffic that we can be reasonably sure will be dropped at the RPC layer.

Is there a reason for resuming the follower when sending the heartbeat? It seems more natural to resume the follower when `MsgHeartbeatResp` is received and doing so would prevent the above unnecessary activity.

Cc @spencerkimball, @bdarnell

### PR DESCRIPTION
**Pull request by petermattis**
Previously, paused followers were resumed upon sending a MsgHearbeat.

Fixes #7037

### CODE REVIEW

**Comment by petermattis** [comment]
I'm not sure what the travis failure is about. I can't reproduce that locally, but running `./test` has other problems for `gosimple` and `unused` when I'm running on my Mac laptop.

**Comment by gyuho** [comment]
@petermattis @xiang90 The travis failure is not related to this change. Seems like one of our external testing tool made some breaking changes. Will file an issue there. Thanks!

**Comment by siddontang** [comment]
I worry this change will cause process paused all the time. 
If a snapshot is sent and the FinishedStatus is reported, the process will be paused until getting the MsgAppendResp from the follower. 
If the message is missing, the process status can not be changed if no `resume` in heartbeat later.

**Comment by xiang90** [comment]
@siddontang @petermattis 

I will give this a close look early next week. I will be on vacation for the next few days.

**Comment by petermattis** [comment]
@siddontang Can you elaborate on your concern? If a follower is paused in state probe (e.g. after a snapshot has been sent) the leader will still send `MsgHeartbeat` messages and whenever a `MsgHeartbeatResp` is received the follower will be resumed and a `MsgApp` will be sent. If no `MsgHeartbeatResp` or `MsgAppResp` messages are being sent by the follower (or they are not being received by the leader), why should the leader continue to send `MsgApps`?

**Comment by siddontang** [comment]
@petermattis 

If the progress is paused, it can't be resumed until getting MsgHeartbeatRes, and leader won't send any following new entry to the follower:

```
// sendAppend sends RPC, with entries to the given peer.
func (r *raft) sendAppend(to uint64) {
	pr := r.prs[to]
	if pr.IsPaused() {
		return
	}
```

Of course, the leader can still send heartbeat to follower, but the progress can't be resumed in MsgHeartbeatResp.

**Comment by xiang90** [comment]
@siddontang 

This is a trade-off between fast recovery and cost saving. The recovery delay can be as long as a round trip time (~200ms) across continents after this change as you mentioned. Or we will waste CPU cycles to generate quite a few append entries requests. See https://github.com/cockroachdb/cockroach/issues/12485 for details.

For etcd, this is fine. The downtime is usually ~minutes, so 200ms additional down time seems fine to me.

For CockroachDB, they are aware of this problem, and they seems to be OK with it.

What is your concert? @siddontang 

I do not quite get 

> but the progress can't be resumed in MsgHeartbeatResp.

Can you explain more?

/cc @manishrjain Any concern from dgraph? @aaronlehmann Any concern from swarmkit?

**Comment by siddontang** [comment]
@xiang90 @petermattis 

Sorry that I don't see this PR handle `resume` in heartbeat response. I think it is ok now.

**Comment by petermattis** [comment]
> For etcd, this is fine. The downtime is usually ~minutes, so 200ms additional down time seems fine to me.
> 
> For CockroachDB, they are aware of this problem, and they seems to be OK with it.

This is true for CockroachDB as well. Adding a few hundred milliseconds to the time to recover a replica is a small price in comparison to the wasted CPU cycles of trying to send Raft log entries that will likely be dropped at the RPC layer. To give a more concrete example of what we are seeing and which this PR alleviates:

* Run a 3-node cluster.
* Take one node down for 5 min.
* While the node is down, every 200ms (our configured heartbeat interval) Raft generates a `MsgHeartbeat` to the down node which resumes the follower. The next proposal then triggers a `MsgApp` to the down node.
* The size of the `MsgApp` messages to the down node increase over time as Raft helpfully includes up to `MaxMsgSize` bytes of Raft log entries.

If there were only a small number of Raft groups the generation of the `MsgApp` messages for the down node wouldn't be too noticeable. But CockroachDB can have O(10k) Raft groups per node.

@xiang90 No rush on reviewing. I'm leaving on my own vacation tomorrow.

**Comment by aaronlehmann** [comment]
This change seems fine for SwarmKit. Fast recovery isn't very important for us. It seems logical to avoid generating `MsgApp` traffic until the recipient node is confirmed to have recovered. I don't think the current approach has caused us any problems, though.

**Comment by manishrjain** [comment]
Sounds good for Dgraph as well. It's the logical thing to do.

**Comment by xiang90** [comment]
LGTM

**Pull request merged**
