### PR TITLE
storage: simplify watch store

### PR DESCRIPTION
**Pull request by xiang90**
We decided that we will not support modifing the same
key in one txn multiple times. That can simlify the current
code/design a lot.

### CODE REVIEW

**Comment by gyuho** [comment]
Lgtm. Thanks

**Comment by tisonkun** [comment]
> That can simlify the current code/design a lot.

I'm wondering what is exactly simplified with this assumption. Can you elaborate a bit?

**Comment by tisonkun** [comment]
It seems that we can always use the next revision for an updated key in one transaction, so we don't have to care about the `sub` part. But this PR doesn't contain changes there so it's still a bit vague to me.

**Pull request merged**
