### PR TITLE
etcdctl: use os.Stdout, os.Stderr directly for cmd

### PR DESCRIPTION
**Pull request by gyuho**
Related to https://github.com/coreos/etcd/issues/4287.

### CODE REVIEW

**Comment by heyitsanthony** [comment]
lgtm

**Comment by gyuho** [comment]
Thanks.

@xiang90  If you don't have any objection, I will merge.

I don't see any reason to use another goroutine to copy stdout, stderr.
I saw this pattern in old etcdctl code (since day 1).

**Comment by xiang90** [comment]
LGTM

**Comment by gyuho** [comment]
Thanks

**Pull request merged**
