### PR TITLE
*: separate Dockerfile for quay build trigger

### PR DESCRIPTION
**Pull request by gyuho**
Fix https://quay.io/repository/coreos/etcd-git/build/d75d80b1-7d8d-42bd-af07-645b7da3a118.

### CODE REVIEW

**Comment by gyuho** [comment]
/cc @xiang90 @heyitsanthony 

Thanks.

**Comment by heyitsanthony** [comment]
lgtm

**Comment by gyuho** [comment]
Ok merging, and will see if it's fixed.

**Comment by gyuho** [comment]
great. now fixed https://quay.io/repository/coreos/etcd-git/build/13e67fc1-020e-4f2d-a90b-70cb22ccc4cb.

**Pull request merged**
