### PR TITLE
clientv3: break etcdserver dependency

### LINKED ISSUE #4771: clientv3: break etcdserver dependency
Related to #4770
```
~/src/etcd/clientv3 $ go list -f '{{ .Deps }}'  | sed 's/ /\n/g' | grep etcd | grep -v Godeps
github.com/coreos/etcd/auth
github.com/coreos/etcd/client
github.com/coreos/etcd/compactor
github.com/coreos/etcd/discovery
github.com/coreos/etcd/error
github.com/coreos/etcd/etcdserver
github.com/coreos/etcd/etcdserver/api/v3rpc
github.com/coreos/etcd/etcdserver/etcdhttp/httptypes
github.com/coreos/etcd/etcdserver/etcdserverpb
github.com/coreos/etcd/etcdserver/stats
github.com/coreos/etcd/lease
github.com/coreos/etcd/lease/leasehttp
github.com/coreos/etcd/lease/leasepb
github.com/coreos/etcd/pkg/adt
github.com/coreos/etcd/pkg/contention
github.com/coreos/etcd/pkg/crc
github.com/coreos/etcd/pkg/fileutil
github.com/coreos/etcd/pkg/httputil
github.com/coreos/etcd/pkg/idutil
github.com/coreos/etcd/pkg/ioutil
github.com/coreos/etcd/pkg/logutil
github.com/coreos/etcd/pkg/netutil
github.com/coreos/etcd/pkg/pathutil
github.com/coreos/etcd/pkg/pbutil
github.com/coreos/etcd/pkg/runtime
github.com/coreos/etcd/pkg/schedule
github.com/coreos/etcd/pkg/testutil
github.com/coreos/etcd/pkg/transport
github.com/coreos/etcd/pkg/types
github.com/coreos/etcd/pkg/wait
github.com/coreos/etcd/raft
github.com/coreos/etcd/raft/raftpb
github.com/coreos/etcd/rafthttp
github.com/coreos/etcd/snap
github.com/coreos/etcd/snap/snappb
github.com/coreos/etcd/storage
github.com/coreos/etcd/storage/backend
github.com/coreos/etcd/storage/storagepb
github.com/coreos/etcd/store
github.com/coreos/etcd/version
github.com/coreos/etcd/wal
github.com/coreos/etcd/wal/walpb
```

### PR DESCRIPTION
**Pull request by heyitsanthony**
Fixes #4771

### CODE REVIEW

**Comment by heyitsanthony** [comment]
Still seeing some prometheus dependencies via importing storage. Will dig more.

**Comment by hongchaodeng** [comment]
@heyitsanthony 

It still has this dependency
```
github.com/coreos/etcd/storage
```

**Comment by hongchaodeng** [comment]
Other than "etcd_storage_xxx" metrics, it looks fine.

**Comment by heyitsanthony** [comment]
client looks clean now /cc @hongchaodeng

**Comment by hongchaodeng** [comment]
Great job! @heyitsanthony 
Running k8s test suite now. Will update shortly.

**Comment by hongchaodeng** [comment]
Success confirmed!
LGTM

**Comment by xiang90** [comment]
lgtm

**Pull request merged**
