### PR TITLE
tools: Add etcd 3.0 load test tool refernece

### PR DESCRIPTION
**Pull request by sinsharat**
Added load test tool reference for etcd version 3.0 and above.

### CODE REVIEW

**Comment by heyitsanthony** [comment]
s/refernece/reference in the commit message and lgtm

**Comment by sinsharat** [comment]
@heyitsanthony its done. Thanks!

**Comment by sinsharat** [comment]
@xiang90 I have added the reference for the load test tool as you wanted. PTAL if its fine.
Thank you!

**Comment by gyuho** [comment]
@sinsharat Please change the commit title back to `tools: Add etcd 3.0 load test tool reference`?

**Comment by sinsharat** [comment]
@gyuho Its done. Thanks!

**Comment by xiang90** [comment]
LGTM. Merging.

**Pull request merged**
