### PR TITLE
etcdserver: close response body when getting cluster information

### LINKED ISSUE #5119: code bug in etcdserver/cluster_util.go
i think [this response](https://github.com/coreos/etcd/blob/master/etcdserver/cluster_util.go#L68) should be closed

### PR DESCRIPTION
**Pull request by magicwang-cn**
Fixes #5119

### CODE REVIEW

**Comment by heyitsanthony** [comment]
Why not just put a `resp.Body.Close()` before this line: https://github.com/coreos/etcd/blob/master/etcdserver/cluster_util.go#L76 ? Creating a closure seems like overkill...

Also the commit title should to be prefixed by the package name like `etcdserver: close response body when getting cluster information`

**Comment by magicwang-cn** [comment]
@heyitsanthony thanks for your review. i think it is more safer to use (`defer`) to clean unused resource, right? yeah. the commit should be clear

**Comment by heyitsanthony** [comment]
@magicwang-cn No, it's not safer. It's more complicated: semantically, lexically, and cyclomatically. The defer only buys a close if `ReadAll` panics, but there's no `recover`, so it doesn't matter if the resource is closed anyway. Where's the additional safety, exactly?

**Comment by magicwang-cn** [comment]
yeah, you are right.:)

>but there's no recover, so it doesn't matter if the resource is closed anyway

**Comment by heyitsanthony** [comment]
lgtm

**Pull request merged**
