### PR TITLE
Default stm isolation level is serializable snapshot isolation

### PR DESCRIPTION
**Pull request by huikang**
Update the comment of NewSTM function

Signed-off-by: Hui Kang <kangh@us.ibm.com>

# Contributing guidelines

Please read our [contribution workflow][contributing] before submitting a pull request.

[contributing]: https://github.com/coreos/etcd/blob/master/CONTRIBUTING.md#contribution-flow

### CODE REVIEW

**Comment by heyitsanthony** [comment]
@huikang for the first line of the commit message please have `concurrency: comment the default stm isolation level is serializable snapshot` so this passes the CI commit checking and can be merged. Thanks!

**Comment by huikang** [comment]
@heyitsanthony please checkout the updated commit message. Thanks.

**Comment by heyitsanthony** [comment]
@huikang it should be the first line / title

**Comment by xiang90** [comment]
thanks. merging.

**Pull request merged**
