### PR TITLE
windows: added build script for functional tester

### PR DESCRIPTION
**Pull request by sinsharat**
Added build script in windows to support build of functional tester.

### CODE REVIEW

**Comment by sinsharat** [comment]
@gyuho Can we run semaphore again. Since the build script cannot cause any test case to fail.
Thanks!

**Comment by sinsharat** [comment]
@xiang90 request you to provide feedback for this PR.
Thank you!

**Comment by xiang90** [comment]
I do not really care about making sure we have window build scripts for everything inside etcd repo, especially for dev tool like this functional tester. If you want this and plan to maintain it, I am fine with it.

**Comment by sinsharat** [comment]
@xiang90 i had not deliberately thought of developing it. It just happened that when you had assigned me to work on functional tester, i was at home and had only windows environment. So in order to work on it from home as well i had written this. Most of the time when you reach office i reach home from office :). But its fine now, i have setup linux env at home as well now. So i leave it up-to you to take a call on this. If its not so important even i would not like to spend too much time on writing windows scripts. Since even the Procfile for goreamn required changes windows and spent quite a lot of time on it to make it work in windows.
Thank you!

**Comment by xiang90** [comment]
OK. I am closing this.

**Pull request closed without merging**
