### PR TITLE
v3rpc: move Hash RPC to Maintenance service

### PR DESCRIPTION
**Pull request by heyitsanthony**

### CODE REVIEW

**Comment by gyuho** [comment]
lgtm. /cc @xiang90

**Comment by gyuho** [comment]
Btw this. Fix https://github.com/coreos/etcd/issues/4712.

Thanks!

**Comment by xiang90** [comment]
@heyitsanthony @gyuho I do not think this fixes #4712. Does it?

**Comment by heyitsanthony** [comment]
@gyuho @xiang90 I think #4863 fixes #4712?

**Comment by xiang90** [comment]
LGTM

**Comment by gyuho** [comment]
@heyitsanthony @xiang90 nvm. yeah we need https://github.com/coreos/etcd/pull/4863 for https://github.com/coreos/etcd/issues/4712

**Pull request merged**
