### PR TITLE
*: update gRPC godep and dependent changes

### PR DESCRIPTION
**Pull request by gyuho**
rkt uses the master branch as of today. etcd is still using the one
from Jun 29, 2015. For compatibility, we should have the same dependency code.
Need this for kubernetes/kubernetes#19931.

### CODE REVIEW

**Comment by jonboulle** [comment]
What version of godep are you using? some of these test files shouldn't get vendored.

**Comment by gyuho** [comment]
@jonboulle I ran `godep update -t  google.golang.org/grpc` with the latest godep version but now it is missing `http2` dependency.

```
godep version
godep v51 (linux/amd64/go1.5.3)
```

**Comment by xiang90** [comment]
Even if we update gRPC in master branch, k8s will not use it. We have to back port to 2.2. :(

**Comment by jonboulle** [comment]
@xiang90 hmm? the only things that use grpc in the k8s codebase are rkt and etcd - https://github.com/kubernetes/kubernetes/pull/19931

**Comment by xiang90** [comment]
@jonboulle Sorry. I should be more clear. k8s godeps the released branch of etcd, which is 2.2 currently. So after we update the gRPC in etcd master branch. I should back port it to 2.2 branch.

**Comment by gyuho** [comment]
@xiang90 Think this requires changes in our rpc proto. Should I fix it in this PR?

**Comment by gyuho** [comment]
I will fix the rpc proto issues tomorrow.

**Comment by gyuho** [comment]
@yifan-gu @jonboulle Sorry, this seems much more complicated than I thought. I created the issue here https://github.com/coreos/etcd/issues/4264. I will try to resolve it as soon as possible.

Thanks,

**Comment by gyuho** [comment]
@jonboulle Could you take a look at https://github.com/gyuho/etcd/commit/a65ab93c57a1979564ad445cbcef325f3a608cb2?

In the meantime, I just need to fix other packages now to follow the proto changes. I can do it by today.

**Comment by gyuho** [comment]
/cc @xiang90 @heyitsanthony @jonboulle I think these are ready for **first** review. There are still quite a few things breaking in integration test (mostly in `v3_queue_test.go` and `v3_barrier_test.go`). 

```
--- FAIL: TestBarrierSingleNode (2.05s)
	v3_barrier_test.go:42: able to double-hold barrier
=== RUN   TestBarrierMultiNode
--- FAIL: TestBarrierMultiNode (2.06s)
	v3_barrier_test.go:42: able to double-hold barrier

=== RUN   TestV3PutMissingLease
--- FAIL: TestV3PutMissingLease (2.06s)
	v3_grpc_test.go:157: failed good txn. req: success:<request_range:<key:"bar" > > failure:<request_put:<key:"foo" lease:123456 > > . resp: <nil>
=== RUN   TestV3DeleteRange
--- PASS: TestV3DeleteRange (12.30s)


=== RUN   TestQueueOneReaderOneWriter
2016/01/25 22:06:43 grpc: Server.processUnaryRPC failed to write status: stream error: code = 1 desc = "context canceled"
--- FAIL: TestQueueOneReaderOneWriter (0.07s)
	v3_queue_test.go:50: error dequeueing (rpc error: code = 2 desc = "cannot type-assert on *etcdserverpb.RequestUnion_RequestDeleteRange")
	v3_queue_test.go:40: error enqueuing (rpc error: code = 13 desc = "transport is closing")
=== RUN   TestQueueManyReaderOneWriter
--- FAIL: TestQueueManyReaderOneWriter (2.11s)
	v3_queue_test.go:168: error reading (rpc error: code = 2 desc = "cannot type-assert on *etcdserverpb.RequestUnion_RequestDeleteRange")
	v3_queue_test.go:168: error reading (rpc error: code = 2 desc = "cannot type-assert on *etcdserverpb.RequestUnion_RequestDeleteRange")
=== RUN   TestQueueOneReaderManyWriter
--- FAIL: TestQueueOneReaderManyWriter (2.12s)
	v3_queue_test.go:168: error reading (rpc error: code = 2 desc = "cannot type-assert on *etcdserverpb.RequestUnion_RequestDeleteRange")
=== RUN   TestQueueManyReaderManyWriter
--- FAIL: TestQueueManyReaderManyWriter (2.04s)
	v3_queue_test.go:168: error reading (rpc error: code = 2 desc = "cannot type-assert on *etcdserverpb.RequestUnion_RequestDeleteRange")
	v3_queue_test.go:168: error reading (rpc error: code = 2 desc = "cannot type-assert on *etcdserverpb.RequestUnion_RequestDeleteRange")
	v3_queue_test.go:168: error reading (rpc error: code = 2 desc = "cannot type-assert on *etcdserverpb.RequestUnion_RequestDeleteRange")
=== RUN   TestPrQueueOneReaderOneWriter
--- FAIL: TestPrQueueOneReaderOneWriter (0.05s)
	v3_queue_test.go:101: error dequeueing (rpc error: code = 2 desc = "cannot type-assert on *etcdserverpb.RequestUnion_RequestDeleteRange")
=== RUN   TestPrQueueManyReaderManyWriter
--- FAIL: TestPrQueueManyReaderManyWriter (2.12s)
	v3_queue_test.go:168: error reading (rpc error: code = 2 desc = "cannot type-assert on *etcdserverpb.RequestUnion_RequestDeleteRange")
	v3_queue_test.go:168: error reading (rpc error: code = 2 desc = "cannot type-assert on *etcdserverpb.RequestUnion_RequestDeleteRange")
	v3_queue_test.go:168: error reading (rpc error: code = 2 desc = "cannot type-assert on *etcdserverpb.RequestUnion_RequestDeleteRange")

```

Before I take a look at them, I would like to get this reviewed to see if I am missing anything.


I separate into multiple commits to make it easy if possible.

@heyitsanthony Please ignore my previous complaint about gRPC. I was passing `grpc.WithInsecure` the latter but when I pass it in `grpc.Dial` first then it works (grpc does not document this).

**Comment by gyuho** [comment]
Just fixed all test failures except `STMAbort` leaky goroutines https://semaphoreci.com/coreos/etcd/branches/pull-request-4256/builds/15

 @heyitsanthony   do you have any idea? I will take a look more,.

PTAL.

Thanks.

**Comment by heyitsanthony** [comment]
Only insight here is that it's not the STM code; it doesn't use leases or watchers so no streams. The v3 lease tests don't have `AfterTest`, so the leak detector could be picking up something left over from that (or possibly the queues or barriers since they use watchers).

**Comment by gyuho** [comment]
Right. I will look at the parts with leases and watchers. Thanks!

**Comment by gyuho** [comment]
will rebase in a separate branch.

**Pull request closed without merging**
