### PR TITLE
clientv3/txn.go : removed the TODO: add a Do for shortcut the txn without any condition

### PR DESCRIPTION
**Pull request by vimalk78**
fixes TODO : 
clientv3/txn.go:      // TODO: add a Do for shortcut the txn without any condition

### CODE REVIEW

**Comment by heyitsanthony** [comment]
@xiang90 should we support this or just nix the TODO? It seems people are fine using Txn().Then().Commit() and I'm a little averse toward expanding an interface if the functionality can already be had with what's already available....

**Comment by xiang90** [comment]
@heyitsanthony Probably we can remove the TODO. we can add TxnDo(txn, ops) if we really want to have the shortcut. I do not want to expand the interface either.

**Comment by vimalk78** [comment]
while implementing the `Do` method i also got the feeling that it adds nothing new. 
and no changes were needed on server side.

shall i modify the PR to remove the TODO or close the PR ?

**Comment by xiang90** [comment]
@vimalk78 Yes. Just remove the todo.

**Comment by xiang90** [comment]
lgtm

**Pull request merged**
