### PR TITLE
[wip] integration/fixtures, e2e: recreate certs with cfssl

### PR DESCRIPTION
**Pull request by gyuho**
Fixes https://github.com/coreos/etcd/issues/4368.
I just recreated them with https://github.com/cloudflare/cfssl
with key usage specified in the config.

### CODE REVIEW

**Comment by gyuho** [comment]
@heyitsanthony Ran the same integration test in cloud environment and confirmed that `cURL` tests pass without `SSL` error now. Please review.

Thanks,

**Comment by heyitsanthony** [comment]
lgtm; was curl rejecting the cipher?

**Comment by gyuho** [comment]
@heyitsanthony Thanks,

No idea. They were rejecting `SSL v3` I think:

```
curl: (35) error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure
```

Will merge after green lights.

**Comment by gyuho** [comment]
Now `TestTLSClusterOf3` is hanging with new certs. Will fix them.

**Pull request closed without merging**
