### PR TITLE
Update api_grpc_gateway.md

### PR DESCRIPTION
**Pull request by RuthDevlaeminck**
Change curl command to contain v3alpha instead of v3 (v3alpha works, v3 does not).

# Contributing guidelines

Please read our [contribution workflow][contributing] before submitting a pull request.

[contributing]: https://github.com/coreos/etcd/blob/master/CONTRIBUTING.md#contribution-flow

### CODE REVIEW

**Comment by gyuho** [comment]
We are deprecating `/v3alpha` endpoints, and promoting it to `/v3beta` and `/v3` in v3.4. So, this is correct.

**Comment by gyuho** [comment]
Also see https://github.com/coreos/etcd/blob/master/CHANGELOG-3.4.md#added-grpc-gateway.

**Comment by RuthDevlaeminck** [comment]
@gyuho Would it be possible to update the documentation for now and then revert it when 3.4 comes out?  I spent literally three days trying to figure out why my etcd v3 box didn't work.

**Comment by gyuho** [comment]
@RuthDevlaeminck Sorry about that.

The master branch is meant to include all the changes for our upcoming release (3.4). It's easier for us to update the docs whenever changes happen, and not forget to update before release comes out.

For the meantime, you can see https://github.com/coreos/etcd/blob/release-3.3/Documentation/dev-guide/api_grpc_gateway.md. Or we are open to add notes in the master branch (e.g. use `/v3alpha` if you use etcd server v3.2, etc.).

**Comment by RuthDevlaeminck** [comment]
I think adding a note would be a great idea.  When we do a pull of the docker image it is not the latest code but this was the documentation that I could find.

**Comment by gyuho** [comment]
@RuthDevlaeminck Now it's explicitly documented here https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/api_grpc_gateway.md#notes.

Thanks for report and let me know if this still reads confusing.

**Comment by RuthDevlaeminck** [comment]
@gyuho This is great.  Thank you so much!

**Pull request closed without merging**
