### PR TITLE
Handle ETCDCTL_USERNAME environment

### PR DESCRIPTION
**Pull request by kayrus**
/cc @yichengq @yifan-gu

### CODE REVIEW

**Comment by gyuho** [comment]
LGTM.

@kayrus Thanks for PR.

I don't have any objection on this, but I will wait for @xiang90's final decision.

**Comment by kayrus** [comment]
@xiang90 any objection?

**Comment by kayrus** [comment]
@xiang90 ping

**Comment by kayrus** [comment]
@xiang90 ping

**Comment by xiang90** [comment]
@kayrus What is the use case of this?

**Comment by kayrus** [comment]
@xiang90 it will automatically extract password from the uFlag.

Use case: use [EnvironmentFile](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#EnvironmentFile=) inside systemd units. Or [--env-file](https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables-e-env-env-file) with docker.

**Comment by xiang90** [comment]
@kayrus can you rebase? The change lgtm!

**Comment by xiang90** [comment]
Also can you please add this into the env section in the README doc?

**Comment by kayrus** [comment]
@xiang90 done

**Comment by xiang90** [comment]
@kayrus Thanks!

**Pull request merged**
