### PR TITLE
Cherry-picking PR 7967 to release-3.1

### PR DESCRIPTION
**Pull request by mohitsoni**
etcdserver: purge old snap.db files
Lots of garbage db files in #7957. Should purge.

### CODE REVIEW

**Comment by gyuho** [comment]
@mohitsoni Can you also cherry-pick the same patch into 3.2 branch with a separate PR?

**Comment by mohitsoni** [comment]
@gyuho Sure will do!

**Comment by mohitsoni** [comment]
@gyuho cherry-pick PR for release-3.2 branch: https://github.com/coreos/etcd/pull/9694

**Pull request merged**
