### PR TITLE
etcdserverV2: do not return body for HEAD request

### PR DESCRIPTION
**Pull request by mqliang**
@xiang90 @gyuho

### CODE REVIEW

**Comment by gyuho** [comment]
@mqliang What is your use case of `HEAD` requests? Do you use just to ping etcd endpoints?

I will defer to @xiang90 and @heyitsanthony 

Thanks!

**Comment by heyitsanthony** [comment]
I think this would be cleaner overall if instead of changing the code to pass `withBody` everywhere, it would use a custom response writer like this (haven't tested it, might need some minor tweaking):

```go
type headResponseWriter struct { http.ResponseWriter; wroteHeader bool }
func (w *headResponseWriter) Write(v []byte) (int, error) {
    if !w.wroteHeader {
        w.ResponseWriter.WriteHeader(http.StatusOK)
    }
    w.wroteHeader = true
    return len(v), nil
}
func (w *headResponseWriter) WriteHeader(v int) {
    w.ResponseWriter.WriteHeader(v)
    w.wroteHeader = true
}

...

if r.method == http.MethodHead {
    w = &headResponseWriter{w}
}
```

**Comment by mqliang** [comment]
cc/ @jerryzh168

**Comment by xiang90** [comment]
@mqliang I think this is a good direction. Can you try what @heyitsanthony suggested?

**Comment by xiang90** [comment]
This is inactive. Closing.

**Pull request closed without merging**
