### PR TITLE
follow golint notice replace '+=1' to '++'

### PR DESCRIPTION
**Pull request by davygeek**
Follow the golint notice, replace '+=1' to '++'

### CODE REVIEW

**Comment by heyitsanthony** [comment]
lgtm

**Comment by davygeek** [comment]
thanks, I got it
@heyitsanthony

**Comment by heyitsanthony** [comment]
You didn't have to close this PR-- `git rebase -i master`, `reword`, then `git push -f` would've done the trick...

**Comment by davygeek** [comment]
thanks, it closed automatic， I push again
@heyitsanthony

**Comment by xiang90** [comment]
LGTM

**Pull request merged**
