### PR TITLE
pkg/ioutil: Return written size when flushing fails in PageWriter.Write

### PR DESCRIPTION
**Pull request by lorneli**
When flushing fails in PageWriter.Write function, return actual written
size instead of zero.

Add halfPageWriter in test, which simulates flushing error.

### CODE REVIEW

**Comment by xiang90** [comment]
what is the motivation for this change?

**Comment by lorneli** [comment]
@xiang90 
I try to figure out how write-ahead-log handles torn-write recently, related to PageWriter. So I start to read the code of PageWriter.
In PageWriter.Write function, if flushing data fails, this function [returns written size 0](https://github.com/coreos/etcd/blob/master/pkg/ioutil/pagewriter.go#L80). But under this circumstance, bytes may be written partially to underlayer via [PageWriter.w](https://github.com/coreos/etcd/blob/master/pkg/ioutil/pagewriter.go#L26), which means actual written size != 0.

**Comment by heyitsanthony** [comment]
@lorneli can the wal code use the extra information in any meaningful way?

**Comment by lorneli** [comment]
@heyitsanthony wal.encoder.encode function uses PageWriter.Write, but ignores its written size:
 `_, err = e.bw.Write(data)` . Maybe encoder can use this written size in PackageLogger, which isn't quite meaningful. 

Sorry for the noise.

**Pull request closed without merging**
