### PR TITLE
add unit tests for storage

### PR DESCRIPTION
**Pull request by yichengq**
for #3306 

The coverage reaches 90%

### CODE REVIEW

**Comment by yichengq** [comment]
updated. address all comments. PTAL

**Comment by yichengq** [comment]
changed the way to generate temp filename. please check.

**Comment by yichengq** [comment]
Improved the temp path again. I checked it carefully and it should be the best.

**Comment by xiang90** [comment]
LGTM. Thanks!

**Comment by yichengq** [comment]
Thanks for patient reviewing!

**Pull request merged**
