### PR TITLE
etcdctlv3: refactoring

### PR DESCRIPTION
**Pull request by xiang90**
1. Make the flag description more generic and prefer TLS over SSL.
2. Separate out cmd parsing logic for creating client.

### CODE REVIEW

**Comment by gyuho** [comment]
Lgtm

**Comment by xiang90** [comment]
We want to separate out the parsing logic since we need to create another client from another set of flags when adding mirrormaker command for the destination cluster.

/cc @heyitsanthony @mitake

**Comment by mitake** [comment]
@xiang90 The change looks good to me. However, will the users of the new `mustClient()` added in the future (currently the funcition doesn't have users)? And what is the mirrormaker?

**Comment by heyitsanthony** [comment]
lgtm

**Pull request merged**
