### PR TITLE
Documentation/faq: fix typo in flag names

### PR DESCRIPTION
**Pull request by huikang**
Signed-off-by: Hui Kang <kangh@us.ibm.com>

# Contributing guidelines

Please read our [contribution workflow][contributing] before submitting a pull request.

[contributing]: https://github.com/coreos/etcd/blob/master/CONTRIBUTING.md#contribution-flow

### CODE REVIEW

**Comment by heyitsanthony** [comment]
This is meant to address both peer advertising and client advertising. It shouldn't be specialized to only client advertise/listen.

**Comment by huikang** [comment]
@heyitsanthony there is no ``--advertise-peer-url`` flag. So I changed the question a bit. Please see if it addresses your concern. Thanks.

**Comment by xiang90** [comment]
this patch makes things worse. if you want to make things clear, you should change `listen-urls` to `listen-<client,peer>-urls` and `advertise-urls` to `advertise-<client,peer>-urls` in the question title. nothing else should be changed.

**Comment by huikang** [comment]
@xiang90 looks like there is no such flag ``--advertise-peer-url``; could you confirm? Thanks.

**Comment by xiang90** [comment]
probably it is initial-advertise-peer-urls or something.

**Comment by xiang90** [comment]
lgtm. thanks @huikang !

**Comment by xiang90** [comment]
merging. CI failure is tracked here: https://github.com/coreos/etcd/issues/8182

**Pull request merged**
