### PR TITLE
Documentation: alert.rules. fix labels bug

### PR DESCRIPTION
**Pull request by WIZARD-CXY**
Hi~
When I used the default alert rule files to do the alert job, I found some small bugs. Here is the fix and tested on my environment.

### CODE REVIEW

**Comment by WIZARD-CXY** [comment]
@heyitsanthony will do

**Comment by WIZARD-CXY** [comment]
I happend to see prometheus-operator with wrong configuration too . https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-rules.yaml

**Comment by WIZARD-CXY** [comment]
I will fire a pr to fix this same bug in prometheus-operator

**Comment by xiang90** [comment]
CI failure is irrelevant. Merging now. We will fix CI soon.

**Pull request merged**
