### PR TITLE
Documentation: make -bind-addr and -peer-bind-addr docs match the code

### LINKED ISSUE #2072: Respect of interface in configuration
Hi,

For now, I'm using a single node etcd cluster, with planning to expand to many nodes.
As a security mesure, I decided to map the `etcd` ports to the docker gateway network interface (I needed it inside a confd container).
(For the future, I'll build a vpn between my node, and map `etcd` ports to the VPN network interface)

Here is my configration:
````
cat /var/run/systemd/system/etcd.service.d/20-cloudinit.conf  
[Service]
Environment="ETCD_ADDR=172.17.42.1:4001"
Environment="ETCD_PEER_ADDR=172.17.42.1:7001"
````

My issue: I can see that the port `4001` and `7001` are also open to the wild (my public IP...), and I'm not confident about that.
I think my configuration is good, but maybe there is a mistake there. If my configuration is good, I believe it's a bug in etcd that doesn't respect the network inteface.
(If you send me an [email](pierre@ozoux.net), I can give you an IP of a server with this config and "bug")

Thanks for your help!

### PR DESCRIPTION
**Pull request by kelseyhightower**
Fixes #2072.

### CODE REVIEW

**Comment by xiang90** [comment]
@kelseyhightower I think the default of the old peer-bind flag is the advertised flag. We changed it in 2.0.

/cc @yichengq

**Comment by yichengq** [comment]
@kelseyhightower default is to listen on the port of advertise addr on all interfaces(0.0.0.0) in etcd v0.4

**Comment by yichengq** [comment]
yes. lgtm

**Pull request merged**
