### PR TITLE
rafthttp: fix misprint in readBytesLimit value

### PR DESCRIPTION
**Pull request by nekto0n**
Simple fix for miscalculated value in readBytesLimit

### CODE REVIEW

**Comment by gyuho** [comment]
LGTM.

Thanks a lot. Merging in greens.

**Comment by nekto0n** [comment]
Seems like `512mb` is too much too ask

```
runtime: out of memory: cannot allocate 536936448-byte block (1091698688 in use)
```

**Comment by gyuho** [comment]
Right, can you do something like

```go
originalLimit := readBytesLimit
readBytesLimit = 1000
defer func() {
   readBytesLimit = originalLimit
}()
```

inside test?

**Comment by nekto0n** [comment]
I'll try right away

**Pull request merged**
