### PR TITLE
*: gRPC update

### PR DESCRIPTION
**Pull request by gyuho**

### CODE REVIEW

**Comment by heyitsanthony** [comment]
lgtm aside from missing recvLoop

**Comment by gyuho** [comment]
@heyitsanthony what `recvLoop`?

BTW. I am almost done with figuring out leaky goroutines.

gRPC changes its behavior with context where we need to explicitly cancel the context in the client stream.

**Comment by heyitsanthony** [comment]
I meant the `recvLoop` bit that's failing CI.

**Comment by gyuho** [comment]
I see. I will double check. Thanks

**Comment by gyuho** [comment]
@heyitsanthony @xiang90  Please review.


Mostly interface change except one thing that I need to point out.
So there are 3 lease tests previously leaking goroutines from gRPC update:

```
go test -cpu 4 -run TestV3LeaseExpire -v;
go test -cpu 4 -run TestV3LeaseKeepAlive -v;
go test -cpu 4 -run TestV3LeaseExists -v;
```

Log below:

```

=== RUN   TestV3LeaseExpire
--- PASS: TestV3LeaseExpire (7.54s)
PASS
Too many goroutines running after all test(s).
1 instances of:
github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc.NewClientStream.func1(0x7f6746f45c38, 0xc820286000, 0x
c8201ab500, 0xc820099360)
        /home/gyu_ho_lee/go/src/github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc/stream.go:151 +0x258
created by github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc.NewClientStream
        /home/gyu_ho_lee/go/src/github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc/stream.go:159 +0xa5d
exit status 1
FAIL    github.com/coreos/etcd/integration      7.567s


=== RUN   TestV3LeaseKeepAlive
--- PASS: TestV3LeaseKeepAlive (8.11s)
PASS
Too many goroutines running after all test(s).
        }
1 instances of:
github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc.NewClientStream.func1(0x7f3d1366e678, 0xc820262000, 0x
c8201a76c0, 0xc820099040)
        /home/gyu_ho_lee/go/src/github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc/stream.go:151 +0x258
created by github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc.NewClientStream
        /home/gyu_ho_lee/go/src/github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc/stream.go:159 +0xa5d
exit status 1
FAIL    github.com/coreos/etcd/integration      8.128s


=== RUN   TestV3LeaseExists
--- PASS: TestV3LeaseExists (2.09s)
PASS
Too many goroutines running after all test(s).
1 instances of:
github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc.NewClientStream.func1(0x7f6a99557488, 0xc820272000, 0x
c82019cee0, 0xc82008cbe0)
        /home/gyu_ho_lee/go/src/github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc/stream.go:151 +0x258
created by github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc.NewClientStream
        /home/gyu_ho_lee/go/src/github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc/stream.go:159 +0xa5d
exit status 1
FAIL    github.com/coreos/etcd/integration      2.107s
```


If you look at https://github.com/grpc/grpc-go/blob/master/stream.go#L148-L160:

```go
google.golang.org/grpc/stream.go:151
google.golang.org/grpc/stream.go:159

// Listen on ctx.Done() to detect cancellation when there is no pending
// I/O operations on this stream.
go func() {
	select {
	case <-t.Error():
		// Incur transport error, simply exit.
	case <-s.Context().Done():
		err := s.Context().Err()
		cs.finish(err)
		cs.closeTransportStream(transport.ContextErr(err))
	}
}()
return cs, nil
```

It closes the stream only after the context is done. So we need to make sure
close the context with cancel function whenever we use grpc.NewClientStream

```
ctx, cancel := context.WithCancel(context.Background())
defer cancel()
```

**Comment by gyuho** [comment]
test script ran in gcloud and passed but I will rebase it to the master branch now, with the raft revert.

**Comment by heyitsanthony** [comment]
lgtm

**Comment by gyuho** [comment]
Thanks!

@xiang90 Will merge after fixing all other leaky goroutines. Will make sure to pass all CI tests.

**Comment by gyuho** [comment]
test passed. Will talk to Yifan tomorrow about Kubernetes dependency.

**Comment by jonboulle** [comment]
@gyuho belatedly: thanks for getting this through!

**Comment by gyuho** [comment]
Np!

**Pull request merged**
