### PR TITLE
README: develop etcd with Go 1.7+

### PR DESCRIPTION
**Pull request by gyuho**

### CODE REVIEW

**Comment by xiang90** [comment]
I do not think this is necessary. Why do we require 1.7+? I think go 1.6 still works now.

**Comment by gyuho** [comment]
@xiang90 

Go 1.6

https://github.com/golang/go/blob/release-branch.go1.6/src/crypto/tls/common.go#L314-L332

Go 1.7

https://github.com/golang/go/blob/release-branch.go1.7/src/crypto/tls/common.go#L380-L388

`DynamicRecordSizingDisabled` is not defined in Go 1.6, so it won't compile the shallow tls.Config copy method.

```
# github.com/coreos/etcd/pkg/transport
./listener.go:271: unknown tls.Config field 'DynamicRecordSizingDisabled' in struct literal
./listener.go:272: unknown tls.Config field 'Renegotiation' in struct literal
FAIL	github.com/coreos/etcd/pkg/transport [build failed]
```

**Comment by xiang90** [comment]
@gyuho Can we not copy these two fields then? We can do that when we start to support go 1.8.

**Comment by gyuho** [comment]
Sounds good. I will revert the change.

**Pull request closed without merging**
