### PR TITLE
Documentation: Add etcd version support notes for Using TLS common name in RBAC and notes about inter-peer CN filtering

### PR DESCRIPTION
**Pull request by primeroz**
Please read https://github.com/coreos/etcd/blob/master/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by hexfusion** [comment]
@primeroz also please rename commit `Documentation: Add support notes for Using TLS common name in RBAC` so travis passes.

**Comment by primeroz** [comment]
@hexfusion  Changes done.

**Comment by hexfusion** [comment]
@primeroz small nit can we simplify this a hair, `As of v3.3, If an etcd server is launched with the option ..` same for the other paragraph and I don't think we need the second section `## Filtering CN for Inter Peer Connections` as they both fall under _Using TLS Common Name_ just the paragraph detailing the flag. Rebase your commits into one and we should be good. Thanks a lot for the help with this!

**Comment by primeroz** [comment]
@hexfusion After many commits i *think* my change is good. I can see a "functional" test still failing , i doubt that is because of my change but i am not sure

**Pull request merged**
