### PR TITLE
doc: modify vonage usecase, adding kubernetes and vault

### PR DESCRIPTION
**Pull request by raoofm**
adding kubernetes and vault

### CODE REVIEW

**Comment by fanminshi** [comment]
lgtm

**Comment by heyitsanthony** [comment]
lgtm

**Comment by philips** [comment]
@raoofm could you send me an email? I want to learn more about your vault usage with the etcd backend: brandon.philips@coreos.com

**Comment by raoofm** [comment]
@philips, sent you an email.

**Pull request merged**
