### PR TITLE
etcdctl/ctlv3: minor clean ups

### PR DESCRIPTION
**Pull request by gyuho**
- Fix typo
- Improve command ordering (elect should be below lock)
- Update migrate command description

### CODE REVIEW

**Comment by gyuho** [comment]
/cc @heyitsanthony @xiang90 @mitake 

Thanks.

**Comment by xiang90** [comment]
lgtm. Thanks a lot!

**Comment by heyitsanthony** [comment]
lgtm

**Comment by gyuho** [comment]
thanks. merging in greens.

**Pull request merged**
