### PR TITLE
Documentation: write-out=table for v3 commands

### PR DESCRIPTION
**Pull request by gyuho**
/cc @xiang90 @heyitsanthony

### CODE REVIEW

**Comment by heyitsanthony** [comment]
`Documentation/dev-guide/local_cluster.md` too?

**Comment by gyuho** [comment]
@heyitsanthony Just fixed. PTAL.

Thanks!

**Comment by heyitsanthony** [comment]
lgtm

**Comment by gyuho** [comment]
thanks.

**Pull request merged**
