### PR TITLE
Documentation/integrations: add PHP v3 client

### PR DESCRIPTION
**Pull request by ouqiang**
# Contributing guidelines

Please read our [contribution workflow][contributing] before submitting a pull request.

[contributing]: https://github.com/coreos/etcd/blob/master/CONTRIBUTING.md#contribution-flow

### CODE REVIEW

**Comment by ouqiang** [comment]
ok

**Comment by hexfusion** [comment]
@ouqiang kind ping, if you can update commit and rebase I will get this merged. Thanks!

**Comment by ouqiang** [comment]
Sorry, I can't currently provide a client using a gRPC gateway, I think using HTTP is more suitable for PHP

**Comment by hexfusion** [comment]
> Sorry, I can't currently provide a client using a gRPC gateway, I think using HTTP is more suitable for PHP

@ouqiang your solution uses the v3 HTTP API which is exposed by the gRPC gateway. So all that I need is for you to change your commit from
```
[ouqiang/etcd-php](https://github.com/ouqiang/etcd-php) - Client for v3
```

to 

```
[ouqiang/etcd-php](https://github.com/ouqiang/etcd-php) - Client for v3 gRPC gateway
```
So that people can understand this.

Thanks!

**Pull request merged**
