### PR TITLE
Godeps: update prometheus dependency

### PR DESCRIPTION
**Pull request by yichengq**
prometheus updates its directory layout
(https://github.com/prometheus/client_golang#where-is-model-extraction-and-text)
and makes Godeps restore/save unable to work.

Remove all prometheus dependency manually and godep save again to fix
this problem.

/cc @timothysc

### CODE REVIEW

**Comment by timothysc** [comment]
I think the only way to verify would be to repeat the same commands: 

go get github.com/coreos/etcd/etcdserver
godep save -r ./...

**Comment by yichengq** [comment]
@timothysc I have tested it and it could work. Moreover, we would recommend people to godep on our stable release, so i am backporting it to branch release-2.2.

**Comment by yichengq** [comment]
Merge it as-is due to low risk...

**Comment by timothysc** [comment]
updating my deps and it appears your 'godep -r ./...' on your local repository causes issues on anyone attempting to use, b/c it can't resolve. 


Godeps/_workspace/src/github.com/coreos/etcd/storage/backend/backend.go:25:2: cannot find package "github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt" in any of:
	/usr/lib/golang/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt (from $GOROOT)
	/home/tstclair/work/spaces/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt (from $GOPATH)
	/home/tstclair/work/spaces/kubernetes/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt

I literally get 100s of these.

**Pull request merged**
