### PR TITLE
*: migrate Godeps to vendor/

### LINKED ISSUE #4784: *: use go vendoring
The current Godeps vendoring setup makes it difficult to use etcd with other projects (e.g., conflicts with the vendored context package). Eventually etcd should move to using `vendor/` so vendored packages are better behaved.

### PR DESCRIPTION
**Pull request by heyitsanthony**
Fixes #4784

### CODE REVIEW

**Comment by gyuho** [comment]
lgtm as long as all tests pass.

Defer to @xiang90 

Thanks.

**Comment by heyitsanthony** [comment]
everything seems to be working /cc @xiang90

**Comment by xiang90** [comment]
LGTM

**Comment by xiang90** [comment]
probably every pending pr needs a rebase?

**Comment by heyitsanthony** [comment]
We'll find out...

**Comment by radamsfc** [comment]
My dependencies no longer build in Travis

```package github.com/coreos/etcd/Godeps/_workspace/src/github.com/stretchr/testify/assert: cannot find package "github.com/coreos/etcd/Godeps/_workspace/src/github.com/stretchr/testify/assert" in any of:
        /usr/local/go/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/stretchr/testify/assert (from $GOROOT)
        <GOPATH>/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/stretchr/testify/assert (from $GOPATH)```

Any thoughts on how I can recitify this - I've tried `GO15VENDOREXPERIMENT=1`

**Comment by heyitsanthony** [comment]
@radamsfc travis gets confused by godep + vendoring, try:
```
# disable godep restore override
install:
 - go get -t -v ./...
```

**Comment by obeattie** [comment]
I was previously providing my own implementations of `KeysAPI` and `Client`, which have a `Context` in their arguments. I now cannot import the package necessary to satisfy this interface as it is in the `vendor` directory. Is there a solution?

Error if I try and use the "standard" `context` package:

```
libraries/etcd/kv.go:96: cannot use errWatcher literal (type errWatcher) as type "github.com/coreos/etcd/client".Watcher in return argument:
	errWatcher does not implement "github.com/coreos/etcd/client".Watcher (wrong type for Next method)
		have Next("golang.org/x/net/context".Context) (*"github.com/coreos/etcd/client".Response, error)
		want Next("github.com/coreos/etcd/vendor/golang.org/x/net/context".Context) (*"github.com/coreos/etcd/client".Response, error)
libraries/etcd/kv.go:147: cannot use ka (type *keysApi) as type "github.com/coreos/etcd/client".KeysAPI in return argument:
	*keysApi does not implement "github.com/coreos/etcd/client".KeysAPI (wrong type for Create method)
		have Create("golang.org/x/net/context".Context, string, string) (*"github.com/coreos/etcd/client".Response, error)
		want Create("github.com/coreos/etcd/vendor/golang.org/x/net/context".Context, string, string) (*"github.com/coreos/etcd/client".Response, error)
```

**Comment by heyitsanthony** [comment]
@obeattie 

Just tried this on 1.6 and it seems to work fine:
```go
package main

import (
        "fmt"

        etcd "github.com/coreos/etcd/client"
        "golang.org/x/net/context"
)

type A struct {}

func (a *A) Next(context.Context) (*etcd.Response, error) { return nil, nil }

func main() {
        var w etcd.Watcher
        w = &A{}
        fmt.Println(w)
}
```

**Comment by obeattie** [comment]
That exact same code doesn't work for me :confused: 

```
$ go version
go version go1.6 darwin/amd64
$ go run test.go
./test.go:16: cannot use A literal (type *A) as type client.Watcher in assignment:
	*A does not implement client.Watcher (wrong type for Next method)
		have Next("golang.org/x/net/context".Context) (*client.Response, error)
		want Next("github.com/coreos/etcd/Godeps/_workspace/src/golang.org/x/net/context".Context) (*client.Response, error)
```

**Comment by xiang90** [comment]
@obeattie Where does `github.com/coreos/etcd/Godeps/_workspace/src/golang.org/x/net/context".Context` come from? I think the etcd is not head of master branch?

**Comment by obeattie** [comment]
Oops; I forgot I had checked out an old commit locally :flushed:. I still get an error when running this code locally though with the latest `master`

```
$ go version
go version go1.6 darwin/amd64
$ go run test.go
# command-line-arguments
./test.go:16: cannot use A literal (type *A) as type client.Watcher in assignment:
	*A does not implement client.Watcher (wrong type for Next method)
		have Next("golang.org/x/net/context".Context) (*client.Response, error)
		want Next("github.com/coreos/etcd/vendor/golang.org/x/net/context".Context) (*client.Response, error)
```

**Comment by xiang90** [comment]
where do you put the test.go?

**Comment by xiang90** [comment]
before go run test.go, can you do pwd?

**Comment by obeattie** [comment]
In a completely empty directory. The idea here is I want to create a `Watcher` in my own code, outside the `etcd` codebase.

```
$ pwd
/Users/obeattie/Desktop/test-etcd

$ ls -l
total 8
-rw-r--r--  1 obeattie  staff  258 Mar 23 17:55 test.go

$ go version
go version go1.6 darwin/amd64

$ go run test.go
# command-line-arguments
./test.go:16: cannot use A literal (type *A) as type client.Watcher in assignment:
	*A does not implement client.Watcher (wrong type for Next method)
		have Next("golang.org/x/net/context".Context) (*client.Response, error)
		want Next("github.com/coreos/etcd/vendor/golang.org/x/net/context".Context) (*client.Response, error)```

**Comment by obeattie** [comment]
(It's entirely possible I am missing some obvious way to make this work – I'm a bit behind with the latest in Go vendoring :wink:)

**Comment by heyitsanthony** [comment]
@obeattie xiang and I worked out what's necessary to get it building:
* vendor the etcd client for the project by putting it in vendor/github.com/coreos/etcd/client
* the project must be in the GOPATH

**Comment by obeattie** [comment]
Thanks, this works. It feels somewhat fragile; vendoring the entire `github.com/etcd/coreos/etcd` project makes this break for now, but I'm happy that this works for now. Cheers.

**Pull request merged**
