### PR TITLE
integration: make read/write io timeout longer

### LINKED ISSUE #2746: adding back a failed node crashed etcd (v2.0.10)
Adding back a failed node (with a fresh, empty data-dir) to a 6-node cluster failed 
with following log trace.

```
2015/04/23 08:45:37 etcd: listening for peers on http://0.0.0.0:2380
2015/04/23 08:45:37 etcd: listening for client requests on http://0.0.0.0:2379
2015/04/23 08:45:37 etcdserver: datadir is valid for the 2.0.1 format
2015/04/23 08:45:37 etcdserver: name = cne069
2015/04/23 08:45:37 etcdserver: data dir = /etcd-data
2015/04/23 08:45:37 etcdserver: member dir = /etcd-data/member
2015/04/23 08:45:37 etcdserver: heartbeat = 100ms
2015/04/23 08:45:37 etcdserver: election = 1000ms
2015/04/23 08:45:37 etcdserver: snapshot count = 10000
2015/04/23 08:45:37 etcdserver: advertise client URLs = http://cne069:2379
2015/04/23 08:45:37 etcdserver: start member b2d62e962fccdc77 in cluster ea2e39675334c1a3
2015/04/23 08:45:37 raft: b2d62e962fccdc77 became follower at term 0
2015/04/23 08:45:37 raft: newRaft b2d62e962fccdc77 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2015/04/23 08:45:37 raft: b2d62e962fccdc77 became follower at term 1
2015/04/23 08:45:37 raft: b2d62e962fccdc77 [term: 1] received a MsgHeartbeat message with higher term from 21b659ea1139a684 [term: 5]
2015/04/23 08:45:37 raft: b2d62e962fccdc77 became follower at term 5
2015/04/23 08:45:37 raft.node: b2d62e962fccdc77 elected leader 21b659ea1139a684 at term 5
2015/04/23 08:45:37 raft: b2d62e962fccdc77 [logterm: 0, index: 21305] rejected msgApp [logterm: 5, index: 21305] from 21b659ea1139a684
2015/04/23 08:45:37 raft: b2d62e962fccdc77 [commit: 0, lastindex: 0, lastterm: 0] starts to restore snapshot [index: 20002, term: 4]
2015/04/23 08:45:37 raftlog: log [committed=1, applied=0, unstable.offset=0, len(unstable.Entries)=0] starts to restore snapshot [index: 20002, term: 4]
2015/04/23 08:45:37 raft: b2d62e962fccdc77 restored progress of 21b659ea1139a684 [next = 20003, match = 0, wait = 0]
2015/04/23 08:45:37 raft: b2d62e962fccdc77 restored progress of 4ff26076565bf354 [next = 20003, match = 0, wait = 0]
2015/04/23 08:45:37 raft: b2d62e962fccdc77 restored progress of 5d487845232dae55 [next = 20003, match = 0, wait = 0]
2015/04/23 08:45:37 raft: b2d62e962fccdc77 restored progress of 672796e3197d3607 [next = 20003, match = 0, wait = 0]
2015/04/23 08:45:37 raft: b2d62e962fccdc77 restored progress of 8f181250536b3e6a [next = 20003, match = 0, wait = 0]
2015/04/23 08:45:37 raft: b2d62e962fccdc77 restored progress of bd1cfbd83540643e [next = 20003, match = 0, wait = 0]
2015/04/23 08:45:37 raft: b2d62e962fccdc77 restored progress of f234803abb54b919 [next = 20003, match = 0, wait = 0]
2015/04/23 08:45:37 raft: b2d62e962fccdc77 [commit: 0] restored snapshot [index: 20002, term: 4]
2015/04/23 08:45:37 etcdserver: saved incoming snapshot at index 20002
2015/04/23 08:45:37 rafthttp: starting client stream to 21b659ea1139a684 at term 5
2015/04/23 08:45:37 etcdserver: recovered from incoming snapshot at index 20002
2015/04/23 08:45:38 raft: b2d62e962fccdc77 [commit: 20002] ignored snapshot [index: 20002, term: 4]
2015/04/23 08:45:38 rafthttp: unexpected removal of unknown peer '7433075612127671815'
2015/04/23 08:45:38 rafthttp: encountered error reading the client log stream: read tcp 10.20.81.228:2380: use of closed network connection
2015/04/23 08:45:38 rafthttp: client streaming to 21b659ea1139a684 at term 5 has been stopped
panic: rafthttp: unexpected removal of unknown peer '7433075612127671815'

goroutine 39 [running]:
log.Panicf(0x8d67f0, 0x31, 0xc2081194f8, 0x1, 0x1)
        /home/core/go/src/log/log.go:314 +0xd0
github.com/coreos/etcd/rafthttp.(*transport).removePeer(0xc208010380, 0x672796e3197d3607)
        /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/rafthttp/transport.go:152 +0x1c3
github.com/coreos/etcd/rafthttp.(*transport).RemovePeer(0xc208010380, 0x672796e3197d3607)
        /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/rafthttp/transport.go:136 +0x77
github.com/coreos/etcd/etcdserver.(*EtcdServer).applyConfChange(0xc208048200, 0x844ce4d4ee0002c4, 0x1, 0x672796e3197d3607, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:795 +0x81e
github.com/coreos/etcd/etcdserver.(*EtcdServer).apply(0xc208048200, 0xc2081fe000, 0x51e, 0x555, 0xc2080ba1b0, 0x0, 0x0)
        /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:699 +0x399
github.com/coreos/etcd/etcdserver.(*EtcdServer).run(0xc208048200)
        /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:430 +0xf4c
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).start
        /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:298 +0x294

goroutine 1 [runnable]:
github.com/coreos/etcd/etcdmain.Main()
        /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:102 +0x9f7
main.main()
        /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/main.go:29 +0x1b

goroutine 5 [syscall]:
os/signal.loop()
        /home/core/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /home/core/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 11 [sleep]:
net.func·019()
        /home/core/go/src/net/dnsclient_unix.go:240 +0x5a
created by net.loadConfig
        /home/core/go/src/net/dnsclient_unix.go:269 +0x20c

goroutine 40 [runnable]:
github.com/coreos/etcd/etcdserver.(*EtcdServer).Do(0xc208048200, 0x7f0da4e27530, 0xc208070360, 0x774ce57428ec0001, 0x83e480, 0x3, 0xc2080ba720, 0x26, 0xc2080380f0, 0x43, ...)
        /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:496 +0x5df
github.com/coreos/etcd/etcdserver.(*EtcdServer).publish(0xc208048200, 0x12a05f200)
        /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:658 +0x30b
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).Start
        /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:279 +0x4f

goroutine 41 [runnable]:
github.com/coreos/etcd/etcdserver.(*EtcdServer).purgeFile(0xc208048200)
        /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:309 +0x48c
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).Start
        /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:280 +0x69

goroutine 42 [IO wait]:
net.(*pollDesc).Wait(0xc20808aa00, 0x72, 0x0, 0x0)
        /home/core/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20808aa00, 0x0, 0x0)
        /home/core/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc20808a9a0, 0x0, 0x7f0da4e24c18, 0xc2080f8da0)
        /home/core/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208036040, 0x7f0da4e27670, 0x0, 0x0)
        /home/core/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc208036040, 0x0, 0x0, 0x0, 0x0)
        /home/core/go/src/net/tcpsock_posix.go:244 +0x4c
github.com/coreos/etcd/pkg/transport.(*rwTimeoutListener).Accept(0xc20801fa40, 0x0, 0x0, 0x0, 0x0)
        /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/transport/timeout_listener.go:44 +0x7a
net/http.(*Server).Serve(0xc2080704e0, 0x7f0da4e26448, 0xc20801fa40, 0x0, 0x0)
        /home/core/go/src/net/http/server.go:1728 +0x92
github.com/coreos/etcd/etcdmain.serveHTTP(0x7f0da4e26448, 0xc20801fa40, 0x7f0da4e27420, 0xc2080ba150, 0x45d964b800, 0x0, 0x0)
        /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x1be
github.com/coreos/etcd/etcdmain.func·005(0x7f0da4e26448, 0xc20801fa40)
        /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:198 +0x5a
created by github.com/coreos/etcd/etcdmain.startEtcd
        /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:199 +0x18a6

goroutine 43 [IO wait]:
net.(*pollDesc).Wait(0xc20808aae0, 0x72, 0x0, 0x0)
        /home/core/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20808aae0, 0x0, 0x0)
        /home/core/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc20808aa80, 0x0, 0x7f0da4e24c18, 0xc2080bc3a0)
        /home/core/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208036048, 0x0, 0x0, 0x0)
        /home/core/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc208036048, 0x0, 0x0, 0x0, 0x0)
        /home/core/go/src/net/tcpsock_posix.go:244 +0x4c
github.com/coreos/etcd/pkg/transport.(*keepaliveListener).Accept(0xc208033690, 0x0, 0x0, 0x0, 0x0)
        /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/transport/keepalive_listener.go:48 +0x71
net/http.(*Server).Serve(0xc208070540, 0x7f0da4e26480, 0xc208033690, 0x0, 0x0)
        /home/core/go/src/net/http/server.go:1728 +0x92
github.com/coreos/etcd/etcdmain.serveHTTP(0x7f0da4e26480, 0xc208033690, 0x7f0da4e27570, 0xc2080b2040, 0x0, 0x0, 0x0)
        /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x1be
github.com/coreos/etcd/etcdmain.func·006(0x7f0da4e26480, 0xc208033690)
        /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:206 +0x80
created by github.com/coreos/etcd/etcdmain.startEtcd
        /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:207 +0x19f2

goroutine 44 [chan receive]:
github.com/coreos/etcd/pkg/osutil.func·001()
        /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/osutil/interrupt_unix.go:53 +0x68
created by github.com/coreos/etcd/pkg/osutil.HandleInterrupts
        /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/osutil/interrupt_unix.go:74 +0x1f6

goroutine 45 [runnable]:
github.com/coreos/etcd/pkg/fileutil.func·001()
        /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/fileutil/purge.go:69 +0x658
created by github.com/coreos/etcd/pkg/fileutil.PurgeFile
        /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/fileutil/purge.go:75 +0x231

goroutine 46 [runnable]:
github.com/coreos/etcd/pkg/fileutil.func·001()
        /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/fileutil/purge.go:69 +0x658
created by github.com/coreos/etcd/pkg/fileutil.PurgeFile
        /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/fileutil/purge.go:75 +0x231
```

It was added with following args
```
 -name cne069 -data-dir '/etcd-data' 
 -initial-advertise-peer-urls http://cne069:2380
 -advertise-client-urls http://cne069:2379
 -listen-peer-urls http://0.0.0.0:2380
 -listen-client-urls http://0.0.0.0:2379
 -initial-cluster-token setcd
 -initial-cluster cne068=http://tne068:2380,tne069=http://tne069:2380,cne070=http://cne070:2380,cne064=http://cne064:2380,tne070=http://tne070:2380,cne069=http://cne069:2380,tne064=http://tne064:2380
 -initial-cluster-state existing
```

This does not happen 100% of time.
but when it does trigger a crash, even adding another new never-been-in-the-cluster node crashes.

Also, sometimes this heals itself ??
For example, what crashed yesterday will work fine after a day. (with same set of commands adding the same node to the same cluster)

### LINKED ISSUE #5022: test: TestIssue2746
```
=== RUN   TestIssue2746
--- FAIL: TestIssue2746 (1.67s)
	cluster_test.go:360: #1: watch on http://127.0.0.1:20114 error: client: etcd cluster is unavailable or misconfigured
```

### PR DESCRIPTION
**Pull request by xiang90**
Fix #5022

### CODE REVIEW

**Comment by gyuho** [comment]
LGTM. Thanks.

**Comment by xiang90** [comment]
@AkihiroSuda I am not exactly sure this is the right fix. Can you try to reproduce the issue with this patch? Thanks!

**Comment by AkihiroSuda** [comment]
Hi @xiang90, sorry for late.

I tested your PR 77fde6a3d0f3817d1704eaf5ddeca616355f2a55 with a printf-debug patch https://github.com/coreos/etcd/issues/5022#issuecomment-213285042, and still getting an error (Note that the error strings seems changed!):

```
suda@suda-PC2:~/WORK/etcd⟫ GOPATH=$(pwd)/gopath go test -c -race github.com/coreos/etcd/integration
suda@suda-PC2:~/WORK/etcd⟫ ./integration.test -test.run TestIssue2746 -test.count 100
--- FAIL: TestIssue2746 (6.59s)
        cluster_test.go:356: create on http://127.0.0.1:21254 error: client: etcd cluster is unavailable or misconfigured(detail: error #0: client: etcd member http://127.0.0.1:21254 has no leader
                )
FAIL
```

When I hit the issue on my 4-core Xeon(E3-1220 v3 @ 3.10GHz) machine, I did not do anything special nor running heavy applications (although some daemons and X11 were running).
Before running the test, the loadavg were under 1.0.
So I think the issue is not specific to slow machines.

I'll try to add more debug prints and investigate the cause.

**Comment by mitake** [comment]
@AkihiroSuda interesting. Do you have logs of etcd servers?

**Comment by AkihiroSuda** [comment]
More detailed error message (`ErrTimeoutDueToLeaderFail`):
```
--- FAIL: TestIssue2746 (6.67s)
        cluster_test.go:356: create on http://127.0.0.1:21564 error: client: etcd cluster is unavailable or misconfigured(detail: error #0: client: etcd member http://127.0.0.1:21564 has no leader: {"errorCode":300,"message":"Raft Internal Error","cause":"etcdserver: request timed out, possibly due to previous leader failure","index":0}

                )
```
Printf-debug patch: https://github.com/AkihiroSuda/etcd/commit/546fed2d7e22d524d76dd61afb29d45d12a764db

@mitake
I'm still not sure how to get logs for the integration tests. `go test -v` didn't work for me.

**Comment by heyitsanthony** [comment]
@AkihiroSuda @mitake I'm getting full logs by changing `init()` in `integration/v2_http_kv_test.go` to another log level. The failed runs I'm seeing (ex. https://gist.github.com/c34360590438f87cd054003e7c2bdda2) look unremarkable compared to the passing runs.

**Comment by AkihiroSuda** [comment]
@heyitsanthony 

This line seems specific to failed runs

```
 raft: found conflict at index %d [existing term: %d, conflicting term: %d]
```
https://github.com/coreos/etcd/blob/master/raft/log.go#L120
[test.txt](https://github.com/coreos/etcd/files/270094/test.txt)

**Comment by heyitsanthony** [comment]
@AkihiroSuda I'm seeing the same thing. I think the conflict is from an election and the key create call is failing because of a lost leader:

failure1:
```
2016-05-17 18:01:35.537971 D | v2http: [PUT] /v2/keys/foo905924239627700637?prevExist=false remote:127.0.0.1:47451
2016-05-17 18:01:35.577044 I | raft: 31d48e392eff524d is starting a new election at term 2
2016-05-17 18:01:35.577227 I | raft: 31d48e392eff524d became candidate at term 3
2016-05-17 18:01:35.577305 I | raft: 31d48e392eff524d received vote from 31d48e392eff524d at term 3
2016-05-17 18:01:35.577384 I | raft: 31d48e392eff524d [logterm: 2, index: 12] sent vote request to 689c78810a053338 at term 3
2016-05-17 18:01:35.577456 I | raft: 31d48e392eff524d [logterm: 2, index: 12] sent vote request to e100ba9816f5bc05 at term 3
2016-05-17 18:01:35.577527 I | raft: 31d48e392eff524d [logterm: 2, index: 12] sent vote request to 130e2a9f96ae6923 at term 3
2016-05-17 18:01:35.577597 I | raft: 31d48e392eff524d [logterm: 2, index: 12] sent vote request to 3f29caeae3aeba7b at term 3
2016-05-17 18:01:35.577661 I | raft: raft.node: 31d48e392eff524d lost leader 130e2a9f96ae6923 at term 3
```

failure2:
```
2016-05-17 18:01:15.672599 D | v2http: [PUT] /v2/keys/foo1710423896842187924?prevExist=false remote:127.0.0.1:59201
2016-05-17 18:01:15.714356 I | raft: 52c5a45f267b1cda [term: 3] received a MsgVote message with higher term from 9668a13b909c1ad5 [term: 4]
2016-05-17 18:01:15.714575 I | raft: 52c5a45f267b1cda became follower at term 4
2016-05-17 18:01:15.714837 I | raft: 52c5a45f267b1cda [logterm: 3, index: 13, vote: 0] voted for 9668a13b909c1ad5 [logterm: 3, index: 13] at term 4
2016-05-17 18:01:15.714955 I | raft: raft.node: 52c5a45f267b1cda lost leader c65f9846abf9c609 at term 4
2016-05-17 18:01:15.715125 I | raft: 74c456ab7366def4 [term: 3] received a MsgVote message with higher term from 9668a13b909c1ad5 [term: 4]
2016-05-17 18:01:15.715320 I | raft: 74c456ab7366def4 became follower at term 4
2016-05-17 18:01:15.715451 I | raft: 74c456ab7366def4 [logterm: 3, index: 13, vote: 0] voted for 9668a13b909c1ad5 [logterm: 3, index: 13] at term 4
2016-05-17 18:01:15.715529 I | raft: a7250e99bf59f0f3 [term: 3] received a MsgVote message with higher term from 9668a13b909c1ad5 [term: 4]
2016-05-17 18:01:15.715803 I | raft: a7250e99bf59f0f3 became follower at term 4
2016-05-17 18:01:15.715925 I | raft: c65f9846abf9c609 [term: 3] received a MsgVote message with higher term from 9668a13b909c1ad5 [term: 4]
2016-05-17 18:01:15.716122 I | raft: c65f9846abf9c609 became follower at term 4
2016-05-17 18:01:15.716229 I | raft: c65f9846abf9c609 [logterm: 3, index: 14, vote: 0] rejected vote from 9668a13b909c1ad5 [logterm: 3, index: 13] at term 4
2016-05-17 18:01:15.716317 I | raft: raft.node: c65f9846abf9c609 lost leader c65f9846abf9c609 at term 4
```

**Comment by mitake** [comment]
Is returning an error in no leader duration invalid? I think the test failure doesn't mean a bug of etcd because Raft is a leader based consensus algorithm and its unavailability in no leader duration seems to be a valid behavior. How about just retrying requests from client for handling the case (maybe more detailed error code is required?) ?

**Comment by mitake** [comment]
I created a PR https://github.com/coreos/etcd/pull/5395 . The PR reduces test failures according to the test of @AkihiroSuda . But the fix would be partial because of the reason I described above. For removing the failure completely, client side retry would be needed, I think.

**Pull request closed without merging**
