### PR TITLE
documentation: Add authentication walkthrough with etcdctl. Fixes #2949

### LINKED ISSUE #2949: etcdctl docs for security
Now that etcdctl supports security, let's make sure people know how to use it correctly.

### PR DESCRIPTION
**Pull request by barakmich**

### CODE REVIEW

**Comment by yichengq** [comment]
looks pretty awesome!

I have three questions:
1. we don't mention disabling auth in this doc. Should we add that?
2. We have an example workflow here: https://github.com/coreos/etcd/blob/master/Documentation/auth_api.md#example-workflow . Do we need to add this into this doc?
3. Could we add a link to auth_api.md? So people who are fond of cURL/Restful could be noticed about that.

**Comment by barakmich** [comment]
1) It's there. See line 152
2) We could, but it's easy enough now that I don't think so -- plus the "enabling" section is very similar, and is the minimal number of steps
3) Yeah, that makes a lot of sense. Doing that.

**Comment by yichengq** [comment]
lgtm. defer to @xiang90

**Comment by yichengq** [comment]
One more question: is authentication experimental? If so, we need to add notice about it.

**Comment by xiang90** [comment]
lgtm

**Pull request merged**
