### PR TITLE
storage: have Range on rev=0 work even if compacted to current revision

### PR DESCRIPTION
**Pull request by heyitsanthony**
to repro, from fresh kvstore:
ETCDCTL_API=3 ./bin/etcdctl put abc 123
ETCDCTL_API=3 ./bin/etcdctl compaction 2
ETCDCTL_API=3 ./bin/etcdctl get abc

### CODE REVIEW

**Comment by gyuho** [comment]
could you also add a few lines to test that command to e2e? https://github.com/coreos/etcd/blob/master/e2e/ctl_v3_compact_test.go#L56

**Comment by heyitsanthony** [comment]
@gyuho I don't think it's necessary to test this at the etcdctl level-- there's not much etcdctl-side compaction/get could do wrong here.

**Comment by gyuho** [comment]
@heyitsanthony Got it. LGTM. Thanks!

**Comment by xiang90** [comment]
@heyitsanthony I agree. etctctl e2e test is mainly about output and flag parsing correctness, not to ensure server side response correctness.

**Comment by heyitsanthony** [comment]
The status of keys at the compaction revision seemed somewhat wordy/unclear. I cleaned up some comments to make it easier to understand / match what `key_index.go` does. /cc @xiang90

**Comment by xiang90** [comment]
Looks good. Thanks!

**Pull request merged**
