### PR TITLE
clientv3/integration: do not remove client member in TestMemberRemove

### LINKED ISSUE #4716: test member remove fails on CI
```
=== RUN   TestMemberRemove
2016-03-08 05:51:17.880602 I | etcdserver: name = node8162987141596479378
2016-03-08 05:51:17.880639 I | etcdserver: data dir = /tmp/etcd988753435
2016-03-08 05:51:17.880655 I | etcdserver: member dir = /tmp/etcd988753435/member
2016-03-08 05:51:17.880663 I | etcdserver: heartbeat = 10ms
2016-03-08 05:51:17.880670 I | etcdserver: election = 100ms
2016-03-08 05:51:17.880677 I | etcdserver: snapshot count = 0
2016-03-08 05:51:17.880692 I | etcdserver: advertise client URLs = http://127.0.0.1:20194
2016-03-08 05:51:17.880700 I | etcdserver: initial advertise peer URLs = http://127.0.0.1:20193
2016-03-08 05:51:17.880732 I | etcdserver: initial cluster = node5467211863980644661=http://127.0.0.1:20189,node598356869608421287=http://127.0.0.1:20191,node8162987141596479378=http://127.0.0.1:20193
2016-03-08 05:51:17.880756 I | etcdserver: name = node598356869608421287
2016-03-08 05:51:17.880773 I | etcdserver: data dir = /tmp/etcd901099692
2016-03-08 05:51:17.880782 I | etcdserver: member dir = /tmp/etcd901099692/member
2016-03-08 05:51:17.880791 I | etcdserver: heartbeat = 10ms
2016-03-08 05:51:17.880798 I | etcdserver: election = 100ms
2016-03-08 05:51:17.880804 I | etcdserver: snapshot count = 0
2016-03-08 05:51:17.880816 I | etcdserver: advertise client URLs = http://127.0.0.1:20192
2016-03-08 05:51:17.880824 I | etcdserver: initial advertise peer URLs = http://127.0.0.1:20191
2016-03-08 05:51:17.880844 I | etcdserver: initial cluster = node5467211863980644661=http://127.0.0.1:20189,node598356869608421287=http://127.0.0.1:20191,node8162987141596479378=http://127.0.0.1:20193
2016-03-08 05:51:17.881067 I | etcdserver: name = node5467211863980644661
2016-03-08 05:51:17.881099 I | etcdserver: data dir = /tmp/etcd573352513
2016-03-08 05:51:17.881124 I | etcdserver: member dir = /tmp/etcd573352513/member
2016-03-08 05:51:17.881137 I | etcdserver: heartbeat = 10ms
2016-03-08 05:51:17.881149 I | etcdserver: election = 100ms
2016-03-08 05:51:17.881160 I | etcdserver: snapshot count = 0
2016-03-08 05:51:17.881176 I | etcdserver: advertise client URLs = http://127.0.0.1:20190
2016-03-08 05:51:17.881192 I | etcdserver: initial advertise peer URLs = http://127.0.0.1:20189
2016-03-08 05:51:17.881217 I | etcdserver: initial cluster = node5467211863980644661=http://127.0.0.1:20189,node598356869608421287=http://127.0.0.1:20191,node8162987141596479378=http://127.0.0.1:20193
2016-03-08 05:51:17.881359 I | etcdserver: starting member e9926f6404e5a7c3 in cluster 3ed5d76142ee866f
2016-03-08 05:51:17.881439 I | raft: e9926f6404e5a7c3 became follower at term 0
2016-03-08 05:51:17.881474 I | raft: newRaft e9926f6404e5a7c3 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2016-03-08 05:51:17.881497 I | raft: e9926f6404e5a7c3 became follower at term 1
2016-03-08 05:51:17.881595 I | etcdserver: starting member 6a250c1a267bbf2c in cluster 3ed5d76142ee866f
2016-03-08 05:51:17.881649 I | raft: 6a250c1a267bbf2c became follower at term 0
2016-03-08 05:51:17.881671 I | raft: newRaft 6a250c1a267bbf2c [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2016-03-08 05:51:17.881685 I | raft: 6a250c1a267bbf2c became follower at term 1
2016-03-08 05:51:17.884987 I | etcdserver: set snapshot count to default 10000
2016-03-08 05:51:17.885048 I | etcdserver: starting server... [version: 2.3.0-alpha.1+git, cluster version: to_be_decided]
2016-03-08 05:51:17.885085 I | etcdserver: set snapshot count to default 10000
2016-03-08 05:51:17.885128 I | etcdserver: starting server... [version: 2.3.0-alpha.1+git, cluster version: to_be_decided]
2016-03-08 05:51:17.885429 I | etcdserver: starting member 331b18f8e514e721 in cluster 3ed5d76142ee866f
2016-03-08 05:51:17.885525 I | raft: 331b18f8e514e721 became follower at term 0
2016-03-08 05:51:17.885567 I | raft: newRaft 331b18f8e514e721 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2016-03-08 05:51:17.885604 I | raft: 331b18f8e514e721 became follower at term 1
2016-03-08 05:51:17.907046 N | etcdserver: added member 331b18f8e514e721 [http://127.0.0.1:20191] to cluster 3ed5d76142ee866f
2016-03-08 05:51:17.907222 N | etcdserver: added local member 6a250c1a267bbf2c [http://127.0.0.1:20189] to cluster 3ed5d76142ee866f
2016-03-08 05:51:17.907418 N | etcdserver: added member e9926f6404e5a7c3 [http://127.0.0.1:20193] to cluster 3ed5d76142ee866f
2016-03-08 05:51:17.907479 N | etcdserver: added member 331b18f8e514e721 [http://127.0.0.1:20191] to cluster 3ed5d76142ee866f
2016-03-08 05:51:17.907656 N | etcdserver: added member 6a250c1a267bbf2c [http://127.0.0.1:20189] to cluster 3ed5d76142ee866f
2016-03-08 05:51:17.907788 I | rafthttp: the connection with e9926f6404e5a7c3 became active
2016-03-08 05:51:17.907882 N | etcdserver: added local member e9926f6404e5a7c3 [http://127.0.0.1:20193] to cluster 3ed5d76142ee866f
2016-03-08 05:51:17.910371 I | rafthttp: the connection with 6a250c1a267bbf2c became active
2016-03-08 05:51:17.911502 I | etcdserver: set snapshot count to default 10000
2016-03-08 05:51:17.911532 I | etcdserver: starting server... [version: 2.3.0-alpha.1+git, cluster version: to_be_decided]
2016-03-08 05:51:17.912605 I | rafthttp: the connection with 331b18f8e514e721 became active
2016-03-08 05:51:17.912674 I | rafthttp: the connection with 6a250c1a267bbf2c became active
2016-03-08 05:51:17.913363 I | rafthttp: the connection with e9926f6404e5a7c3 became active
2016-03-08 05:51:17.913518 I | rafthttp: the connection with 331b18f8e514e721 became active
2016-03-08 05:51:17.913817 N | etcdserver: added local member 331b18f8e514e721 [http://127.0.0.1:20191] to cluster 3ed5d76142ee866f
2016-03-08 05:51:17.913875 N | etcdserver: added member 6a250c1a267bbf2c [http://127.0.0.1:20189] to cluster 3ed5d76142ee866f
2016-03-08 05:51:17.913920 N | etcdserver: added member e9926f6404e5a7c3 [http://127.0.0.1:20193] to cluster 3ed5d76142ee866f
2016-03-08 05:51:17.921789 I | raft: e9926f6404e5a7c3 is starting a new election at term 1
2016-03-08 05:51:17.921846 I | raft: e9926f6404e5a7c3 became candidate at term 2
2016-03-08 05:51:17.921851 I | raft: e9926f6404e5a7c3 received vote from e9926f6404e5a7c3 at term 2
2016-03-08 05:51:17.921858 I | raft: e9926f6404e5a7c3 [logterm: 1, index: 3] sent vote request to 331b18f8e514e721 at term 2
2016-03-08 05:51:17.921864 I | raft: e9926f6404e5a7c3 [logterm: 1, index: 3] sent vote request to 6a250c1a267bbf2c at term 2
2016-03-08 05:51:17.922030 I | raft: 331b18f8e514e721 [term: 1] received a MsgVote message with higher term from e9926f6404e5a7c3 [term: 2]
2016-03-08 05:51:17.922042 I | raft: 331b18f8e514e721 became follower at term 2
2016-03-08 05:51:17.922060 I | raft: 331b18f8e514e721 [logterm: 1, index: 3, vote: 0] voted for e9926f6404e5a7c3 [logterm: 1, index: 3] at term 2
2016-03-08 05:51:17.922098 I | raft: 6a250c1a267bbf2c [term: 1] received a MsgVote message with higher term from e9926f6404e5a7c3 [term: 2]
2016-03-08 05:51:17.922112 I | raft: 6a250c1a267bbf2c became follower at term 2
2016-03-08 05:51:17.922127 I | raft: 6a250c1a267bbf2c [logterm: 1, index: 3, vote: 0] voted for e9926f6404e5a7c3 [logterm: 1, index: 3] at term 2
2016-03-08 05:51:17.922146 I | raft: e9926f6404e5a7c3 received vote from 331b18f8e514e721 at term 2
2016-03-08 05:51:17.922163 I | raft: e9926f6404e5a7c3 [quorum:2] has received 2 votes and 0 vote rejections
2016-03-08 05:51:17.922172 I | raft: e9926f6404e5a7c3 became leader at term 2
2016-03-08 05:51:17.922179 I | raft: raft.node: e9926f6404e5a7c3 elected leader e9926f6404e5a7c3 at term 2
2016-03-08 05:51:17.922265 I | raft: raft.node: 331b18f8e514e721 elected leader e9926f6404e5a7c3 at term 2
2016-03-08 05:51:17.922283 I | raft: raft.node: 6a250c1a267bbf2c elected leader e9926f6404e5a7c3 at term 2
2016-03-08 05:51:17.922876 I | etcdserver: published {Name:node8162987141596479378 ClientURLs:[http://127.0.0.1:20194]} to cluster 3ed5d76142ee866f
2016-03-08 05:51:17.923100 I | etcdserver: published {Name:node598356869608421287 ClientURLs:[http://127.0.0.1:20192]} to cluster 3ed5d76142ee866f
2016-03-08 05:51:17.923162 I | etcdserver: published {Name:node5467211863980644661 ClientURLs:[http://127.0.0.1:20190]} to cluster 3ed5d76142ee866f
2016-03-08 05:51:17.923275 I | etcdserver: setting up the initial cluster version to 2.3
2016-03-08 05:51:17.923467 N | etcdserver: set the initial cluster version to 2.3
2016-03-08 05:51:17.923523 N | etcdserver: set the initial cluster version to 2.3
2016-03-08 05:51:17.923540 N | etcdserver: set the initial cluster version to 2.3
2016-03-08 05:51:17.935711 N | etcdserver: removed member 331b18f8e514e721 from cluster 3ed5d76142ee866f
2016-03-08 05:51:17.936174 E | rafthttp: failed to read 331b18f8e514e721 on stream Message (net/http: request canceled)
2016-03-08 05:51:17.936211 I | rafthttp: the connection with 331b18f8e514e721 became inactive
2016-03-08 05:51:17.936943 N | etcdserver: removed member 331b18f8e514e721 from cluster 3ed5d76142ee866f
2016-03-08 05:51:18.036260 W | rafthttp: rejected the stream from peer 331b18f8e514e721 since it was removed
2016-03-08 05:51:18.036298 W | rafthttp: rejected the stream from peer 331b18f8e514e721 since it was removed
2016-03-08 05:51:18.036396 E | rafthttp: failed to dial e9926f6404e5a7c3 on stream Message (the member has been permanently removed from the cluster)
2016-03-08 05:51:18.036411 I | rafthttp: the connection with e9926f6404e5a7c3 became inactive
2016-03-08 05:51:18.036444 E | etcdserver: the member has been permanently removed from the cluster
2016-03-08 05:51:18.036452 I | etcdserver: the data-dir used by this member must be removed.
2016-03-08 05:51:18.036825 W | rafthttp: rejected the stream from peer 331b18f8e514e721 since it was removed
2016-03-08 05:51:18.036975 E | rafthttp: failed to dial 6a250c1a267bbf2c on stream MsgApp v2 (the member has been permanently removed from the cluster)
2016-03-08 05:51:18.036991 I | rafthttp: the connection with 6a250c1a267bbf2c became inactive
2016-03-08 05:51:18.038703 E | rafthttp: failed to read e9926f6404e5a7c3 on stream MsgApp v2 (net/http: request canceled)
2016-03-08 05:51:18.038723 I | rafthttp: the connection with e9926f6404e5a7c3 became inactive
--- FAIL: TestMemberRemove (0.18s)
	cluster_test.go:78: failed to remove member rpc error: code = 13 desc = "etcdserver: server stopped"
```

### PR DESCRIPTION
**Pull request by heyitsanthony**
Fixes #4716

### CODE REVIEW

**Comment by xiang90** [comment]
lgtm

**Comment by gyuho** [comment]
lgtm. thanks.

**Comment by xiang90** [comment]
@heyitsanthony This does not fix the double panic one mentioned in #4716, right?

**Comment by heyitsanthony** [comment]
@xiang90, the double panic doesn't seem to happen with this fix, but I imagine it's still there if the client asks the server to remove itself. Probably needs a separate test case.

**Pull request merged**
