### PR TITLE
storage: add store field in watchableStore

### PR DESCRIPTION
**Pull request by yichengq**
We need to access the underlying store to use its RangeEvents function.
It is not good to use unnecessary type conversion.

The underlying store is also needed for further store upon
watchableStore.

### CODE REVIEW

**Comment by xiang90** [comment]
Why do we need the KV then?

**Comment by xiang90** [comment]
This does not make sense to me. :(

**Comment by yichengq** [comment]
> Why do we need the KV then?

Didn't notice that private field could be embedded too. Change it to avoid two same fields. Does it make sense now?

**Comment by gyuho** [comment]
This will be conflict with https://github.com/coreos/etcd/pull/3588.
Please feel free to close my PR (I can push another PR or fetch from master after this merge).

Thanks,

**Comment by xiang90** [comment]
LGTM

**Comment by yichengq** [comment]
@gyuho Sorry for the conflict. :( I am merging this because this blocks my further work.

You could rebase on the master and force push to the original PR. A new PR will lose the context and conversation around the PR.

**Comment by gyuho** [comment]
@yichengq No worry! I will just sync with this merge on the same PR.
Thanks!

**Pull request merged**
