### PR TITLE
storage: fix panic in test

### PR DESCRIPTION
**Pull request by xiang90**
Fix https://github.com/coreos/etcd/issues/4039

I believe the root cause of panic is that the defer closed backend while the last operation was still running. That happens since the wait timeouted. 

This pull request increase the wait time for slow IO and also only close backend when we know all txn are finished. Then we will not get panic at lease. Leaving some files in tmp dir seems to be just fine.

### CODE REVIEW

**Comment by gyuho** [comment]
lgtm. I tried this and no panic found yet.

@AkihiroSuda could you try this branch? I think your environment is more consistent when
reproducing that panic. 

Thanks!

**Comment by heyitsanthony** [comment]
does it matter if that test leaks a goroutine from blocking on `done <- struct{}{}` if the timeout triggers?

**Comment by xiang90** [comment]
@heyitsanthony Fixed.

**Comment by heyitsanthony** [comment]
lgtm

**Comment by AkihiroSuda** [comment]
I tested, and it seems working!
Thanks!

**Comment by gyuho** [comment]
great. Thanks

**Pull request merged**
