### PR TITLE
travis.yml: switch back to VM-based infrastructure

### PR DESCRIPTION
**Pull request by yichengq**
container-based infrastructure does not work well to match our
expectation, so let us switch back to VM one to give it another try.

/cc @xiang90

### CODE REVIEW

**Comment by xiang90** [comment]
@yichengq Why do you think this can help?

**Comment by yichengq** [comment]
@xiang90 I want to give travis another try considering travis provides two kinds of infrastructure.

**Comment by yichengq** [comment]
If it doesn't work, I will drop it.

**Comment by jonboulle** [comment]
If this fails, my suggestion would be to just have travis doing unit tests (and the other things like checking gofmt etc), and having semaphore do the full integration suite; that's what we do in rkt, and then Travis gives us a "fast fail" for basic things that are wrong.

**Comment by yichengq** [comment]
That sounds fair to me.

**Comment by jonboulle** [comment]
Closing in favour of #3755

**Pull request closed without merging**
