### PR TITLE
clientv3/integration: test Get retry

### PR DESCRIPTION
**Pull request by heyitsanthony**
make sure Get will succeed after reconnect cycle

### CODE REVIEW

**Comment by gyuho** [comment]
lgtm.

**Comment by xiang90** [comment]
lgtm

**Comment by heyitsanthony** [comment]
@gyuho @xiang90 added another test to this one PTAL

**Comment by gyuho** [comment]
lgtm. thanks

**Comment by xiang90** [comment]
lgtm again.

**Pull request merged**
