### PR TITLE
etcdctl/ctlv3: allow empty key

### PR DESCRIPTION
**Pull request by gyuho**
Fix coreos#5323.

### CODE REVIEW

**Comment by gyuho** [comment]
/cc @heyitsanthony @xiang90  etcdctl part is not implemented. Wanted to get this reviewed first.

How should we expose this option to etcdctl? Just add `null-key` flag?

**Comment by heyitsanthony** [comment]
@gyuho there's no way to do a full keyspace range with the client without this option?

**Comment by gyuho** [comment]
@heyitsanthony Think people can do `cli.Get(context.Background(), "\x00", clientv3.WithFromKey())`?

**Comment by heyitsanthony** [comment]
@gyuho ok then the client probably shouldn't have this option if it's already possible to pull the data

**Comment by gyuho** [comment]
Will do this in etcdctl. Thanks!

**Comment by gyuho** [comment]
/cc @xiang90 @heyitsanthony PTAL.

Failures are not related.

Thanks.

**Comment by heyitsanthony** [comment]
lgtm

**Pull request merged**
