### PR TITLE
docs/security: link cfssl example

### PR DESCRIPTION
**Pull request by yichengq**
This provides a new way for users to set TLS cluster.

/cc @gtank

### CODE REVIEW

**Comment by yichengq** [comment]
It may be good to recommend people to use cfssl and delete etcd-ca because they perform the same functionality while cfssl provides more features. Do I understand correctly? /cc @gtank 

I don't have enough time now to support/answer the questions about the certs generated by cfssl, so this could become a pain to users. Could you take care of this? /cc @gtank

**Comment by gtank** [comment]
LGTM

I would suggest cfssl over etcd-ca because cfssl is under active development with a lot of eyes on it and offers more functionality.

**Comment by gtank** [comment]
LGTM

**Comment by xiang90** [comment]
LGTM

**Pull request merged**
