### PR TITLE
Dir problem/518

### PR DESCRIPTION
**Pull request by iankronquist**
Addresses issue #518
I think this fixes the issue, but I'm not sure if it's the right approach. After I dived in to the issue I realized why it sat open for a year.
I'm very open for alternate approaches.

### CODE REVIEW

**Comment by iankronquist** [comment]
Can someone take a look at this?

**Comment by iankronquist** [comment]
@philips I know you're busy, but can you take a look at this when you get a chance?

**Comment by xiang90** [comment]
@iankronquist The checking logic should happen in the store not in etcd server. So can you try to make the change?

**Comment by iankronquist** [comment]
So the interesting thing about this bug, as I understand it, is that the store doesn't know some key information in order to make that check, and the etcd server doesn't know whether the key is a directory. Both have really clean interfaces which prevent you from knowing both that a key is a directory and that prevExist=true at the same point in the code. I suspect this is why the bug hasn't been fixed for a year.
I chose to leak whether a given key is a directory to the etcd server, as opposed to leaking part of the content of the request to the store. I understand that the other option may be preferable, and I will prepare an implementation of what you suggest.
Unfortunately I have a midterm next week and am leading a bug bounty hunt tomorrow, so I may not get to it until later next week.

**Pull request closed without merging**
