### PR TITLE
make auth key, rangeEnd typed like mvcc ([]byte)

### LINKED ISSUE #5655: auth: use bytes comparasion
In the auth pkg, we use string comparison now. this is inconsistent with how the range ordering works in mvcc store. We should use bytes instead and keep []byte all over the place instead of converting them to string. 

/cc @gyuho can you please fix this?

### PR DESCRIPTION
**Pull request by gyuho**
Fix #5655.

### CODE REVIEW

**Comment by gyuho** [comment]
Locally tested and tests passed. Please review.

/cc @xiang90 @mitake @heyitsanthony 

Thanks!

**Comment by heyitsanthony** [comment]
lgtm defer to @xiang90

**Comment by xiang90** [comment]
lgtm. i will rebase my pr.

**Comment by gyuho** [comment]
ok, let me merge this first then. Thanks.

**Comment by mitake** [comment]
@gyuho thanks for the fix!

**Pull request merged**
