### PR TITLE
Highlight differences between example run commands in docker_guide

### PR DESCRIPTION
**Pull request by tobilarscheid**
Hi everyone,

when my team set up our first etcd cluster based on docker, we strictly followed the instructions found in docker_guide.md. One thing that was a bit problematic for us is that the run commands for all cluster members are _mostly_ the same, with only minor variations. I felt like it would be useful to highlight these differences in the documentation so that they are visible right away. In order to highlight the parts within a code block, I changed the code block to a ```<pre></pre>``` block.

Regards,

Tobi

### CODE REVIEW

**Comment by tobilarscheid** [comment]
I think the failing build is due to errors in the master branch I based my changes on. My changes only happen in one markdown document, this should not influence the build.

**Comment by heyitsanthony** [comment]
I think HTML in md files violates md style conventions (https://github.com/coreos/docs/blob/master/STYLE.md#source-formatting).

/cc @joshix

**Comment by joshix** [comment]
@tobilarscheid You catch us where our tools don't quite live up to your good idea. The docs have multiple output targets, not all of them processed through a browser, making me reluctant to introduce styling in these excerpts.

But I agree with the spirit of the changes. Could this be successfully highlighted with a bit of bold introductory prose prior to each section, or a heading?

**Comment by tobilarscheid** [comment]
Hi guys,

thanks for your valuable feedback. I was not really happy with the html in markdown either and I am somewhat glad you found hard facts that prohibit it. ;-)

I found another markdown-only solution (read: hack) for bold highlighting in codeblocks, but to my understanding it only works in single-line code blocks. See for yourself: http://meta.stackexchange.com/a/193197

Adding some prose is kind of the last resort for me.  I feel like the people like me who just copy paste the code and totally ignore the prose will probably not profit from this, but it is definitely better than nothing. I will update my branch!

Regards,

Tobi

**Comment by joshix** [comment]
@tobilarscheid Thanks for being flexible, and for the changes. I gave your note a light editorial brush for house style and will merge this after CI.

**Comment by tobilarscheid** [comment]
I thank you for being so open and responsive to the community!

**Pull request merged**
