### PR TITLE
pkg/netutil: use native byte ordering

### PR DESCRIPTION
**Pull request by heyitsanthony**
Tests were failing on non-386/amd64 archs since the build flags were trying to enforce little endian ordering. Just detect endianness instead and have the route detection code work everywhere.

/cc @mkumatag

### CODE REVIEW

**Comment by mkumatag** [comment]
I see a error in travis : 

`# github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/netutil
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/netutil/routes_linux.go:31: GetDefaultHost redeclared in this block
	previous declaration at gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/netutil/routes.go:26
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/netutil/routes_linux.go:124: GetDefaultInterface redeclared in this block
	previous declaration at gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/netutil/routes.go:31`


https://github.com/coreos/etcd/blob/master/pkg/netutil/routes.go#L15 contains the fallback functions for unsupported platform, we might need to add architectures here to get away with re-declaration error.

line should be modified to : 
`+build !linux !386,!amd64,!arm,!arm64,!ppc64le`

**Comment by mkumatag** [comment]
Added applied following change on top of this PR and able to run test successfully 

```
ubuntu@ubuntu:~/heyitsanthony/etcd$ git diff
diff --git a/pkg/netutil/routes.go b/pkg/netutil/routes.go
index d6979c1..4cb0a24 100644
--- a/pkg/netutil/routes.go
+++ b/pkg/netutil/routes.go
@@ -12,7 +12,7 @@
 // See the License for the specific language governing permissions and
 // limitations under the License.
 
-// +build !linux !386,!amd64
+// +build !linux !386,!amd64,!arm,!arm64,!ppc64le
 
 package netutil
 
ubuntu@ubuntu:~/heyitsanthony/etcd$ 
```

**Comment by gyuho** [comment]
LGTM after test fixes

**Comment by heyitsanthony** [comment]
ci failures look runtime related (httptest); merging

**Pull request merged**
