### PR TITLE
Godeps: missing Godeps for appengine, others

### PR DESCRIPTION
**Pull request by gyuho**
This adds missing dependencies especially for the ones with appengine
build tags. This is for https://github.com/coreos/etcd/issues/3928.

### CODE REVIEW

**Comment by gyuho** [comment]
Some major change is on build constraints on `appengine`

- `google.golang.org/appengine`
- `google.golang.org/cloud/compute/metadata` and `google.golang.org/cloud/internal` -> `google.golang.org/cloud`

**Comment by jonboulle** [comment]
@gyuho how did you work around the platform/build tags issue?

**Comment by gyuho** [comment]
@jonboulle I have a pending PR on Godep https://github.com/tools/godep/pull/337, which seems to work for cases like this.

**Comment by gyuho** [comment]
Closing this in favor of https://github.com/coreos/etcd/pull/4040.

We still have missing dependencies in `appengine` though...

```
gyuho@gyuho: ~/branches/etcd $
grep -r "google.golang.org/appengin"
Godeps/_workspace/src/golang.org/x/oauth2/client_appengine.go:	"google.golang.org/appengine/urlfetch"
Godeps/_workspace/src/golang.org/x/oauth2/google/appengine_hook.go:import "google.golang.org/appengine"
Godeps/_workspace/src/golang.org/x/oauth2/google/example_test.go:	"google.golang.org/appengine"
Godeps/_workspace/src/golang.org/x/oauth2/google/example_test.go:	"google.golang.org/appengine/urlfetch"
Godeps/_workspace/src/golang.org/x/oauth2/README.md:To work around this, you may use the new `"google.golang.org/appengine"`
Godeps/_workspace/src/golang.org/x/oauth2/README.md:		newappengine "google.golang.org/appengine"

```

**Pull request closed without merging**
