### PR TITLE
[WIP] Update parent `Modified Index` on node Write()

### LINKED ISSUE #5148: RFE: update directory modifiedIndex on any child modifications.
Currently the kubernetes data model represents "resources" (replication controllers, endpoints, etc), by creating directories per resource, and elements are added or removed from that directory based on user interactions.  

Each kubernetes controller keeps a cache of it's respective directory that it's responsible for, and rectifies their state accordingly.  There are no guarantees that the controller has the full state of the directory so it forces a periodic relist.  The problem that exists, is that these directories can become large, making a list arguably the most expensive operation in the system.  

A simple fix that would prevent this re-list from occurring would be to update the parent directories modified index whenever a new item is added, changed, or removed.  This would allow the controller to only need to perform a periodic get on the directory and relist only when it's state differs.  

/cc @xiang90 @rrati @hongchaodeng @wojtek-t @jeremyeder

### PR DESCRIPTION
**Pull request by timothysc**
Simple modification to update the Parent Nodes Modified Index on node write.

Fixes #5148.

### CODE REVIEW

**Comment by xiang90** [comment]
This breaks the existing v2 API. We have to add options to enable this feature. User needs to explicitly tell etcd to update the index of its direct parent.

**Comment by timothysc** [comment]
k, let me fix that up ;-)

**Comment by heyitsanthony** [comment]
@timothysc What happens if one node has this option set but all the others don't?

**Comment by timothysc** [comment]
@heyitsanthony, You would need to set for all.

**Comment by heyitsanthony** [comment]
@timothysc my point is that implementing it like this seems like a good way to corrupt your cluster with inconsistent data

**Comment by timothysc** [comment]
@heyitsanthony could you please explain?  do you mean inconsistent setting?

**Comment by heyitsanthony** [comment]
@timothysc if the options don't match, the nodes won't write the same data to their stores so despite having consensus they'll serve different data. I think the only way to safely upgrade to this option would be to take the cluster down entirely and then restart with the option set across all nodes. It seems risky.

**Comment by timothysc** [comment]
@heyitsanthony I'm totally ok with that, and I could document as well.  

Almost all of our deployments are automated, and most checks are not looking at the parents modified index.  This is more a kubernetes enablement then anything.

**Comment by timothysc** [comment]
@heyitsanthony Is there another option that you propose..?

**Comment by heyitsanthony** [comment]
@timothysc still seems too easy to mess up. I don't think it's a good policy to have options that can corrupt the cluster if you're not super careful. From the client side, it's bad because a client has no way of knowing which mode the cluster is using so if it relies on the old behavior, it could subtly and silently break due to the new behavior. Plus, this option percolates through more files than it seems it should; there's probably a better way to do it.

One way to do this safely is to set an opt-in flag through the client via `SetOptions` which would say that the modifiedindex is updated on child writes and store that flag with the directory metadata.

I'll note it's already possible to have something like this in V3 by using transactions.

**Comment by timothysc** [comment]
> One way to do this safely is to set an opt-in flag through the client via SetOptions which would say that the modifiedindex is updated on child writes and store that flag with the directory metadata.

ok, so add a variable say ```UpdateParentModifiedIndex bool``` to the client side ```SetOptions```, and on the server side do the update based on the parameter? 

>  I'll note it's already possible to have something like this in V3 by using transactions.

example?

**Comment by heyitsanthony** [comment]
@timothysc my thinking was the directory would be created/set the flag and when a child is written, the server will check the directory for the flag to see if the modified index should be updated.

On v3 it can be done client-side with code like:
```go
client.Txn(context.TODO()).Then(OpPut("/this/is/a/key", "value"), OpPut("/this/is/a/.lastMod", "")).Commit()
```
where `/this/is/a/.lastMod`'s modified revision would represent the directory's last modified index.

**Comment by timothysc** [comment]
So we would need to modify OpPut to support updating meta-data? 

Also, this is only a single trip over the wire, correct?

**Comment by heyitsanthony** [comment]
@timothysc OpPut wouldn't need to change. The client would atomically update a special key whenever there's a child put/delete by using v3 transactions. The network traffic is the same as a regular put/delete-- one round trip.

**Comment by timothysc** [comment]
> The network traffic is the same as a regular put/delete-- one round trip.

Sorry I should clarify: 
```Then(OpPut("/this/is/a/key", "value"), OpPut("/this/is/a/.lastMod", "")).Commit()```
is a single trip over the wire, or two?

**Comment by xiang90** [comment]
@timothysc 

> is a single trip over the wire, or two?

One. The two ops are in one transaction and committed in a batch.

**Comment by timothysc** [comment]
Well then, this solves my problem nicely, I'll close out this PR and make the change in kube.

**Comment by xiang90** [comment]
@timothysc This is for v3 only.

**Comment by timothysc** [comment]
I know.

**Pull request closed without merging**
