### PR TITLE
refactor recorder-based mock objects into separate packages

### PR DESCRIPTION
**Pull request by hongchaodeng**
ref: https://github.com/kubernetes/kubernetes/issues/22908

"clientv3" is importing "testutil" which would lead to import "testing". This is causing failure in upstream CI.

> (Deprecated)
I found that "clientv3" is only using recorder.go file. It can pass the upstream CI by doing the following:
- refactor recorder.go into a single package
- refactor WaitSchedule into a single package; This is used by recorder.go

This can be fixed by refactoring out recorder based objects into different packages.

### CODE REVIEW

**Comment by heyitsanthony** [comment]
```
etcd $ grep "pkg/testutil" clientv3 -R 2>/dev/null | grep coreos
../clientv3/integration/main_test.go:   "github.com/coreos/etcd/pkg/testutil"
../clientv3/integration/cluster_test.go:        "github.com/coreos/etcd/pkg/testutil"
../clientv3/integration/kv_test.go:     "github.com/coreos/etcd/pkg/testutil"
../clientv3/integration/mirror_test.go: "github.com/coreos/etcd/pkg/testutil"
../clientv3/integration/watch_test.go:  "github.com/coreos/etcd/pkg/testutil"
../clientv3/integration/txn_test.go:    "github.com/coreos/etcd/pkg/testutil"
../clientv3/integration/lease_test.go:  "github.com/coreos/etcd/pkg/testutil"
../clientv3/txn_test.go:        "github.com/coreos/etcd/pkg/testutil"
```
Where's the testutil import? It's only being pulled in by test files.

**Comment by hongchaodeng** [comment]
It's multi-step importing:
```
github.com/coreos/etcd/clientv3
github.com/coreos/etcd/etcdserver/api/v3rpc
github.com/coreos/etcd/etcdserver
github.com/coreos/etcd/pkg/testutil
testing
```

**Comment by heyitsanthony** [comment]
I think the better fix for this is to move all the recorder-based mock objects into a `mocks` package since this stuff has little use outside of tests. The etcdserver dependency seems bad regardless. /cc @xiang90

**Comment by xiang90** [comment]
@heyitsanthony fine with me.

**Comment by hongchaodeng** [comment]
@heyitsanthony 
Moved everything to "mock"

**Comment by heyitsanthony** [comment]
@hongchaodeng I meant the bits that are pulling `testutil` into the regular build should be moved to `mock`;  the testutil package should stay the same...

**Comment by hongchaodeng** [comment]
@heyitsanthony 
All fixed. PTAL

**Comment by heyitsanthony** [comment]
lgtm once it's squashed /cc @xiang90

**Comment by xiang90** [comment]
Please fix tests and squash. Then LGTM

**Comment by hongchaodeng** [comment]
I can confirm that this also passed "verify-symbol" check in k8s.

**Pull request merged**
