### PR TITLE
etcdctl: parse auth related options in endpoint health command

### PR DESCRIPTION
**Pull request by mitake**
Partially fixes https://github.com/coreos/etcd/issues/6611

/cc @jy02471192 @xiang90

### CODE REVIEW

**Comment by mitake** [comment]
@jy02471192 could you try it with a root user or a user with root role? The root role can access to every key unconditionally so the health check can work.

**Comment by xiang90** [comment]
Can we add an e2e test for this?

**Comment by jy02471192** [comment]
>The root role can access to every key unconditionally

@mitake In my situation, the root role doesn't have any keys' permissions initially.
In fact, my case was found with a root user.

**Comment by xiang90** [comment]
> the root role doesn't have any keys' permissions initially.

The root role should have permissions on all keys by default.

**Comment by mitake** [comment]
@xiang90 updated for e2e test, PTAL

**Comment by mitake** [comment]
@lonelili the semantics of root role is changed in https://github.com/coreos/etcd/pull/6356 , but it isn't backported to stable releases yet. It is available in the master branch or v3.1.0-alpha1.

**Comment by xiang90** [comment]
LGTM. Thanks!

**Comment by lonelili** [comment]
Good news. [Thumbs up]

**Pull request merged**
