### PR TITLE
travis: unit test on 386

### PR DESCRIPTION
**Pull request by heyitsanthony**
/cc @philips @jaredeh @xiang90

I nuked ppc64le and replaced it with 386 to save some resources. People have asked for 386 (e.g., @blp), but I am unaware of anyone actually using ppc64le (@luxas added it, but afaik he's only doing arm dev).

### CODE REVIEW

**Comment by xiang90** [comment]
lgtm

**Comment by luxas** [comment]
Removing ppc64le is sad, very sad, and I must honestly say I'm disappointed.
Yes, I'm mostly doing amd64, arm and arm64 dev, but remember that I decreased the travis build time for you by adding arm and ppc64le to build on every CI run.

I added ppc64le just because of kindness, IBM is gathering its forces to run Kubernetes on ppc64le and while I have no connection to IBM at all, I've been helping them anyway.

I haven't got my head around why you don't like other arches yet, but from my point of view, having ppc64le there to catch possible future compilation breakages isn't bad in any way at all.

I'm not gonna fight against you, and I don't want to. I'm letting the IBM devs take the decision if they want to enable it again, and I guess they can setup integration testing if you want them to.

cc-ing some of the IBM devs: @Pensu @bpradipt @laboger

**Comment by xiang90** [comment]
@luxas Please understand that we (etcd community) have limited resources. We need to care about the most of the users, not ALL of the potential users. Also we are very open. If you want to put resource into etcd and help to maintain arm64 and ppc64le, we are very welcome! For the resource we spend on any work, we need to have a clear goal and a clear path to support the work in long term.

**Comment by luxas** [comment]
> Please understand that we (etcd community) have limited resources

That's the best argument so far I've heard, but still it can grow with more architectures => more people caring about it.

> If you want to put resource into etcd and help to maintain arm64 and ppc64le, we are very welcome!

If I had more time, I'd maybe do it. I'm maintaining Kubernetes on my spare time only, and unfortunately one can't be everywhere. Also, I'm not paid/sponsored right now, and that's also a concern.

But I thought I helped you with the arm and ppc64le work when I digged through the code looking for things not properly aligned on 32-bit, came up with a (very simple indeed) solution to the arm compilation error, and decreased travis build time while adding arm and ppc64le.

I think it's great that 386 was added, via that platform we may find why the boltdb overflow panic occurs, and use that knowledge for arm too.

I just don't understand in this case why ppc64le was removed, it was a thing that already was "implemented". So if you are open to new arches/opportunities, I'd suggest adding ppc64le back to the compilation verification list, but that's just my opinion.

And if we ask, maybe some of the IBM developers want to maintain etcd for ppc64le?

**Comment by xiang90** [comment]
@luxas We are open to add it back or even not removing it at the first place. That is why you were cced. Again, if there is some people care about ppc64le, please say it. Then we can figure a long term plan out.

Thanks for your help on 32 bit. And now we run CI against 32bit.

**Comment by Pensu** [comment]
@xiang90 Hi, we  have been using etcd for ppc64le and I would be more than happy to provide any help you need. Please let me know whatever help is required here.

**Comment by bpradipt** [comment]
@xiang90, we are actively using ppc64le builds.. Please do let us know what is required.

**Comment by luxas** [comment]
Whoa, the etcd community just got bigger :smile:

From https://github.com/coreos/etcd/blob/master/Documentation/op-guide/supported-platform.md

> An "official" maintainer for the platform with clear motivation; someone must be responsible for taking care of the platform.

Some of @Pensu, @bpradipt and @laboger should be the maintainer I think

> Set up CI for build; etcd must compile.

It does. We should just add the travis hook back.

> Set up CI for running unit tests; etcd must pass simple tests.

I'm pretty sure it does, Go code is pretty the same everywhere (while having the same amount of bits)

> Set up CI for running integration tests; etcd must pass intensive tests.

ref: #5054 
You might want to run a Jenkins build system for testing this.

**Comment by heyitsanthony** [comment]
> I'm pretty sure it [passes unit tests], Go code is pretty the same everywhere (while having the same amount of bits)

No. Different archs will pull in different arch/platform specific code. "Pretty sure" isn't good enough.

**Comment by luxas** [comment]
> Different archs will pull in different arch/platform specific code.

Yes, I obviously I know that. 

Calm down and feel free to ignore that comment, that was just a guess from my side that the unit test will pass (since they do on both arm, 386 and other platforms)

Of course they should set up the CI that testes everything. @glevand might have instructions how to setup the CI. But we should probably make a separate issue for maintaining ppc64le.

**Pull request merged**
