### PR TITLE
*: codegangsta/cli to urfave/cli

### PR DESCRIPTION
**Pull request by gyuho**
Fix https://github.com/coreos/etcd/issues/3901

```
./bin/etcdctl dsfsd
No help topic for 'dsfsd'

echo $?
3  # now it returns 3, not 0
```

```
./bin/etcdctl -vadfsdf
Incorrect Usage.

NAME:
   etcdctl - A simple command line client for etcd.
...

flag provided but not defined: -vadfsdf
echo $?
1
```

### CODE REVIEW

**Comment by gyuho** [comment]
actually I can receive an error from the package and exit with non-zero. Will fix.

**Comment by gyuho** [comment]
@xiang90 @heyitsanthony PTAL.

**Comment by heyitsanthony** [comment]
lgtm

**Comment by gyuho** [comment]
thanks. merging in greens.

**Comment by gyuho** [comment]
`TestCtlV2Backup` is failing... investigating...

**Comment by gyuho** [comment]
Test all passed. Was complaining about some interface changes in newer version. Merging.

**Pull request merged**
