### PR TITLE
Update ugorji

### PR DESCRIPTION
**Pull request by sttts**
Prerequisite for https://github.com/kubernetes/kubernetes/pull/37557.

### CODE REVIEW

**Comment by sttts** [comment]
Tests panic.

**Comment by timothysc** [comment]
@xiang90 @hongchaodeng fyi.

**Comment by sttts** [comment]
Am not sure about the panics. Seeing the same issues when running locally on Mac.

**Comment by xiang90** [comment]
@sttts Please format your commit message first.

vendor: update ...
client: update ...

I think travis fails due to malformed commit message.

**Comment by xiang90** [comment]
@sttts It seems that travis passed. 

> Seeing the same issues when running locally on Mac.

What did you see?

**Comment by sttts** [comment]
Unit tests fail locally, with **and** without this PR. So probably not relevant.

**Comment by xiang90** [comment]
> Unit tests fail locally,

Do you have any logging?

**Comment by sttts** [comment]
Will look into it tomorrow. Am on the road right now.

**Comment by xiang90** [comment]
@sttts OK. Thanks.

**Comment by sttts** [comment]
@xiang90 had to fix their GOPATH magic in the ./test script. Now it runs through:
```
$ ./test -v
...
Running unit tests...
ok  	github.com/coreos/etcd/auth	2.479s	coverage: 46.6% of statements
ok  	github.com/coreos/etcd/client	1.921s	coverage: 43.6% of statements
ok  	github.com/coreos/etcd/clientv3	8.252s	coverage: 24.3% of statements
ok  	github.com/coreos/etcd/clientv3/naming	4.001s	coverage: 78.3% of statements
ok  	github.com/coreos/etcd/compactor	3.730s	coverage: 89.7% of statements
ok  	github.com/coreos/etcd/discovery	1.438s	coverage: 65.7% of statements
ok  	github.com/coreos/etcd/embed	1.090s	coverage: 18.0% of statements
ok  	github.com/coreos/etcd/error	1.041s	coverage: 84.6% of statements
ok  	github.com/coreos/etcd/etcdctl/ctlv2/command	1.067s	coverage: 0.7% of statements
ok  	github.com/coreos/etcd/etcdmain	1.236s	coverage: 28.0% of statements
ok  	github.com/coreos/etcd/etcdserver	7.219s	coverage: 27.9% of statements
ok  	github.com/coreos/etcd/etcdserver/api/v2http	1.185s	coverage: 71.9% of statements
ok  	github.com/coreos/etcd/etcdserver/api/v2http/httptypes	1.067s	coverage: 76.2% of statements
ok  	github.com/coreos/etcd/etcdserver/api/v3rpc/rpctypes	1.051s	coverage: 75.0% of statements
ok  	github.com/coreos/etcd/etcdserver/auth	6.296s	coverage: 74.7% of statements
ok  	github.com/coreos/etcd/etcdserver/membership	1.090s	coverage: 59.5% of statements
ok  	github.com/coreos/etcd/lease	7.497s	coverage: 77.0% of statements
ok  	github.com/coreos/etcd/lease/leasehttp	1.075s	coverage: 60.0% of statements
ok  	github.com/coreos/etcd/mvcc	11.330s	coverage: 77.9% of statements
ok  	github.com/coreos/etcd/mvcc/backend	4.844s	coverage: 82.1% of statements
ok  	github.com/coreos/etcd/pkg/adt	1.866s	coverage: 87.0% of statements
ok  	github.com/coreos/etcd/pkg/cors	1.028s	coverage: 92.9% of statements
ok  	github.com/coreos/etcd/pkg/crc	1.025s	coverage: 100.0% of statements
ok  	github.com/coreos/etcd/pkg/expect	1.110s	coverage: 95.3% of statements
ok  	github.com/coreos/etcd/pkg/fileutil	1.505s	coverage: 73.6% of statements
ok  	github.com/coreos/etcd/pkg/flags	1.020s	coverage: 57.5% of statements
ok  	github.com/coreos/etcd/pkg/idutil	1.022s	coverage: 100.0% of statements
ok  	github.com/coreos/etcd/pkg/ioutil	1.197s	coverage: 74.6% of statements
ok  	github.com/coreos/etcd/pkg/logutil	7.188s	coverage: 58.5% of statements
ok  	github.com/coreos/etcd/pkg/monotime	1.021s	coverage: 50.0% of statements
ok  	github.com/coreos/etcd/pkg/netutil	1.027s	coverage: 75.0% of statements
ok  	github.com/coreos/etcd/pkg/osutil	1.023s	coverage: 87.1% of statements
ok  	github.com/coreos/etcd/pkg/pathutil	1.020s	coverage: 100.0% of statements
ok  	github.com/coreos/etcd/pkg/pbutil	1.022s	coverage: 76.9% of statements
ok  	github.com/coreos/etcd/pkg/report	1.016s	coverage: 20.9% of statements
ok  	github.com/coreos/etcd/pkg/schedule	1.022s	coverage: 85.7% of statements
ok  	github.com/coreos/etcd/pkg/testutil	1.139s	coverage: 20.2% of statements
ok  	github.com/coreos/etcd/pkg/transport	1.661s	coverage: 66.7% of statements
ok  	github.com/coreos/etcd/pkg/types	1.039s	coverage: 90.8% of statements
ok  	github.com/coreos/etcd/pkg/wait	1.301s	coverage: 92.9% of statements
ok  	github.com/coreos/etcd/proxy/grpcproxy	2.627s	coverage: 5.1% of statements
ok  	github.com/coreos/etcd/proxy/httpproxy	1.057s	coverage: 75.8% of statements
ok  	github.com/coreos/etcd/proxy/tcpproxy	1.041s	coverage: 64.2% of statements
ok  	github.com/coreos/etcd/raft	6.795s	coverage: 86.0% of statements
ok  	github.com/coreos/etcd/rafthttp	2.795s	coverage: 75.7% of statements
ok  	github.com/coreos/etcd/snap	1.157s	coverage: 54.2% of statements
ok  	github.com/coreos/etcd/store	1.199s	coverage: 90.1% of statements
ok  	github.com/coreos/etcd/wal	42.681s	coverage: 79.9% of statements
Success
293,89s user 78,85s system 202% cpu 3:04,03s total
```

So all looks green.

**Comment by xiang90** [comment]
OK. LGTM. Defer to @heyitsanthony

**Comment by heyitsanthony** [comment]
shouldn't this have some updates to `github.com/ugorji/go/codec`?

**Comment by sttts** [comment]
Called `scripts/updatedep.sh` and pushed `cmd/vendor`.

**Comment by heyitsanthony** [comment]
@sttts squash the updated vendor files into the `vendor:` commit? CI is complaining about commit title formatting. Thanks!

**Comment by sttts** [comment]
@heyitsanthony squashed and all green

**Comment by timothysc** [comment]
Dunno if we need a release to patch kube.  @sttts I didn't see anything in this PR that changed code that would be pulled in via godep.

**Comment by timothysc** [comment]
Damn, the generated code changed... 

We'll probably need a release to patch kube.

**Comment by sttts** [comment]
@timothysc why a release?

**Comment by timothysc** [comment]
@sttts you'll need to rev etcd dependence in kube that includes the generated code.

**Comment by sttts** [comment]
Sure. I thought you meant a versioned etcd Github release for some reason.

**Pull request merged**
