### PR TITLE
etcdctl: use endpoints instead of endpoint flag

### PR DESCRIPTION
**Pull request by AdoHe**
@xiang90 This is a quite small PR, I come across this when I am re-learning your code, from the `endpoint` flag help info and also as a replacement of `peers` flag I think we should change the `endpoint` to `endpoints`. Also I know this will break backward-compatible maybe we should still keep `endpoint` support here `getPeersFlagValue`.

### CODE REVIEW

**Comment by gyuho** [comment]
@AdoHe I personally like `endpoints` more, but this is not backward-compatible. Defer to @xiang90.

**Comment by AdoHe** [comment]
@gyuho yeah, I know that so I just added a comment.

**Comment by xiang90** [comment]
@AdoHe Adding a comment is not good enough. We probably need to keep the old one anyway.

**Comment by AdoHe** [comment]
@xiang90 how about doing same thing as `peers` flag? Mark it as `DEPRECATED` but still try to parse it value.

**Comment by AdoHe** [comment]
Just update this to ensure backward-compatible. Also in long term we should remove the DEPRECATED flags support.

**Comment by xiang90** [comment]
LGTM.

defer to @gyuho or @heyitsanthony

**Comment by gyuho** [comment]
lgtm. thanks @AdoHe!

**Comment by heyitsanthony** [comment]
lgtm

**Comment by xiang90** [comment]
@AdoHe Can you update the commit message to "etcdctl: use endpoints instead of endpoint flag" though? Follow `subsystem: message` thing.

**Comment by AdoHe** [comment]
Just update this commit message.

**Comment by xiang90** [comment]
@AdoHe Awesome! Thanks!

**Pull request merged**
