### PR TITLE
concurrency: fix typo in Serializable godoc

### PR DESCRIPTION
**Pull request by arthurkiller**
concurrency: fix typo in Serializable godoc

### CODE REVIEW

**Comment by heyitsanthony** [comment]
@arthurkiller please change the first line of the commit / title to `concurrency: fix typo in Serializable godoc` so this passes the CI [commit style](https://github.com/coreos/etcd/blob/master/CONTRIBUTING.md#format-of-the-commit-message) check and it should be good to merge. Thanks!

**Comment by heyitsanthony** [comment]
@arthurkiller `git commit --amend` the title? CI checks the commit message, not the github PR..

**Comment by arthurkiller** [comment]
@heyitsanthony  so I need to revert and then re-commit this?

**Comment by arthurkiller** [comment]
@heyitsanthony  done that

**Comment by xiang90** [comment]
Do not do revert.

Now do this 

```
git reset --soft HEAD~3
git commit -am "concurrency: fix typo in Serializable godoc"
```

then you should have a clean git history

**Comment by arthurkiller** [comment]
k, I have force pushed

**Comment by xiang90** [comment]
lgtm

**Pull request merged**
