### PR TITLE
etcdctl: allow to add a user within one command line

### PR DESCRIPTION
**Pull request by johnbazan**
This makes the "user add usr:pwd" feature available for ctlv3
without asking for the password in a new prompt.

Also forbids adding an empty username.

### CODE REVIEW

**Comment by mitake** [comment]
Is `--interactive=false` not enough? e.g. `echo password | etcdctl user add username --interfactive=false`

**Comment by johnbazan** [comment]
Yes, the interactive works...
Will that be the official way to do it now?

I mean, etcd2 supported creating the user in a much more simple way...
But maybe this is how we will have to do it now...

Changes like this puts a lot more resistance for us, for example, to migrate from etcd2 to etcd3...
We have a lot, really, a lot of automatized scripts using **etcdctl user add root:toor** that will have to be migrated to this way.

**Comment by mitake** [comment]
I agree with supporting the option notation for the migration purpose. Opinions? /cc @xiang90

**Comment by gyuho** [comment]
We need e2e test cases if we add this.

**Comment by johnbazan** [comment]
Sure, I can add them. Just wanted to make sure you want to add this.

**Comment by johnbazan** [comment]
@mitake @gyuho 
I'm sorry to bother you guys, but, are there any guidelines on how to setup my environment to run the tests properly?

Either runing the binary **test** or going into e2e and running them separately are giving me a lot of errors.

**Comment by gyuho** [comment]
@johnbazan You need to build binaries first by running `./build` and run e2e test with `go test -v -run TestName`.

Thanks!

**Comment by johnbazan** [comment]
I am receiving:

```
**jbazan@jbazan-virtual-machine:~/etcd/e2e$** go test -v -run userAddTest
PASS
ok  	_/home/jbazan/etcd/e2e	0.022s
```


Even when I am trying to make them fail on purpose.

I will push the tests and let the CI tell me if they pass, just to try.

**Comment by gyuho** [comment]
@johnbazan In Go, you need to prefix the test functions. So I would name it `TestUserAddOneLine` or something `Test*`

**Comment by johnbazan** [comment]
Oh, right. I have to use TestCtlV3UserAdd in order to run the tests within the class userAddTest.

Got it.

They've passed:
=== RUN   TestCtlV3UserAdd
--- PASS: TestCtlV3UserAdd (1.55s)

So the CI will I guess. :)



(Sorry, firsts approaches with Golang, hehe)

**Comment by heyitsanthony** [comment]
lgtm

**Comment by gyuho** [comment]
@johnbazan Lastly let's squash the first two commits into one? (changes in `user_command.go`)

And then we can merge. Thanks!

**Comment by johnbazan** [comment]
@gyuho Done. :)

**Comment by gyuho** [comment]
Semaphore failed with `command not found`, but seems like failure from outdated fork branch.

I manually tested this patch and ran e2e tests, which all passed.

**Pull request merged**
