### PR TITLE
*: update 'golang.org/x/net/context' and its dependencies

### PR DESCRIPTION
**Pull request by gyuho**
For #7180.

### CODE REVIEW

**Comment by xiang90** [comment]
for 3.2 branch, we can just use context in standard library instead?

**Comment by heyitsanthony** [comment]
seems like this is pulling in more updates than it needs to?

**Comment by gyuho** [comment]
This breaks out tests. Will also investigate why glide is creating more diffs than needed.

**Comment by gyuho** [comment]
@heyitsanthony PTAL. Test failure seems unrelated. Will open an issue if it happens again.

**Comment by heyitsanthony** [comment]
lgtm

**Comment by mwf** [comment]
@xiang90, note that if you use standard lib context you will lose compatibility with go1.6

**Comment by xiang90** [comment]
@mwf Yes. we are going to drop go16 support after 3.1.

**Comment by gyuho** [comment]
Think we are fine with completely dropping go 1.6 since it already breaks our TLS + gRPC. https://github.com/coreos/etcd/issues/6951

**Comment by mwf** [comment]
@gyuho amazing, thanks for the notice :)

**Pull request merged**
