### PR TITLE
vendor: update cobra and testify

### PR DESCRIPTION
**Pull request by heyitsanthony**
k8s is having problems with these old packages /cc @hongchaodeng

### CODE REVIEW

**Comment by gyuho** [comment]
lgtm

**Comment by hongchaodeng** [comment]
Can we hold it?
I think I have figured out other solutions..

**Comment by heyitsanthony** [comment]
@hongchaodeng sure, no rush

**Comment by hongchaodeng** [comment]
Let's just close this.
It's unreasonable to update etcd's dependency because of another project.
If we want to update it ourselves, that's fine.

**Pull request closed without merging**
