### PR TITLE
mvcc: delete EXPIRE event type

### PR DESCRIPTION
**Pull request by gyuho**
Addressing https://github.com/coreos/etcd/pull/5484#discussion_r65005236.
etcd v3 doesn't expire keys. It's either PUT of DELETE.

### CODE REVIEW

**Comment by purpleidea** [comment]
Is it appropriate then to open an issue that I'd like to receive a watch event when a lease expires on a certain key or have I misunderstood this? When the lease expires isn't the key automatically deleted?

**Comment by gyuho** [comment]
Yeah lease expiration deletes the key and if you had been watching on that deleted key, your watcher will receive event type `DELETE` event.

**Comment by purpleidea** [comment]
On Sun, May 29, 2016 at 6:13 PM, Gyu-Ho Lee <notifications@github.com>
wrote:

> Yeah lease expiration deletes the key and if you had been watching on that
> deleted key, your watcher will receive event type DELETE event.
>

Well that's great, except wouldn't it be useful to know that it got deleted
via lease expiration, hence a different event type?? How else could you
detect the difference between the two. Important because lease expiration
could represent a timeout message for example.

**Comment by gyuho** [comment]
Not that we shouldn't differentiate, but that's how our current lease implementation works now. Users are expected to see expired keys as deleted.

https://github.com/coreos/etcd/blob/master/mvcc/watchable_store.go#L125

`lease` and `mvcc` use the same backend interface, but in different key-value spaces(buckets). So I don't think `mvcc` could understand the expiration. @xiang90 should have better explanation.

**Comment by xiang90** [comment]
@purpleidea 

> Well that's great, except wouldn't it be useful to know that it got deleted
via lease expiration, hence a different event type?? How else could you
detect the difference between the two. Important because lease expiration
could represent a timeout message for example.

We do not want to couple the lease and key APIs. Lease is just another object that deletes keys attached to it when it expires.

We have implemented tons of stuff on top of v3 API and we do not have a real need for it.

**Comment by purpleidea** [comment]
On Sun, May 29, 2016 at 6:43 PM, Xiang Li <notifications@github.com> wrote:

> We do not want to couple the lease and key APIs. Lease is just another
> object that deletes keys attached to it when it expires.
>
> We have implemented tons of stuff on top of v3 API and we do not have a
> real need for it.
>

This is a good explanation, thanks. I suppose when I create a lease, I
could also create an extra key that expires along with all the other keys I
care about, and then when there is a deletion event, if I see that extra
key, then I assume it was the expiry. It's a bit of a hack, and it would be
nice if we could add an extra data field to track this internally. I
suppose it's not urgent though.

Cheers!

**Comment by xiang90** [comment]
Another idea we were thinking is to add last words to a deleted key. So you can attach whatever you want. But we can always get around this pretty easily. So we decided to keep this simple for now.

**Comment by purpleidea** [comment]
On Sun, May 29, 2016 at 6:56 PM, Xiang Li <notifications@github.com> wrote:

> Another idea we were thinking is to add last words to a deleted key. So
> you can attach whatever you want. But we can always get around this pretty
> easily. So we decided to keep this simple for now.



Could you please elaborate? What does last words mean?

**Comment by xiang90** [comment]
@gyuho lgtm

**Comment by gyuho** [comment]
thanks

**Pull request merged**
