### PR TITLE
*: etcd member rejects unary call with leader requirement when it does not have leader

### PR DESCRIPTION
**Pull request by xiang90**
/cc @heyitsanthony @gyuho

### CODE REVIEW

**Comment by gyuho** [comment]
So this means that clients will see `ErrGRPCNoLeader` errors when there's no leader?

**Comment by xiang90** [comment]
@gyuho Yes.

**Comment by xiang90** [comment]
@gyuho More specifically, If user set requireLeader, then yes.

**Comment by gyuho** [comment]
> If user set requireLeader, then yes.

And do you implement that logic in client side after this?

LGTM. Thanks.

Defer to @heyitsanthony

**Comment by heyitsanthony** [comment]
lgtm

**Comment by xiang90** [comment]
> And do you implement that logic in client side after this?

We need to. If you want, you can give it a try. My next thing is to make stream call works.

**Comment by gyuho** [comment]
@xiang90 Sure, I will give it a try.

**Pull request merged**
