### PR TITLE
lessor: delete keys in deterministic order on revoke

### LINKED ISSUE #6558: lease: Inconsistent hashes
On a 3 nodes etcd cluster, I call each node using raw rpc to create 1 lease and attach 2 keys to it. I wait for 3 seconds and find out that hash of individual node is inconsistent with each other.

Setup:
OS: OS X El Captitan 10.11.6
etcd Version: 3.1.0-alpha.0+gi
Go Version: go1.7
Go OS/Arch: darwin/amd64

Recreating the issue:
1. Download ectd code in your working directory.
2. CD into ../github.com/coreos/etcd, start a three node etcd quorum via goreman start 
3. In a another terminal, run following script

```Go
package main

import (
	"context"
	"fmt"
	"time"

	pb "github.com/coreos/etcd/etcdserver/etcdserverpb"

	"google.golang.org/grpc"
)

func grant(hostURL string) int64 {
	ctx, cancel := context.WithCancel(context.Background())
	conn, err := grpc.Dial(hostURL, grpc.WithInsecure())
	if err != nil {
		panic(err)
	}
	lc := pb.NewLeaseClient(conn)
	resp, err := lc.LeaseGrant(ctx, &pb.LeaseGrantRequest{TTL: 2})
	if err != nil {
		panic(err)
	}
	cancel()
	conn.Close()
	leaseID := resp.ID
	return leaseID
}

func putTwoKeys(leaseID int64, hostURL string) {
	ctx, cancel := context.WithCancel(context.Background())
	conn, err := grpc.Dial(hostURL, grpc.WithInsecure())
	if err != nil {
		panic(err)
	}
	kvc := pb.NewKVClient(conn)
	_, err = kvc.Put(ctx, &pb.PutRequest{
		Key:   []byte(fmt.Sprintf("%d%s%d", leaseID, "_", 1)),
		Value: []byte(fmt.Sprintf("bar")),
		Lease: leaseID,
	}, grpc.FailFast(false))
	if err != nil {
		panic(err)
	}
	_, err = kvc.Put(ctx, &pb.PutRequest{
		Key:   []byte(fmt.Sprintf("%d%s%d", leaseID, "_", 2)),
		Value: []byte(fmt.Sprintf("bar")),
		Lease: leaseID,
	}, grpc.FailFast(false))

	if err != nil {
		panic(err)
	}
	cancel()
	conn.Close()
}

func checkHashes(hostURL string) int64 {
	conn, err := grpc.Dial(hostURL, grpc.WithInsecure())
	if err != nil {
		panic(err)
	}
	mt := pb.NewMaintenanceClient(conn)
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	resp, err := mt.Hash(ctx, &pb.HashRequest{}, grpc.FailFast(false))
	if err != nil {
		panic(err)
	}
	cancel()
	conn.Close()
	return int64(resp.Hash)
}

func main() {
	hostURL1 := "localhost:2379"
	hostURL2 := "localhost:22379"
	hostURL3 := "localhost:32379"

	for i := 0; i < 100; i++ {
		lease1 := grant(hostURL1)
		lease2 := grant(hostURL2)
		lease3 := grant(hostURL3)
		putTwoKeys(lease1, hostURL1)
		putTwoKeys(lease2, hostURL2)
		putTwoKeys(lease3, hostURL3)
		time.Sleep(3000 * time.Millisecond)
		str1 := checkHashes(hostURL1)
		str2 := checkHashes(hostURL2)
		str3 := checkHashes(hostURL3)
		fmt.Printf("same hashes? %v \n", str1 == str2 && str2 == str3)
	}

}
```
4. Observe that the terminal output shows false in the very first run
```
fanmins-MBP:playground fanminshi$ go run HashInconsistency.go
same hashes? false
same hashes? false
same hashes? false
same hashes? false
```

### PR DESCRIPTION
**Pull request by heyitsanthony**
Fixes #6558

/cc @fanminshi @gyuho

### CODE REVIEW

**Comment by gyuho** [comment]
LGTM. Thanks!

**Comment by xiang90** [comment]
LGTM.

**Comment by fanminshi** [comment]
LGTM

**Comment by xiang90** [comment]
@fanminshi Can you verify this fix your issue? (or after this get merged) Thanks!

**Comment by fanminshi** [comment]
@xiang90 checking it right now

**Comment by fanminshi** [comment]
The inconsistency issue still exist with this change.

**Comment by fanminshi** [comment]
I checked out `heyitsanthony:fix-lease-hash` branch on my local machine, and it is working. LGTM

**Pull request merged**
