### PR TITLE
build: fix build error on ubuntu

### PR DESCRIPTION
**Pull request by AdoHe**
@xiang90 I tried to fix the issue#3417, I think this would also work with Go1.5. Would you like to have a look?

### CODE REVIEW

**Comment by yichengq** [comment]
It doesn't work with dash still:
```
./build: 18: ./build: [[: not found
```

**Comment by AdoHe** [comment]
@yichengq I think we can just use `[]` or we can just use `#!/bin/bash` instead.

**Comment by yichengq** [comment]
@AdoHe I prefer the first solution. People may not have /bin/bash on their system.

**Comment by AdoHe** [comment]
Ok, I will change `[[` to `[` and open a new pull request.

**Comment by AdoHe** [comment]
@yichengq Ok, I will change `[[` to '[' and open a new pull request.

**Comment by yichengq** [comment]
the code lgtm. Could you squash and rename the commit tile to `build: fix build error on ubuntu`?

**Comment by AdoHe** [comment]
@yichengq Ok, I will update this.

**Comment by AdoHe** [comment]
@yichengq I changed the pull request title, do I need to change the commit message?

**Comment by yichengq** [comment]
@AdoHe Yes. and squash into one commit

**Comment by AdoHe** [comment]
@yichengq Ok, I will.

**Comment by yichengq** [comment]
LGTM. Thanks for fixing it quickly!

**Pull request merged**
