### PR TITLE
Fix typo's

### PR DESCRIPTION
**Pull request by jeis2497052**
# Contributing guidelines

Please read our [contribution workflow][contributing] before submitting a pull request.

[contributing]: https://github.com/coreos/etcd/blob/master/CONTRIBUTING.md#contribution-flow

just proposing a small doc update

### CODE REVIEW

**Comment by gyuho** [comment]
@jeis2497052 Could you change the commit title to something like `*: fix typos`?

Thanks for your contribution!

**Comment by jeis2497052** [comment]
Sure, is the title OK now?

**Comment by gyuho** [comment]
@jeis2497052 I meant `git commit --amend`?

https://github.com/coreos/etcd/blob/master/CONTRIBUTING.md#format-of-the-commit-message

Thanks!

**Comment by jeis2497052** [comment]
is the amended commit OK ?

**Comment by gyuho** [comment]
@jeis2497052 We don't include merge commits.

Please rebase and combine the commits into one with git commit title `*: fix typo`?

**Comment by jeis2497052** [comment]
I will try again as rebase was a challenge for me.

**Comment by hexfusion** [comment]
kind ping @jeis2497052 :)

**Comment by jeis2497052** [comment]
sorry for my slow response.  I have time today to resolve my side.

**Comment by jeis2497052** [comment]
sorry but I broke my fork.  I will make a new fork.

**Pull request closed without merging**
