### PR TITLE
doc: add etcd docker guide

### LINKED ISSUE #2253: Problems with connecting to etcd 2.0 that runs in a docker container
I have been following this online page to run etcd in a container.
https://coreos.com/blog/Running-etcd-in-Containers/
The page talks about running etcd:0.4.6 in a container and it works.

When I tried doing this with etcd 2.0.0, the etcd service seems to start up but I am unable to connect to it via etcdctl.

(The docker images used below are hosted on dockerhub and are public)
------------- etcd 0.4.6 steps ----------------
The following command starts etcd 0.4.6 in docker, and works. I can connect to it with etcdctl.
>docker run   -p 4001:4001  kubernetes/etcd:0.4.6 /usr/local/bin/etcd   -name abhi-master   -addr `hostname -i`:4001

> docker exec {container-id-that-just-started} /usr/local/bin/etcdctl -C="http://localhost:4001" ls
(this works)

------------- etcd 2.0.0 steps ---------------- 
The following command starts etcd 2.0.0 in docker, but can't connect to it via etcdctl.
> docker run   -p 4001:4001  kubernetes/etcd:2.0.0 /usr/local/bin/etcd  --addr `hostname -i`:4001 

> docker exec {container-id-that-just-started} /usr/local/bin/etcdctl -C="http://localhost:4001" ls
Error: 501:  All the given peers are not reachable (Tried to connect to each peer twice and failed)[0]

cc @dchen1107 @thockin

### PR DESCRIPTION
**Pull request by kelseyhightower**
Fixes #2253

### CODE REVIEW

**Comment by xiang90** [comment]
@kelseyhightower The doc looks good to me. Shall we link into this doc somewhere from the existing docs?

**Comment by xiang90** [comment]
probably this section along with goreman?
https://github.com/coreos/etcd#running-local-etcd-cluster

**Comment by kelseyhightower** [comment]
@xiang90 Sure. I don't think we need to wait for that link before we merge though.

**Comment by xiang90** [comment]
lgtm

**Pull request merged**
