### PR TITLE
etcdhttp/auth: BasicAuth method in standard pkg

### PR DESCRIPTION
**Pull request by gyuho**
I created a new PR from https://github.com/coreos/etcd/pull/3598.
This is for `TODO: use the standard lib BasicAuth method when we move to
Go 1.4.` [1]. `BasicAuth` method got into Go standard package a year ago. [2]

---
1. https://github.com/coreos/etcd/blob/master/pkg/netutil/netutil.go#L126-L138
2. https://codereview.appspot.com/76540043/

### CODE REVIEW

**Comment by yichengq** [comment]
LGTM. defer to @xiang90

**Comment by xiang90** [comment]
@gyuho @yichengq We need to add a note somewhere to say etcd can be only built from go 1.4+.

**Comment by gyuho** [comment]
@xiang90 

Maybe we can add something like, below [Getting etcd](https://github.com/coreos/etcd#getting-etcd):

<br>

### Developing etcd

You will first need [*Go*](https://golang.org/) installed on your machine (version 1.4+ is required).

**Comment by xiang90** [comment]
@gyuho I think we should put the notice in getting etcd section. We talk about if you want the latest version of etcd, you can build from master. We should add we require at least go 1.4

**Comment by gyuho** [comment]
@xiang90 Just added `You will first need Go installed on your machine (version 1.4+ is required).` to the `Getting etcd` section, if I understand it correctly. Please let me know if you have any feedback. And thanks for review!

**Comment by xiang90** [comment]
LGTM

**Comment by gyuho** [comment]
Thanks!

**Pull request merged**
