### PR TITLE
Documentation/proxy: Change proxy port from 8080 to 2379

### PR DESCRIPTION
**Pull request by joshix**
Ref https://github.com/coreos/etcd/pull/5693 in v3 track (master).
Ref backport to 2.3.7 docs in https://github.com/coreos-inc/coreos-pages/pull/747

### CODE REVIEW

**Comment by gyuho** [comment]
lgtm. thanks. /cc @xiang90

**Comment by xiang90** [comment]
@gyuho Do you know why the build fails on 2.3.x branch?

**Comment by gyuho** [comment]
@xiang90 It's failing from goword https://travis-ci.org/coreos/etcd/jobs/139683761#L361. But I think we can ignore for this PR?

**Comment by heyitsanthony** [comment]
goword added package checking on march 19th, 2.3.0 shipped on march 18th, so the breakage makes sense since it's pulling from master. Maybe the static tests should lock a commit revision on the tooling so backporting doesn't explode?

lgtm

**Comment by xiang90** [comment]
lgtm

**Pull request merged**
