### PR TITLE
clientv3: added client side metrics support

### PR DESCRIPTION
**Pull request by sinsharat**
#6711
@xiang90 Will be adding test case to this.

### CODE REVIEW

**Comment by xiang90** [comment]
Thanks. LGTM. defer to @heyitsanthony

**Comment by sinsharat** [comment]
@xiang90 For test case i was thinking of adding it as an example test case, since it will be helpful for developers want to have client code metrics. For that i was thinking of having two test case example in example_metrics_test.go file one for ExampleMetrics_unary_KV and the other for ExampleMetrics_stream_Watch. What do you suggest?

**Comment by heyitsanthony** [comment]
@xiang90 why are we making this mandatory + adding a grpc-prometheus dependency? why not just have a grpc.DialOpts in the config structure to pass this sort of thing in?

**Comment by sinsharat** [comment]
@heyitsanthony its not mandatory. For users intending to have it they will have to enable it by calling "go-grpc-prometheus.EnableClientHandlingTimeHistogram()"

**Comment by heyitsanthony** [comment]
@sinsharat sure, except it's adding the interceptors and forcing a dependency unconditionally

**Comment by xiang90** [comment]
@sinsharat I think @heyitsanthony worries more about the dependencies management part.

@heyitsanthony I want to introduce this into the core client library since I want to enable this by default for all clients. The metrics collections overhead is minimal. I want to encourage every client to report metrics, and then the operators know how clients are doing and which generates the most load.

**Comment by heyitsanthony** [comment]
ok lgtm

**Comment by sinsharat** [comment]
@xiang90 Is my examples suggestion fine?

**Comment by xiang90** [comment]
@sinsharat Here is what I suggest:

1. add an example. set up http server, call `http.Handle("/metrics", prometheus.Handler())`, then you can see client side metrics

2. add a test case to make sure the metrics works

3. add a doc into readme or godoc.

**Comment by sinsharat** [comment]
@xiang90 sure will try it the way you have suggested. Also already had planned to add docs to it.
Will check out the http.Handle way.
I had written example code something like this:
```
package clientv3_test

import (
	"bufio"
	"fmt"
	"io"
	"log"
	"net/http"
	"net/http/httptest"
	"strconv"
	"strings"

	grpcprometheus "github.com/grpc-ecosystem/go-grpc-prometheus"
	"github.com/prometheus/client_golang/prometheus"

	"github.com/coreos/etcd/clientv3"
	"golang.org/x/net/context"
)

func ExampleMetrics_unary_Put_stream_Watch() {

	grpcprometheus.EnableClientHandlingTimeHistogram()

	ctxb := context.Background()

	ctx, cancel := context.WithCancel(ctxb)

	cliw, err := getClient()

	if err != nil {
		log.Fatal(err)
	}

	done := make(chan bool)
	rch := cliw.Watch(ctx, "foo")
	watchResponseBefore := sumCountersForMetricAndLabels("grpc_client_msg_received_total", "Watch", "bidi_stream")
	go func(done chan bool) {
		for wresp := range rch {
			for _, ev := range wresp.Events {
				fmt.Printf("%s %q : %q\n", ev.Type, ev.Kv.Key, ev.Kv.Value)
			}
		}
		done <- true
	}(done)

	clio, erro := getClient()

	if erro != nil {
		log.Fatal(erro)
	}

	putTotalBefore := sumCountersForMetricAndLabels("grpc_client_started_total", "Put", "unary")
	clio.Put(ctx, "foo", "bar")
	clio.Put(ctx, "foo", "bar1")
	clio.Put(ctx, "foo", "bar2")
	putTotalAfter := sumCountersForMetricAndLabels("grpc_client_started_total", "Put", "unary")

	if putTotalBefore+3 != putTotalAfter {
		log.Fatalf("grpc_client_started_total : Expected increment to be 3 but recieved : %v\n", putTotalAfter-putTotalBefore)
	}

	watchResponseAfter := sumCountersForMetricAndLabels("grpc_client_msg_received_total", "Watch", "bidi_stream")
	if watchResponseBefore+3 != watchResponseAfter {
		log.Fatalf("grpc_client_msg_received_total should be incremented : Expected increment to be 3 but recieved %v\n", watchResponseAfter-watchResponseBefore)
	}

	cancel()

	clio.Close()
	cliw.Close()

}

func getClient() (*clientv3.Client, error) {
	cli, err := clientv3.New(clientv3.Config{
		Endpoints:   endpoints,
		DialTimeout: dialTimeout,
	})
	return cli, err
}

func sumCountersForMetricAndLabels(metricName string, matchingLabelValues ...string) int {
	count := 0
	for _, line := range fetchPrometheusLines(metricName, matchingLabelValues...) {
		valueString := line[strings.LastIndex(line, " ")+1 : len(line)-1]
		valueFloat, err := strconv.ParseFloat(valueString, 32)
		if err != nil {
			log.Fatalf("failed parsing value for line: %v", line)
		}
		count += int(valueFloat)
	}
	return count
}

func fetchPrometheusLines(metricName string, matchingLabelValues ...string) []string {
	resp := httptest.NewRecorder()
	req, err := http.NewRequest("GET", "/", nil)
	if err != nil {
		log.Fatalf("failed creating request for Prometheus handler")
	}

	prometheus.Handler().ServeHTTP(resp, req)
	reader := bufio.NewReader(resp.Body)
	ret := []string{}
	for {
		line, err := reader.ReadString('\n')
		fmt.Println("line : ", line)
		if err != nil {
			if err == io.EOF {
				break
			} else {
				log.Fatalf("error reading stuff and the err is : %v", err)
			}
		}

		if !strings.HasPrefix(line, metricName) {
			continue
		}
		matches := true
		for _, labelValue := range matchingLabelValues {
			if !strings.Contains(line, `"`+labelValue+`"`) {
				matches = false
			}
		}
		if matches {
			ret = append(ret, line)
		}

	}
	return ret
}
```
Was planning to separate it out as i had suggested earlier.

**Comment by xiang90** [comment]
This seems like a test.

Example shows how people normally use this feature I think. All they need to do is to setup a http server and the http handler.

**Comment by sinsharat** [comment]
@xiang90 yes i tried what you suggested. Doing that and hitting it via browser lists all the details. But what i wanted to show in example was, that generally people write their own etcdctl instance in the code and use clientv3 for performing various operations. So if they want to in-corporate the metrics as well, i thought this might be a way since by users might not be interested in getting the entire dump, and may want to look for specific metrics.

**Comment by xiang90** [comment]
@sinsharat For examples

```
    if putTotalBefore+3 != putTotalAfter {
```

this is unnecessary. this is testing the correctness.

you can just issue an http request and print out the body.

**Comment by sinsharat** [comment]
@xiang90 yes you are right. So will remove the comparison part. Just wanted to ask shall we print log.Printf(lines) in the func fetchPrometheusLines. Since its already getting all the metrics. From the metrics we were filtering out the metrics we were searching for and counting them. Instead what we can do is return it and print the filtered metrics.
Another example we can have where it simple prints all the metrics.
Will that be fine?

**Comment by xiang90** [comment]
> So will remove the comparison part. Just wanted to ask shall we print log.Printf(lines) in the func fetchPrometheusLines. Since its already getting all the metrics. From the metrics we were filtering out the metrics we were searching for and counting them. Instead what we can do is return it and print the filtered metrics.

This is not how metrics should work. We only need to expose it, users should use https://prometheus.io/ to do filtering, aggregation or query. They will not directly interact with metrics.

**Comment by sinsharat** [comment]
@xiang90 ok got your point. Will do the way you are suggesting for examples.
How do you want it for test case?
Thanks.

**Comment by xiang90** [comment]
> How do you want it for test case?

For this case, we need to ensure a client request increases the counter. so the promfetch stuff makes sense for testing.

**Comment by xiang90** [comment]
I am going to merge this in. We can add test/example/doc in other prs.

**Comment by sinsharat** [comment]
@xiang90 ok sure will do it. Thanks a lot for your suggestions.

**Pull request merged**
