### PR TITLE
clientv3: Use LeaseID in all the client APIs.

### LINKED ISSUE #4988: ID from LeaseCreateResponse should be able to used directly in WithLease
Currently if you use the ID from LeaseCreateResponse in WithLease option:
```
lcr := client.lease.Create(...)
client.kv.Put(..., clientv3.WithLease(lcr.ID))
```

It will complain:
```
cannot use lcr.ID (type int64) as type clientv3.LeaseID in argument to clientv3.WithLease
```

That's awkward -- both are int64 though. In order to make it work, users have to cast it:
```
clientv3.WithLease(clientv3.LeaseID(lcr.ID))
```

It would be nice from user's perspective to not cast it.

### PR DESCRIPTION
**Pull request by ajityagaty**
In order to use LeaseID type instead of int64 we have to convert
the protobuf lease responses into client lease reponses.

Fixes #4988

### CODE REVIEW

**Comment by ajityagaty** [comment]
@heyitsanthony @xiang90 Please let me know if I have missed anything.

**Comment by ajityagaty** [comment]
Oh! the example_lease_test.go and the integration tests have imported `clientv3` from `github.com/coreos/etcd/clientv3` and hence will not have access to the changes made to the response types. Hence the failure. Perhaps I should put out the integration test changes in a separate PR?

**Comment by heyitsanthony** [comment]
@ajityagaty The tests use code from the current branch, not from the github repo master branch. Otherwise the CI system wouldn't be useful for gating changes. The GOPATH, which controls where packages are found, is set here: https://github.com/coreos/etcd/blob/master/test#L23 and the travis install, which loads all the packages, is here: https://github.com/coreos/etcd/blob/master/.travis.yml#L30 . I did a quick system audit and I am pretty sure it's working as intended.

It seems the tests aren't very picky about this change since they've only gone from doing `clientv3.LeaseID(int64)` to `clientv3.LeaseID(clientv3.LeaseID))`. I was expecting something to break, but I guess the tests can stay the same after all...

Please update `example_lease_test.go` to get rid of the superfluous `clientv3.LeaseID()` casts and I think this should be good to merge. Thanks!

**Comment by ajityagaty** [comment]
@heyitsanthony Thanks for giving some pointers about the test env setup. I hadn't paid much attention to it. Will remove the casts in `example_lease_test.go` and re-post.

**Comment by heyitsanthony** [comment]
lgtm

**Pull request merged**
