### PR TITLE
etcdmain: drop journald output

### PR DESCRIPTION
**Pull request by gyuho**
Fix https://github.com/coreos/etcd/issues/5449

@xiang90 https://github.com/coreos/etcd/issues/5449#issuecomment-229721613

### CODE REVIEW

**Comment by xiang90** [comment]
I believe @jonboulle and @philips suggests log directly to stdout by default.

I also think it is better.

**Comment by gyuho** [comment]
@xiang90 Changed it to `stdout` by default.

capnslog defaults to `stderr`, by the way.

**Comment by gyuho** [comment]
@xiang90 Now it just overwrites `NewDefaultFormatter` https://github.com/coreos/pkg/blob/master/capnslog/init.go#L36-L40 to drop journald

PTAL.

**Comment by xiang90** [comment]
@gyuho I am fine with this. Please wait for @jonboulle and @philips's opinion on this one. Thanks.

**Comment by gyuho** [comment]
Closing in preference of https://github.com/coreos/etcd/pull/6799

**Pull request closed without merging**
