### PR TITLE
wal: support fadatasync on linux

### PR DESCRIPTION
**Pull request by xiang90**
/cc @heyitsanthony @gyuho

### CODE REVIEW

**Comment by gyuho** [comment]
lgtm.

**Comment by gyuho** [comment]
@xiang90 

Why do we need separate function for linux? 

https://github.com/golang/go/blob/master/src/os/file_posix.go#L114-L125

Looks like `Sync` does the same thing?

**Comment by gyuho** [comment]
oh nvm. they are different.

**Comment by heyitsanthony** [comment]
would this be better as `pkg/fileutil/fdatasync*.go` instead?

**Comment by xiang90** [comment]
@heyitsanthony I will move.

**Comment by xiang90** [comment]
@heyitsanthony PTAL.

**Comment by heyitsanthony** [comment]
lgtm

**Pull request merged**
