### PR TITLE
concurrency: provide old STM functions as deprecated

### PR DESCRIPTION
**Pull request by heyitsanthony**
semver paranoia via upgrading zetcd

### CODE REVIEW

**Comment by gyuho** [comment]
Is this breaking change that needs to be addressed in release note?

**Comment by heyitsanthony** [comment]
@gyuho this shouldn't break anything from 3.1; same behavior and interfaces

**Comment by xiang90** [comment]
lgtm. ci failure is irrelevant?

**Comment by heyitsanthony** [comment]
Jenkins test failure filed under #7865. Semaphore likely failing due to #7823 which is fixed by/waiting on #7842. Merging.

**Pull request merged**
