### PR TITLE
Godeps: update boltdb/bolt for MAP_POPULATE

### PR DESCRIPTION
**Pull request by gyuho**
This is for https://github.com/boltdb/bolt/pull/455.

Please let me know if you have any feedback.

### CODE REVIEW

**Comment by xiang90** [comment]
Do you know why there are a lot of tests.go got removed?

**Comment by gyuho** [comment]
Ah, I `go get -v -u` the bolt. I will clone it instead.

**Comment by xiang90** [comment]
@gyuho No problem. Thanks.

**Comment by gyuho** [comment]
@xiang90 And I forgot the `-t` flag in `godep update`. Should be there now. Thanks,

**Comment by xiang90** [comment]
LGTM

**Comment by gyuho** [comment]
Thanks, once merged, I will do some benchmarks to make sure it benefits the backend package.

**Comment by xiang90** [comment]
@gyuho You need to change the backend code to utilize the new feature first. :)

**Pull request merged**
