### PR TITLE
client: add CreateOptions and GetOptions to client.KeysAPI

### PR DESCRIPTION
**Pull request by chirino**
Support creating in order keys from the client.KeysAPI.Create
Support get sorted nodes in client.KeysAPI.Get

### CODE REVIEW

**Comment by bcwaldon** [comment]
@chirino Please rebase this work off of the `210` branch - there has been a lot of work on the client pkg there that has not yet been merged back to master. For example, the sorted/recursive flags have already been implemented. Additionally, I'd prefer not to overload the `KeysAPI.Create` method with the InOrder functionality. Please establish a new method for this.

**Comment by chirino** [comment]
@bcwaldon what would you like the new Create method to be called?  Since Create is implemented with Set, perhaps we should just add a new InOrder bool to the SetOptions.

**Comment by bcwaldon** [comment]
@chirino Since Set implies that you already know the key of the node you're writing, I think it would be best to create a new KeysAPI.CreateInOrder method implemented with a new createInOrderAction struct.

**Comment by chirino** [comment]
I think we are missing a Create with CreateOptions.  For example you might want to combine the InOrder with the TTL options.  You might even want to specify the PrevIndex too.

**Comment by chirino** [comment]
I've submitted the new PR at https://github.com/coreos/etcd/pull/2365

**Pull request closed without merging**
