### PR TITLE
contrib: Give ownership on ETCD_DATA_DIR

### PR DESCRIPTION
**Pull request by guilhem**
This fix ownership problems when mount a new volume for etcd data

### CODE REVIEW

**Comment by xiang90** [comment]
LGTM. Defer to @jonboulle

**Comment by jonboulle** [comment]
I'd rather leave this up to the responsibility of whatever creates the directory (typically the packaging system). Otherwise, if etcd happens to have been run as root or something, this command is just giving a false sense of security. Can you elaborate on your use case? How are you mounting/adding a new volume for etcd?

**Comment by guilhem** [comment]
@jonboulle as there is already a `User=etcd` and a `ETCD_DATA_DIR=/var/lib/etcd` it seems to be quite normal to check if etcd has enough right to write in it.

Any packaging can change it there own way of course.

In my case, I'm booting CoreOS from PXE, then create btrfs subvolumes only for persistent software (/var/lib/docker, /var/lib/etcd2 etc) and mount them before software launch.

For docker there isn't problem as it run in root, but for etcd (and that's one of the only software like that on CoreOS) it run on different user. After first mount `/var/lib/etcd2` is owned by `root`...
I put a `drop-ins` in my cloud-init... but it seems quite legit to have it in upstream one (as user and path are already set).

**Comment by jonboulle** [comment]
@guilhem If this is biting you in CoreOS Linux, with `/var/lib/etcd2`, we definitely want to fix that, but this isn't the right place (it should either be in the CoreOS [etcd2 service file](https://github.com/coreos/coreos-overlay/blob/master/dev-db/etcd/files/etcd2.service) or solved some other way). I don't think it's very useful to change this contrib file, as it's just an example and I don't think having the chown there is best practice.

paging @crawford for sanity check/advice

**Comment by crawford** [comment]
Using tmpfiles is the more appropriate mechanism. That's what we use [in CoreOS](https://github.com/coreos/coreos-overlay/blob/master/dev-db/etcd/files/etcd2.conf).

**Comment by xiang90** [comment]
@guilhem Can you try what @crawford suggested? I am closing after @jonboulle and @crawford's opinion.

**Pull request closed without merging**
