### PR TITLE
client: drop unnecessary else and outdent its block

### PR DESCRIPTION
**Pull request by davygeek**

### CODE REVIEW

**Comment by xiang90** [comment]
there is a merge conflict. can you rebase with current master?

**Comment by gyuho** [comment]
Hi @davygeek 

Your forks seems outdated, a lot. Can you do something like

```
git clone git@github.com:gyuho/etcd.git $HOME/go/src/github.com/coreos/etcd
cd $HOME/go/src/github.com/coreos/etcd
git remote add upstream git@github.com:coreos/etcd.git
git fetch upstream
git merge upstream/master
git remote -v
git branch
git push
cd $HOME/go/src/github.com/coreos/etcd
```

**Comment by davygeek** [comment]
@gyuho thanks

**Comment by davygeek** [comment]
my forks seems outdated, I'll create a new PR, thanks.

**Pull request closed without merging**
