### PR TITLE
ctlv3: overwrite "snapshot restore" output with os.Stdout

### PR DESCRIPTION
**Pull request by gyuho**
Fix https://github.com/coreos/etcd/issues/9179.

### CODE REVIEW

**Comment by xiang90** [comment]
what is the output are we talking about here? the error message should still go to stderr, and the normal informational output of the command should go to stdout.

**Comment by gyuho** [comment]
@xiang90 

@hongchaodeng's issue was the info level logs are written to stderr

```
2018-02-06 12:23:45.945705 I | snapshot: restoring snapshot file "/home/gyuho/a.db" to data-dir "aaaaa", wal-dir "aaaaa/member/wal"
2018-02-06 12:23:45.945762 I | snapshot: writing snapshot directory "aaaaa/member/snap"
2018-02-06 12:23:45.953142 I | snapshot: writing WAL directory "aaaaa/member/wal" and raft snapshot to "aaaaa/member/snap"
2018-02-06 12:23:45.953340 I | etcdserver/membership: added member 8e9e05c52164694d [http://localhost:2380] to cluster cdf818194e3a8c32
2018-02-06 12:23:46.197989 I | snapshot: wrote WAL snapshot to "aaaaa/member/wal"
2018-02-06 12:23:46.341871 I | snapshot: finished restore "/home/gyuho/a.db" to data directory "aaaaa", wal directory "aaaaa/member/wal"
```

which is capnslog's default writer

**Comment by xiang90** [comment]
they should go to stderr. they are diagnostic informations, not the expected output of the program.

**Comment by xiang90** [comment]
@gyuho see https://github.com/coreos/etcd/issues/4052#issuecomment-166898533.

**Comment by gyuho** [comment]
Closing. To be consistent with other Unix tools, as @xiang90 mentioned.

ref. https://github.com/coreos/etcd/issues/4052#issuecomment-166898533

**Pull request closed without merging**
