### PR TITLE
*: update dependencies

### PR DESCRIPTION
**Pull request by xiang90**
Mostly for gRPC. Now it supports server side interceptor. We can do rate limiting / logging at RPC level easily now.

### CODE REVIEW

**Comment by heyitsanthony** [comment]
lgtm

**Comment by gyuho** [comment]
lgtm after test passes. thanks.

**Comment by xiang90** [comment]
Seems like we need to wait for protoc-gen-gogo update. The gRPC change requires some change of generated code.

**Comment by gyuho** [comment]
This is blocked on https://github.com/gogo/protobuf/issues/169.

**Comment by gyuho** [comment]
Closing via https://github.com/coreos/etcd/pull/5159.

**Pull request closed without merging**
