### PR TITLE
etcd-tester: do not exit for compaction timeout

### PR DESCRIPTION
**Pull request by gyuho**
This is temporary fix for #5606.

### CODE REVIEW

**Comment by gyuho** [comment]
/cc @xiang90 @heyitsanthony 

Please review.

Thanks.

**Comment by heyitsanthony** [comment]
The mvcc logs seem sort of chatty for Printf level (e.g., the compaction Printf's would be hourly if auto-scheduling).

**Comment by gyuho** [comment]
@heyitsanthony Yeah, now I think it's not necessary, since it is only useful when I was debugging a specific functional-tester issue. Will revert.

**Comment by gyuho** [comment]
@heyitsanthony PTAL.

Thanks.

**Comment by heyitsanthony** [comment]
lgtm, defer to @xiang90

**Comment by gyuho** [comment]
Changing it to skip the snapshot cycles, and start over the cluster,
because it will take longer and longer, so this makes it more complicated.

**Comment by gyuho** [comment]
@xiang90 PTAL. Now tester will keep running even after compaction time-out errors (but keeping the etcd logs for later debugging purposes).

Thanks.

**Comment by gyuho** [comment]
@xiang90 Changed it to just count it as a failure and clean up the cluster.

And added one more log line just in case `Bootstrap` fails.

PTAL.

Thanks.

**Comment by xiang90** [comment]
lgtm

**Comment by gyuho** [comment]
thanks. redeploying the cluster now.

**Pull request merged**
