### PR TITLE
EXPERIMENTAL: Add --keep-cluster-id and --node-id to 'etcdctl backup'

### PR DESCRIPTION
**Pull request by sttts**
This PR adds two flags to `etcdctl backup`:
- `--keep-cluster-id` stop etcdctl from rewriting the cluster id with a random value
- `--node-id <id>` sets an explicit node id in the WAL metadata (instead of using a random value again).

This allows to do disaster recoveries with copies of a data backup, following the idea in https://github.com/coreos/etcd/blame/master/contrib/systemd/etcd2-backup-coreos/README.md#L249. The latter is only a sketch which does not work with current etcd because the non-founder nodes will read their node id from the WAL and therefore all use the same node id as the founder.

This PR makes it possible to rewrite a WAL with a new node id. This allows the following disaster recovery procedure:

- take a backup of a data-dir and anonymize it with
```
$ etcdctl backup --backup-dir restored.etcd -data-dir <data-dir-backup>
$ etcd --force-new-cluster --data-dir restored.etcd
<ctrl-c>
$ cp -avx restored.etcd /var/lib/etcd/data
$ systemctl start etcd2
```

- add the non-founder node:
```
$ etcdctl member add non-founder http://non-founder:2380
```
  giving a node id `12345678901234567890`.

- on the non-founder nodes:
```
$ rm -rf /var/lib/etcd/data/member
$ rsync founder:restored.etcd restored.etcd
$ etcdctl backup --backup-dir restored.etcd --data-dir /var/lib/etcd/data --keep-cluster-id --node-id 12345678901234567890
$ systemctl start etcd2
```

### CODE REVIEW

**Comment by xiang90** [comment]
@sttts The main reason we decided to randomize the cluster id is to avoid accidental overlapping cluster. That happens A LOT when we do not have this feature enabled in etcd 0.4. User recreates a cluster and the members in that cluster might talk to the existing cluster. It would screw up everything.

Can you let us know your use case?

**Comment by ncdc** [comment]
We'd like to be able to provision a new cluster member using an existing
member's backup rather than relying on transferring the database snapshot
over the wire. This is a very specific, purposeful operation for disaster
recovery.

**Comment by xiang90** [comment]
> relying on transferring the database snapshot over the wire.

Can you provide more details on this? Why do you want to do that. For etcd2, the snapshot size is limited to 100MB or so. The cost is not HUGE. For etcd3, we do want to enable that when users can have GB snapshot.

**Comment by ncdc** [comment]
We have a setup with a 700mb database and we aren't able to add a new
member to the cluster. It has trouble sending the snapshot and times out. I
can provide more details if needed.

**Comment by xiang90** [comment]
> We have a setup with a 700mb database and we aren't able to add a new

Yea. etcd2 does not work when you have a snapshot larger than 200MB. Similar thing happens to zk or consul, which does full snapshot. My advice is to reduce snapshot size or switch to etcd3, which supports max 8GB snapshot by doing incremental snapshot.

**Comment by ncdc** [comment]
Neither of those options is possible right now. This is an OpenShift /
Kubernetes deployment and we aren't ready to move to etcd3. Would this PR
be a possible temporary solution, given an existing member's backup and a
new server?

**Comment by xiang90** [comment]
@ncdc I think this workaround might work for you if you strictly do what you described by just adding member. But we probably would not accept this patch. We do not expect etcd2 to work with 700MB snapshot at the first place; this patch has the risk as I mentioned above.

**Comment by xiang90** [comment]
I am closing this based on the discussion above. Let me know (reopen or create an issue) if you have further concerns. Thanks.

**Pull request closed without merging**
